In [1]:
import pandas as pd
import numpy as np
import re

In [2]:
fromhdf5 = pd.read_hdf('bdv-data-clean.h5', key='Results')

In [3]:
fromhdf5.set_index('BvD ID number',inplace=True)

In [4]:
fromhdf5.drop('Unnamed: 0', axis=1,inplace=True)

In [5]:
fromhdf5.index

Index(['GB07133524', 'GB07537279', 'GB09567757', 'GB07588867', 'GBOC353264',
       'GB10106271', 'IE566240', 'GB09683141', 'GB10212266', 'GBSC487640',
       ...
       'GB09564843', 'GB08633289', 'GB09748738', 'GB09153143', 'GBOC365296',
       'IE505067', 'GB07266603', 'GBOC369696', 'GBSC452461', 'GBOC381395'],
      dtype='object', name='BvD ID number', length=125990)

In [6]:
yearre= r"[0-9]{4}$" # to catch [2011..2019]
py = re.compile(yearre)
year_dot_re = r"[0-9]{4}\.[0-9]$" # to catch [2011.1..2019.1] 
pyd = re.compile(year_dot_re)
unique_cols = []
strange_ones = []
gifi_columns = []
gifi_dictionary = {}

print(gifi_columns)


only_unique_cols_df =  pd.DataFrame(index=fromhdf5.index)
for col_name in fromhdf5.columns:
    parts = col_name.split()
    year = parts[-1]
    if py.match(year) or pyd.match(year): # one of those <.. 2011> <.. 2011>
        # gifi column
        cleanned_up_col_name = '_'.join(e for e in parts[:-1])
        if not pyd.match(year):
            if cleanned_up_col_name not in gifi_columns:
                gifi_columns.append(cleanned_up_col_name)
            gifi_dictionary[col_name] = (cleanned_up_col_name,int(year))
        print(year + " of " + cleanned_up_col_name)
        if pyd.match(year) and cleanned_up_col_name not in strange_ones:
            strange_ones.append(cleanned_up_col_name)
        
        
    else: # just a column
        cleanned_up_col_name = '_'.join(e for e in parts)
        if cleanned_up_col_name not in unique_cols:
            unique_cols.append(cleanned_up_col_name)
            only_unique_cols_df[cleanned_up_col_name] = fromhdf5[col_name] # 
            print("Added : " + cleanned_up_col_name)

[]
Added : Company_name
Added : Registered_number
Added : Primary_UK_SIC_(2007)_code
Added : Primary_UK_SIC_(2003)_code
Added : Primary_UK_SIC_(2003)_code.1
Added : Primary_US_SIC_code
Added : Primary_NAICS_2017_code
Added : BvD_sector
Added : Date_of_incorporation
Added : Status_date
Added : Company_status
2019 of Turnover_th_GBP
2018 of Turnover_th_GBP
2017 of Turnover_th_GBP
2016 of Turnover_th_GBP
2015 of Turnover_th_GBP
2014 of Turnover_th_GBP
2013 of Turnover_th_GBP
2012 of Turnover_th_GBP
2011 of Turnover_th_GBP
2019 of Profit_(Loss)_before_Taxation_th_GBP
2018 of Profit_(Loss)_before_Taxation_th_GBP
2017 of Profit_(Loss)_before_Taxation_th_GBP
2016 of Profit_(Loss)_before_Taxation_th_GBP
2015 of Profit_(Loss)_before_Taxation_th_GBP
2014 of Profit_(Loss)_before_Taxation_th_GBP
2013 of Profit_(Loss)_before_Taxation_th_GBP
2012 of Profit_(Loss)_before_Taxation_th_GBP
2011 of Profit_(Loss)_before_Taxation_th_GBP
2019 of Net_Tangible_Assets_(Liab.)_th_GBP
2018 of Net_Tangible_Assets_(Liab.)_th_GBP
2017 of Net_Tangible_Assets_(Liab.)_th_GBP
2016 of Net_Tangible_Assets_(Liab.)_th_GBP
2015 of Net_Tangible_Assets_(Liab.)_th_GBP
2014 of Net_Tangible_Assets_(Liab.)_th_GBP
2013 of Net_Tangible_Assets_(Liab.)_th_GBP
2012 of Net_Tangible_Assets_(Liab.)_th_GBP
2011 of Net_Tangible_Assets_(Liab.)_th_GBP
2019 of Shareholders_Funds_th_GBP
2018 of Shareholders_Funds_th_GBP
2017 of Shareholders_Funds_th_GBP
2016 of Shareholders_Funds_th_GBP
2015 of Shareholders_Funds_th_GBP
2014 of Shareholders_Funds_th_GBP
2013 of Shareholders_Funds_th_GBP
2012 of Shareholders_Funds_th_GBP
2011 of Shareholders_Funds_th_GBP
2019 of Profit_Margin
2018 of Profit_Margin
2017 of Profit_Margin
2016 of Profit_Margin
2015 of Profit_Margin
2014 of Profit_Margin
2013 of Profit_Margin
2012 of Profit_Margin
2011 of Profit_Margin
2019 of Return_on_Shareholders_Funds
2018 of Return_on_Shareholders_Funds
2017 of Return_on_Shareholders_Funds
2016 of Return_on_Shareholders_Funds
2015 of Return_on_Shareholders_Funds
2014 of Return_on_Shareholders_Funds
2013 of Return_on_Shareholders_Funds
2012 of Return_on_Shareholders_Funds
2011 of Return_on_Shareholders_Funds
2019 of Return_on_Capital_Employed
2018 of Return_on_Capital_Employed
2017 of Return_on_Capital_Employed
2016 of Return_on_Capital_Employed
2015 of Return_on_Capital_Employed
2014 of Return_on_Capital_Employed
2013 of Return_on_Capital_Employed
2012 of Return_on_Capital_Employed
2011 of Return_on_Capital_Employed
2019 of Liquidity_Ratio_(x)
2018 of Liquidity_Ratio_(x)
2017 of Liquidity_Ratio_(x)
2016 of Liquidity_Ratio_(x)
2015 of Liquidity_Ratio_(x)
2014 of Liquidity_Ratio_(x)
2013 of Liquidity_Ratio_(x)
2012 of Liquidity_Ratio_(x)
2011 of Liquidity_Ratio_(x)
2019 of Gearing_(%)
2018 of Gearing_(%)
2017 of Gearing_(%)
2016 of Gearing_(%)
2015 of Gearing_(%)
2014 of Gearing_(%)
2013 of Gearing_(%)
2012 of Gearing_(%)
2011 of Gearing_(%)
2019 of Number_of_employees
2018 of Number_of_employees
2017 of Number_of_employees
2016 of Number_of_employees
2015 of Number_of_employees
2014 of Number_of_employees
2013 of Number_of_employees
2012 of Number_of_employees
2011 of Number_of_employees
2019 of Tangible_Assets_th_GBP
2018 of Tangible_Assets_th_GBP
2017 of Tangible_Assets_th_GBP
2016 of Tangible_Assets_th_GBP
2015 of Tangible_Assets_th_GBP
2014 of Tangible_Assets_th_GBP
2013 of Tangible_Assets_th_GBP
2012 of Tangible_Assets_th_GBP
2011 of Tangible_Assets_th_GBP
2019 of Land_&_Buildings_th_GBP
2018 of Land_&_Buildings_th_GBP
2017 of Land_&_Buildings_th_GBP
2016 of Land_&_Buildings_th_GBP
2015 of Land_&_Buildings_th_GBP
2014 of Land_&_Buildings_th_GBP
2013 of Land_&_Buildings_th_GBP
2012 of Land_&_Buildings_th_GBP
2011 of Land_&_Buildings_th_GBP
2019 of Freehold_Land_th_GBP
2018 of Freehold_Land_th_GBP
2017 of Freehold_Land_th_GBP
2016 of Freehold_Land_th_GBP
2015 of Freehold_Land_th_GBP
2014 of Freehold_Land_th_GBP
2013 of Freehold_Land_th_GBP
2012 of Freehold_Land_th_GBP
2011 of Freehold_Land_th_GBP
2019 of Leasehold_Land_th_GBP
2018 of Leasehold_Land_th_GBP
2017 of Leasehold_Land_th_GBP
2016 of Leasehold_Land_th_GBP
2015 of Leasehold_Land_th_GBP
2014 of Leasehold_Land_th_GBP
2013 of Leasehold_Land_th_GBP
2012 of Leasehold_Land_th_GBP
2011 of Leasehold_Land_th_GBP
2019 of Fixtures_&_Fittings_th_GBP
2018 of Fixtures_&_Fittings_th_GBP
2017 of Fixtures_&_Fittings_th_GBP
2016 of Fixtures_&_Fittings_th_GBP
2015 of Fixtures_&_Fittings_th_GBP
2014 of Fixtures_&_Fittings_th_GBP
2013 of Fixtures_&_Fittings_th_GBP
2012 of Fixtures_&_Fittings_th_GBP
2011 of Fixtures_&_Fittings_th_GBP
2019 of Plant_&_Vehicles_th_GBP
2018 of Plant_&_Vehicles_th_GBP
2017 of Plant_&_Vehicles_th_GBP
2016 of Plant_&_Vehicles_th_GBP
2015 of Plant_&_Vehicles_th_GBP
2014 of Plant_&_Vehicles_th_GBP
2013 of Plant_&_Vehicles_th_GBP
2012 of Plant_&_Vehicles_th_GBP
2011 of Plant_&_Vehicles_th_GBP
2019 of Plant_th_GBP
2018 of Plant_th_GBP
2017 of Plant_th_GBP
2016 of Plant_th_GBP
2015 of Plant_th_GBP
2014 of Plant_th_GBP
2013 of Plant_th_GBP
2012 of Plant_th_GBP
2011 of Plant_th_GBP
2019 of Vehicles_th_GBP
2018 of Vehicles_th_GBP
2017 of Vehicles_th_GBP
2016 of Vehicles_th_GBP
2015 of Vehicles_th_GBP
2014 of Vehicles_th_GBP
2013 of Vehicles_th_GBP
2012 of Vehicles_th_GBP
2011 of Vehicles_th_GBP
2019 of Other_Fixed_Assets_th_GBP
2018 of Other_Fixed_Assets_th_GBP
2017 of Other_Fixed_Assets_th_GBP
2016 of Other_Fixed_Assets_th_GBP
2015 of Other_Fixed_Assets_th_GBP
2014 of Other_Fixed_Assets_th_GBP
2013 of Other_Fixed_Assets_th_GBP
2012 of Other_Fixed_Assets_th_GBP
2011 of Other_Fixed_Assets_th_GBP
2019 of Intangible_Assets_th_GBP
2018 of Intangible_Assets_th_GBP
2017 of Intangible_Assets_th_GBP
2016 of Intangible_Assets_th_GBP
2015 of Intangible_Assets_th_GBP
2014 of Intangible_Assets_th_GBP
2013 of Intangible_Assets_th_GBP
2012 of Intangible_Assets_th_GBP
2011 of Intangible_Assets_th_GBP
2019 of Investments_th_GBP
2018 of Investments_th_GBP
2017 of Investments_th_GBP
2016 of Investments_th_GBP
2015 of Investments_th_GBP
2014 of Investments_th_GBP
2013 of Investments_th_GBP
2012 of Investments_th_GBP
2011 of Investments_th_GBP
2019 of Fixed_Assets_th_GBP
2018 of Fixed_Assets_th_GBP
2017 of Fixed_Assets_th_GBP
2016 of Fixed_Assets_th_GBP
2015 of Fixed_Assets_th_GBP
2014 of Fixed_Assets_th_GBP
2013 of Fixed_Assets_th_GBP
2012 of Fixed_Assets_th_GBP
2011 of Fixed_Assets_th_GBP
2019 of Stock_&_W.I.P._th_GBP
2018 of Stock_&_W.I.P._th_GBP
2017 of Stock_&_W.I.P._th_GBP
2016 of Stock_&_W.I.P._th_GBP
2015 of Stock_&_W.I.P._th_GBP
2014 of Stock_&_W.I.P._th_GBP
2013 of Stock_&_W.I.P._th_GBP
2012 of Stock_&_W.I.P._th_GBP
2011 of Stock_&_W.I.P._th_GBP
2019 of Stock_th_GBP
2018 of Stock_th_GBP
2017 of Stock_th_GBP
2016 of Stock_th_GBP
2015 of Stock_th_GBP
2014 of Stock_th_GBP
2013 of Stock_th_GBP
2012 of Stock_th_GBP
2011 of Stock_th_GBP
2019 of W.I.P._th_GBP
2018 of W.I.P._th_GBP
2017 of W.I.P._th_GBP
2016 of W.I.P._th_GBP
2015 of W.I.P._th_GBP
2014 of W.I.P._th_GBP
2013 of W.I.P._th_GBP
2012 of W.I.P._th_GBP
2011 of W.I.P._th_GBP
2019 of Finished_Goods_th_GBP
2018 of Finished_Goods_th_GBP
2017 of Finished_Goods_th_GBP
2016 of Finished_Goods_th_GBP
2015 of Finished_Goods_th_GBP
2014 of Finished_Goods_th_GBP
2013 of Finished_Goods_th_GBP
2012 of Finished_Goods_th_GBP
2011 of Finished_Goods_th_GBP
2019 of Trade_Debtors_th_GBP
2018 of Trade_Debtors_th_GBP
2017 of Trade_Debtors_th_GBP
2016 of Trade_Debtors_th_GBP
2015 of Trade_Debtors_th_GBP
2014 of Trade_Debtors_th_GBP
2013 of Trade_Debtors_th_GBP
2012 of Trade_Debtors_th_GBP
2011 of Trade_Debtors_th_GBP
2019 of Bank_&_Deposits_th_GBP
2018 of Bank_&_Deposits_th_GBP
2017 of Bank_&_Deposits_th_GBP
2016 of Bank_&_Deposits_th_GBP
2015 of Bank_&_Deposits_th_GBP
2014 of Bank_&_Deposits_th_GBP
2013 of Bank_&_Deposits_th_GBP
2012 of Bank_&_Deposits_th_GBP
2011 of Bank_&_Deposits_th_GBP
2019 of Other_Current_Assets_th_GBP
2018 of Other_Current_Assets_th_GBP
2017 of Other_Current_Assets_th_GBP
2016 of Other_Current_Assets_th_GBP
2015 of Other_Current_Assets_th_GBP
2014 of Other_Current_Assets_th_GBP
2013 of Other_Current_Assets_th_GBP
2012 of Other_Current_Assets_th_GBP
2011 of Other_Current_Assets_th_GBP
2019 of Group_Loans_(asset)_th_GBP
2018 of Group_Loans_(asset)_th_GBP
2017 of Group_Loans_(asset)_th_GBP
2016 of Group_Loans_(asset)_th_GBP
2015 of Group_Loans_(asset)_th_GBP
2014 of Group_Loans_(asset)_th_GBP
2013 of Group_Loans_(asset)_th_GBP
2012 of Group_Loans_(asset)_th_GBP
2011 of Group_Loans_(asset)_th_GBP
2019 of Directors_Loans_(asset)_th_GBP
2018 of Directors_Loans_(asset)_th_GBP
2017 of Directors_Loans_(asset)_th_GBP
2016 of Directors_Loans_(asset)_th_GBP
2015 of Directors_Loans_(asset)_th_GBP
2014 of Directors_Loans_(asset)_th_GBP
2013 of Directors_Loans_(asset)_th_GBP
2012 of Directors_Loans_(asset)_th_GBP
2011 of Directors_Loans_(asset)_th_GBP
2019 of Other_Debtors_th_GBP
2018 of Other_Debtors_th_GBP
2017 of Other_Debtors_th_GBP
2016 of Other_Debtors_th_GBP
2015 of Other_Debtors_th_GBP
2014 of Other_Debtors_th_GBP
2013 of Other_Debtors_th_GBP
2012 of Other_Debtors_th_GBP
2011 of Other_Debtors_th_GBP
2019 of Prepayments_th_GBP
2018 of Prepayments_th_GBP
2017 of Prepayments_th_GBP
2016 of Prepayments_th_GBP
2015 of Prepayments_th_GBP
2014 of Prepayments_th_GBP
2013 of Prepayments_th_GBP
2012 of Prepayments_th_GBP
2011 of Prepayments_th_GBP
2019 of Deferred_Taxation_th_GBP
2018 of Deferred_Taxation_th_GBP
2017 of Deferred_Taxation_th_GBP
2016 of Deferred_Taxation_th_GBP
2015 of Deferred_Taxation_th_GBP
2014 of Deferred_Taxation_th_GBP
2013 of Deferred_Taxation_th_GBP
2012 of Deferred_Taxation_th_GBP
2011 of Deferred_Taxation_th_GBP
2019.1 of Investments_th_GBP
2018.1 of Investments_th_GBP
2017.1 of Investments_th_GBP
2016.1 of Investments_th_GBP
2015.1 of Investments_th_GBP
2014.1 of Investments_th_GBP
2013.1 of Investments_th_GBP
2012.1 of Investments_th_GBP
2011.1 of Investments_th_GBP
2019 of Current_Assets_th_GBP
2018 of Current_Assets_th_GBP
2017 of Current_Assets_th_GBP
2016 of Current_Assets_th_GBP
2015 of Current_Assets_th_GBP
2014 of Current_Assets_th_GBP
2013 of Current_Assets_th_GBP
2012 of Current_Assets_th_GBP
2011 of Current_Assets_th_GBP
2019 of Trade_Creditors_th_GBP
2018 of Trade_Creditors_th_GBP
2017 of Trade_Creditors_th_GBP
2016 of Trade_Creditors_th_GBP
2015 of Trade_Creditors_th_GBP
2014 of Trade_Creditors_th_GBP
2013 of Trade_Creditors_th_GBP
2012 of Trade_Creditors_th_GBP
2011 of Trade_Creditors_th_GBP
2019 of Short_Term_Loans_&_Overdrafts_th_GBP
2018 of Short_Term_Loans_&_Overdrafts_th_GBP
2017 of Short_Term_Loans_&_Overdrafts_th_GBP
2016 of Short_Term_Loans_&_Overdrafts_th_GBP
2015 of Short_Term_Loans_&_Overdrafts_th_GBP
2014 of Short_Term_Loans_&_Overdrafts_th_GBP
2013 of Short_Term_Loans_&_Overdrafts_th_GBP
2012 of Short_Term_Loans_&_Overdrafts_th_GBP
2011 of Short_Term_Loans_&_Overdrafts_th_GBP
2019 of Bank_Overdrafts_th_GBP
2018 of Bank_Overdrafts_th_GBP
2017 of Bank_Overdrafts_th_GBP
2016 of Bank_Overdrafts_th_GBP
2015 of Bank_Overdrafts_th_GBP
2014 of Bank_Overdrafts_th_GBP
2013 of Bank_Overdrafts_th_GBP
2012 of Bank_Overdrafts_th_GBP
2011 of Bank_Overdrafts_th_GBP
2019 of Group_Loans_(short_t.)_th_GBP
2018 of Group_Loans_(short_t.)_th_GBP
2017 of Group_Loans_(short_t.)_th_GBP
2016 of Group_Loans_(short_t.)_th_GBP
2015 of Group_Loans_(short_t.)_th_GBP
2014 of Group_Loans_(short_t.)_th_GBP
2013 of Group_Loans_(short_t.)_th_GBP
2012 of Group_Loans_(short_t.)_th_GBP
2011 of Group_Loans_(short_t.)_th_GBP
2019 of Director_Loans_(short_t.)_th_GBP
2018 of Director_Loans_(short_t.)_th_GBP
2017 of Director_Loans_(short_t.)_th_GBP
2016 of Director_Loans_(short_t.)_th_GBP
2015 of Director_Loans_(short_t.)_th_GBP
2014 of Director_Loans_(short_t.)_th_GBP
2013 of Director_Loans_(short_t.)_th_GBP
2012 of Director_Loans_(short_t.)_th_GBP
2011 of Director_Loans_(short_t.)_th_GBP
2019 of Hire_Purch._&_Leas._(short_t.)_th_GBP
2018 of Hire_Purch._&_Leas._(short_t.)_th_GBP
2017 of Hire_Purch._&_Leas._(short_t.)_th_GBP
2016 of Hire_Purch._&_Leas._(short_t.)_th_GBP
2015 of Hire_Purch._&_Leas._(short_t.)_th_GBP
2014 of Hire_Purch._&_Leas._(short_t.)_th_GBP
2013 of Hire_Purch._&_Leas._(short_t.)_th_GBP
2012 of Hire_Purch._&_Leas._(short_t.)_th_GBP
2011 of Hire_Purch._&_Leas._(short_t.)_th_GBP
2019 of Hire_Purchase_(short_t.)_th_GBP
2018 of Hire_Purchase_(short_t.)_th_GBP
2017 of Hire_Purchase_(short_t.)_th_GBP
2016 of Hire_Purchase_(short_t.)_th_GBP
2015 of Hire_Purchase_(short_t.)_th_GBP
2014 of Hire_Purchase_(short_t.)_th_GBP
2013 of Hire_Purchase_(short_t.)_th_GBP
2012 of Hire_Purchase_(short_t.)_th_GBP
2011 of Hire_Purchase_(short_t.)_th_GBP
2019 of Leasing_(short_t.)_th_GBP
2018 of Leasing_(short_t.)_th_GBP
2017 of Leasing_(short_t.)_th_GBP
2016 of Leasing_(short_t.)_th_GBP
2015 of Leasing_(short_t.)_th_GBP
2014 of Leasing_(short_t.)_th_GBP
2013 of Leasing_(short_t.)_th_GBP
2012 of Leasing_(short_t.)_th_GBP
2011 of Leasing_(short_t.)_th_GBP
2019 of Other_Short_Term_Loans_th_GBP
2018 of Other_Short_Term_Loans_th_GBP
2017 of Other_Short_Term_Loans_th_GBP
2016 of Other_Short_Term_Loans_th_GBP
2015 of Other_Short_Term_Loans_th_GBP
2014 of Other_Short_Term_Loans_th_GBP
2013 of Other_Short_Term_Loans_th_GBP
2012 of Other_Short_Term_Loans_th_GBP
2011 of Other_Short_Term_Loans_th_GBP
2019 of Total_Other_Current_Liabilities_th_GBP
2018 of Total_Other_Current_Liabilities_th_GBP
2017 of Total_Other_Current_Liabilities_th_GBP
2016 of Total_Other_Current_Liabilities_th_GBP
2015 of Total_Other_Current_Liabilities_th_GBP
2014 of Total_Other_Current_Liabilities_th_GBP
2013 of Total_Other_Current_Liabilities_th_GBP
2012 of Total_Other_Current_Liabilities_th_GBP
2011 of Total_Other_Current_Liabilities_th_GBP
2019 of Corporation_Tax_th_GBP
2018 of Corporation_Tax_th_GBP
2017 of Corporation_Tax_th_GBP
2016 of Corporation_Tax_th_GBP
2015 of Corporation_Tax_th_GBP
2014 of Corporation_Tax_th_GBP
2013 of Corporation_Tax_th_GBP
2012 of Corporation_Tax_th_GBP
2011 of Corporation_Tax_th_GBP
2019 of Dividends_th_GBP
2018 of Dividends_th_GBP
2017 of Dividends_th_GBP
2016 of Dividends_th_GBP
2015 of Dividends_th_GBP
2014 of Dividends_th_GBP
2013 of Dividends_th_GBP
2012 of Dividends_th_GBP
2011 of Dividends_th_GBP
2019 of Accruals_&_Def._Inc._(short_t.)_th_GBP
2018 of Accruals_&_Def._Inc._(short_t.)_th_GBP
2017 of Accruals_&_Def._Inc._(short_t.)_th_GBP
2016 of Accruals_&_Def._Inc._(short_t.)_th_GBP
2015 of Accruals_&_Def._Inc._(short_t.)_th_GBP
2014 of Accruals_&_Def._Inc._(short_t.)_th_GBP
2013 of Accruals_&_Def._Inc._(short_t.)_th_GBP
2012 of Accruals_&_Def._Inc._(short_t.)_th_GBP
2011 of Accruals_&_Def._Inc._(short_t.)_th_GBP
2019 of Social_Securities_&_V.A.T._th_GBP
2018 of Social_Securities_&_V.A.T._th_GBP
2017 of Social_Securities_&_V.A.T._th_GBP
2016 of Social_Securities_&_V.A.T._th_GBP
2015 of Social_Securities_&_V.A.T._th_GBP
2014 of Social_Securities_&_V.A.T._th_GBP
2013 of Social_Securities_&_V.A.T._th_GBP
2012 of Social_Securities_&_V.A.T._th_GBP
2011 of Social_Securities_&_V.A.T._th_GBP
2019 of Other_Current_Liabilities_th_GBP
2018 of Other_Current_Liabilities_th_GBP
2017 of Other_Current_Liabilities_th_GBP
2016 of Other_Current_Liabilities_th_GBP
2015 of Other_Current_Liabilities_th_GBP
2014 of Other_Current_Liabilities_th_GBP
2013 of Other_Current_Liabilities_th_GBP
2012 of Other_Current_Liabilities_th_GBP
2011 of Other_Current_Liabilities_th_GBP
2019 of Current_Liabilities_th_GBP
2018 of Current_Liabilities_th_GBP
2017 of Current_Liabilities_th_GBP
2016 of Current_Liabilities_th_GBP
2015 of Current_Liabilities_th_GBP
2014 of Current_Liabilities_th_GBP
2013 of Current_Liabilities_th_GBP
2012 of Current_Liabilities_th_GBP
2011 of Current_Liabilities_th_GBP
2019 of Net_Current_Assets_(Working_Capital)_th_GBP
2018 of Net_Current_Assets_(Working_Capital)_th_GBP
2017 of Net_Current_Assets_(Working_Capital)_th_GBP
2016 of Net_Current_Assets_(Working_Capital)_th_GBP
2015 of Net_Current_Assets_(Working_Capital)_th_GBP
2014 of Net_Current_Assets_(Working_Capital)_th_GBP
2013 of Net_Current_Assets_(Working_Capital)_th_GBP
2012 of Net_Current_Assets_(Working_Capital)_th_GBP
2011 of Net_Current_Assets_(Working_Capital)_th_GBP
2019.1 of Net_Tangible_Assets_(Liab.)_th_GBP
2018.1 of Net_Tangible_Assets_(Liab.)_th_GBP
2017.1 of Net_Tangible_Assets_(Liab.)_th_GBP
2016.1 of Net_Tangible_Assets_(Liab.)_th_GBP
2015.1 of Net_Tangible_Assets_(Liab.)_th_GBP
2014.1 of Net_Tangible_Assets_(Liab.)_th_GBP
2013.1 of Net_Tangible_Assets_(Liab.)_th_GBP
2012.1 of Net_Tangible_Assets_(Liab.)_th_GBP
2011.1 of Net_Tangible_Assets_(Liab.)_th_GBP
2019 of Working_Capital_needs_th_GBP
2018 of Working_Capital_needs_th_GBP
2017 of Working_Capital_needs_th_GBP
2016 of Working_Capital_needs_th_GBP
2015 of Working_Capital_needs_th_GBP
2014 of Working_Capital_needs_th_GBP
2013 of Working_Capital_needs_th_GBP
2012 of Working_Capital_needs_th_GBP
2011 of Working_Capital_needs_th_GBP
2019 of Total_Assets_th_GBP
2018 of Total_Assets_th_GBP
2017 of Total_Assets_th_GBP
2016 of Total_Assets_th_GBP
2015 of Total_Assets_th_GBP
2014 of Total_Assets_th_GBP
2013 of Total_Assets_th_GBP
2012 of Total_Assets_th_GBP
2011 of Total_Assets_th_GBP
2019 of Total_Assets_less_Cur._Liab._th_GBP
2018 of Total_Assets_less_Cur._Liab._th_GBP
2017 of Total_Assets_less_Cur._Liab._th_GBP
2016 of Total_Assets_less_Cur._Liab._th_GBP
2015 of Total_Assets_less_Cur._Liab._th_GBP
2014 of Total_Assets_less_Cur._Liab._th_GBP
2013 of Total_Assets_less_Cur._Liab._th_GBP
2012 of Total_Assets_less_Cur._Liab._th_GBP
2011 of Total_Assets_less_Cur._Liab._th_GBP
2019 of Long_Term_Debt_th_GBP
2018 of Long_Term_Debt_th_GBP
2017 of Long_Term_Debt_th_GBP
2016 of Long_Term_Debt_th_GBP
2015 of Long_Term_Debt_th_GBP
2014 of Long_Term_Debt_th_GBP
2013 of Long_Term_Debt_th_GBP
2012 of Long_Term_Debt_th_GBP
2011 of Long_Term_Debt_th_GBP
2019 of Group_Loans_(long_t.)_th_GBP
2018 of Group_Loans_(long_t.)_th_GBP
2017 of Group_Loans_(long_t.)_th_GBP
2016 of Group_Loans_(long_t.)_th_GBP
2015 of Group_Loans_(long_t.)_th_GBP
2014 of Group_Loans_(long_t.)_th_GBP
2013 of Group_Loans_(long_t.)_th_GBP
2012 of Group_Loans_(long_t.)_th_GBP
2011 of Group_Loans_(long_t.)_th_GBP
2019 of Director_Loans_(long_t.)_th_GBP
2018 of Director_Loans_(long_t.)_th_GBP
2017 of Director_Loans_(long_t.)_th_GBP
2016 of Director_Loans_(long_t.)_th_GBP
2015 of Director_Loans_(long_t.)_th_GBP
2014 of Director_Loans_(long_t.)_th_GBP
2013 of Director_Loans_(long_t.)_th_GBP
2012 of Director_Loans_(long_t.)_th_GBP
2011 of Director_Loans_(long_t.)_th_GBP
2019 of Hire_Purch._&_Leas._(long_t.)_th_GBP
2018 of Hire_Purch._&_Leas._(long_t.)_th_GBP
2017 of Hire_Purch._&_Leas._(long_t.)_th_GBP
2016 of Hire_Purch._&_Leas._(long_t.)_th_GBP
2015 of Hire_Purch._&_Leas._(long_t.)_th_GBP
2014 of Hire_Purch._&_Leas._(long_t.)_th_GBP
2013 of Hire_Purch._&_Leas._(long_t.)_th_GBP
2012 of Hire_Purch._&_Leas._(long_t.)_th_GBP
2011 of Hire_Purch._&_Leas._(long_t.)_th_GBP
2019 of Hire_Purchase_(long_t.)_th_GBP
2018 of Hire_Purchase_(long_t.)_th_GBP
2017 of Hire_Purchase_(long_t.)_th_GBP
2016 of Hire_Purchase_(long_t.)_th_GBP
2015 of Hire_Purchase_(long_t.)_th_GBP
2014 of Hire_Purchase_(long_t.)_th_GBP
2013 of Hire_Purchase_(long_t.)_th_GBP
2012 of Hire_Purchase_(long_t.)_th_GBP
2011 of Hire_Purchase_(long_t.)_th_GBP
2019 of Leasing_(long_t.)_th_GBP
2018 of Leasing_(long_t.)_th_GBP
2017 of Leasing_(long_t.)_th_GBP
2016 of Leasing_(long_t.)_th_GBP
2015 of Leasing_(long_t.)_th_GBP
2014 of Leasing_(long_t.)_th_GBP
2013 of Leasing_(long_t.)_th_GBP
2012 of Leasing_(long_t.)_th_GBP
2011 of Leasing_(long_t.)_th_GBP
2019 of Preference_Shares_th_GBP
2018 of Preference_Shares_th_GBP
2017 of Preference_Shares_th_GBP
2016 of Preference_Shares_th_GBP
2015 of Preference_Shares_th_GBP
2014 of Preference_Shares_th_GBP
2013 of Preference_Shares_th_GBP
2012 of Preference_Shares_th_GBP
2011 of Preference_Shares_th_GBP
2019 of Other_Long_Term_Loans_th_GBP
2018 of Other_Long_Term_Loans_th_GBP
2017 of Other_Long_Term_Loans_th_GBP
2016 of Other_Long_Term_Loans_th_GBP

2016 of Paid_on_Leasing_th_GBP
2015 of Paid_on_Leasing_th_GBP
2014 of Paid_on_Leasing_th_GBP
2013 of Paid_on_Leasing_th_GBP
2012 of Paid_on_Leasing_th_GBP
2011 of Paid_on_Leasing_th_GBP
2019 of Other_Interest_Paid_th_GBP
2018 of Other_Interest_Paid_th_GBP
2017 of Other_Interest_Paid_th_GBP
2016 of Other_Interest_Paid_th_GBP
2015 of Other_Interest_Paid_th_GBP
2014 of Other_Interest_Paid_th_GBP
2013 of Other_Interest_Paid_th_GBP
2012 of Other_Interest_Paid_th_GBP
2011 of Other_Interest_Paid_th_GBP
2019 of Net_Interest_th_GBP
2018 of Net_Interest_th_GBP
2017 of Net_Interest_th_GBP
2016 of Net_Interest_th_GBP
2015 of Net_Interest_th_GBP
2014 of Net_Interest_th_GBP
2013 of Net_Interest_th_GBP
2012 of Net_Interest_th_GBP
2011 of Net_Interest_th_GBP
2019 of Profit_(Loss)_before_Tax_th_GBP
2018 of Profit_(Loss)_before_Tax_th_GBP
2017 of Profit_(Loss)_before_Tax_th_GBP
2016 of Profit_(Loss)_before_Tax_th_GBP
2015 of Profit_(Loss)_before_Tax_th_GBP
2014 of Profit_(Loss)_before_Tax_th_GBP
2013 of Profit_(Loss)_before_Tax_th_GBP
2012 of Profit_(Loss)_before_Tax_th_GBP
2011 of Profit_(Loss)_before_Tax_th_GBP
2019 of Taxation_th_GBP
2018 of Taxation_th_GBP
2017 of Taxation_th_GBP
2016 of Taxation_th_GBP
2015 of Taxation_th_GBP
2014 of Taxation_th_GBP
2013 of Taxation_th_GBP
2012 of Taxation_th_GBP
2011 of Taxation_th_GBP
2019 of Profit_(Loss)_after_Tax_th_GBP
2018 of Profit_(Loss)_after_Tax_th_GBP
2017 of Profit_(Loss)_after_Tax_th_GBP
2016 of Profit_(Loss)_after_Tax_th_GBP
2015 of Profit_(Loss)_after_Tax_th_GBP
2014 of Profit_(Loss)_after_Tax_th_GBP
2013 of Profit_(Loss)_after_Tax_th_GBP
2012 of Profit_(Loss)_after_Tax_th_GBP
2011 of Profit_(Loss)_after_Tax_th_GBP
2019 of Extraordinary_Items_th_GBP
2018 of Extraordinary_Items_th_GBP
2017 of Extraordinary_Items_th_GBP
2016 of Extraordinary_Items_th_GBP
2015 of Extraordinary_Items_th_GBP
2014 of Extraordinary_Items_th_GBP
2013 of Extraordinary_Items_th_GBP
2012 of Extraordinary_Items_th_GBP
2011 of Extraordinary_Items_th_GBP
2019 of Minority_Interests_th_GBP
2018 of Minority_Interests_th_GBP
2017 of Minority_Interests_th_GBP
2016 of Minority_Interests_th_GBP
2015 of Minority_Interests_th_GBP
2014 of Minority_Interests_th_GBP
2013 of Minority_Interests_th_GBP
2012 of Minority_Interests_th_GBP
2011 of Minority_Interests_th_GBP
2019 of Profit_(Loss)_for_period_[=Net_income]_th_GBP
2018 of Profit_(Loss)_for_period_[=Net_income]_th_GBP
2017 of Profit_(Loss)_for_period_[=Net_income]_th_GBP
2016 of Profit_(Loss)_for_period_[=Net_income]_th_GBP
2015 of Profit_(Loss)_for_period_[=Net_income]_th_GBP
2014 of Profit_(Loss)_for_period_[=Net_income]_th_GBP
2013 of Profit_(Loss)_for_period_[=Net_income]_th_GBP
2012 of Profit_(Loss)_for_period_[=Net_income]_th_GBP
2011 of Profit_(Loss)_for_period_[=Net_income]_th_GBP
2019.1 of Dividends_th_GBP
2018.1 of Dividends_th_GBP
2017.1 of Dividends_th_GBP
2016.1 of Dividends_th_GBP
2015.1 of Dividends_th_GBP
2014.1 of Dividends_th_GBP
2013.1 of Dividends_th_GBP
2012.1 of Dividends_th_GBP
2011.1 of Dividends_th_GBP
2019 of Retained_Profit(Loss)_th_GBP
2018 of Retained_Profit(Loss)_th_GBP
2017 of Retained_Profit(Loss)_th_GBP
2016 of Retained_Profit(Loss)_th_GBP
2015 of Retained_Profit(Loss)_th_GBP
2014 of Retained_Profit(Loss)_th_GBP
2013 of Retained_Profit(Loss)_th_GBP
2012 of Retained_Profit(Loss)_th_GBP
2011 of Retained_Profit(Loss)_th_GBP
2019 of Depreciation_th_GBP
2018 of Depreciation_th_GBP
2017 of Depreciation_th_GBP
2016 of Depreciation_th_GBP
2015 of Depreciation_th_GBP
2014 of Depreciation_th_GBP
2013 of Depreciation_th_GBP
2012 of Depreciation_th_GBP
2011 of Depreciation_th_GBP
2019 of Depreciation_Owned_Assets_th_GBP
2018 of Depreciation_Owned_Assets_th_GBP
2017 of Depreciation_Owned_Assets_th_GBP
2016 of Depreciation_Owned_Assets_th_GBP
2015 of Depreciation_Owned_Assets_th_GBP
2014 of Depreciation_Owned_Assets_th_GBP
2013 of Depreciation_Owned_Assets_th_GBP
2012 of Depreciation_Owned_Assets_th_GBP
2011 of Depreciation_Owned_Assets_th_GBP
2019 of Depreciation_Other_Assets_th_GBP
2018 of Depreciation_Other_Assets_th_GBP
2017 of Depreciation_Other_Assets_th_GBP
2016 of Depreciation_Other_Assets_th_GBP
2015 of Depreciation_Other_Assets_th_GBP
2014 of Depreciation_Other_Assets_th_GBP
2013 of Depreciation_Other_Assets_th_GBP
2012 of Depreciation_Other_Assets_th_GBP
2011 of Depreciation_Other_Assets_th_GBP
2019 of Impairment_Tangibles_th_GBP
2018 of Impairment_Tangibles_th_GBP
2017 of Impairment_Tangibles_th_GBP
2016 of Impairment_Tangibles_th_GBP
2015 of Impairment_Tangibles_th_GBP
2014 of Impairment_Tangibles_th_GBP
2013 of Impairment_Tangibles_th_GBP
2012 of Impairment_Tangibles_th_GBP
2011 of Impairment_Tangibles_th_GBP
2019 of Audit_Fee_th_GBP
2018 of Audit_Fee_th_GBP
2017 of Audit_Fee_th_GBP
2016 of Audit_Fee_th_GBP
2015 of Audit_Fee_th_GBP
2014 of Audit_Fee_th_GBP
2013 of Audit_Fee_th_GBP
2012 of Audit_Fee_th_GBP
2011 of Audit_Fee_th_GBP
2019 of Non-Audit_Fee_th_GBP
2018 of Non-Audit_Fee_th_GBP
2017 of Non-Audit_Fee_th_GBP
2016 of Non-Audit_Fee_th_GBP
2015 of Non-Audit_Fee_th_GBP
2014 of Non-Audit_Fee_th_GBP
2013 of Non-Audit_Fee_th_GBP
2012 of Non-Audit_Fee_th_GBP
2011 of Non-Audit_Fee_th_GBP
2019 of Tax_Advice_th_GBP
2018 of Tax_Advice_th_GBP
2017 of Tax_Advice_th_GBP
2016 of Tax_Advice_th_GBP
2015 of Tax_Advice_th_GBP
2014 of Tax_Advice_th_GBP
2013 of Tax_Advice_th_GBP
2012 of Tax_Advice_th_GBP
2011 of Tax_Advice_th_GBP
2019 of Non-Tax_Advisory_Services_th_GBP
2018 of Non-Tax_Advisory_Services_th_GBP
2017 of Non-Tax_Advisory_Services_th_GBP
2016 of Non-Tax_Advisory_Services_th_GBP
2015 of Non-Tax_Advisory_Services_th_GBP
2014 of Non-Tax_Advisory_Services_th_GBP
2013 of Non-Tax_Advisory_Services_th_GBP
2012 of Non-Tax_Advisory_Services_th_GBP
2011 of Non-Tax_Advisory_Services_th_GBP
2019 of Other_Auditors_Services_th_GBP
2018 of Other_Auditors_Services_th_GBP
2017 of Other_Auditors_Services_th_GBP
2016 of Other_Auditors_Services_th_GBP
2015 of Other_Auditors_Services_th_GBP
2014 of Other_Auditors_Services_th_GBP
2013 of Other_Auditors_Services_th_GBP
2012 of Other_Auditors_Services_th_GBP
2011 of Other_Auditors_Services_th_GBP
2019 of Non-Audit_Fees_paid_to_Other_Auditors_th_GBP
2018 of Non-Audit_Fees_paid_to_Other_Auditors_th_GBP
2017 of Non-Audit_Fees_paid_to_Other_Auditors_th_GBP
2016 of Non-Audit_Fees_paid_to_Other_Auditors_th_GBP
2015 of Non-Audit_Fees_paid_to_Other_Auditors_th_GBP
2014 of Non-Audit_Fees_paid_to_Other_Auditors_th_GBP
2013 of Non-Audit_Fees_paid_to_Other_Auditors_th_GBP
2012 of Non-Audit_Fees_paid_to_Other_Auditors_th_GBP
2011 of Non-Audit_Fees_paid_to_Other_Auditors_th_GBP
2019 of Total_Amortization_and_Impairment_th_GBP
2018 of Total_Amortization_and_Impairment_th_GBP
2017 of Total_Amortization_and_Impairment_th_GBP
2016 of Total_Amortization_and_Impairment_th_GBP
2015 of Total_Amortization_and_Impairment_th_GBP
2014 of Total_Amortization_and_Impairment_th_GBP
2013 of Total_Amortization_and_Impairment_th_GBP
2012 of Total_Amortization_and_Impairment_th_GBP
2011 of Total_Amortization_and_Impairment_th_GBP
2019 of Amortisation_th_GBP
2018 of Amortisation_th_GBP
2017 of Amortisation_th_GBP
2016 of Amortisation_th_GBP
2015 of Amortisation_th_GBP
2014 of Amortisation_th_GBP
2013 of Amortisation_th_GBP
2012 of Amortisation_th_GBP
2011 of Amortisation_th_GBP
2019 of Impairment_th_GBP
2018 of Impairment_th_GBP
2017 of Impairment_th_GBP
2016 of Impairment_th_GBP
2015 of Impairment_th_GBP
2014 of Impairment_th_GBP
2013 of Impairment_th_GBP
2012 of Impairment_th_GBP
2011 of Impairment_th_GBP
2019 of Total_Operating_Lease_Rentals_th_GBP
2018 of Total_Operating_Lease_Rentals_th_GBP
2017 of Total_Operating_Lease_Rentals_th_GBP
2016 of Total_Operating_Lease_Rentals_th_GBP
2015 of Total_Operating_Lease_Rentals_th_GBP
2014 of Total_Operating_Lease_Rentals_th_GBP
2013 of Total_Operating_Lease_Rentals_th_GBP
2012 of Total_Operating_Lease_Rentals_th_GBP
2011 of Total_Operating_Lease_Rentals_th_GBP
2019 of Hire_of_Plant_&_Machinery_th_GBP
2018 of Hire_of_Plant_&_Machinery_th_GBP
2017 of Hire_of_Plant_&_Machinery_th_GBP
2016 of Hire_of_Plant_&_Machinery_th_GBP
2015 of Hire_of_Plant_&_Machinery_th_GBP
2014 of Hire_of_Plant_&_Machinery_th_GBP
2013 of Hire_of_Plant_&_Machinery_th_GBP
2012 of Hire_of_Plant_&_Machinery_th_GBP
2011 of Hire_of_Plant_&_Machinery_th_GBP
2019 of Land_&_Building_or_Property_Rents_&_Other_th_GBP
2018 of Land_&_Building_or_Property_Rents_&_Other_th_GBP
2017 of Land_&_Building_or_Property_Rents_&_Other_th_GBP
2016 of Land_&_Building_or_Property_Rents_&_Other_th_GBP
2015 of Land_&_Building_or_Property_Rents_&_Other_th_GBP
2014 of Land_&_Building_or_Property_Rents_&_Other_th_GBP
2013 of Land_&_Building_or_Property_Rents_&_Other_th_GBP
2012 of Land_&_Building_or_Property_Rents_&_Other_th_GBP
2011 of Land_&_Building_or_Property_Rents_&_Other_th_GBP
2019 of Research_&_Development_th_GBP
2018 of Research_&_Development_th_GBP
2017 of Research_&_Development_th_GBP
2016 of Research_&_Development_th_GBP
2015 of Research_&_Development_th_GBP
2014 of Research_&_Development_th_GBP
2013 of Research_&_Development_th_GBP
2012 of Research_&_Development_th_GBP
2011 of Research_&_Development_th_GBP
2019 of Foreign_Exchange_Gains/Losses_th_GBP
2018 of Foreign_Exchange_Gains/Losses_th_GBP
2017 of Foreign_Exchange_Gains/Losses_th_GBP
2016 of Foreign_Exchange_Gains/Losses_th_GBP
2015 of Foreign_Exchange_Gains/Losses_th_GBP
2014 of Foreign_Exchange_Gains/Losses_th_GBP
2013 of Foreign_Exchange_Gains/Losses_th_GBP
2012 of Foreign_Exchange_Gains/Losses_th_GBP
2011 of Foreign_Exchange_Gains/Losses_th_GBP
2019 of Remuneration_th_GBP
2018 of Remuneration_th_GBP
2017 of Remuneration_th_GBP
2016 of Remuneration_th_GBP
2015 of Remuneration_th_GBP
2014 of Remuneration_th_GBP
2013 of Remuneration_th_GBP
2012 of Remuneration_th_GBP
2011 of Remuneration_th_GBP
2019 of Wages_&_Salaries_th_GBP
2018 of Wages_&_Salaries_th_GBP
2017 of Wages_&_Salaries_th_GBP
2016 of Wages_&_Salaries_th_GBP
2015 of Wages_&_Salaries_th_GBP
2014 of Wages_&_Salaries_th_GBP
2013 of Wages_&_Salaries_th_GBP
2012 of Wages_&_Salaries_th_GBP
2011 of Wages_&_Salaries_th_GBP
2019 of Social_Security_Costs_th_GBP
2018 of Social_Security_Costs_th_GBP
2017 of Social_Security_Costs_th_GBP
2016 of Social_Security_Costs_th_GBP
2015 of Social_Security_Costs_th_GBP
2014 of Social_Security_Costs_th_GBP
2013 of Social_Security_Costs_th_GBP
2012 of Social_Security_Costs_th_GBP
2011 of Social_Security_Costs_th_GBP
2019 of Pension_Costs_th_GBP
2018 of Pension_Costs_th_GBP
2017 of Pension_Costs_th_GBP
2016 of Pension_Costs_th_GBP
2015 of Pension_Costs_th_GBP
2014 of Pension_Costs_th_GBP
2013 of Pension_Costs_th_GBP
2012 of Pension_Costs_th_GBP
2011 of Pension_Costs_th_GBP
2019 of Other_Staff_Costs_th_GBP
2018 of Other_Staff_Costs_th_GBP
2017 of Other_Staff_Costs_th_GBP
2016 of Other_Staff_Costs_th_GBP
2015 of Other_Staff_Costs_th_GBP
2014 of Other_Staff_Costs_th_GBP
2013 of Other_Staff_Costs_th_GBP
2012 of Other_Staff_Costs_th_GBP
2011 of Other_Staff_Costs_th_GBP
2019 of Directors'_Remuneration_th_GBP
2018 of Directors'_Remuneration_th_GBP
2017 of Directors'_Remuneration_th_GBP
2016 of Directors'_Remuneration_th_GBP
2015 of Directors'_Remuneration_th_GBP
2014 of Directors'_Remuneration_th_GBP
2013 of Directors'_Remuneration_th_GBP
2012 of Directors'_Remuneration_th_GBP
2011 of Directors'_Remuneration_th_GBP
2019 of Directors'_Fees_th_GBP
2018 of Directors'_Fees_th_GBP
2017 of Directors'_Fees_th_GBP
2016 of Directors'_Fees_th_GBP
2015 of Directors'_Fees_th_GBP
2014 of Directors'_Fees_th_GBP
2013 of Directors'_Fees_th_GBP
2012 of Directors'_Fees_th_GBP
2011 of Directors'_Fees_th_GBP
2019 of Pension_Contribution_th_GBP
2018 of Pension_Contribution_th_GBP
2017 of Pension_Contribution_th_GBP
2016 of Pension_Contribution_th_GBP
2015 of Pension_Contribution_th_GBP
2014 of Pension_Contribution_th_GBP
2013 of Pension_Contribution_th_GBP
2012 of Pension_Contribution_th_GBP
2011 of Pension_Contribution_th_GBP
2019 of Other_Emoluments_th_GBP
2018 of Other_Emoluments_th_GBP
2017 of Other_Emoluments_th_GBP
2016 of Other_Emoluments_th_GBP
2015 of Other_Emoluments_th_GBP
2014 of Other_Emoluments_th_GBP
2013 of Other_Emoluments_th_GBP
2012 of Other_Emoluments_th_GBP
2011 of Other_Emoluments_th_GBP
2019 of Highest_Paid_Director_th_GBP
2018 of Highest_Paid_Director_th_GBP
2017 of Highest_Paid_Director_th_GBP
2016 of Highest_Paid_Director_th_GBP
2015 of Highest_Paid_Director_th_GBP
2014 of Highest_Paid_Director_th_GBP
2013 of Highest_Paid_Director_th_GBP
2012 of Highest_Paid_Director_th_GBP
2011 of Highest_Paid_Director_th_GBP
2019 of EBITDA_th_GBP
2018 of EBITDA_th_GBP
2017 of EBITDA_th_GBP
2016 of EBITDA_th_GBP
2015 of EBITDA_th_GBP
2014 of EBITDA_th_GBP
2013 of EBITDA_th_GBP
2012 of EBITDA_th_GBP
2011 of EBITDA_th_GBP
2019.1 of Number_of_employees
2018.1 of Number_of_employees
2017.1 of Number_of_employees
2016.1 of Number_of_employees
2015.1 of Number_of_employees
2014.1 of Number_of_employees
2013.1 of Number_of_employees
2012.1 of Number_of_employees
2011.1 of Number_of_employees
2019 of Cash_In(Out)flow_Operat._Activ._th_GBP
2018 of Cash_In(Out)flow_Operat._Activ._th_GBP
2017 of Cash_In(Out)flow_Operat._Activ._th_GBP
2016 of Cash_In(Out)flow_Operat._Activ._th_GBP
2015 of Cash_In(Out)flow_Operat._Activ._th_GBP
2014 of Cash_In(Out)flow_Operat._Activ._th_GBP
2013 of Cash_In(Out)flow_Operat._Activ._th_GBP
2012 of Cash_In(Out)flow_Operat._Activ._th_GBP
2011 of Cash_In(Out)flow_Operat._Activ._th_GBP
2019 of Cash_In(Out)flow_Ret._on_Invest._th_GBP
2018 of Cash_In(Out)flow_Ret._on_Invest._th_GBP
2017 of Cash_In(Out)flow_Ret._on_Invest._th_GBP
2016 of Cash_In(Out)flow_Ret._on_Invest._th_GBP
2015 of Cash_In(Out)flow_Ret._on_Invest._th_GBP
2014 of Cash_In(Out)flow_Ret._on_Invest._th_GBP
2013 of Cash_In(Out)flow_Ret._on_Invest._th_GBP
2012 of Cash_In(Out)flow_Ret._on_Invest._th_GBP
2011 of Cash_In(Out)flow_Ret._on_Invest._th_GBP
2019.1 of Taxation_th_GBP
2018.1 of Taxation_th_GBP
2017.1 of Taxation_th_GBP
2016.1 of Taxation_th_GBP
2015.1 of Taxation_th_GBP
2014.1 of Taxation_th_GBP
2013.1 of Taxation_th_GBP
2012.1 of Taxation_th_GBP
2011.1 of Taxation_th_GBP
2019 of Cash_Out(In)flow_Investing_Activ._th_GBP
2018 of Cash_Out(In)flow_Investing_Activ._th_GBP
2017 of Cash_Out(In)flow_Investing_Activ._th_GBP
2016 of Cash_Out(In)flow_Investing_Activ._th_GBP
2015 of Cash_Out(In)flow_Investing_Activ._th_GBP
2014 of Cash_Out(In)flow_Investing_Activ._th_GBP
2013 of Cash_Out(In)flow_Investing_Activ._th_GBP
2012 of Cash_Out(In)flow_Investing_Activ._th_GBP
2011 of Cash_Out(In)flow_Investing_Activ._th_GBP
2019 of Capital_Expenditure_&_Financ._Invest._th_GBP
2018 of Capital_Expenditure_&_Financ._Invest._th_GBP
2017 of Capital_Expenditure_&_Financ._Invest._th_GBP
2016 of Capital_Expenditure_&_Financ._Invest._th_GBP
2015 of Capital_Expenditure_&_Financ._Invest._th_GBP
2014 of Capital_Expenditure_&_Financ._Invest._th_GBP
2013 of Capital_Expenditure_&_Financ._Invest._th_GBP
2012 of Capital_Expenditure_&_Financ._Invest._th_GBP
2011 of Capital_Expenditure_&_Financ._Invest._th_GBP
2019 of Acquisition_&_Disposal_th_GBP
2018 of Acquisition_&_Disposal_th_GBP
2017 of Acquisition_&_Disposal_th_GBP
2016 of Acquisition_&_Disposal_th_GBP
2015 of Acquisition_&_Disposal_th_GBP
2014 of Acquisition_&_Disposal_th_GBP
2013 of Acquisition_&_Disposal_th_GBP
2012 of Acquisition_&_Disposal_th_GBP
2011 of Acquisition_&_Disposal_th_GBP
2019 of Equity_Dividends_Paid_th_GBP
2018 of Equity_Dividends_Paid_th_GBP
2017 of Equity_Dividends_Paid_th_GBP
2016 of Equity_Dividends_Paid_th_GBP
2015 of Equity_Dividends_Paid_th_GBP
2014 of Equity_Dividends_Paid_th_GBP
2013 of Equity_Dividends_Paid_th_GBP
2012 of Equity_Dividends_Paid_th_GBP
2011 of Equity_Dividends_Paid_th_GBP
2019 of Management_of_Liquid_Resources_th_GBP
2018 of Management_of_Liquid_Resources_th_GBP
2017 of Management_of_Liquid_Resources_th_GBP
2016 of Management_of_Liquid_Resources_th_GBP
2015 of Management_of_Liquid_Resources_th_GBP
2014 of Management_of_Liquid_Resources_th_GBP
2013 of Management_of_Liquid_Resources_th_GBP
2012 of Management_of_Liquid_Resources_th_GBP
2011 of Management_of_Liquid_Resources_th_GBP
2019 of Cash_Out(In)flow_from_Financing_th_GBP
2018 of Cash_Out(In)flow_from_Financing_th_GBP
2017 of Cash_Out(In)flow_from_Financing_th_GBP
2016 of Cash_Out(In)flow_from_Financing_th_GBP
2015 of Cash_Out(In)flow_from_Financing_th_GBP
2014 of Cash_Out(In)flow_from_Financing_th_GBP
2013 of Cash_Out(In)flow_from_Financing_th_GBP
2012 of Cash_Out(In)flow_from_Financing_th_GBP
2011 of Cash_Out(In)flow_from_Financing_th_GBP
2019 of Increase(Decrease)_Cash_&_Equiv._th_GBP
2018 of Increase(Decrease)_Cash_&_Equiv._th_GBP
2017 of Increase(Decrease)_Cash_&_Equiv._th_GBP
2016 of Increase(Decrease)_Cash_&_Equiv._th_GBP
2015 of Increase(Decrease)_Cash_&_Equiv._th_GBP
2014 of Increase(Decrease)_Cash_&_Equiv._th_GBP
2013 of Increase(Decrease)_Cash_&_Equiv._th_GBP
2012 of Increase(Decrease)_Cash_&_Equiv._th_GBP
2011 of Increase(Decrease)_Cash_&_Equiv._th_GBP
2019 of Return_on_Shareholders_Funds_(%)
2018 of Return_on_Shareholders_Funds_(%)
2017 of Return_on_Shareholders_Funds_(%)
2016 of Return_on_Shareholders_Funds_(%)
2015 of Return_on_Shareholders_Funds_(%)
2014 of Return_on_Shareholders_Funds_(%)
2013 of Return_on_Shareholders_Funds_(%)
2012 of Return_on_Shareholders_Funds_(%)
2011 of Return_on_Shareholders_Funds_(%)
2019 of Return_on_Capital_Employed_(%)
2018 of Return_on_Capital_Employed_(%)
2017 of Return_on_Capital_Employed_(%)
2016 of Return_on_Capital_Employed_(%)
2015 of Return_on_Capital_Employed_(%)
2014 of Return_on_Capital_Employed_(%)
2013 of Return_on_Capital_Employed_(%)
2012 of Return_on_Capital_Employed_(%)
2011 of Return_on_Capital_Employed_(%)
2019 of Return_on_Total_Assets_(%)
2018 of Return_on_Total_Assets_(%)
2017 of Return_on_Total_Assets_(%)
2016 of Return_on_Total_Assets_(%)
2015 of Return_on_Total_Assets_(%)
2014 of Return_on_Total_Assets_(%)
2013 of Return_on_Total_Assets_(%)
2012 of Return_on_Total_Assets_(%)
2011 of Return_on_Total_Assets_(%)
2019 of Profit_margin_(%)
2018 of Profit_margin_(%)
2017 of Profit_margin_(%)
2016 of Profit_margin_(%)
2015 of Profit_margin_(%)
2014 of Profit_margin_(%)
2013 of Profit_margin_(%)
2012 of Profit_margin_(%)
2011 of Profit_margin_(%)
2019 of Gross_margin_(%)
2018 of Gross_margin_(%)
2017 of Gross_margin_(%)
2016 of Gross_margin_(%)
2015 of Gross_margin_(%)
2014 of Gross_margin_(%)
2013 of Gross_margin_(%)
2012 of Gross_margin_(%)
2011 of Gross_margin_(%)
2019 of Berry_ratio_(x)
2018 of Berry_ratio_(x)
2017 of Berry_ratio_(x)
2016 of Berry_ratio_(x)
2015 of Berry_ratio_(x)
2014 of Berry_ratio_(x)
2013 of Berry_ratio_(x)
2012 of Berry_ratio_(x)
2011 of Berry_ratio_(x)
2019 of EBIT_margin_(%)
2018 of EBIT_margin_(%)
2017 of EBIT_margin_(%)
2016 of EBIT_margin_(%)
2015 of EBIT_margin_(%)
2014 of EBIT_margin_(%)
2013 of EBIT_margin_(%)
2012 of EBIT_margin_(%)
2011 of EBIT_margin_(%)
2019 of EBITDA_margin_(%)
2018 of EBITDA_margin_(%)
2017 of EBITDA_margin_(%)
2016 of EBITDA_margin_(%)
2015 of EBITDA_margin_(%)
2014 of EBITDA_margin_(%)
2013 of EBITDA_margin_(%)
2012 of EBITDA_margin_(%)
2011 of EBITDA_margin_(%)
2019 of Net_Assets_Turnover_(x)
2018 of Net_Assets_Turnover_(x)
2017 of Net_Assets_Turnover_(x)
2016 of Net_Assets_Turnover_(x)
2015 of Net_Assets_Turnover_(x)
2014 of Net_Assets_Turnover_(x)
2013 of Net_Assets_Turnover_(x)
2012 of Net_Assets_Turnover_(x)
2011 of Net_Assets_Turnover_(x)
2019 of Fixed_Assets_Turnover_(x)
2018 of Fixed_Assets_Turnover_(x)
2017 of Fixed_Assets_Turnover_(x)
2016 of Fixed_Assets_Turnover_(x)
2015 of Fixed_Assets_Turnover_(x)
2014 of Fixed_Assets_Turnover_(x)
2013 of Fixed_Assets_Turnover_(x)
2012 of Fixed_Assets_Turnover_(x)
2011 of Fixed_Assets_Turnover_(x)
2019 of Interest_Cover_(x)
2018 of Interest_Cover_(x)
2017 of Interest_Cover_(x)
2016 of Interest_Cover_(x)
2015 of Interest_Cover_(x)
2014 of Interest_Cover_(x)
2013 of Interest_Cover_(x)
2012 of Interest_Cover_(x)
2011 of Interest_Cover_(x)

In [7]:
gifi_dictionary

{'Turnover\nth GBP 2019': ('Turnover_th_GBP', 2019),
 'Turnover\nth GBP 2018': ('Turnover_th_GBP', 2018),
 'Turnover\nth GBP 2017': ('Turnover_th_GBP', 2017),
 'Turnover\nth GBP 2016': ('Turnover_th_GBP', 2016),
 'Turnover\nth GBP 2015': ('Turnover_th_GBP', 2015),
 'Turnover\nth GBP 2014': ('Turnover_th_GBP', 2014),
 'Turnover\nth GBP 2013': ('Turnover_th_GBP', 2013),
 'Turnover\nth GBP 2012': ('Turnover_th_GBP', 2012),
 'Turnover\nth GBP 2011': ('Turnover_th_GBP', 2011),
 'Profit (Loss) before Taxation\nth GBP 2019': ('Profit_(Loss)_before_Taxation_th_GBP',
  2019),
 'Profit (Loss) before Taxation\nth GBP 2018': ('Profit_(Loss)_before_Taxation_th_GBP',
  2018),
 'Profit (Loss) before Taxation\nth GBP 2017': ('Profit_(Loss)_before_Taxation_th_GBP',
  2017),
 'Profit (Loss) before Taxation\nth GBP 2016': ('Profit_(Loss)_before_Taxation_th_GBP',
  2016),
 'Profit (Loss) before Taxation\nth GBP 2015': ('Profit_(Loss)_before_Taxation_th_GBP',
  2015),
 'Profit (Loss) before Taxation\nth GBP 2014': ('Profit_(Loss)_before_Taxation_th_GBP',
  2014),
 'Profit (Loss) before Taxation\nth GBP 2013': ('Profit_(Loss)_before_Taxation_th_GBP',
  2013),
 'Profit (Loss) before Taxation\nth GBP 2012': ('Profit_(Loss)_before_Taxation_th_GBP',
  2012),
 'Profit (Loss) before Taxation\nth GBP 2011': ('Profit_(Loss)_before_Taxation_th_GBP',
  2011),
 'Net Tangible Assets (Liab.)\nth GBP 2019': ('Net_Tangible_Assets_(Liab.)_th_GBP',
  2019),
 'Net Tangible Assets (Liab.)\nth GBP 2018': ('Net_Tangible_Assets_(Liab.)_th_GBP',
  2018),
 'Net Tangible Assets (Liab.)\nth GBP 2017': ('Net_Tangible_Assets_(Liab.)_th_GBP',
  2017),
 'Net Tangible Assets (Liab.)\nth GBP 2016': ('Net_Tangible_Assets_(Liab.)_th_GBP',
  2016),
 'Net Tangible Assets (Liab.)\nth GBP 2015': ('Net_Tangible_Assets_(Liab.)_th_GBP',
  2015),
 'Net Tangible Assets (Liab.)\nth GBP 2014': ('Net_Tangible_Assets_(Liab.)_th_GBP',
  2014),
 'Net Tangible Assets (Liab.)\nth GBP 2013': ('Net_Tangible_Assets_(Liab.)_th_GBP',
  2013),
 'Net Tangible Assets (Liab.)\nth GBP 2012': ('Net_Tangible_Assets_(Liab.)_th_GBP',
  2012),
 'Net Tangible Assets (Liab.)\nth GBP 2011': ('Net_Tangible_Assets_(Liab.)_th_GBP',
  2011),
 'Shareholders Funds\nth GBP 2019': ('Shareholders_Funds_th_GBP', 2019),
 'Shareholders Funds\nth GBP 2018': ('Shareholders_Funds_th_GBP', 2018),
 'Shareholders Funds\nth GBP 2017': ('Shareholders_Funds_th_GBP', 2017),
 'Shareholders Funds\nth GBP 2016': ('Shareholders_Funds_th_GBP', 2016),
 'Shareholders Funds\nth GBP 2015': ('Shareholders_Funds_th_GBP', 2015),
 'Shareholders Funds\nth GBP 2014': ('Shareholders_Funds_th_GBP', 2014),
 'Shareholders Funds\nth GBP 2013': ('Shareholders_Funds_th_GBP', 2013),
 'Shareholders Funds\nth GBP 2012': ('Shareholders_Funds_th_GBP', 2012),
 'Shareholders Funds\nth GBP 2011': ('Shareholders_Funds_th_GBP', 2011),
 'Profit Margin\n2019': ('Profit_Margin', 2019),
 'Profit Margin\n2018': ('Profit_Margin', 2018),
 'Profit Margin\n2017': ('Profit_Margin', 2017),
 'Profit Margin\n2016': ('Profit_Margin', 2016),
 'Profit Margin\n2015': ('Profit_Margin', 2015),
 'Profit Margin\n2014': ('Profit_Margin', 2014),
 'Profit Margin\n2013': ('Profit_Margin', 2013),
 'Profit Margin\n2012': ('Profit_Margin', 2012),
 'Profit Margin\n2011': ('Profit_Margin', 2011),
 'Return on Shareholders Funds\n2019': ('Return_on_Shareholders_Funds', 2019),
 'Return on Shareholders Funds\n2018': ('Return_on_Shareholders_Funds', 2018),
 'Return on Shareholders Funds\n2017': ('Return_on_Shareholders_Funds', 2017),
 'Return on Shareholders Funds\n2016': ('Return_on_Shareholders_Funds', 2016),
 'Return on Shareholders Funds\n2015': ('Return_on_Shareholders_Funds', 2015),
 'Return on Shareholders Funds\n2014': ('Return_on_Shareholders_Funds', 2014),
 'Return on Shareholders Funds\n2013': ('Return_on_Shareholders_Funds', 2013),
 'Return on Shareholders Funds\n2012': ('Return_on_Shareholders_Funds', 2012),
 'Return on Shareholders Funds\n2011': ('Return_on_Shareholders_Funds', 2011),
 'Return on Capital Employed\n2019': ('Return_on_Capital_Employed', 2019),
 'Return on Capital Employed\n2018': ('Return_on_Capital_Employed', 2018),
 'Return on Capital Employed\n2017': ('Return_on_Capital_Employed', 2017),
 'Return on Capital Employed\n2016': ('Return_on_Capital_Employed', 2016),
 'Return on Capital Employed\n2015': ('Return_on_Capital_Employed', 2015),
 'Return on Capital Employed\n2014': ('Return_on_Capital_Employed', 2014),
 'Return on Capital Employed\n2013': ('Return_on_Capital_Employed', 2013),
 'Return on Capital Employed\n2012': ('Return_on_Capital_Employed', 2012),
 'Return on Capital Employed\n2011': ('Return_on_Capital_Employed', 2011),
 'Liquidity Ratio (x)\n2019': ('Liquidity_Ratio_(x)', 2019),
 'Liquidity Ratio (x)\n2018': ('Liquidity_Ratio_(x)', 2018),
 'Liquidity Ratio (x)\n2017': ('Liquidity_Ratio_(x)', 2017),
 'Liquidity Ratio (x)\n2016': ('Liquidity_Ratio_(x)', 2016),
 'Liquidity Ratio (x)\n2015': ('Liquidity_Ratio_(x)', 2015),
 'Liquidity Ratio (x)\n2014': ('Liquidity_Ratio_(x)', 2014),
 'Liquidity Ratio (x)\n2013': ('Liquidity_Ratio_(x)', 2013),
 'Liquidity Ratio (x)\n2012': ('Liquidity_Ratio_(x)', 2012),
 'Liquidity Ratio (x)\n2011': ('Liquidity_Ratio_(x)', 2011),
 'Gearing (%)\n2019': ('Gearing_(%)', 2019),
 'Gearing (%)\n2018': ('Gearing_(%)', 2018),
 'Gearing (%)\n2017': ('Gearing_(%)', 2017),
 'Gearing (%)\n2016': ('Gearing_(%)', 2016),
 'Gearing (%)\n2015': ('Gearing_(%)', 2015),
 'Gearing (%)\n2014': ('Gearing_(%)', 2014),
 'Gearing (%)\n2013': ('Gearing_(%)', 2013),
 'Gearing (%)\n2012': ('Gearing_(%)', 2012),
 'Gearing (%)\n2011': ('Gearing_(%)', 2011),
 'Number of employees\n2019': ('Number_of_employees', 2019),
 'Number of employees\n2018': ('Number_of_employees', 2018),
 'Number of employees\n2017': ('Number_of_employees', 2017),
 'Number of employees\n2016': ('Number_of_employees', 2016),
 'Number of employees\n2015': ('Number_of_employees', 2015),
 'Number of employees\n2014': ('Number_of_employees', 2014),
 'Number of employees\n2013': ('Number_of_employees', 2013),
 'Number of employees\n2012': ('Number_of_employees', 2012),
 'Number of employees\n2011': ('Number_of_employees', 2011),
 'Tangible Assets\nth GBP 2019': ('Tangible_Assets_th_GBP', 2019),
 'Tangible Assets\nth GBP 2018': ('Tangible_Assets_th_GBP', 2018),
 'Tangible Assets\nth GBP 2017': ('Tangible_Assets_th_GBP', 2017),
 'Tangible Assets\nth GBP 2016': ('Tangible_Assets_th_GBP', 2016),
 'Tangible Assets\nth GBP 2015': ('Tangible_Assets_th_GBP', 2015),
 'Tangible Assets\nth GBP 2014': ('Tangible_Assets_th_GBP', 2014),
 'Tangible Assets\nth GBP 2013': ('Tangible_Assets_th_GBP', 2013),
 'Tangible Assets\nth GBP 2012': ('Tangible_Assets_th_GBP', 2012),
 'Tangible Assets\nth GBP 2011': ('Tangible_Assets_th_GBP', 2011),
 'Land & Buildings\nth GBP 2019': ('Land_&_Buildings_th_GBP', 2019),
 'Land & Buildings\nth GBP 2018': ('Land_&_Buildings_th_GBP', 2018),
 'Land & Buildings\nth GBP 2017': ('Land_&_Buildings_th_GBP', 2017),
 'Land & Buildings\nth GBP 2016': ('Land_&_Buildings_th_GBP', 2016),
 'Land & Buildings\nth GBP 2015': ('Land_&_Buildings_th_GBP', 2015),
 'Land & Buildings\nth GBP 2014': ('Land_&_Buildings_th_GBP', 2014),
 'Land & Buildings\nth GBP 2013': ('Land_&_Buildings_th_GBP', 2013),
 'Land & Buildings\nth GBP 2012': ('Land_&_Buildings_th_GBP', 2012),
 'Land & Buildings\nth GBP 2011': ('Land_&_Buildings_th_GBP', 2011),
 'Freehold Land\nth GBP 2019': ('Freehold_Land_th_GBP', 2019),
 'Freehold Land\nth GBP 2018': ('Freehold_Land_th_GBP', 2018),
 'Freehold Land\nth GBP 2017': ('Freehold_Land_th_GBP', 2017),
 'Freehold Land\nth GBP 2016': ('Freehold_Land_th_GBP', 2016),
 'Freehold Land\nth GBP 2015': ('Freehold_Land_th_GBP', 2015),
 'Freehold Land\nth GBP 2014': ('Freehold_Land_th_GBP', 2014),
 'Freehold Land\nth GBP 2013': ('Freehold_Land_th_GBP', 2013),
 'Freehold Land\nth GBP 2012': ('Freehold_Land_th_GBP', 2012),
 'Freehold Land\nth GBP 2011': ('Freehold_Land_th_GBP', 2011),
 'Leasehold Land\nth GBP 2019': ('Leasehold_Land_th_GBP', 2019),
 'Leasehold Land\nth GBP 2018': ('Leasehold_Land_th_GBP', 2018),
 'Leasehold Land\nth GBP 2017': ('Leasehold_Land_th_GBP', 2017),
 'Leasehold Land\nth GBP 2016': ('Leasehold_Land_th_GBP', 2016),
 'Leasehold Land\nth GBP 2015': ('Leasehold_Land_th_GBP', 2015),
 'Leasehold Land\nth GBP 2014': ('Leasehold_Land_th_GBP', 2014),
 'Leasehold Land\nth GBP 2013': ('Leasehold_Land_th_GBP', 2013),
 'Leasehold Land\nth GBP 2012': ('Leasehold_Land_th_GBP', 2012),
 'Leasehold Land\nth GBP 2011': ('Leasehold_Land_th_GBP', 2011),
 'Fixtures & Fittings\nth GBP 2019': ('Fixtures_&_Fittings_th_GBP', 2019),
 'Fixtures & Fittings\nth GBP 2018': ('Fixtures_&_Fittings_th_GBP', 2018),
 'Fixtures & Fittings\nth GBP 2017': ('Fixtures_&_Fittings_th_GBP', 2017),
 'Fixtures & Fittings\nth GBP 2016': ('Fixtures_&_Fittings_th_GBP', 2016),
 'Fixtures & Fittings\nth GBP 2015': ('Fixtures_&_Fittings_th_GBP', 2015),
 'Fixtures & Fittings\nth GBP 2014': ('Fixtures_&_Fittings_th_GBP', 2014),
 'Fixtures & Fittings\nth GBP 2013': ('Fixtures_&_Fittings_th_GBP', 2013),
 'Fixtures & Fittings\nth GBP 2012': ('Fixtures_&_Fittings_th_GBP', 2012),
 'Fixtures & Fittings\nth GBP 2011': ('Fixtures_&_Fittings_th_GBP', 2011),
 'Plant & Vehicles\nth GBP 2019': ('Plant_&_Vehicles_th_GBP', 2019),
 'Plant & Vehicles\nth GBP 2018': ('Plant_&_Vehicles_th_GBP', 2018),
 'Plant & Vehicles\nth GBP 2017': ('Plant_&_Vehicles_th_GBP', 2017),
 'Plant & Vehicles\nth GBP 2016': ('Plant_&_Vehicles_th_GBP', 2016),
 'Plant & Vehicles\nth GBP 2015': ('Plant_&_Vehicles_th_GBP', 2015),
 'Plant & Vehicles\nth GBP 2014': ('Plant_&_Vehicles_th_GBP', 2014),
 'Plant & Vehicles\nth GBP 2013': ('Plant_&_Vehicles_th_GBP', 2013),
 'Plant & Vehicles\nth GBP 2012': ('Plant_&_Vehicles_th_GBP', 2012),
 'Plant & Vehicles\nth GBP 2011': ('Plant_&_Vehicles_th_GBP', 2011),
 'Plant\nth GBP 2019': ('Plant_th_GBP', 2019),
 'Plant\nth GBP 2018': ('Plant_th_GBP', 2018),
 'Plant\nth GBP 2017': ('Plant_th_GBP', 2017),
 'Plant\nth GBP 2016': ('Plant_th_GBP', 2016),
 'Plant\nth GBP 2015': ('Plant_th_GBP', 2015),
 'Plant\nth GBP 2014': ('Plant_th_GBP', 2014),
 'Plant\nth GBP 2013': ('Plant_th_GBP', 2013),
 'Plant\nth GBP 2012': ('Plant_th_GBP', 2012),
 'Plant\nth GBP 2011': ('Plant_th_GBP', 2011),
 'Vehicles\nth GBP 2019': ('Vehicles_th_GBP', 2019),
 'Vehicles\nth GBP 2018': ('Vehicles_th_GBP', 2018),
 'Vehicles\nth GBP 2017': ('Vehicles_th_GBP', 2017),
 'Vehicles\nth GBP 2016': ('Vehicles_th_GBP', 2016),
 'Vehicles\nth GBP 2015': ('Vehicles_th_GBP', 2015),
 'Vehicles\nth GBP 2014': ('Vehicles_th_GBP', 2014),
 'Vehicles\nth GBP 2013': ('Vehicles_th_GBP', 2013),
 'Vehicles\nth GBP 2012': ('Vehicles_th_GBP', 2012),
 'Vehicles\nth GBP 2011': ('Vehicles_th_GBP', 2011),
 'Other Fixed Assets\nth GBP 2019': ('Other_Fixed_Assets_th_GBP', 2019),
 'Other Fixed Assets\nth GBP 2018': ('Other_Fixed_Assets_th_GBP', 2018),
 'Other Fixed Assets\nth GBP 2017': ('Other_Fixed_Assets_th_GBP', 2017),
 'Other Fixed Assets\nth GBP 2016': ('Other_Fixed_Assets_th_GBP', 2016),
 'Other Fixed Assets\nth GBP 2015': ('Other_Fixed_Assets_th_GBP', 2015),
 'Other Fixed Assets\nth GBP 2014': ('Other_Fixed_Assets_th_GBP', 2014),
 'Other Fixed Assets\nth GBP 2013': ('Other_Fixed_Assets_th_GBP', 2013),
 'Other Fixed Assets\nth GBP 2012': ('Other_Fixed_Assets_th_GBP', 2012),
 'Other Fixed Assets\nth GBP 2011': ('Other_Fixed_Assets_th_GBP', 2011),
 'Intangible Assets\nth GBP 2019': ('Intangible_Assets_th_GBP', 2019),
 'Intangible Assets\nth GBP 2018': ('Intangible_Assets_th_GBP', 2018),
 'Intangible Assets\nth GBP 2017': ('Intangible_Assets_th_GBP', 2017),
 'Intangible Assets\nth GBP 2016': ('Intangible_Assets_th_GBP', 2016),
 'Intangible Assets\nth GBP 2015': ('Intangible_Assets_th_GBP', 2015),
 'Intangible Assets\nth GBP 2014': ('Intangible_Assets_th_GBP', 2014),
 'Intangible Assets\nth GBP 2013': ('Intangible_Assets_th_GBP', 2013),
 'Intangible Assets\nth GBP 2012': ('Intangible_Assets_th_GBP', 2012),
 'Intangible Assets\nth GBP 2011': ('Intangible_Assets_th_GBP', 2011),
 'Investments\nth GBP 2019': ('Investments_th_GBP', 2019),
 'Investments\nth GBP 2018': ('Investments_th_GBP', 2018),
 'Investments\nth GBP 2017': ('Investments_th_GBP', 2017),
 'Investments\nth GBP 2016': ('Investments_th_GBP', 2016),
 'Investments\nth GBP 2015': ('Investments_th_GBP', 2015),
 'Investments\nth GBP 2014': ('Investments_th_GBP', 2014),
 'Investments\nth GBP 2013': ('Investments_th_GBP', 2013),
 'Investments\nth GBP 2012': ('Investments_th_GBP', 2012),
 'Investments\nth GBP 2011': ('Investments_th_GBP', 2011),
 'Fixed Assets\nth GBP 2019': ('Fixed_Assets_th_GBP', 2019),
 'Fixed Assets\nth GBP 2018': ('Fixed_Assets_th_GBP', 2018),
 'Fixed Assets\nth GBP 2017': ('Fixed_Assets_th_GBP', 2017),
 'Fixed Assets\nth GBP 2016': ('Fixed_Assets_th_GBP', 2016),
 'Fixed Assets\nth GBP 2015': ('Fixed_Assets_th_GBP', 2015),
 'Fixed Assets\nth GBP 2014': ('Fixed_Assets_th_GBP', 2014),
 'Fixed Assets\nth GBP 2013': ('Fixed_Assets_th_GBP', 2013),
 'Fixed Assets\nth GBP 2012': ('Fixed_Assets_th_GBP', 2012),
 'Fixed Assets\nth GBP 2011': ('Fixed_Assets_th_GBP', 2011),
 'Stock & W.I.P.\nth GBP 2019': ('Stock_&_W.I.P._th_GBP', 2019),
 'Stock & W.I.P.\nth GBP 2018': ('Stock_&_W.I.P._th_GBP', 2018),
 'Stock & W.I.P.\nth GBP 2017': ('Stock_&_W.I.P._th_GBP', 2017),
 'Stock & W.I.P.\nth GBP 2016': ('Stock_&_W.I.P._th_GBP', 2016),
 'Stock & W.I.P.\nth GBP 2015': ('Stock_&_W.I.P._th_GBP', 2015),
 'Stock & W.I.P.\nth GBP 2014': ('Stock_&_W.I.P._th_GBP', 2014),
 'Stock & W.I.P.\nth GBP 2013': ('Stock_&_W.I.P._th_GBP', 2013),
 'Stock & W.I.P.\nth GBP 2012': ('Stock_&_W.I.P._th_GBP', 2012),
 'Stock & W.I.P.\nth GBP 2011': ('Stock_&_W.I.P._th_GBP', 2011),
 'Stock\nth GBP 2019': ('Stock_th_GBP', 2019),
 'Stock\nth GBP 2018': ('Stock_th_GBP', 2018),
 'Stock\nth GBP 2017': ('Stock_th_GBP', 2017),
 'Stock\nth GBP 2016': ('Stock_th_GBP', 2016),
 'Stock\nth GBP 2015': ('Stock_th_GBP', 2015),
 'Stock\nth GBP 2014': ('Stock_th_GBP', 2014),
 'Stock\nth GBP 2013': ('Stock_th_GBP', 2013),
 'Stock\nth GBP 2012': ('Stock_th_GBP', 2012),
 'Stock\nth GBP 2011': ('Stock_th_GBP', 2011),
 'W.I.P.\nth GBP 2019': ('W.I.P._th_GBP', 2019),
 'W.I.P.\nth GBP 2018': ('W.I.P._th_GBP', 2018),
 'W.I.P.\nth GBP 2017': ('W.I.P._th_GBP', 2017),
 'W.I.P.\nth GBP 2016': ('W.I.P._th_GBP', 2016),
 'W.I.P.\nth GBP 2015': ('W.I.P._th_GBP', 2015),
 'W.I.P.\nth GBP 2014': ('W.I.P._th_GBP', 2014),
 'W.I.P.\nth GBP 2013': ('W.I.P._th_GBP', 2013),
 'W.I.P.\nth GBP 2012': ('W.I.P._th_GBP', 2012),
 'W.I.P.\nth GBP 2011': ('W.I.P._th_GBP', 2011),
 'Finished Goods\nth GBP 2019': ('Finished_Goods_th_GBP', 2019),
 'Finished Goods\nth GBP 2018': ('Finished_Goods_th_GBP', 2018),
 'Finished Goods\nth GBP 2017': ('Finished_Goods_th_GBP', 2017),
 'Finished Goods\nth GBP 2016': ('Finished_Goods_th_GBP', 2016),
 'Finished Goods\nth GBP 2015': ('Finished_Goods_th_GBP', 2015),
 'Finished Goods\nth GBP 2014': ('Finished_Goods_th_GBP', 2014),
 'Finished Goods\nth GBP 2013': ('Finished_Goods_th_GBP', 2013),
 'Finished Goods\nth GBP 2012': ('Finished_Goods_th_GBP', 2012),
 'Finished Goods\nth GBP 2011': ('Finished_Goods_th_GBP', 2011),
 'Trade Debtors\nth GBP 2019': ('Trade_Debtors_th_GBP', 2019),
 'Trade Debtors\nth GBP 2018': ('Trade_Debtors_th_GBP', 2018),
 'Trade Debtors\nth GBP 2017': ('Trade_Debtors_th_GBP', 2017),
 'Trade Debtors\nth GBP 2016': ('Trade_Debtors_th_GBP', 2016),
 'Trade Debtors\nth GBP 2015': ('Trade_Debtors_th_GBP', 2015),
 'Trade Debtors\nth GBP 2014': ('Trade_Debtors_th_GBP', 2014),
 'Trade Debtors\nth GBP 2013': ('Trade_Debtors_th_GBP', 2013),
 'Trade Debtors\nth GBP 2012': ('Trade_Debtors_th_GBP', 2012),
 'Trade Debtors\nth GBP 2011': ('Trade_Debtors_th_GBP', 2011),
 'Bank & Deposits\nth GBP 2019': ('Bank_&_Deposits_th_GBP', 2019),
 'Bank & Deposits\nth GBP 2018': ('Bank_&_Deposits_th_GBP', 2018),
 'Bank & Deposits\nth GBP 2017': ('Bank_&_Deposits_th_GBP', 2017),
 'Bank & Deposits\nth GBP 2016': ('Bank_&_Deposits_th_GBP', 2016),
 'Bank & Deposits\nth GBP 2015': ('Bank_&_Deposits_th_GBP', 2015),
 'Bank & Deposits\nth GBP 2014': ('Bank_&_Deposits_th_GBP', 2014),
 'Bank & Deposits\nth GBP 2013': ('Bank_&_Deposits_th_GBP', 2013),
 'Bank & Deposits\nth GBP 2012': ('Bank_&_Deposits_th_GBP', 2012),
 'Bank & Deposits\nth GBP 2011': ('Bank_&_Deposits_th_GBP', 2011),
 'Other Current Assets\nth GBP 2019': ('Other_Current_Assets_th_GBP', 2019),
 'Other Current Assets\nth GBP 2018': ('Other_Current_Assets_th_GBP', 2018),
 'Other Current Assets\nth GBP 2017': ('Other_Current_Assets_th_GBP', 2017),
 'Other Current Assets\nth GBP 2016': ('Other_Current_Assets_th_GBP', 2016),
 'Other Current Assets\nth GBP 2015': ('Other_Current_Assets_th_GBP', 2015),
 'Other Current Assets\nth GBP 2014': ('Other_Current_Assets_th_GBP', 2014),
 'Other Current Assets\nth GBP 2013': ('Other_Current_Assets_th_GBP', 2013),
 'Other Current Assets\nth GBP 2012': ('Other_Current_Assets_th_GBP', 2012),
 'Other Current Assets\nth GBP 2011': ('Other_Current_Assets_th_GBP', 2011),
 'Group Loans (asset)\nth GBP 2019': ('Group_Loans_(asset)_th_GBP', 2019),
 'Group Loans (asset)\nth GBP 2018': ('Group_Loans_(asset)_th_GBP', 2018),
 'Group Loans (asset)\nth GBP 2017': ('Group_Loans_(asset)_th_GBP', 2017),
 'Group Loans (asset)\nth GBP 2016': ('Group_Loans_(asset)_th_GBP', 2016),
 'Group Loans (asset)\nth GBP 2015': ('Group_Loans_(asset)_th_GBP', 2015),
 'Group Loans (asset)\nth GBP 2014': ('Group_Loans_(asset)_th_GBP', 2014),
 'Group Loans (asset)\nth GBP 2013': ('Group_Loans_(asset)_th_GBP', 2013),
 'Group Loans (asset)\nth GBP 2012': ('Group_Loans_(asset)_th_GBP', 2012),
 'Group Loans (asset)\nth GBP 2011': ('Group_Loans_(asset)_th_GBP', 2011),
 'Directors Loans (asset)\nth GBP 2019': ('Directors_Loans_(asset)_th_GBP',
  2019),
 'Directors Loans (asset)\nth GBP 2018': ('Directors_Loans_(asset)_th_GBP',
  2018),
 'Directors Loans (asset)\nth GBP 2017': ('Directors_Loans_(asset)_th_GBP',
  2017),
 'Directors Loans (asset)\nth GBP 2016': ('Directors_Loans_(asset)_th_GBP',
  2016),
 'Directors Loans (asset)\nth GBP 2015': ('Directors_Loans_(asset)_th_GBP',
  2015),
 'Directors Loans (asset)\nth GBP 2014': ('Directors_Loans_(asset)_th_GBP',
  2014),
 'Directors Loans (asset)\nth GBP 2013': ('Directors_Loans_(asset)_th_GBP',
  2013),
 'Directors Loans (asset)\nth GBP 2012': ('Directors_Loans_(asset)_th_GBP',
  2012),
 'Directors Loans (asset)\nth GBP 2011': ('Directors_Loans_(asset)_th_GBP',
  2011),
 'Other Debtors\nth GBP 2019': ('Other_Debtors_th_GBP', 2019),
 'Other Debtors\nth GBP 2018': ('Other_Debtors_th_GBP', 2018),
 'Other Debtors\nth GBP 2017': ('Other_Debtors_th_GBP', 2017),
 'Other Debtors\nth GBP 2016': ('Other_Debtors_th_GBP', 2016),
 'Other Debtors\nth GBP 2015': ('Other_Debtors_th_GBP', 2015),
 'Other Debtors\nth GBP 2014': ('Other_Debtors_th_GBP', 2014),
 'Other Debtors\nth GBP 2013': ('Other_Debtors_th_GBP', 2013),
 'Other Debtors\nth GBP 2012': ('Other_Debtors_th_GBP', 2012),
 'Other Debtors\nth GBP 2011': ('Other_Debtors_th_GBP', 2011),
 'Prepayments\nth GBP 2019': ('Prepayments_th_GBP', 2019),
 'Prepayments\nth GBP 2018': ('Prepayments_th_GBP', 2018),
 'Prepayments\nth GBP 2017': ('Prepayments_th_GBP', 2017),
 'Prepayments\nth GBP 2016': ('Prepayments_th_GBP', 2016),
 'Prepayments\nth GBP 2015': ('Prepayments_th_GBP', 2015),
 'Prepayments\nth GBP 2014': ('Prepayments_th_GBP', 2014),
 'Prepayments\nth GBP 2013': ('Prepayments_th_GBP', 2013),
 'Prepayments\nth GBP 2012': ('Prepayments_th_GBP', 2012),
 'Prepayments\nth GBP 2011': ('Prepayments_th_GBP', 2011),
 'Deferred Taxation\nth GBP 2019': ('Deferred_Taxation_th_GBP', 2019),
 'Deferred Taxation\nth GBP 2018': ('Deferred_Taxation_th_GBP', 2018),
 'Deferred Taxation\nth GBP 2017': ('Deferred_Taxation_th_GBP', 2017),
 'Deferred Taxation\nth GBP 2016': ('Deferred_Taxation_th_GBP', 2016),
 'Deferred Taxation\nth GBP 2015': ('Deferred_Taxation_th_GBP', 2015),
 'Deferred Taxation\nth GBP 2014': ('Deferred_Taxation_th_GBP', 2014),

In [8]:
gifi_columns

['Turnover_th_GBP',
 'Profit_(Loss)_before_Taxation_th_GBP',
 'Net_Tangible_Assets_(Liab.)_th_GBP',
 'Shareholders_Funds_th_GBP',
 'Profit_Margin',
 'Return_on_Shareholders_Funds',
 'Return_on_Capital_Employed',
 'Liquidity_Ratio_(x)',
 'Gearing_(%)',
 'Number_of_employees',
 'Tangible_Assets_th_GBP',
 'Land_&_Buildings_th_GBP',
 'Freehold_Land_th_GBP',
 'Leasehold_Land_th_GBP',
 'Fixtures_&_Fittings_th_GBP',
 'Plant_&_Vehicles_th_GBP',
 'Plant_th_GBP',
 'Vehicles_th_GBP',
 'Other_Fixed_Assets_th_GBP',
 'Intangible_Assets_th_GBP',
 'Investments_th_GBP',
 'Fixed_Assets_th_GBP',
 'Stock_&_W.I.P._th_GBP',
 'Stock_th_GBP',
 'W.I.P._th_GBP',
 'Finished_Goods_th_GBP',
 'Trade_Debtors_th_GBP',
 'Bank_&_Deposits_th_GBP',
 'Other_Current_Assets_th_GBP',
 'Group_Loans_(asset)_th_GBP',
 'Directors_Loans_(asset)_th_GBP',
 'Other_Debtors_th_GBP',
 'Prepayments_th_GBP',
 'Deferred_Taxation_th_GBP',
 'Current_Assets_th_GBP',
 'Trade_Creditors_th_GBP',
 'Short_Term_Loans_&_Overdrafts_th_GBP',
 'Bank_Overdrafts_th_GBP',
 'Group_Loans_(short_t.)_th_GBP',
 'Director_Loans_(short_t.)_th_GBP',
 'Hire_Purch._&_Leas._(short_t.)_th_GBP',
 'Hire_Purchase_(short_t.)_th_GBP',
 'Leasing_(short_t.)_th_GBP',
 'Other_Short_Term_Loans_th_GBP',
 'Total_Other_Current_Liabilities_th_GBP',
 'Corporation_Tax_th_GBP',
 'Dividends_th_GBP',
 'Accruals_&_Def._Inc._(short_t.)_th_GBP',
 'Social_Securities_&_V.A.T._th_GBP',
 'Other_Current_Liabilities_th_GBP',
 'Current_Liabilities_th_GBP',
 'Net_Current_Assets_(Working_Capital)_th_GBP',
 'Working_Capital_needs_th_GBP',
 'Total_Assets_th_GBP',
 'Total_Assets_less_Cur._Liab._th_GBP',
 'Long_Term_Debt_th_GBP',
 'Group_Loans_(long_t.)_th_GBP',
 'Director_Loans_(long_t.)_th_GBP',
 'Hire_Purch._&_Leas._(long_t.)_th_GBP',
 'Hire_Purchase_(long_t.)_th_GBP',
 'Leasing_(long_t.)_th_GBP',
 'Preference_Shares_th_GBP',
 'Other_Long_Term_Loans_th_GBP',
 'Total_Other_Long_Term_Liab._th_GBP',
 'Accruals_&_Def._Inc._(long_t.)_th_GBP',
 'Other_Long_Term_Liab._th_GBP',
 'Provisions_for_Other_Liab._th_GBP',
 'Deferred_Tax_th_GBP',
 'Other_Provisions_th_GBP',
 'Pension_Liabilities_th_GBP',
 'Balance_sheet_Minorities_th_GBP',
 'Long_Term_Liabilities_th_GBP',
 'Net_assets_th_GBP',
 'Issued_Capital_th_GBP',
 'Ordinary_Shares_th_GBP',
 'Other_Shares_th_GBP',
 'Total_Reserves_th_GBP',
 'Share_Premium_Account_th_GBP',
 'Revaluation_Reserves_th_GBP',
 'Profit_(Loss)_Account_th_GBP',
 'Other_Reserves_th_GBP',
 'National_Turnover_th_GBP',
 'Overseas_Turnover_th_GBP',
 'Cost_of_Sales_th_GBP',
 'Exceptional_Items_pre_GP_th_GBP',
 'Other_Income_pre_GP_th_GBP',
 'Gross_Profit_th_GBP',
 'Administration_Expenses_th_GBP',
 'Other_Operating_Income/Costs_pre_OP_th_GBP',
 'Exceptional_Items_pre_OP_th_GBP',
 'Operating_Profit_th_GBP',
 'Other_Income_th_GBP',
 'Total_Other_Income_&_Int._Received_th_GBP',
 'Exceptional_Items_th_GBP',
 'Profit_(Loss)_on_Sale_of_Operations_th_GBP',
 'Costs_of_Reorganisation_th_GBP',
 'Profit_(Loss)_on_Disposal_th_GBP',
 'Other_Exceptional_Items_th_GBP',
 'Profit_(Loss)_before_Interest_paid_th_GBP',
 'Interest_Received_th_GBP',
 'Interest_Paid_th_GBP',
 'Paid_to_Bank_th_GBP',
 'Paid_on_Hire_Purchase_th_GBP',
 'Paid_on_Leasing_th_GBP',
 'Other_Interest_Paid_th_GBP',
 'Net_Interest_th_GBP',
 'Profit_(Loss)_before_Tax_th_GBP',
 'Taxation_th_GBP',
 'Profit_(Loss)_after_Tax_th_GBP',
 'Extraordinary_Items_th_GBP',
 'Minority_Interests_th_GBP',
 'Profit_(Loss)_for_period_[=Net_income]_th_GBP',
 'Retained_Profit(Loss)_th_GBP',
 'Depreciation_th_GBP',
 'Depreciation_Owned_Assets_th_GBP',
 'Depreciation_Other_Assets_th_GBP',
 'Impairment_Tangibles_th_GBP',
 'Audit_Fee_th_GBP',
 'Non-Audit_Fee_th_GBP',
 'Tax_Advice_th_GBP',
 'Non-Tax_Advisory_Services_th_GBP',
 'Other_Auditors_Services_th_GBP',
 'Non-Audit_Fees_paid_to_Other_Auditors_th_GBP',
 'Total_Amortization_and_Impairment_th_GBP',
 'Amortisation_th_GBP',
 'Impairment_th_GBP',
 'Total_Operating_Lease_Rentals_th_GBP',
 'Hire_of_Plant_&_Machinery_th_GBP',
 'Land_&_Building_or_Property_Rents_&_Other_th_GBP',
 'Research_&_Development_th_GBP',
 'Foreign_Exchange_Gains/Losses_th_GBP',
 'Remuneration_th_GBP',
 'Wages_&_Salaries_th_GBP',
 'Social_Security_Costs_th_GBP',
 'Pension_Costs_th_GBP',
 'Other_Staff_Costs_th_GBP',
 "Directors'_Remuneration_th_GBP",
 "Directors'_Fees_th_GBP",
 'Pension_Contribution_th_GBP',
 'Other_Emoluments_th_GBP',
 'Highest_Paid_Director_th_GBP',
 'EBITDA_th_GBP',
 'Cash_In(Out)flow_Operat._Activ._th_GBP',
 'Cash_In(Out)flow_Ret._on_Invest._th_GBP',
 'Cash_Out(In)flow_Investing_Activ._th_GBP',
 'Capital_Expenditure_&_Financ._Invest._th_GBP',
 'Acquisition_&_Disposal_th_GBP',
 'Equity_Dividends_Paid_th_GBP',
 'Management_of_Liquid_Resources_th_GBP',
 'Cash_Out(In)flow_from_Financing_th_GBP',
 'Increase(Decrease)_Cash_&_Equiv._th_GBP',
 'Return_on_Shareholders_Funds_(%)',
 'Return_on_Capital_Employed_(%)',
 'Return_on_Total_Assets_(%)',
 'Profit_margin_(%)',
 'Gross_margin_(%)',
 'Berry_ratio_(x)',
 'EBIT_margin_(%)',
 'EBITDA_margin_(%)',
 'Net_Assets_Turnover_(x)',
 'Fixed_Assets_Turnover_(x)',
 'Interest_Cover_(x)',
 'Stock_Turnover_(x)',
 'Debtors_Turnover_(x)',
 'Debtor_Collection_(days)',
 'Creditors_Payment_(days)',
 'Current_ratio_(x)',
 'Liquidity_ratio_(x)',
 'Shareholders_liquidity_ratio_(x)',
 'Solvency_ratio_(Asset_based)_(%)',
 'Solvency_ratio_(Liability_based)_(%)',
 'Asset_Cover_(x)',
 'Profit_per_employee_(unit)_GBP',
 'Turnover_per_employee_(unit)_GBP',
 'Salaries/Turnover',
 'Average_Remuneration_per_employee_(unit)_GBP',
 'Shareholders_Funds_per_employee_(unit)_GBP',
 'Working_Capital_per_employee_(unit)_GBP',
 'Total_Assets_per_employee_(unit)_GBP']

In [9]:
#gifi_df = None
same_column_df = None
store = pd.HDFStore('bdv-data-gifi.h5')
i=0
last_common_column_name = None
for col_name in fromhdf5.columns:
    if col_name in gifi_dictionary.keys():
        (common_column_name, year) = gifi_dictionary[col_name]
        # if column name changes 
        the_column_of_data = pd.DataFrame(data=fromhdf5[col_name],copy=True)
        print(the_column_of_data.size)
        the_column_of_data.dropna(inplace=True)
        print("After dropna size is:")
        print(the_column_of_data.size)
        the_column_of_data.rename_axis("bv_id",inplace=True)
        the_column_of_data['year'] = year
        the_column_of_data.set_index(['year'], append=True, inplace=True)
        the_column_of_data.rename(columns={col_name: common_column_name},inplace=True)
        # not first column
        if last_common_column_name is None:
            last_common_column_name = common_column_name # deal with the first column
        if not last_common_column_name == common_column_name:
            # new column name 
            store.put(last_common_column_name, same_column_df)
            same_column_df = None
            #if gifi_df is None:
            #    gifi_df = same_column_df
            #else:
                #gifi_df = gifi_df.join(same_column_df, how='outer', on=['bv_id','year'])
                #gifi_df.info(memory_usage=True)
                
            
        # accumulate same column with append
        if same_column_df is not None:
            same_column_df = same_column_df.append(the_column_of_data)
            same_column_df.info(memory_usage=True)
        else:
            same_column_df = the_column_of_data
        print(str(i))
        i=i+1
        last_common_column_name = common_column_name
        #if i > 128:
        #    break

store.close()

125990
After dropna size is:
59457
0
125990
After dropna size is:
66876
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 126333 entries, ('GB09567757', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Turnover_th_GBP  126333 non-null  float64
dtypes: float64(1)
memory usage: 2.3+ MB
1
125990
After dropna size is:
57652
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 183985 entries, ('GB09567757', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Turnover_th_GBP  183985 non-null  float64
dtypes: float64(1)
memory usage: 3.1+ MB
2
125990
After dropna size is:
45640
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 229625 entries, ('GB09567757', 2019) to ('GBSC452461', 2016)
Data columns (total 1 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Turnover_th_GBP  229625 non-null  float64
dtypes: float64(1)
memory usage: 3.7+ MB
3
125990
After dropna size is:
37067
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 266692 entries, ('GB09567757', 2019) to ('GBSC452461', 2015)
Data columns (total 1 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Turnover_th_GBP  266692 non-null  float64
dtypes: float64(1)
memory usage: 4.2+ MB
4
125990
After dropna size is:
31172
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 297864 entries, ('GB09567757', 2019) to ('GBOC369696', 2014)
Data columns (total 1 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Turnover_th_GBP  297864 non-null  float64
dtypes: float64(1)
memory usage: 4.6+ MB
5
125990
After dropna size is:
26370
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 324234 entries, ('GB09567757', 2019) to ('GBOC369696', 2013)
Data columns (total 1 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Turnover_th_GBP  324234 non-null  float64
dtypes: float64(1)
memory usage: 5.0+ MB
6
125990
After dropna size is:
19353
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 343587 entries, ('GB09567757', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Turnover_th_GBP  343587 non-null  float64
dtypes: float64(1)
memory usage: 5.2+ MB
7
125990
After dropna size is:
10314
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 353901 entries, ('GB09567757', 2019) to ('GB07266603', 2011)
Data columns (total 1 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Turnover_th_GBP  353901 non-null  float64
dtypes: float64(1)
memory usage: 5.3+ MB
8
125990
After dropna size is:
22983
9
125990
After dropna size is:
45470
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 68453 entries, ('GB09567757', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Profit_(Loss)_before_Taxation_th_GBP  68453 non-null  float64
dtypes: float64(1)
memory usage: 1.2+ MB
10
125990
After dropna size is:
54623
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 123076 entries, ('GB09567757', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   Profit_(Loss)_before_Taxation_th_GBP  123076 non-null  float64
dtypes: float64(1)
memory usage: 2.1+ MB
11
125990
After dropna size is:
43364
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 166440 entries, ('GB09567757', 2019) to ('GBOC381395', 2016)
Data columns (total 1 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   Profit_(Loss)_before_Taxation_th_GBP  166440 non-null  float64
dtypes: float64(1)
memory usage: 2.7+ MB
12
125990
After dropna size is:
35630
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 202070 entries, ('GB09567757', 2019) to ('GBSC452461', 2015)
Data columns (total 1 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   Profit_(Loss)_before_Taxation_th_GBP  202070 non-null  float64
dtypes: float64(1)
memory usage: 3.2+ MB
13
125990
After dropna size is:
30353
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 232423 entries, ('GB09567757', 2019) to ('GBOC369696', 2014)
Data columns (total 1 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   Profit_(Loss)_before_Taxation_th_GBP  232423 non-null  float64
dtypes: float64(1)
memory usage: 3.7+ MB
14
125990
After dropna size is:
26149
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 258572 entries, ('GB09567757', 2019) to ('GBOC369696', 2013)
Data columns (total 1 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   Profit_(Loss)_before_Taxation_th_GBP  258572 non-null  float64
dtypes: float64(1)
memory usage: 4.1+ MB
15
125990
After dropna size is:
19654
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 278226 entries, ('GB09567757', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   Profit_(Loss)_before_Taxation_th_GBP  278226 non-null  float64
dtypes: float64(1)
memory usage: 4.4+ MB
16
125990
After dropna size is:
10503
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 288729 entries, ('GB09567757', 2019) to ('GB07266603', 2011)
Data columns (total 1 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   Profit_(Loss)_before_Taxation_th_GBP  288729 non-null  float64
dtypes: float64(1)
memory usage: 4.5+ MB
17
125990
After dropna size is:
59539

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Profit_(Loss)_before_Taxation_th_GBP'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

18
125990
After dropna size is:
101397
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 160936 entries, ('GB09567757', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   Net_Tangible_Assets_(Liab.)_th_GBP  160936 non-null  float64
dtypes: float64(1)
memory usage: 2.8+ MB
19
125990
After dropna size is:
108869
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 269805 entries, ('GB09567757', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   Net_Tangible_Assets_(Liab.)_th_GBP  269805 non-null  float64
dtypes: float64(1)
memory usage: 4.2+ MB
20
125990
After dropna size is:
106118
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 375923 entries, ('GB09567757', 2019) to ('GBOC381395', 2016)
Data columns (total 1 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   Net_Tangible_Assets_(Liab.)_th_GBP  375923 non-null  float64
dtypes: float64(1)
memory usage: 5.5+ MB
21
125990
After dropna size is:
93707
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 469630 entries, ('GB09567757', 2019) to ('GBOC381395', 2015)
Data columns (total 1 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   Net_Tangible_Assets_(Liab.)_th_GBP  469630 non-null  float64
dtypes: float64(1)
memory usage: 6.7+ MB
22
125990
After dropna size is:
78650
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 548280 entries, ('GB09567757', 2019) to ('GBOC381395', 2014)
Data columns (total 1 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   Net_Tangible_Assets_(Liab.)_th_GBP  548280 non-null  float64
dtypes: float64(1)
memory usage: 7.7+ MB
23
125990
After dropna size is:
60527
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 608807 entries, ('GB09567757', 2019) to ('GBSC452461', 2013)
Data columns (total 1 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   Net_Tangible_Assets_(Liab.)_th_GBP  608807 non-null  float64
dtypes: float64(1)
memory usage: 8.5+ MB
24
125990
After dropna size is:
41458
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 650265 entries, ('GB09567757', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   Net_Tangible_Assets_(Liab.)_th_GBP  650265 non-null  float64
dtypes: float64(1)
memory usage: 9.0+ MB
25
125990
After dropna size is:
21033
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 671298 entries, ('GB09567757', 2019) to ('GB07266603', 2011)
Data columns (total 1 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   Net_Tangible_Assets_(Liab.)_th_GBP  671298 non-null  float64
dtypes: float64(1)
memory usage: 9.3+ MB
26
125990
After dropna size is:
58455

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Net_Tangible_Assets_(Liab.)_th_GBP'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

27
125990
After dropna size is:
99589
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 158044 entries, ('GB07588867', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Shareholders_Funds_th_GBP  158044 non-null  float64
dtypes: float64(1)
memory usage: 2.7+ MB
28
125990
After dropna size is:
106811
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 264855 entries, ('GB07588867', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Shareholders_Funds_th_GBP  264855 non-null  float64
dtypes: float64(1)
memory usage: 4.1+ MB
29
125990
After dropna size is:
103950
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 368805 entries, ('GB07588867', 2019) to ('GBOC381395', 2016)
Data columns (total 1 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Shareholders_Funds_th_GBP  368805 non-null  float64
dtypes: float64(1)
memory usage: 5.4+ MB
30
125990
After dropna size is:
91591
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 460396 entries, ('GB07588867', 2019) to ('GBSC452461', 2015)
Data columns (total 1 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Shareholders_Funds_th_GBP  460396 non-null  float64
dtypes: float64(1)
memory usage: 6.6+ MB
31
125990
After dropna size is:
76788
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 537184 entries, ('GB07588867', 2019) to ('GBSC452461', 2014)
Data columns (total 1 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Shareholders_Funds_th_GBP  537184 non-null  float64
dtypes: float64(1)
memory usage: 7.6+ MB
32
125990
After dropna size is:
58975
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 596159 entries, ('GB07588867', 2019) to ('GBSC452461', 2013)
Data columns (total 1 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Shareholders_Funds_th_GBP  596159 non-null  float64
dtypes: float64(1)
memory usage: 8.3+ MB
33
125990
After dropna size is:
40387
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 636546 entries, ('GB07588867', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Shareholders_Funds_th_GBP  636546 non-null  float64
dtypes: float64(1)
memory usage: 8.8+ MB
34
125990
After dropna size is:
20539
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 657085 entries, ('GB07588867', 2019) to ('GB07266603', 2011)
Data columns (total 1 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Shareholders_Funds_th_GBP  657085 non-null  float64
dtypes: float64(1)
memory usage: 9.1+ MB
35
125990
After dropna size is:
19513
36
125990
After dropna size is:
38286
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 57799 entries, ('GB09567757', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Profit_Margin  57799 non-null  float64
dtypes: float64(1)
memory usage: 1.1+ MB
37
125990
After dropna size is:
46265
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 104064 entries, ('GB09567757', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Profit_Margin  104064 non-null  float64
dtypes: float64(1)
memory usage: 1.8+ MB
38
125990
After dropna size is:
36088
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 140152 entries, ('GB09567757', 2019) to ('GBSC452461', 2016)
Data columns (total 1 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Profit_Margin  140152 non-null  float64
dtypes: float64(1)
memory usage: 2.3+ MB
39
125990
After dropna size is:
29814
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 169966 entries, ('GB09567757', 2019) to ('GBSC452461', 2015)
Data columns (total 1 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Profit_Margin  169966 non-null  float64
dtypes: float64(1)
memory usage: 2.8+ MB
40
125990
After dropna size is:
25563
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 195529 entries, ('GB09567757', 2019) to ('GB08389817', 2014)
Data columns (total 1 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Profit_Margin  195529 non-null  float64
dtypes: float64(1)
memory usage: 3.2+ MB
41
125990
After dropna size is:
22326
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 217855 entries, ('GB09567757', 2019) to ('GB07266603', 2013)
Data columns (total 1 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Profit_Margin  217855 non-null  float64
dtypes: float64(1)
memory usage: 3.5+ MB
42
125990
After dropna size is:
16815
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 234670 entries, ('GB09567757', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Profit_Margin  234670 non-null  float64
dtypes: float64(1)
memory usage: 3.8+ MB
43
125990
After dropna size is:
8879
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 243549 entries, ('GB09567757', 2019) to ('GB07266603', 2011)
Data columns (total 1 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Profit_Margin  243549 non-null  float64
dtypes: float64(1)
memory usage: 3.9+ MB
44
125990
After dropna size is:
12305
45
125990
After dropna size is:
23191
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 35496 entries, ('GB07588867', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Return_on_Shareholders_Funds  35496 non-null  float64
dtypes: float64(1)
memory usage: 600.1+ KB
46
125990
After dropna size is:
27073
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 62569 entries, ('GB07588867', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Return_on_Shareholders_Funds  62569 non-null  float64
dtypes: float64(1)
memory usage: 1.1+ MB
47
125990
After dropna size is:
20752
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 83321 entries, ('GB07588867', 2019) to ('GBOC381395', 2016)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Return_on_Shareholders_Funds  83321 non-null  float64
dtypes: float64(1)
memory usage: 1.4+ MB
48
125990
After dropna size is:
17104
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 100425 entries, ('GB07588867', 2019) to ('GBSC452461', 2015)
Data columns (total 1 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Return_on_Shareholders_Funds  100425 non-null  float64
dtypes: float64(1)
memory usage: 1.7+ MB
49
125990
After dropna size is:
14295
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 114720 entries, ('GB07588867', 2019) to ('GB08058491', 2014)
Data columns (total 1 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Return_on_Shareholders_Funds  114720 non-null  float64
dtypes: float64(1)
memory usage: 1.9+ MB
50
125990
After dropna size is:
11908
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 126628 entries, ('GB07588867', 2019) to ('GB07266603', 2013)
Data columns (total 1 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Return_on_Shareholders_Funds  126628 non-null  float64
dtypes: float64(1)
memory usage: 2.1+ MB
51
125990
After dropna size is:
8859

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 135487 entries, ('GB07588867', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Return_on_Shareholders_Funds  135487 non-null  float64
dtypes: float64(1)
memory usage: 2.2+ MB
52
125990
After dropna size is:
4620
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 140107 entries, ('GB07588867', 2019) to ('GB07361608', 2011)
Data columns (total 1 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Return_on_Shareholders_Funds  140107 non-null  float64
dtypes: float64(1)
memory usage: 2.3+ MB
53
125990
After dropna size is:
19579
54
125990
After dropna size is:
39291
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 58870 entries, ('GB09567757', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Return_on_Capital_Employed  58870 non-null  float64
dtypes: float64(1)
memory usage: 1.1+ MB
55
125990
After dropna size is:
46329
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 105199 entries, ('GB09567757', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Return_on_Capital_Employed  105199 non-null  float64
dtypes: float64(1)
memory usage: 1.8+ MB
56
125990
After dropna size is:
37356
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 142555 entries, ('GB09567757', 2019) to ('GBOC381395', 2016)
Data columns (total 1 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Return_on_Capital_Employed  142555 non-null  float64
dtypes: float64(1)
memory usage: 2.3+ MB
57
125990
After dropna size is:
30495
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 173050 entries, ('GB09567757', 2019) to ('GBSC452461', 2015)
Data columns (total 1 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Return_on_Capital_Employed  173050 non-null  float64
dtypes: float64(1)
memory usage: 2.8+ MB
58
125990
After dropna size is:
25855
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 198905 entries, ('GB09567757', 2019) to ('GBOC369696', 2014)
Data columns (total 1 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Return_on_Capital_Employed  198905 non-null  float64
dtypes: float64(1)
memory usage: 3.2+ MB
59
125990
After dropna size is:
21813
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 220718 entries, ('GB09567757', 2019) to ('GBOC369696', 2013)
Data columns (total 1 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Return_on_Capital_Employed  220718 non-null  float64
dtypes: float64(1)
memory usage: 3.5+ MB
60
125990
After dropna size is:
16254
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 236972 entries, ('GB09567757', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Return_on_Capital_Employed  236972 non-null  float64
dtypes: float64(1)
memory usage: 3.7+ MB
61
125990
After dropna size is:
8773
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 245745 entries, ('GB09567757', 2019) to ('GB07361608', 2011)
Data columns (total 1 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Return_on_Capital_Employed  245745 non-null  float64
dtypes: float64(1)
memory usage: 3.9+ MB
62
125990
After dropna size is:
47234
63
125990
After dropna size is:
82438
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 129672 entries, ('GB07588867', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Liquidity_Ratio_(x)  129672 non-null  float64
dtypes: float64(1)
memory usage: 2.3+ MB
64
125990
After dropna size is:
88963
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 218635 entries, ('GB07588867', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Liquidity_Ratio_(x)  218635 non-null  float64
dtypes: float64(1)
memory usage: 3.4+ MB
65
125990
After dropna size is:
86958
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 305593 entries, ('GB07588867', 2019) to ('GBOC381395', 2016)
Data columns (total 1 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Liquidity_Ratio_(x)  305593 non-null  float64
dtypes: float64(1)
memory usage: 4.6+ MB
66
125990
After dropna size is:
77063
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 382656 entries, ('GB07588867', 2019) to ('GBSC452461', 2015)
Data columns (total 1 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Liquidity_Ratio_(x)  382656 non-null  float64
dtypes: float64(1)
memory usage: 5.6+ MB
67
125990
After dropna size is:
64476
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 447132 entries, ('GB07588867', 2019) to ('GBOC369696', 2014)
Data columns (total 1 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Liquidity_Ratio_(x)  447132 non-null  float64
dtypes: float64(1)
memory usage: 6.4+ MB
68
125990
After dropna size is:
49885
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 497017 entries, ('GB07588867', 2019) to ('GBOC369696', 2013)
Data columns (total 1 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Liquidity_Ratio_(x)  497017 non-null  float64
dtypes: float64(1)
memory usage: 7.0+ MB
69
125990
After dropna size is:
33772
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 530789 entries, ('GB07588867', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Liquidity_Ratio_(x)  530789 non-null  float64
dtypes: float64(1)
memory usage: 7.5+ MB
70
125990
After dropna size is:
16656
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 547445 entries, ('GB07588867', 2019) to ('GB07266603', 2011)
Data columns (total 1 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Liquidity_Ratio_(x)  547445 non-null  float64
dtypes: float64(1)
memory usage: 7.7+ MB
71
125990
After dropna size is:
11839
72
125990
After dropna size is:
19660

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Liquidity_Ratio_(x)'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 31499 entries, ('GB09488271', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Gearing_(%)  31499 non-null  float64
dtypes: float64(1)
memory usage: 522.3+ KB
73
125990
After dropna size is:
19968
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 51467 entries, ('GB09488271', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Gearing_(%)  51467 non-null  float64
dtypes: float64(1)
memory usage: 790.4+ KB
74
125990
After dropna size is:
16000
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 67467 entries, ('GB09488271', 2019) to ('GBSC452461', 2016)
Data columns (total 1 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Gearing_(%)  67467 non-null  float64
dtypes: float64(1)
memory usage: 1.1+ MB
75
125990
After dropna size is:
13458
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 80925 entries, ('GB09488271', 2019) to ('GBSC452461', 2015)
Data columns (total 1 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Gearing_(%)  80925 non-null  float64
dtypes: float64(1)
memory usage: 1.3+ MB
76
125990
After dropna size is:
10899
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 91824 entries, ('GB09488271', 2019) to ('GB07560895', 2014)
Data columns (total 1 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Gearing_(%)  91824 non-null  float64
dtypes: float64(1)
memory usage: 1.5+ MB
77
125990
After dropna size is:
8226
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 100050 entries, ('GB09488271', 2019) to ('GB07266603', 2013)
Data columns (total 1 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Gearing_(%)  100050 non-null  float64
dtypes: float64(1)
memory usage: 1.6+ MB
78
125990
After dropna size is:
5304
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 105354 entries, ('GB09488271', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Gearing_(%)  105354 non-null  float64
dtypes: float64(1)
memory usage: 1.7+ MB
79
125990
After dropna size is:
2520
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 107874 entries, ('GB09488271', 2019) to ('GB07266603', 2011)
Data columns (total 1 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Gearing_(%)  107874 non-null  float64
dtypes: float64(1)
memory usage: 1.7+ MB
80
125990
After dropna size is:
59267

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Gearing_(%)'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

81
125990
After dropna size is:
61517
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 120784 entries, ('GB09567757', 2019) to ('GBSC452461', 2018)
Data columns (total 1 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Number_of_employees  120784 non-null  float64
dtypes: float64(1)
memory usage: 2.3+ MB
82
125990
After dropna size is:
39127
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 159911 entries, ('GB09567757', 2019) to ('IE505067', 2017)
Data columns (total 1 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Number_of_employees  159911 non-null  float64
dtypes: float64(1)
memory usage: 2.8+ MB
83
125990
After dropna size is:
25882
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 185793 entries, ('GB09567757', 2019) to ('IE505067', 2016)
Data columns (total 1 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Number_of_employees  185793 non-null  float64
dtypes: float64(1)
memory usage: 3.2+ MB
84
125990
After dropna size is:
14099
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 199892 entries, ('GB09567757', 2019) to ('GBOC369696', 2015)
Data columns (total 1 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Number_of_employees  199892 non-null  float64
dtypes: float64(1)
memory usage: 3.4+ MB
85
125990
After dropna size is:
9084
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 208976 entries, ('GB09567757', 2019) to ('GBOC369696', 2014)
Data columns (total 1 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Number_of_employees  208976 non-null  float64
dtypes: float64(1)
memory usage: 3.5+ MB
86
125990
After dropna size is:
6139
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 215115 entries, ('GB09567757', 2019) to ('GBOC369696', 2013)
Data columns (total 1 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Number_of_employees  215115 non-null  float64
dtypes: float64(1)
memory usage: 3.6+ MB
87
125990
After dropna size is:
3398
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 218513 entries, ('GB09567757', 2019) to ('GB07361608', 2012)
Data columns (total 1 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Number_of_employees  218513 non-null  float64
dtypes: float64(1)
memory usage: 3.6+ MB
88
125990
After dropna size is:
1733
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 220246 entries, ('GB09567757', 2019) to ('GB07361608', 2011)
Data columns (total 1 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Number_of_employees  220246 non-null  float64
dtypes: float64(1)
memory usage: 3.7+ MB
89
125990
After dropna size is:
30176
90
125990
After dropna size is:
50515
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 80691 entries, ('IE566240', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Tangible_Assets_th_GBP  80691 non-null  float64
dtypes: float64(1)
memory usage: 1.4+ MB
91
125990
After dropna size is:
53413
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 134104 entries, ('IE566240', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Tangible_Assets_th_GBP  134104 non-null  float64
dtypes: float64(1)
memory usage: 2.1+ MB
92
125990
After dropna size is:
51435
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 185539 entries, ('IE566240', 2019) to ('GBOC381395', 2016)
Data columns (total 1 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Tangible_Assets_th_GBP  185539 non-null  float64
dtypes: float64(1)
memory usage: 2.8+ MB
93
125990
After dropna size is:
45835
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 231374 entries, ('IE566240', 2019) to ('GBOC365296', 2015)
Data columns (total 1 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Tangible_Assets_th_GBP  231374 non-null  float64
dtypes: float64(1)
memory usage: 3.4+ MB
94
125990
After dropna size is:
38373
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 269747 entries, ('IE566240', 2019) to ('GBOC365296', 2014)
Data columns (total 1 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Tangible_Assets_th_GBP  269747 non-null  float64
dtypes: float64(1)
memory usage: 3.9+ MB
95
125990
After dropna size is:
29412
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 299159 entries, ('IE566240', 2019) to ('GB07266603', 2013)
Data columns (total 1 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Tangible_Assets_th_GBP  299159 non-null  float64
dtypes: float64(1)
memory usage: 4.3+ MB
96
125990
After dropna size is:
19573
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 318732 entries, ('IE566240', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Tangible_Assets_th_GBP  318732 non-null  float64
dtypes: float64(1)
memory usage: 4.5+ MB
97
125990
After dropna size is:
9306
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 328038 entries, ('IE566240', 2019) to ('GB07266603', 2011)
Data columns (total 1 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Tangible_Assets_th_GBP  328038 non-null  float64
dtypes: float64(1)
memory usage: 4.6+ MB
98
125990
After dropna size is:
2602
99
125990
After dropna size is:
4996
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 7598 entries, ('GBOC361927', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Land_&_Buildings_th_GBP  7598 non-null   float64
dtypes: float64(1)
memory usage: 124.1+ KB
100
125990
After dropna size is:
5177
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 12775 entries, ('GBOC361927', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Land_&_Buildings_th_GBP  12775 non-null  float64
dtypes: float64(1)
memory usage: 188.8+ KB
101
125990
After dropna size is:
3800
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 16575 entries, ('GBOC361927', 2019) to ('GBOC381395', 2016)
Data columns (total 1 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Land_&_Buildings_th_GBP  16575 non-null  float64
dtypes: float64(1)
memory usage: 236.2+ KB
102
125990
After dropna size is:
2909
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 19484 entries, ('GBOC361927', 2019) to ('GBOC365296', 2015)
Data columns (total 1 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Land_&_Buildings_th_GBP  19484 non-null  float64
dtypes: float64(1)
memory usage: 272.5+ KB
103
125990
After dropna size is:
2406
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 21890 entries, ('GBOC361927', 2019) to ('GBOC365296', 2014)
Data columns (total 1 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Land_&_Buildings_th_GBP  21890 non-null  float64
dtypes: float64(1)
memory usage: 302.0+ KB
104
125990
After dropna size is:
1849
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 23739 entries, ('GBOC361927', 2019) to ('GBOC365296', 2013)
Data columns (total 1 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Land_&_Buildings_th_GBP  23739 non-null  float64
dtypes: float64(1)
memory usage: 324.5+ KB
105
125990
After dropna size is:
1239
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 24978 entries, ('GBOC361927', 2019) to ('GBOC365296', 2012)
Data columns (total 1 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Land_&_Buildings_th_GBP  24978 non-null  float64
dtypes: float64(1)
memory usage: 339.8+ KB
106
125990
After dropna size is:
561

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 25539 entries, ('GBOC361927', 2019) to ('GB07258174', 2011)
Data columns (total 1 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Land_&_Buildings_th_GBP  25539 non-null  float64
dtypes: float64(1)
memory usage: 346.7+ KB
107
125990
After dropna size is:
1918
108
125990
After dropna size is:
3364
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 5282 entries, ('GBOC361927', 2019) to ('GB08151590', 2018)
Data columns (total 1 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Freehold_Land_th_GBP  5282 non-null   float64
dtypes: float64(1)
memory usage: 86.5+ KB
109
125990
After dropna size is:
3490
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 8772 entries, ('GBOC361927', 2019) to ('GB08652508', 2017)
Data columns (total 1 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Freehold_Land_th_GBP  8772 non-null   float64
dtypes: float64(1)
memory usage: 131.9+ KB
110
125990
After dropna size is:
2382
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 11154 entries, ('GBOC361927', 2019) to ('GB07470677', 2016)
Data columns (total 1 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Freehold_Land_th_GBP  11154 non-null  float64
dtypes: float64(1)
memory usage: 163.1+ KB
111
125990
After dropna size is:
1870
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 13024 entries, ('GBOC361927', 2019) to ('GB07258174', 2015)
Data columns (total 1 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Freehold_Land_th_GBP  13024 non-null  float64
dtypes: float64(1)
memory usage: 187.6+ KB
112
125990
After dropna size is:
1586
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 14610 entries, ('GBOC361927', 2019) to ('GB07258174', 2014)
Data columns (total 1 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Freehold_Land_th_GBP  14610 non-null  float64
dtypes: float64(1)
memory usage: 207.9+ KB
113
125990
After dropna size is:
1151

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Land_&_Buildings_th_GBP'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 15761 entries, ('GBOC361927', 2019) to ('GB07258174', 2013)
Data columns (total 1 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Freehold_Land_th_GBP  15761 non-null  float64
dtypes: float64(1)
memory usage: 222.3+ KB
114
125990
After dropna size is:
824
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 16585 entries, ('GBOC361927', 2019) to ('GB07258174', 2012)
Data columns (total 1 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Freehold_Land_th_GBP  16585 non-null  float64
dtypes: float64(1)
memory usage: 232.8+ KB
115
125990
After dropna size is:
365
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 16950 entries, ('GBOC361927', 2019) to ('GB07258174', 2011)
Data columns (total 1 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Freehold_Land_th_GBP  16950 non-null  float64
dtypes: float64(1)
memory usage: 237.4+ KB
116
125990
After dropna size is:
772
117
125990
After dropna size is:
1788
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 2560 entries, ('GB08458591', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Leasehold_Land_th_GBP  2560 non-null   float64
dtypes: float64(1)
memory usage: 42.9+ KB
118
125990
After dropna size is:
1825
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 4385 entries, ('GB08458591', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Leasehold_Land_th_GBP  4385 non-null   float64
dtypes: float64(1)
memory usage: 65.7+ KB
119
125990
After dropna size is:
1544
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 5929 entries, ('GB08458591', 2019) to ('GBOC381395', 2016)
Data columns (total 1 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Leasehold_Land_th_GBP  5929 non-null   float64
dtypes: float64(1)
memory usage: 84.8+ KB
120
125990
After dropna size is:
1161
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 7090 entries, ('GB08458591', 2019) to ('GBOC365296', 2015)
Data columns (total 1 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Leasehold_Land_th_GBP  7090 non-null   float64
dtypes: float64(1)
memory usage: 99.1+ KB
121
125990
After dropna size is:
924
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 8014 entries, ('GB08458591', 2019) to ('GBOC365296', 2014)
Data columns (total 1 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Leasehold_Land_th_GBP  8014 non-null   float64
dtypes: float64(1)
memory usage: 110.5+ KB
122
125990
After dropna size is:
776
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 8790 entries, ('GB08458591', 2019) to ('GBOC365296', 2013)
Data columns (total 1 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Leasehold_Land_th_GBP  8790 non-null   float64
dtypes: float64(1)
memory usage: 120.1+ KB
123
125990
After dropna size is:
468
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 9258 entries, ('GB08458591', 2019) to ('GBOC365296', 2012)
Data columns (total 1 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Leasehold_Land_th_GBP  9258 non-null   float64
dtypes: float64(1)
memory usage: 125.9+ KB
124
125990
After dropna size is:
221
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 9479 entries, ('GB08458591', 2019) to ('GB07373235', 2011)
Data columns (total 1 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Leasehold_Land_th_GBP  9479 non-null   float64
dtypes: float64(1)
memory usage: 128.7+ KB
125
125990
After dropna size is:
3604
126
125990
After dropna size is:
6827
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 10431 entries, ('GBOC361927', 2019) to ('GB09102173', 2018)
Data columns (total 1 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Fixtures_&_Fittings_th_GBP  10431 non-null  float64
dtypes: float64(1)
memory usage: 172.1+ KB
127
125990
After dropna size is:
7080
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 17511 entries, ('GBOC361927', 2019) to ('GB09102173', 2017)
Data columns (total 1 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Fixtures_&_Fittings_th_GBP  17511 non-null  float64
dtypes: float64(1)
memory usage: 264.1+ KB
128
125990
After dropna size is:
4922
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 22433 entries, ('GBOC361927', 2019) to ('GB08470580', 2016)
Data columns (total 1 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Fixtures_&_Fittings_th_GBP  22433 non-null  float64
dtypes: float64(1)
memory usage: 328.4+ KB
129
125990
After dropna size is:
4056
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 26489 entries, ('GBOC361927', 2019) to ('GB08058491', 2015)
Data columns (total 1 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Fixtures_&_Fittings_th_GBP  26489 non-null  float64
dtypes: float64(1)
memory usage: 381.3+ KB
130
125990
After dropna size is:
3640
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 30129 entries, ('GBOC361927', 2019) to ('GB08058491', 2014)
Data columns (total 1 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Fixtures_&_Fittings_th_GBP  30129 non-null  float64
dtypes: float64(1)
memory usage: 428.5+ KB
131
125990
After dropna size is:
3211
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 33340 entries, ('GBOC361927', 2019) to ('GB07266603', 2013)
Data columns (total 1 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Fixtures_&_Fittings_th_GBP  33340 non-null  float64
dtypes: float64(1)
memory usage: 470.5+ KB
132
125990
After dropna size is:
2417
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 35757 entries, ('GBOC361927', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Fixtures_&_Fittings_th_GBP  35757 non-null  float64
dtypes: float64(1)
memory usage: 502.0+ KB
133
125990
After dropna size is:
1314
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 37071 entries, ('GBOC361927', 2019) to ('GB07266603', 2011)
Data columns (total 1 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Fixtures_&_Fittings_th_GBP  37071 non-null  float64
dtypes: float64(1)
memory usage: 519.3+ KB
134
125990
After dropna size is:
8022
135
125990
After dropna size is:
13781

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Fixtures_&_Fittings_th_GBP'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 21803 entries, ('GB10180542', 2019) to ('GB09102173', 2018)
Data columns (total 1 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Plant_&_Vehicles_th_GBP  21803 non-null  float64
dtypes: float64(1)
memory usage: 353.0+ KB
136
125990
After dropna size is:
14611
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 36414 entries, ('GB10180542', 2019) to ('GB09102173', 2017)
Data columns (total 1 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Plant_&_Vehicles_th_GBP  36414 non-null  float64
dtypes: float64(1)
memory usage: 538.8+ KB
137
125990
After dropna size is:
9660
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 46074 entries, ('GB10180542', 2019) to ('GB09102173', 2016)
Data columns (total 1 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Plant_&_Vehicles_th_GBP  46074 non-null  float64
dtypes: float64(1)
memory usage: 665.7+ KB
138
125990
After dropna size is:
7690
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 53764 entries, ('GB10180542', 2019) to ('GBOC365296', 2015)
Data columns (total 1 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Plant_&_Vehicles_th_GBP  53764 non-null  float64
dtypes: float64(1)
memory usage: 765.6+ KB
139
125990
After dropna size is:
6960
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 60724 entries, ('GB10180542', 2019) to ('GBOC365296', 2014)
Data columns (total 1 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Plant_&_Vehicles_th_GBP  60724 non-null  float64
dtypes: float64(1)
memory usage: 854.8+ KB
140
125990
After dropna size is:
6248
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 66972 entries, ('GB10180542', 2019) to ('GB07266603', 2013)
Data columns (total 1 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Plant_&_Vehicles_th_GBP  66972 non-null  float64
dtypes: float64(1)
memory usage: 936.2+ KB
141
125990
After dropna size is:
4321
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 71293 entries, ('GB10180542', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Plant_&_Vehicles_th_GBP  71293 non-null  float64
dtypes: float64(1)
memory usage: 992.4+ KB
142
125990
After dropna size is:
2107
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 73400 entries, ('GB10180542', 2019) to ('GB07266603', 2011)
Data columns (total 1 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Plant_&_Vehicles_th_GBP  73400 non-null  float64
dtypes: float64(1)
memory usage: 1019.7+ KB
143
125990
After dropna size is:
6501

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Plant_&_Vehicles_th_GBP'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

144
125990
After dropna size is:
11382
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 17883 entries, ('GB10180542', 2019) to ('GB09102173', 2018)
Data columns (total 1 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Plant_th_GBP  17883 non-null  float64
dtypes: float64(1)
memory usage: 290.0+ KB
145
125990
After dropna size is:
12021
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 29904 entries, ('GB10180542', 2019) to ('GB09102173', 2017)
Data columns (total 1 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Plant_th_GBP  29904 non-null  float64
dtypes: float64(1)
memory usage: 442.9+ KB
146
125990
After dropna size is:
7923
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 37827 entries, ('GB10180542', 2019) to ('GB09102173', 2016)
Data columns (total 1 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Plant_th_GBP  37827 non-null  float64
dtypes: float64(1)
memory usage: 547.8+ KB
147
125990
After dropna size is:
6131
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 43958 entries, ('GB10180542', 2019) to ('GBOC365296', 2015)
Data columns (total 1 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Plant_th_GBP  43958 non-null  float64
dtypes: float64(1)
memory usage: 627.8+ KB
148
125990
After dropna size is:
5547
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 49505 entries, ('GB10180542', 2019) to ('GBOC365296', 2014)
Data columns (total 1 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Plant_th_GBP  49505 non-null  float64
dtypes: float64(1)
memory usage: 699.6+ KB
149
125990
After dropna size is:
5017
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 54522 entries, ('GB10180542', 2019) to ('GBOC365296', 2013)
Data columns (total 1 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Plant_th_GBP  54522 non-null  float64
dtypes: float64(1)
memory usage: 765.4+ KB
150
125990
After dropna size is:
3338
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 57860 entries, ('GB10180542', 2019) to ('GBOC365296', 2012)
Data columns (total 1 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Plant_th_GBP  57860 non-null  float64
dtypes: float64(1)
memory usage: 809.0+ KB
151
125990
After dropna size is:
1573
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 59433 entries, ('GB10180542', 2019) to ('GBNC000600', 2011)
Data columns (total 1 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Plant_th_GBP  59433 non-null  float64
dtypes: float64(1)
memory usage: 829.7+ KB
152
125990
After dropna size is:
2675
153
125990
After dropna size is:
4243
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 6918 entries, ('GB08893293', 2019) to ('GB08470580', 2018)
Data columns (total 1 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Vehicles_th_GBP  6918 non-null   float64
dtypes: float64(1)
memory usage: 112.8+ KB
154
125990
After dropna size is:
4553
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 11471 entries, ('GB08893293', 2019) to ('GB08470580', 2017)
Data columns (total 1 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Vehicles_th_GBP  11471 non-null  float64
dtypes: float64(1)
memory usage: 172.9+ KB
155
125990
After dropna size is:
2930
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 14401 entries, ('GB08893293', 2019) to ('GB07122226', 2016)
Data columns (total 1 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Vehicles_th_GBP  14401 non-null  float64
dtypes: float64(1)
memory usage: 212.1+ KB
156
125990
After dropna size is:
2496
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 16897 entries, ('GB08893293', 2019) to ('GBSC384248', 2015)
Data columns (total 1 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Vehicles_th_GBP  16897 non-null  float64
dtypes: float64(1)
memory usage: 245.3+ KB
157
125990
After dropna size is:
2286
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 19183 entries, ('GB08893293', 2019) to ('GB08358639', 2014)
Data columns (total 1 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Vehicles_th_GBP  19183 non-null  float64
dtypes: float64(1)
memory usage: 275.1+ KB
158
125990
After dropna size is:
1976
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 21159 entries, ('GB08893293', 2019) to ('GB07266603', 2013)
Data columns (total 1 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Vehicles_th_GBP  21159 non-null  float64
dtypes: float64(1)
memory usage: 301.1+ KB
159
125990
After dropna size is:
1527
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 22686 entries, ('GB08893293', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Vehicles_th_GBP  22686 non-null  float64
dtypes: float64(1)
memory usage: 321.3+ KB
160
125990
After dropna size is:
808
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 23494 entries, ('GB08893293', 2019) to ('GB07266603', 2011)
Data columns (total 1 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Vehicles_th_GBP  23494 non-null  float64
dtypes: float64(1)
memory usage: 331.9+ KB
161
125990
After dropna size is:
21508
162
125990
After dropna size is:
33946
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 55454 entries, ('GB09683141', 2019) to ('GB09102173', 2018)
Data columns (total 1 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Other_Fixed_Assets_th_GBP  55454 non-null  float64
dtypes: float64(1)
memory usage: 993.6+ KB
163
125990
After dropna size is:
35725
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 91179 entries, ('GB09683141', 2019) to ('GB09102173', 2017)
Data columns (total 1 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Other_Fixed_Assets_th_GBP  91179 non-null  float64
dtypes: float64(1)
memory usage: 1.5+ MB
164
125990
After dropna size is:
38878
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 130057 entries, ('GB09683141', 2019) to ('GB09153143', 2016)
Data columns (total 1 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Other_Fixed_Assets_th_GBP  130057 non-null  float64
dtypes: float64(1)
memory usage: 2.0+ MB
165
125990
After dropna size is:
35556
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 165613 entries, ('GB09683141', 2019) to ('GB09153143', 2015)
Data columns (total 1 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Other_Fixed_Assets_th_GBP  165613 non-null  float64
dtypes: float64(1)
memory usage: 2.5+ MB
166
125990
After dropna size is:
29130
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 194743 entries, ('GB09683141', 2019) to ('GB08582762', 2014)
Data columns (total 1 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Other_Fixed_Assets_th_GBP  194743 non-null  float64
dtypes: float64(1)
memory usage: 2.9+ MB
167
125990
After dropna size is:
21377
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 216120 entries, ('GB09683141', 2019) to ('GB07560895', 2013)
Data columns (total 1 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Other_Fixed_Assets_th_GBP  216120 non-null  float64
dtypes: float64(1)
memory usage: 3.2+ MB
168
125990
After dropna size is:
13909
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 230029 entries, ('GB09683141', 2019) to ('GB07560895', 2012)
Data columns (total 1 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Other_Fixed_Assets_th_GBP  230029 non-null  float64
dtypes: float64(1)
memory usage: 3.3+ MB
169
125990
After dropna size is:
6377

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 236406 entries, ('GB09683141', 2019) to ('GB07404972', 2011)
Data columns (total 1 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Other_Fixed_Assets_th_GBP  236406 non-null  float64
dtypes: float64(1)
memory usage: 3.4+ MB
170
125990
After dropna size is:
2345
171
125990
After dropna size is:
5166
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 7511 entries, ('GB08893293', 2019) to ('GB08652508', 2018)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Intangible_Assets_th_GBP  7511 non-null   float64
dtypes: float64(1)
memory usage: 124.0+ KB
172
125990
After dropna size is:
5722
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 13233 entries, ('GB08893293', 2019) to ('GB08368531', 2017)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Intangible_Assets_th_GBP  13233 non-null  float64
dtypes: float64(1)
memory usage: 195.8+ KB
173
125990
After dropna size is:
6588
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 19821 entries, ('GB08893293', 2019) to ('GB08368531', 2016)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Intangible_Assets_th_GBP  19821 non-null  float64
dtypes: float64(1)
memory usage: 281.5+ KB
174
125990
After dropna size is:
6420
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 26241 entries, ('GB08893293', 2019) to ('GB08368531', 2015)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Intangible_Assets_th_GBP  26241 non-null  float64
dtypes: float64(1)
memory usage: 361.4+ KB
175
125990
After dropna size is:
5562
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 31803 entries, ('GB08893293', 2019) to ('GB08368531', 2014)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Intangible_Assets_th_GBP  31803 non-null  float64
dtypes: float64(1)
memory usage: 427.8+ KB
176
125990
After dropna size is:
4334
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 36137 entries, ('GB08893293', 2019) to ('GB07717822', 2013)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Intangible_Assets_th_GBP  36137 non-null  float64
dtypes: float64(1)
memory usage: 478.5+ KB
177
125990
After dropna size is:
2991
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 39128 entries, ('GB08893293', 2019) to ('GB07259438', 2012)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Intangible_Assets_th_GBP  39128 non-null  float64
dtypes: float64(1)
memory usage: 512.9+ KB
178
125990
After dropna size is:
1424
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 40552 entries, ('GB08893293', 2019) to ('GB07259438', 2011)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Intangible_Assets_th_GBP  40552 non-null  float64
dtypes: float64(1)
memory usage: 529.3+ KB
179
125990
After dropna size is:
6306
180
125990
After dropna size is:
12343
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 18649 entries, ('GB09683141', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Investments_th_GBP  18649 non-null  float64
dtypes: float64(1)
memory usage: 307.9+ KB
181
125990
After dropna size is:
12720
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 31369 entries, ('GB09683141', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Investments_th_GBP  31369 non-null  float64
dtypes: float64(1)
memory usage: 469.2+ KB
182
125990
After dropna size is:
11577
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 42946 entries, ('GB09683141', 2019) to ('GBOC381395', 2016)
Data columns (total 1 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Investments_th_GBP  42946 non-null  float64
dtypes: float64(1)
memory usage: 616.6+ KB
183
125990
After dropna size is:
9284
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 52230 entries, ('GB09683141', 2019) to ('IE505067', 2015)
Data columns (total 1 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Investments_th_GBP  52230 non-null  float64
dtypes: float64(1)
memory usage: 734.9+ KB
184
125990
After dropna size is:
6244
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 58474 entries, ('GB09683141', 2019) to ('IE505067', 2014)
Data columns (total 1 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Investments_th_GBP  58474 non-null  float64
dtypes: float64(1)
memory usage: 813.0+ KB
185
125990
After dropna size is:
3506
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 61980 entries, ('GB09683141', 2019) to ('GB07911132', 2013)
Data columns (total 1 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Investments_th_GBP  61980 non-null  float64
dtypes: float64(1)
memory usage: 855.9+ KB
186
125990
After dropna size is:
1977
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 63957 entries, ('GB09683141', 2019) to ('IE493534', 2012)
Data columns (total 1 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Investments_th_GBP  63957 non-null  float64
dtypes: float64(1)
memory usage: 879.0+ KB
187
125990
After dropna size is:
933
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 64890 entries, ('GB09683141', 2019) to ('IE493534', 2011)
Data columns (total 1 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Investments_th_GBP  64890 non-null  float64
dtypes: float64(1)
memory usage: 889.9+ KB
188
125990
After dropna size is:
34679
189
125990
After dropna size is:
59454
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 94133 entries, ('IE566240', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Fixed_Assets_th_GBP  94133 non-null  float64
dtypes: float64(1)
memory usage: 1.6+ MB
190
125990
After dropna size is:
62864
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 156997 entries, ('IE566240', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Fixed_Assets_th_GBP  156997 non-null  float64
dtypes: float64(1)
memory usage: 2.5+ MB
191
125990
After dropna size is:
60606
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 217603 entries, ('IE566240', 2019) to ('GBOC381395', 2016)
Data columns (total 1 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Fixed_Assets_th_GBP  217603 non-null  float64
dtypes: float64(1)
memory usage: 3.3+ MB
192
125990
After dropna size is:
53474
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 271077 entries, ('IE566240', 2019) to ('IE505067', 2015)
Data columns (total 1 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Fixed_Assets_th_GBP  271077 non-null  float64
dtypes: float64(1)
memory usage: 4.0+ MB
193
125990
After dropna size is:
43732
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 314809 entries, ('IE566240', 2019) to ('IE505067', 2014)
Data columns (total 1 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Fixed_Assets_th_GBP  314809 non-null  float64
dtypes: float64(1)
memory usage: 4.5+ MB
194
125990
After dropna size is:
32505

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 347314 entries, ('IE566240', 2019) to ('GB07266603', 2013)
Data columns (total 1 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Fixed_Assets_th_GBP  347314 non-null  float64
dtypes: float64(1)
memory usage: 5.0+ MB
195
125990
After dropna size is:
21499
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 368813 entries, ('IE566240', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Fixed_Assets_th_GBP  368813 non-null  float64
dtypes: float64(1)
memory usage: 5.2+ MB
196
125990
After dropna size is:
10280
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 379093 entries, ('IE566240', 2019) to ('GB07266603', 2011)
Data columns (total 1 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Fixed_Assets_th_GBP  379093 non-null  float64
dtypes: float64(1)
memory usage: 5.4+ MB
197
125990
After dropna size is:
5981
198
125990
After dropna size is:
10939
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 16920 entries, ('IE566240', 2019) to ('GB08582762', 2018)
Data columns (total 1 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Stock_&_W.I.P._th_GBP  16920 non-null  float64
dtypes: float64(1)
memory usage: 273.4+ KB
199
125990
After dropna size is:
12277
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 29197 entries, ('IE566240', 2019) to ('GB08582762', 2017)
Data columns (total 1 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Stock_&_W.I.P._th_GBP  29197 non-null  float64
dtypes: float64(1)
memory usage: 428.7+ KB
200
125990
After dropna size is:
15543
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 44740 entries, ('IE566240', 2019) to ('GB08582762', 2016)
Data columns (total 1 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Stock_&_W.I.P._th_GBP  44740 non-null  float64
dtypes: float64(1)
memory usage: 635.1+ KB
201
125990
After dropna size is:
15204
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 59944 entries, ('IE566240', 2019) to ('GB08582762', 2015)
Data columns (total 1 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Stock_&_W.I.P._th_GBP  59944 non-null  float64
dtypes: float64(1)
memory usage: 823.0+ KB
202
125990
After dropna size is:
13608
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 73552 entries, ('IE566240', 2019) to ('GB08582762', 2014)
Data columns (total 1 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Stock_&_W.I.P._th_GBP  73552 non-null  float64
dtypes: float64(1)
memory usage: 986.1+ KB
203
125990
After dropna size is:
10803
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 84355 entries, ('IE566240', 2019) to ('GB08058491', 2013)
Data columns (total 1 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Stock_&_W.I.P._th_GBP  84355 non-null  float64
dtypes: float64(1)
memory usage: 1.1+ MB
204
125990
After dropna size is:
7321
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 91676 entries, ('IE566240', 2019) to ('GB07693300', 2012)
Data columns (total 1 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Stock_&_W.I.P._th_GBP  91676 non-null  float64
dtypes: float64(1)
memory usage: 1.2+ MB
205
125990
After dropna size is:
3515
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 95191 entries, ('IE566240', 2019) to ('GB07259438', 2011)
Data columns (total 1 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Stock_&_W.I.P._th_GBP  95191 non-null  float64
dtypes: float64(1)
memory usage: 1.2+ MB
206
125990
After dropna size is:
5037

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Stock_&_W.I.P._th_GBP'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

207
125990
After dropna size is:
8607
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 13644 entries, ('GB09488271', 2019) to ('GB08582762', 2018)
Data columns (total 1 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Stock_th_GBP  13644 non-null  float64
dtypes: float64(1)
memory usage: 220.5+ KB
208
125990
After dropna size is:
9783
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 23427 entries, ('GB09488271', 2019) to ('GB08582762', 2017)
Data columns (total 1 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Stock_th_GBP  23427 non-null  float64
dtypes: float64(1)
memory usage: 347.2+ KB
209
125990
After dropna size is:
13288
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 36715 entries, ('GB09488271', 2019) to ('GB08582762', 2016)
Data columns (total 1 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Stock_th_GBP  36715 non-null  float64
dtypes: float64(1)
memory usage: 529.0+ KB
210
125990
After dropna size is:
13531
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 50246 entries, ('GB09488271', 2019) to ('GB08582762', 2015)
Data columns (total 1 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Stock_th_GBP  50246 non-null  float64
dtypes: float64(1)
memory usage: 699.5+ KB
211
125990
After dropna size is:
12224
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 62470 entries, ('GB09488271', 2019) to ('GB08582762', 2014)
Data columns (total 1 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Stock_th_GBP  62470 non-null  float64
dtypes: float64(1)
memory usage: 846.9+ KB
212
125990
After dropna size is:
9739
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 72209 entries, ('GB09488271', 2019) to ('GB08058491', 2013)
Data columns (total 1 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Stock_th_GBP  72209 non-null  float64
dtypes: float64(1)
memory usage: 961.4+ KB
213
125990
After dropna size is:
6503
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 78712 entries, ('GB09488271', 2019) to ('GB07693300', 2012)
Data columns (total 1 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Stock_th_GBP  78712 non-null  float64
dtypes: float64(1)
memory usage: 1.0+ MB
214
125990
After dropna size is:
3084
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 81796 entries, ('GB09488271', 2019) to ('GB07259438', 2011)
Data columns (total 1 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Stock_th_GBP  81796 non-null  float64
dtypes: float64(1)
memory usage: 1.0+ MB
215
125990
After dropna size is:
371
216
125990
After dropna size is:
783
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1154 entries, ('GB08439289', 2019) to ('GB08228494', 2018)
Data columns (total 1 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   W.I.P._th_GBP  1154 non-null   float64
dtypes: float64(1)
memory usage: 19.7+ KB
217
125990
After dropna size is:
877
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 2031 entries, ('GB08439289', 2019) to ('IE549110', 2017)
Data columns (total 1 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   W.I.P._th_GBP  2031 non-null   float64
dtypes: float64(1)
memory usage: 31.9+ KB
218
125990
After dropna size is:
835
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 2866 entries, ('GB08439289', 2019) to ('IE549110', 2016)
Data columns (total 1 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   W.I.P._th_GBP  2866 non-null   float64
dtypes: float64(1)
memory usage: 43.6+ KB
219
125990
After dropna size is:
612
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 3478 entries, ('GB08439289', 2019) to ('IE549110', 2015)
Data columns (total 1 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   W.I.P._th_GBP  3478 non-null   float64
dtypes: float64(1)
memory usage: 51.8+ KB
220
125990
After dropna size is:
543
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 4021 entries, ('GB08439289', 2019) to ('GB08264364', 2014)
Data columns (total 1 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   W.I.P._th_GBP  4021 non-null   float64
dtypes: float64(1)
memory usage: 59.2+ KB
221
125990
After dropna size is:
423
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 4444 entries, ('GB08439289', 2019) to ('GB07418349', 2013)
Data columns (total 1 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   W.I.P._th_GBP  4444 non-null   float64
dtypes: float64(1)
memory usage: 64.9+ KB
222
125990
After dropna size is:
338
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 4782 entries, ('GB08439289', 2019) to ('GB07418349', 2012)
Data columns (total 1 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   W.I.P._th_GBP  4782 non-null   float64
dtypes: float64(1)
memory usage: 69.5+ KB
223
125990
After dropna size is:
191
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 4973 entries, ('GB08439289', 2019) to ('GB07418349', 2011)
Data columns (total 1 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   W.I.P._th_GBP  4973 non-null   float64
dtypes: float64(1)
memory usage: 72.1+ KB
224
125990
After dropna size is:
517
225
125990
After dropna size is:
1224
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1741 entries, ('GB08444030', 2019) to ('GB08790650', 2018)
Data columns (total 1 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Finished_Goods_th_GBP  1741 non-null   float64
dtypes: float64(1)
memory usage: 29.7+ KB
226
125990
After dropna size is:
1266

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'W.I.P._th_GBP'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 3007 entries, ('GB08444030', 2019) to ('IE549110', 2017)
Data columns (total 1 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Finished_Goods_th_GBP  3007 non-null   float64
dtypes: float64(1)
memory usage: 46.8+ KB
227
125990
After dropna size is:
984
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 3991 entries, ('GB08444030', 2019) to ('GB07373235', 2016)
Data columns (total 1 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Finished_Goods_th_GBP  3991 non-null   float64
dtypes: float64(1)
memory usage: 59.8+ KB
228
125990
After dropna size is:
682
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 4673 entries, ('GB08444030', 2019) to ('GB07373235', 2015)
Data columns (total 1 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Finished_Goods_th_GBP  4673 non-null   float64
dtypes: float64(1)
memory usage: 68.7+ KB
229
125990
After dropna size is:
526
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 5199 entries, ('GB08444030', 2019) to ('GB07657353', 2014)
Data columns (total 1 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Finished_Goods_th_GBP  5199 non-null   float64
dtypes: float64(1)
memory usage: 75.6+ KB
230
125990
After dropna size is:
393
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 5592 entries, ('GB08444030', 2019) to ('GB07341487', 2013)
Data columns (total 1 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Finished_Goods_th_GBP  5592 non-null   float64
dtypes: float64(1)
memory usage: 80.6+ KB
231
125990
After dropna size is:
309
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 5901 entries, ('GB08444030', 2019) to ('GB07341487', 2012)
Data columns (total 1 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Finished_Goods_th_GBP  5901 non-null   float64
dtypes: float64(1)
memory usage: 84.8+ KB
232
125990
After dropna size is:
131
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 6032 entries, ('GB08444030', 2019) to ('GB07341487', 2011)
Data columns (total 1 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Finished_Goods_th_GBP  6032 non-null   float64
dtypes: float64(1)
memory usage: 86.5+ KB
233
125990
After dropna size is:
11491
234
125990
After dropna size is:
22926
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 34417 entries, ('GB09507385', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Trade_Debtors_th_GBP  34417 non-null  float64
dtypes: float64(1)
memory usage: 568.2+ KB
235
125990
After dropna size is:
24207
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 58624 entries, ('GB09507385', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Trade_Debtors_th_GBP  58624 non-null  float64
dtypes: float64(1)
memory usage: 876.0+ KB
236
125990
After dropna size is:
17669
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 76293 entries, ('GB09507385', 2019) to ('GBSC452461', 2016)
Data columns (total 1 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Trade_Debtors_th_GBP  76293 non-null  float64
dtypes: float64(1)
memory usage: 1.2+ MB
237
125990
After dropna size is:
14376
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 90669 entries, ('GB09507385', 2019) to ('GBOC369696', 2015)
Data columns (total 1 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Trade_Debtors_th_GBP  90669 non-null  float64
dtypes: float64(1)
memory usage: 1.4+ MB
238
125990
After dropna size is:
12936
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 103605 entries, ('GB09507385', 2019) to ('GBOC369696', 2014)
Data columns (total 1 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Trade_Debtors_th_GBP  103605 non-null  float64
dtypes: float64(1)
memory usage: 1.6+ MB
239
125990
After dropna size is:
11247
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 114852 entries, ('GB09507385', 2019) to ('GBOC369696', 2013)
Data columns (total 1 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Trade_Debtors_th_GBP  114852 non-null  float64
dtypes: float64(1)
memory usage: 1.8+ MB
240
125990
After dropna size is:
8330
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 123182 entries, ('GB09507385', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Trade_Debtors_th_GBP  123182 non-null  float64
dtypes: float64(1)
memory usage: 1.9+ MB
241
125990
After dropna size is:
4108
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 127290 entries, ('GB09507385', 2019) to ('GB07266603', 2011)
Data columns (total 1 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Trade_Debtors_th_GBP  127290 non-null  float64
dtypes: float64(1)
memory usage: 2.0+ MB
242
125990
After dropna size is:
26843
243
125990
After dropna size is:
50014
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 76857 entries, ('GB07588867', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Bank_&_Deposits_th_GBP  76857 non-null  float64
dtypes: float64(1)
memory usage: 1.4+ MB
244
125990
After dropna size is:
57744
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 134601 entries, ('GB07588867', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Bank_&_Deposits_th_GBP  134601 non-null  float64
dtypes: float64(1)
memory usage: 2.2+ MB
245
125990
After dropna size is:
75640
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 210241 entries, ('GB07588867', 2019) to ('GBOC381395', 2016)
Data columns (total 1 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Bank_&_Deposits_th_GBP  210241 non-null  float64
dtypes: float64(1)
memory usage: 3.3+ MB
246
125990
After dropna size is:
73958
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 284199 entries, ('GB07588867', 2019) to ('GBOC381395', 2015)
Data columns (total 1 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Bank_&_Deposits_th_GBP  284199 non-null  float64
dtypes: float64(1)
memory usage: 4.3+ MB
247
125990
After dropna size is:
65198
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 349397 entries, ('GB07588867', 2019) to ('GBOC381395', 2014)
Data columns (total 1 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Bank_&_Deposits_th_GBP  349397 non-null  float64
dtypes: float64(1)
memory usage: 5.1+ MB
248
125990
After dropna size is:
52365
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 401762 entries, ('GB07588867', 2019) to ('GBOC369696', 2013)
Data columns (total 1 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Bank_&_Deposits_th_GBP  401762 non-null  float64
dtypes: float64(1)
memory usage: 5.8+ MB
249
125990
After dropna size is:
35586
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 437348 entries, ('GB07588867', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Bank_&_Deposits_th_GBP  437348 non-null  float64
dtypes: float64(1)
memory usage: 6.3+ MB
250
125990
After dropna size is:
17706

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 455054 entries, ('GB07588867', 2019) to ('GB07266603', 2011)
Data columns (total 1 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Bank_&_Deposits_th_GBP  455054 non-null  float64
dtypes: float64(1)
memory usage: 6.5+ MB
251
125990
After dropna size is:
45129

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Bank_&_Deposits_th_GBP'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

252
125990
After dropna size is:
76895
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 122024 entries, ('GB09567757', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Other_Current_Assets_th_GBP  122024 non-null  float64
dtypes: float64(1)
memory usage: 2.1+ MB
253
125990
After dropna size is:
80047
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 202071 entries, ('GB09567757', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Other_Current_Assets_th_GBP  202071 non-null  float64
dtypes: float64(1)
memory usage: 3.2+ MB
254
125990
After dropna size is:
72320
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 274391 entries, ('GB09567757', 2019) to ('GBOC381395', 2016)
Data columns (total 1 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Other_Current_Assets_th_GBP  274391 non-null  float64
dtypes: float64(1)
memory usage: 4.2+ MB
255
125990
After dropna size is:
60551
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 334942 entries, ('GB09567757', 2019) to ('GBSC452461', 2015)
Data columns (total 1 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Other_Current_Assets_th_GBP  334942 non-null  float64
dtypes: float64(1)
memory usage: 5.0+ MB
256
125990
After dropna size is:
48996
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 383938 entries, ('GB09567757', 2019) to ('GBSC452461', 2014)
Data columns (total 1 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Other_Current_Assets_th_GBP  383938 non-null  float64
dtypes: float64(1)
memory usage: 5.6+ MB
257
125990
After dropna size is:
36735
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 420673 entries, ('GB09567757', 2019) to ('GBSC452461', 2013)
Data columns (total 1 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Other_Current_Assets_th_GBP  420673 non-null  float64
dtypes: float64(1)
memory usage: 6.1+ MB
258
125990
After dropna size is:
24916
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 445589 entries, ('GB09567757', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Other_Current_Assets_th_GBP  445589 non-null  float64
dtypes: float64(1)
memory usage: 6.4+ MB
259
125990
After dropna size is:
12210
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 457799 entries, ('GB09567757', 2019) to ('GB07266603', 2011)
Data columns (total 1 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Other_Current_Assets_th_GBP  457799 non-null  float64
dtypes: float64(1)
memory usage: 6.5+ MB
260
125990
After dropna size is:
3145
261
125990
After dropna size is:
8886
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 12031 entries, ('GB09488271', 2019) to ('GBSC452461', 2018)
Data columns (total 1 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Group_Loans_(asset)_th_GBP  12031 non-null  float64
dtypes: float64(1)
memory usage: 204.9+ KB
262
125990
After dropna size is:
8726
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 20757 entries, ('GB09488271', 2019) to ('GBSC452461', 2017)
Data columns (total 1 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Group_Loans_(asset)_th_GBP  20757 non-null  float64
dtypes: float64(1)
memory usage: 313.7+ KB
263
125990
After dropna size is:
7690
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 28447 entries, ('GB09488271', 2019) to ('GBSC452461', 2016)
Data columns (total 1 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Group_Loans_(asset)_th_GBP  28447 non-null  float64
dtypes: float64(1)
memory usage: 407.6+ KB
264
125990
After dropna size is:
5627
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 34074 entries, ('GB09488271', 2019) to ('GBOC369696', 2015)
Data columns (total 1 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Group_Loans_(asset)_th_GBP  34074 non-null  float64
dtypes: float64(1)
memory usage: 475.4+ KB
265
125990
After dropna size is:
4379
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 38453 entries, ('GB09488271', 2019) to ('GBSC452461', 2014)
Data columns (total 1 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Group_Loans_(asset)_th_GBP  38453 non-null  float64
dtypes: float64(1)
memory usage: 527.6+ KB
266
125990
After dropna size is:
3254
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 41707 entries, ('GB09488271', 2019) to ('GBSC452461', 2013)
Data columns (total 1 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Group_Loans_(asset)_th_GBP  41707 non-null  float64
dtypes: float64(1)
memory usage: 566.2+ KB
267
125990
After dropna size is:
2198
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 43905 entries, ('GB09488271', 2019) to ('GB07937886', 2012)
Data columns (total 1 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Group_Loans_(asset)_th_GBP  43905 non-null  float64
dtypes: float64(1)
memory usage: 592.6+ KB
268
125990
After dropna size is:
1170
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 45075 entries, ('GB09488271', 2019) to ('GB07361608', 2011)
Data columns (total 1 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Group_Loans_(asset)_th_GBP  45075 non-null  float64
dtypes: float64(1)
memory usage: 606.5+ KB
269
125990
After dropna size is:
713
270
125990
After dropna size is:
1185
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1898 entries, ('GB08443448', 2019) to ('GBOC403099', 2018)
Data columns (total 1 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Directors_Loans_(asset)_th_GBP  1898 non-null   float64
dtypes: float64(1)
memory usage: 32.7+ KB
271
125990
After dropna size is:
1076
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 2974 entries, ('GB08443448', 2019) to ('GBSC448163', 2017)
Data columns (total 1 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Directors_Loans_(asset)_th_GBP  2974 non-null   float64
dtypes: float64(1)
memory usage: 49.3+ KB
272
125990
After dropna size is:
598
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 3572 entries, ('GB08443448', 2019) to ('GB07810580', 2016)
Data columns (total 1 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Directors_Loans_(asset)_th_GBP  3572 non-null   float64
dtypes: float64(1)
memory usage: 59.0+ KB
273
125990
After dropna size is:
730
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 4302 entries, ('GB08443448', 2019) to ('GB08425566', 2015)
Data columns (total 1 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Directors_Loans_(asset)_th_GBP  4302 non-null   float64
dtypes: float64(1)
memory usage: 70.6+ KB
274
125990
After dropna size is:
727
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 5029 entries, ('GB08443448', 2019) to ('GB07361608', 2014)
Data columns (total 1 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Directors_Loans_(asset)_th_GBP  5029 non-null   float64
dtypes: float64(1)
memory usage: 81.6+ KB
275
125990
After dropna size is:
643
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 5672 entries, ('GB08443448', 2019) to ('GBOC370142', 2013)
Data columns (total 1 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Directors_Loans_(asset)_th_GBP  5672 non-null   float64
dtypes: float64(1)
memory usage: 91.3+ KB
276
125990
After dropna size is:
542
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 6214 entries, ('GB08443448', 2019) to ('GB07335752', 2012)
Data columns (total 1 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Directors_Loans_(asset)_th_GBP  6214 non-null   float64
dtypes: float64(1)
memory usage: 99.7+ KB
277
125990
After dropna size is:
251

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Group_Loans_(asset)_th_GBP'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 6465 entries, ('GB08443448', 2019) to ('GB07377831', 2011)
Data columns (total 1 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Directors_Loans_(asset)_th_GBP  6465 non-null   float64
dtypes: float64(1)
memory usage: 103.5+ KB
278
125990
After dropna size is:
41055
279
125990
After dropna size is:
68450

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Directors_Loans_(asset)_th_GBP'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 109505 entries, ('GB09567757', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Other_Debtors_th_GBP  109505 non-null  float64
dtypes: float64(1)
memory usage: 1.9+ MB
280
125990
After dropna size is:
71441
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 180946 entries, ('GB09567757', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Other_Debtors_th_GBP  180946 non-null  float64
dtypes: float64(1)
memory usage: 2.9+ MB
281
125990
After dropna size is:
65255
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 246201 entries, ('GB09567757', 2019) to ('GBOC381395', 2016)
Data columns (total 1 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Other_Debtors_th_GBP  246201 non-null  float64
dtypes: float64(1)
memory usage: 3.8+ MB
282
125990
After dropna size is:
54725
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 300926 entries, ('GB09567757', 2019) to ('GBSC452461', 2015)
Data columns (total 1 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Other_Debtors_th_GBP  300926 non-null  float64
dtypes: float64(1)
memory usage: 4.5+ MB
283
125990
After dropna size is:
43940
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 344866 entries, ('GB09567757', 2019) to ('GBOC369696', 2014)
Data columns (total 1 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Other_Debtors_th_GBP  344866 non-null  float64
dtypes: float64(1)
memory usage: 5.1+ MB
284
125990
After dropna size is:
32602
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 377468 entries, ('GB09567757', 2019) to ('GBOC369696', 2013)
Data columns (total 1 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Other_Debtors_th_GBP  377468 non-null  float64
dtypes: float64(1)
memory usage: 5.5+ MB
285
125990
After dropna size is:
21862
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 399330 entries, ('GB09567757', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Other_Debtors_th_GBP  399330 non-null  float64
dtypes: float64(1)
memory usage: 5.8+ MB
286
125990
After dropna size is:
10565
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 409895 entries, ('GB09567757', 2019) to ('GB07266603', 2011)
Data columns (total 1 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Other_Debtors_th_GBP  409895 non-null  float64
dtypes: float64(1)
memory usage: 5.9+ MB
287
125990
After dropna size is:
7214
288
125990
After dropna size is:
14564
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 21778 entries, ('GB09291063', 2019) to ('GBSC452461', 2018)
Data columns (total 1 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Prepayments_th_GBP  21778 non-null  float64
dtypes: float64(1)
memory usage: 362.2+ KB
289
125990
After dropna size is:
14912
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 36690 entries, ('GB09291063', 2019) to ('GB09153143', 2017)
Data columns (total 1 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Prepayments_th_GBP  36690 non-null  float64
dtypes: float64(1)
memory usage: 551.3+ KB
290
125990
After dropna size is:
11499
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 48189 entries, ('GB09291063', 2019) to ('GB09102173', 2016)
Data columns (total 1 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Prepayments_th_GBP  48189 non-null  float64
dtypes: float64(1)
memory usage: 695.4+ KB
291
125990
After dropna size is:
8439
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 56628 entries, ('GB09291063', 2019) to ('GBOC369696', 2015)
Data columns (total 1 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Prepayments_th_GBP  56628 non-null  float64
dtypes: float64(1)
memory usage: 800.1+ KB
292
125990
After dropna size is:
6400
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 63028 entries, ('GB09291063', 2019) to ('GB08058491', 2014)
Data columns (total 1 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Prepayments_th_GBP  63028 non-null  float64
dtypes: float64(1)
memory usage: 879.2+ KB
293
125990
After dropna size is:
4936
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 67964 entries, ('GB09291063', 2019) to ('GB08058491', 2013)
Data columns (total 1 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Prepayments_th_GBP  67964 non-null  float64
dtypes: float64(1)
memory usage: 940.8+ KB
294
125990
After dropna size is:
3428
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 71392 entries, ('GB09291063', 2019) to ('GB07937886', 2012)
Data columns (total 1 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Prepayments_th_GBP  71392 non-null  float64
dtypes: float64(1)
memory usage: 983.5+ KB
295
125990
After dropna size is:
1735
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 73127 entries, ('GB09291063', 2019) to ('GB07361608', 2011)
Data columns (total 1 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Prepayments_th_GBP  73127 non-null  float64
dtypes: float64(1)
memory usage: 1005.4+ KB
296
125990
After dropna size is:
2367
297
125990
After dropna size is:
5413
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 7780 entries, ('GB09044503', 2019) to ('GB09564843', 2018)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Deferred_Taxation_th_GBP  7780 non-null   float64
dtypes: float64(1)
memory usage: 133.1+ KB
298
125990
After dropna size is:
5479
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 13259 entries, ('GB09044503', 2019) to ('GB09564843', 2017)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Deferred_Taxation_th_GBP  13259 non-null  float64
dtypes: float64(1)
memory usage: 208.1+ KB
299
125990
After dropna size is:
4462
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 17721 entries, ('GB09044503', 2019) to ('GB09321895', 2016)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Deferred_Taxation_th_GBP  17721 non-null  float64
dtypes: float64(1)
memory usage: 268.1+ KB
300
125990
After dropna size is:
3551
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 21272 entries, ('GB09044503', 2019) to ('GBOC369696', 2015)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Deferred_Taxation_th_GBP  21272 non-null  float64
dtypes: float64(1)
memory usage: 315.8+ KB
301
125990
After dropna size is:
2900
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 24172 entries, ('GB09044503', 2019) to ('GB07192669', 2014)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Deferred_Taxation_th_GBP  24172 non-null  float64
dtypes: float64(1)
memory usage: 354.0+ KB
302
125990
After dropna size is:
2258
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 26430 entries, ('GB09044503', 2019) to ('GB07258174', 2013)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Deferred_Taxation_th_GBP  26430 non-null  float64
dtypes: float64(1)
memory usage: 384.0+ KB
303
125990
After dropna size is:
1539
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 27969 entries, ('GB09044503', 2019) to ('GBSC384248', 2012)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Deferred_Taxation_th_GBP  27969 non-null  float64
dtypes: float64(1)
memory usage: 404.7+ KB
304
125990
After dropna size is:
767
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 28736 entries, ('GB09044503', 2019) to ('GB07258174', 2011)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Deferred_Taxation_th_GBP  28736 non-null  float64
dtypes: float64(1)
memory usage: 414.8+ KB
305
125990
After dropna size is:
56479

306
125990
After dropna size is:
96560
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 153039 entries, ('GB09567757', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Current_Assets_th_GBP  153039 non-null  float64
dtypes: float64(1)
memory usage: 2.6+ MB
307
125990
After dropna size is:
104061
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 257100 entries, ('GB09567757', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Current_Assets_th_GBP  257100 non-null  float64
dtypes: float64(1)
memory usage: 4.0+ MB
308
125990
After dropna size is:
101815
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 358915 entries, ('GB09567757', 2019) to ('GBOC381395', 2016)
Data columns (total 1 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Current_Assets_th_GBP  358915 non-null  float64
dtypes: float64(1)
memory usage: 5.3+ MB
309
125990
After dropna size is:
90093
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 449008 entries, ('GB09567757', 2019) to ('GBOC381395', 2015)
Data columns (total 1 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Current_Assets_th_GBP  449008 non-null  float64
dtypes: float64(1)
memory usage: 6.5+ MB
310
125990
After dropna size is:
76256
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 525264 entries, ('GB09567757', 2019) to ('GBOC381395', 2014)
Data columns (total 1 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Current_Assets_th_GBP  525264 non-null  float64
dtypes: float64(1)
memory usage: 7.4+ MB
311
125990
After dropna size is:
59352
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 584616 entries, ('GB09567757', 2019) to ('GBSC452461', 2013)
Data columns (total 1 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Current_Assets_th_GBP  584616 non-null  float64
dtypes: float64(1)
memory usage: 8.2+ MB
312
125990
After dropna size is:
40822
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 625438 entries, ('GB09567757', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Current_Assets_th_GBP  625438 non-null  float64
dtypes: float64(1)
memory usage: 8.7+ MB
313
125990
After dropna size is:
20688
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 646126 entries, ('GB09567757', 2019) to ('GB07266603', 2011)
Data columns (total 1 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Current_Assets_th_GBP  646126 non-null  float64
dtypes: float64(1)
memory usage: 9.0+ MB
314
125990
After dropna size is:
12005
315
125990
After dropna size is:
24564
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 36569 entries, ('GB07588867', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Trade_Creditors_th_GBP  36569 non-null  float64
dtypes: float64(1)
memory usage: 603.4+ KB
316
125990
After dropna size is:
25906
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 62475 entries, ('GB07588867', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Trade_Creditors_th_GBP  62475 non-null  float64
dtypes: float64(1)
memory usage: 927.2+ KB
317
125990
After dropna size is:
19420
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 81895 entries, ('GB07588867', 2019) to ('GBOC381395', 2016)
Data columns (total 1 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Trade_Creditors_th_GBP  81895 non-null  float64
dtypes: float64(1)
memory usage: 1.3+ MB
318
125990
After dropna size is:
16160
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 98055 entries, ('GB07588867', 2019) to ('GBSC452461', 2015)
Data columns (total 1 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Trade_Creditors_th_GBP  98055 non-null  float64
dtypes: float64(1)
memory usage: 1.5+ MB
319
125990
After dropna size is:
14009
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 112064 entries, ('GB07588867', 2019) to ('IE505067', 2014)
Data columns (total 1 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Trade_Creditors_th_GBP  112064 non-null  float64
dtypes: float64(1)
memory usage: 1.7+ MB
320
125990
After dropna size is:
11579
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 123643 entries, ('GB07588867', 2019) to ('GBOC369696', 2013)
Data columns (total 1 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Trade_Creditors_th_GBP  123643 non-null  float64
dtypes: float64(1)
memory usage: 1.9+ MB
321
125990
After dropna size is:
8499
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 132142 entries, ('GB07588867', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Trade_Creditors_th_GBP  132142 non-null  float64
dtypes: float64(1)
memory usage: 2.0+ MB
322
125990
After dropna size is:
4451
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 136593 entries, ('GB07588867', 2019) to ('GB07266603', 2011)
Data columns (total 1 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Trade_Creditors_th_GBP  136593 non-null  float64
dtypes: float64(1)
memory usage: 2.1+ MB
323
125990
After dropna size is:
11180
324
125990
After dropna size is:
24132
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 35312 entries, ('GB09488271', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Short_Term_Loans_&_Overdrafts_th_GBP  35312 non-null  float64
dtypes: float64(1)
memory usage: 586.8+ KB
325
125990
After dropna size is:
25480
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 60792 entries, ('GB09488271', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Short_Term_Loans_&_Overdrafts_th_GBP  60792 non-null  float64
dtypes: float64(1)
memory usage: 909.0+ KB
326
125990
After dropna size is:
20362
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 81154 entries, ('GB09488271', 2019) to ('GBSC452461', 2016)
Data columns (total 1 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Short_Term_Loans_&_Overdrafts_th_GBP  81154 non-null  float64
dtypes: float64(1)
memory usage: 1.3+ MB
327
125990
After dropna size is:
16399
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 97553 entries, ('GB09488271', 2019) to ('GBSC452461', 2015)
Data columns (total 1 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Short_Term_Loans_&_Overdrafts_th_GBP  97553 non-null  float64
dtypes: float64(1)
memory usage: 1.5+ MB
328
125990
After dropna size is:
14288
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 111841 entries, ('GB09488271', 2019) to ('GBOC369696', 2014)
Data columns (total 1 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   Short_Term_Loans_&_Overdrafts_th_GBP  111841 non-null  float64
dtypes: float64(1)
memory usage: 1.7+ MB
329
125990
After dropna size is:
11931

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 123772 entries, ('GB09488271', 2019) to ('GBOC369696', 2013)
Data columns (total 1 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   Short_Term_Loans_&_Overdrafts_th_GBP  123772 non-null  float64
dtypes: float64(1)
memory usage: 1.9+ MB
330
125990
After dropna size is:
8769
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 132541 entries, ('GB09488271', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   Short_Term_Loans_&_Overdrafts_th_GBP  132541 non-null  float64
dtypes: float64(1)
memory usage: 2.0+ MB
331
125990
After dropna size is:
4823
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 137364 entries, ('GB09488271', 2019) to ('GB07266603', 2011)
Data columns (total 1 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   Short_Term_Loans_&_Overdrafts_th_GBP  137364 non-null  float64
dtypes: float64(1)
memory usage: 2.1+ MB
332
125990
After dropna size is:
3584
333
125990
After dropna size is:
6462
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 10046 entries, ('GB08438651', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Bank_Overdrafts_th_GBP  10046 non-null  float64
dtypes: float64(1)
memory usage: 168.9+ KB
334
125990
After dropna size is:
6582

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Short_Term_Loans_&_Overdrafts_th_GBP'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 16628 entries, ('GB08438651', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Bank_Overdrafts_th_GBP  16628 non-null  float64
dtypes: float64(1)
memory usage: 259.9+ KB
335
125990
After dropna size is:
4594
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 21222 entries, ('GB08438651', 2019) to ('GB09102173', 2016)
Data columns (total 1 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Bank_Overdrafts_th_GBP  21222 non-null  float64
dtypes: float64(1)
memory usage: 324.3+ KB
336
125990
After dropna size is:
3766
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 24988 entries, ('GB08438651', 2019) to ('GB07618603', 2015)
Data columns (total 1 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Bank_Overdrafts_th_GBP  24988 non-null  float64
dtypes: float64(1)
memory usage: 377.0+ KB
337
125990
After dropna size is:
3537
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 28525 entries, ('GB08438651', 2019) to ('GB07618603', 2014)
Data columns (total 1 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Bank_Overdrafts_th_GBP  28525 non-null  float64
dtypes: float64(1)
memory usage: 425.5+ KB
338
125990
After dropna size is:
2999
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 31524 entries, ('GB08438651', 2019) to ('GB07618603', 2013)
Data columns (total 1 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Bank_Overdrafts_th_GBP  31524 non-null  float64
dtypes: float64(1)
memory usage: 467.1+ KB
339
125990
After dropna size is:
2261
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 33785 entries, ('GB08438651', 2019) to ('GB07937886', 2012)
Data columns (total 1 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Bank_Overdrafts_th_GBP  33785 non-null  float64
dtypes: float64(1)
memory usage: 498.2+ KB
340
125990
After dropna size is:
1158
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 34943 entries, ('GB08438651', 2019) to ('GB07341487', 2011)
Data columns (total 1 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Bank_Overdrafts_th_GBP  34943 non-null  float64
dtypes: float64(1)
memory usage: 514.2+ KB
341
125990
After dropna size is:
4373
342
125990
After dropna size is:
11907
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 16280 entries, ('GB07565512', 2019) to ('GBSC452461', 2018)
Data columns (total 1 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Group_Loans_(short_t.)_th_GBP  16280 non-null  float64
dtypes: float64(1)
memory usage: 273.6+ KB
343
125990
After dropna size is:
12273
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 28553 entries, ('GB07565512', 2019) to ('GBSC452461', 2017)
Data columns (total 1 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Group_Loans_(short_t.)_th_GBP  28553 non-null  float64
dtypes: float64(1)
memory usage: 423.2+ KB
344
125990
After dropna size is:
10651
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 39204 entries, ('GB07565512', 2019) to ('GBSC452461', 2016)
Data columns (total 1 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Group_Loans_(short_t.)_th_GBP  39204 non-null  float64
dtypes: float64(1)
memory usage: 549.7+ KB
345
125990
After dropna size is:
7890
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 47094 entries, ('GB07565512', 2019) to ('GBSC452461', 2015)
Data columns (total 1 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Group_Loans_(short_t.)_th_GBP  47094 non-null  float64
dtypes: float64(1)
memory usage: 643.1+ KB
346
125990
After dropna size is:
6057
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 53151 entries, ('GB07565512', 2019) to ('GBOC369696', 2014)
Data columns (total 1 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Group_Loans_(short_t.)_th_GBP  53151 non-null  float64
dtypes: float64(1)
memory usage: 714.4+ KB
347
125990
After dropna size is:
4461
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 57612 entries, ('GB07565512', 2019) to ('GBOC369696', 2013)
Data columns (total 1 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Group_Loans_(short_t.)_th_GBP  57612 non-null  float64
dtypes: float64(1)
memory usage: 766.8+ KB
348
125990
After dropna size is:
3109
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 60721 entries, ('GB07565512', 2019) to ('GB07361608', 2012)
Data columns (total 1 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Group_Loans_(short_t.)_th_GBP  60721 non-null  float64
dtypes: float64(1)
memory usage: 803.6+ KB
349
125990
After dropna size is:
1603
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 62324 entries, ('GB07565512', 2019) to ('GB07339695', 2011)
Data columns (total 1 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Group_Loans_(short_t.)_th_GBP  62324 non-null  float64
dtypes: float64(1)
memory usage: 822.4+ KB
350
125990
After dropna size is:
3304

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Group_Loans_(short_t.)_th_GBP'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

351
125990
After dropna size is:
5685
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 8989 entries, ('GB09488271', 2019) to ('IE505067', 2018)
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Director_Loans_(short_t.)_th_GBP  8989 non-null   float64
dtypes: float64(1)
memory usage: 148.8+ KB
352
125990
After dropna size is:
6244
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 15233 entries, ('GB09488271', 2019) to ('IE505067', 2017)
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Director_Loans_(short_t.)_th_GBP  15233 non-null  float64
dtypes: float64(1)
memory usage: 234.0+ KB
353
125990
After dropna size is:
4682
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 19915 entries, ('GB09488271', 2019) to ('IE505067', 2016)
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Director_Loans_(short_t.)_th_GBP  19915 non-null  float64
dtypes: float64(1)
memory usage: 301.6+ KB
354
125990
After dropna size is:
4232
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 24147 entries, ('GB09488271', 2019) to ('GB08389817', 2015)
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Director_Loans_(short_t.)_th_GBP  24147 non-null  float64
dtypes: float64(1)
memory usage: 360.7+ KB
355
125990
After dropna size is:
4252
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 28399 entries, ('GB09488271', 2019) to ('GB08389817', 2014)
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Director_Loans_(short_t.)_th_GBP  28399 non-null  float64
dtypes: float64(1)
memory usage: 419.3+ KB
356
125990
After dropna size is:
4259
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 32658 entries, ('GB09488271', 2019) to ('GB07266603', 2013)
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Director_Loans_(short_t.)_th_GBP  32658 non-null  float64
dtypes: float64(1)
memory usage: 478.3+ KB
357
125990
After dropna size is:
3406
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 36064 entries, ('GB09488271', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Director_Loans_(short_t.)_th_GBP  36064 non-null  float64
dtypes: float64(1)
memory usage: 525.0+ KB
358
125990
After dropna size is:
2040
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 38104 entries, ('GB09488271', 2019) to ('GB07266603', 2011)
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Director_Loans_(short_t.)_th_GBP  38104 non-null  float64
dtypes: float64(1)
memory usage: 553.1+ KB
359
125990
After dropna size is:
1006

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Director_Loans_(short_t.)_th_GBP'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

360
125990
After dropna size is:
1815
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 2821 entries, ('GB08460650', 2019) to ('GB09783953', 2018)
Data columns (total 1 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Hire_Purch._&_Leas._(short_t.)_th_GBP  2821 non-null   float64
dtypes: float64(1)
memory usage: 47.0+ KB
361
125990
After dropna size is:
1906
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 4727 entries, ('GB08460650', 2019) to ('GB08400816', 2017)
Data columns (total 1 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Hire_Purch._&_Leas._(short_t.)_th_GBP  4727 non-null   float64
dtypes: float64(1)
memory usage: 72.1+ KB
362
125990
After dropna size is:
1225
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 5952 entries, ('GB08460650', 2019) to ('GB09783953', 2016)
Data columns (total 1 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Hire_Purch._&_Leas._(short_t.)_th_GBP  5952 non-null   float64
dtypes: float64(1)
memory usage: 88.3+ KB
363
125990
After dropna size is:
1048
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 7000 entries, ('GB08460650', 2019) to ('GBOC365323', 2015)
Data columns (total 1 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Hire_Purch._&_Leas._(short_t.)_th_GBP  7000 non-null   float64
dtypes: float64(1)
memory usage: 102.4+ KB
364
125990
After dropna size is:
896
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 7896 entries, ('GB08460650', 2019) to ('GB07841692', 2014)
Data columns (total 1 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Hire_Purch._&_Leas._(short_t.)_th_GBP  7896 non-null   float64
dtypes: float64(1)
memory usage: 114.1+ KB
365
125990
After dropna size is:
673
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 8569 entries, ('GB08460650', 2019) to ('GB07868880', 2013)
Data columns (total 1 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Hire_Purch._&_Leas._(short_t.)_th_GBP  8569 non-null   float64
dtypes: float64(1)
memory usage: 123.0+ KB
366
125990
After dropna size is:
479
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 9048 entries, ('GB08460650', 2019) to ('GBNC000600', 2012)
Data columns (total 1 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Hire_Purch._&_Leas._(short_t.)_th_GBP  9048 non-null   float64
dtypes: float64(1)
memory usage: 129.5+ KB
367
125990
After dropna size is:
218
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 9266 entries, ('GB08460650', 2019) to ('GBNC000600', 2011)
Data columns (total 1 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Hire_Purch._&_Leas._(short_t.)_th_GBP  9266 non-null   float64
dtypes: float64(1)
memory usage: 132.4+ KB
368
125990
After dropna size is:
459

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Hire_Purch._&_Leas._(short_t.)_th_GBP'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)
/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Hire_Purchase_(short_t.)_th_GBP'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

369
125990
After dropna size is:
733
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1192 entries, ('GB08460650', 2019) to ('GB09032302', 2018)
Data columns (total 1 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Hire_Purchase_(short_t.)_th_GBP  1192 non-null   float64
dtypes: float64(1)
memory usage: 19.9+ KB
370
125990
After dropna size is:
732
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1924 entries, ('GB08460650', 2019) to ('GB09032302', 2017)
Data columns (total 1 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Hire_Purchase_(short_t.)_th_GBP  1924 non-null   float64
dtypes: float64(1)
memory usage: 29.8+ KB
371
125990
After dropna size is:
411
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 2335 entries, ('GB08460650', 2019) to ('GB08185130', 2016)
Data columns (total 1 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Hire_Purchase_(short_t.)_th_GBP  2335 non-null   float64
dtypes: float64(1)
memory usage: 35.6+ KB
372
125990
After dropna size is:
368
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 2703 entries, ('GB08460650', 2019) to ('GBOC365323', 2015)
Data columns (total 1 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Hire_Purchase_(short_t.)_th_GBP  2703 non-null   float64
dtypes: float64(1)
memory usage: 40.9+ KB
373
125990
After dropna size is:
355
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 3058 entries, ('GB08460650', 2019) to ('GB07841692', 2014)
Data columns (total 1 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Hire_Purchase_(short_t.)_th_GBP  3058 non-null   float64
dtypes: float64(1)
memory usage: 45.8+ KB
374
125990
After dropna size is:
255
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 3313 entries, ('GB08460650', 2019) to ('GB08067474', 2013)
Data columns (total 1 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Hire_Purchase_(short_t.)_th_GBP  3313 non-null   float64
dtypes: float64(1)
memory usage: 49.4+ KB
375
125990
After dropna size is:
190
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 3503 entries, ('GB08460650', 2019) to ('GBNC000600', 2012)
Data columns (total 1 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Hire_Purchase_(short_t.)_th_GBP  3503 non-null   float64
dtypes: float64(1)
memory usage: 52.2+ KB
376
125990
After dropna size is:
100
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 3603 entries, ('GB08460650', 2019) to ('GBNC000600', 2011)
Data columns (total 1 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Hire_Purchase_(short_t.)_th_GBP  3603 non-null   float64
dtypes: float64(1)
memory usage: 53.6+ KB
377
125990
After dropna size is:
172
378
125990
After dropna size is:
467
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 639 entries, ('GB07143675', 2019) to ('GB07251871', 2018)
Data columns (total 1 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Leasing_(short_t.)_th_GBP  639 non-null    float64
dtypes: float64(1)
memory usage: 11.3+ KB
379
125990
After dropna size is:
532
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1171 entries, ('GB07143675', 2019) to ('GB08014200', 2017)
Data columns (total 1 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Leasing_(short_t.)_th_GBP  1171 non-null   float64
dtypes: float64(1)
memory usage: 18.6+ KB
380
125990
After dropna size is:
381
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1552 entries, ('GB07143675', 2019) to ('GB07253667', 2016)
Data columns (total 1 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Leasing_(short_t.)_th_GBP  1552 non-null   float64
dtypes: float64(1)
memory usage: 23.8+ KB
381
125990
After dropna size is:
303
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1855 entries, ('GB07143675', 2019) to ('GB07168171', 2015)
Data columns (total 1 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Leasing_(short_t.)_th_GBP  1855 non-null   float64
dtypes: float64(1)
memory usage: 27.9+ KB
382
125990
After dropna size is:
206
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 2061 entries, ('GB07143675', 2019) to ('GB07253667', 2014)
Data columns (total 1 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Leasing_(short_t.)_th_GBP  2061 non-null   float64
dtypes: float64(1)
memory usage: 30.5+ KB
383
125990
After dropna size is:
147
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 2208 entries, ('GB07143675', 2019) to ('IE529161', 2013)
Data columns (total 1 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Leasing_(short_t.)_th_GBP  2208 non-null   float64
dtypes: float64(1)
memory usage: 32.4+ KB
384
125990
After dropna size is:
91
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 2299 entries, ('GB07143675', 2019) to ('GB07569777', 2012)
Data columns (total 1 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Leasing_(short_t.)_th_GBP  2299 non-null   float64
dtypes: float64(1)
memory usage: 33.6+ KB
385
125990
After dropna size is:
51
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 2350 entries, ('GB07143675', 2019) to ('GB07262386', 2011)
Data columns (total 1 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Leasing_(short_t.)_th_GBP  2350 non-null   float64
dtypes: float64(1)
memory usage: 34.2+ KB
386
125990
After dropna size is:
1096
387
125990
After dropna size is:
3036
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 4132 entries, ('GB09196510', 2019) to ('GB07810580', 2018)
Data columns (total 1 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Other_Short_Term_Loans_th_GBP  4132 non-null   float64
dtypes: float64(1)
memory usage: 71.6+ KB
388
125990
After dropna size is:
3565
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 7697 entries, ('GB09196510', 2019) to ('GB08652508', 2017)
Data columns (total 1 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Other_Short_Term_Loans_th_GBP  7697 non-null   float64
dtypes: float64(1)
memory usage: 121.9+ KB
389
125990

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Leasing_(short_t.)_th_GBP'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

After dropna size is:
3106
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 10803 entries, ('GB09196510', 2019) to ('GB08094042', 2016)
Data columns (total 1 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Other_Short_Term_Loans_th_GBP  10803 non-null  float64
dtypes: float64(1)
memory usage: 166.1+ KB
390
125990
After dropna size is:
2497
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 13300 entries, ('GB09196510', 2019) to ('GB09025466', 2015)
Data columns (total 1 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Other_Short_Term_Loans_th_GBP  13300 non-null  float64
dtypes: float64(1)
memory usage: 200.4+ KB
391
125990
After dropna size is:
1981
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 15281 entries, ('GB09196510', 2019) to ('GB07937886', 2014)
Data columns (total 1 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Other_Short_Term_Loans_th_GBP  15281 non-null  float64
dtypes: float64(1)
memory usage: 227.5+ KB
392
125990
After dropna size is:
1548
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 16829 entries, ('GB09196510', 2019) to ('GB07810580', 2013)
Data columns (total 1 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Other_Short_Term_Loans_th_GBP  16829 non-null  float64
dtypes: float64(1)
memory usage: 248.6+ KB
393
125990
After dropna size is:
965
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 17794 entries, ('GB09196510', 2019) to ('GB07937886', 2012)
Data columns (total 1 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Other_Short_Term_Loans_th_GBP  17794 non-null  float64
dtypes: float64(1)
memory usage: 261.4+ KB
394
125990
After dropna size is:
519
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 18313 entries, ('GB09196510', 2019) to ('GB07258174', 2011)
Data columns (total 1 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Other_Short_Term_Loans_th_GBP  18313 non-null  float64
dtypes: float64(1)
memory usage: 268.6+ KB
395
125990
After dropna size is:
47745
396
125990
After dropna size is:
82284
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 130029 entries, ('GB07588867', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column                                  Non-Null Count   Dtype
---  ------                                  --------------   -----
 0   Total_Other_Current_Liabilities_th_GBP  130029 non-null  float64
dtypes: float64(1)
memory usage: 2.3+ MB
397
125990
After dropna size is:
88275
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 218304 entries, ('GB07588867', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column                                  Non-Null Count   Dtype
---  ------                                  --------------   -----
 0   Total_Other_Current_Liabilities_th_GBP  218304 non-null  float64
dtypes: float64(1)
memory usage: 3.4+ MB
398
125990
After dropna size is:
86429
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 304733 entries, ('GB07588867', 2019) to ('GBOC381395', 2016)
Data columns (total 1 columns):
 #   Column                                  Non-Null Count   Dtype
---  ------                                  --------------   -----
 0   Total_Other_Current_Liabilities_th_GBP  304733 non-null  float64
dtypes: float64(1)
memory usage: 4.6+ MB
399
125990
After dropna size is:
76431
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 381164 entries, ('GB07588867', 2019) to ('GBSC452461', 2015)
Data columns (total 1 columns):
 #   Column                                  Non-Null Count   Dtype
---  ------                                  --------------   -----
 0   Total_Other_Current_Liabilities_th_GBP  381164 non-null  float64
dtypes: float64(1)
memory usage: 5.6+ MB
400
125990
After dropna size is:
63712
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 444876 entries, ('GB07588867', 2019) to ('GBOC369696', 2014)
Data columns (total 1 columns):
 #   Column                                  Non-Null Count   Dtype
---  ------                                  --------------   -----
 0   Total_Other_Current_Liabilities_th_GBP  444876 non-null  float64
dtypes: float64(1)
memory usage: 6.4+ MB
401
125990
After dropna size is:
49176
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 494052 entries, ('GB07588867', 2019) to ('GBOC369696', 2013)
Data columns (total 1 columns):
 #   Column                                  Non-Null Count   Dtype
---  ------                                  --------------   -----
 0   Total_Other_Current_Liabilities_th_GBP  494052 non-null  float64
dtypes: float64(1)
memory usage: 7.0+ MB
402
125990
After dropna size is:
33189
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 527241 entries, ('GB07588867', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column                                  Non-Null Count   Dtype
---  ------                                  --------------   -----
 0   Total_Other_Current_Liabilities_th_GBP  527241 non-null  float64
dtypes: float64(1)
memory usage: 7.4+ MB
403
125990
After dropna size is:
16232
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 543473 entries, ('GB07588867', 2019) to ('GB07266603', 2011)
Data columns (total 1 columns):
 #   Column                                  Non-Null Count   Dtype
---  ------                                  --------------   -----
 0   Total_Other_Current_Liabilities_th_GBP  543473 non-null  float64
dtypes: float64(1)
memory usage: 7.6+ MB
404
125990
After dropna size is:
6153
405
125990
After dropna size is:
12175
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 18328 entries, ('GB09507385', 2019) to ('IE505067', 2018)
Data columns (total 1 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Corporation_Tax_th_GBP  18328 non-null  float64
dtypes: float64(1)
memory usage: 305.8+ KB
406
125990
After dropna size is:
14126
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 32454 entries, ('GB09507385', 2019) to ('IE505067', 2017)
Data columns (total 1 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Corporation_Tax_th_GBP  32454 non-null  float64
dtypes: float64(1)
memory usage: 500.4+ KB
407
125990
After dropna size is:
10930
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 43384 entries, ('GB09507385', 2019) to ('IE505067', 2016)
Data columns (total 1 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Corporation_Tax_th_GBP  43384 non-null  float64
dtypes: float64(1)
memory usage: 651.4+ KB
408
125990
After dropna size is:
8758
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 52142 entries, ('GB09507385', 2019) to ('IE505067', 2015)
Data columns (total 1 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Corporation_Tax_th_GBP  52142 non-null  float64
dtypes: float64(1)
memory usage: 768.2+ KB
409
125990
After dropna size is:
8332
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 60474 entries, ('GB09507385', 2019) to ('GB07361608', 2014)
Data columns (total 1 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Corporation_Tax_th_GBP  60474 non-null  float64
dtypes: float64(1)
memory usage: 879.3+ KB
410
125990
After dropna size is:
7871
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 68345 entries, ('GB09507385', 2019) to ('GB07266603', 2013)
Data columns (total 1 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Corporation_Tax_th_GBP  68345 non-null  float64
dtypes: float64(1)
memory usage: 985.1+ KB
411
125990
After dropna size is:
5882

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 74227 entries, ('GB09507385', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Corporation_Tax_th_GBP  74227 non-null  float64
dtypes: float64(1)
memory usage: 1.2+ MB
412
125990
After dropna size is:
3358
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 77585 entries, ('GB09507385', 2019) to ('GB07266603', 2011)
Data columns (total 1 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Corporation_Tax_th_GBP  77585 non-null  float64
dtypes: float64(1)
memory usage: 1.2+ MB
413
125990
After dropna size is:
40
414
125990
After dropna size is:
75
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 115 entries, ('GB10003922', 2019) to ('GB07714245', 2018)
Data columns (total 1 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Dividends_th_GBP  115 non-null    float64
dtypes: float64(1)
memory usage: 2.1+ KB
415
125990
After dropna size is:
67
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 182 entries, ('GB10003922', 2019) to ('GB07714245', 2017)
Data columns (total 1 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Dividends_th_GBP  182 non-null    float64
dtypes: float64(1)
memory usage: 3.3+ KB
416
125990
After dropna size is:
44
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 226 entries, ('GB10003922', 2019) to ('GB07714245', 2016)
Data columns (total 1 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Dividends_th_GBP  226 non-null    float64
dtypes: float64(1)
memory usage: 4.0+ KB
417
125990
After dropna size is:
46
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 272 entries, ('GB10003922', 2019) to ('GB08608455', 2015)
Data columns (total 1 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Dividends_th_GBP  272 non-null    float64
dtypes: float64(1)
memory usage: 4.7+ KB
418
125990
After dropna size is:
42
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 314 entries, ('GB10003922', 2019) to ('GB07124128', 2014)
Data columns (total 1 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Dividends_th_GBP  314 non-null    float64
dtypes: float64(1)
memory usage: 5.4+ KB
419
125990
After dropna size is:
28
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 342 entries, ('GB10003922', 2019) to ('GB07564202', 2013)
Data columns (total 1 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Dividends_th_GBP  342 non-null    float64
dtypes: float64(1)
memory usage: 5.8+ KB
420
125990
After dropna size is:
28
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 370 entries, ('GB10003922', 2019) to ('GB07593499', 2012)
Data columns (total 1 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Dividends_th_GBP  370 non-null    float64
dtypes: float64(1)
memory usage: 6.3+ KB
421
125990
After dropna size is:
24
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 394 entries, ('GB10003922', 2019) to ('GB07255748', 2011)
Data columns (total 1 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Dividends_th_GBP  394 non-null    float64
dtypes: float64(1)
memory usage: 6.7+ KB
422
125990
After dropna size is:
9885
423
125990
After dropna size is:
21084
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 30969 entries, ('GB09488271', 2019) to ('GBSC452461', 2018)
Data columns (total 1 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Accruals_&_Def._Inc._(short_t.)_th_GBP  30969 non-null  float64
dtypes: float64(1)
memory usage: 512.2+ KB
424
125990
After dropna size is:
21739
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 52708 entries, ('GB09488271', 2019) to ('GBSC452461', 2017)
Data columns (total 1 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Accruals_&_Def._Inc._(short_t.)_th_GBP  52708 non-null  float64
dtypes: float64(1)
memory usage: 780.3+ KB
425
125990
After dropna size is:
17574
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 70282 entries, ('GB09488271', 2019) to ('GBSC452461', 2016)
Data columns (total 1 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Accruals_&_Def._Inc._(short_t.)_th_GBP  70282 non-null  float64
dtypes: float64(1)
memory usage: 999.8+ KB
426
125990
After dropna size is:
14105
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 84387 entries, ('GB09488271', 2019) to ('GBSC452461', 2015)
Data columns (total 1 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Accruals_&_Def._Inc._(short_t.)_th_GBP  84387 non-null  float64
dtypes: float64(1)
memory usage: 1.3+ MB
427
125990
After dropna size is:
12075
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 96462 entries, ('GB09488271', 2019) to ('GB08389817', 2014)
Data columns (total 1 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Accruals_&_Def._Inc._(short_t.)_th_GBP  96462 non-null  float64
dtypes: float64(1)
memory usage: 1.5+ MB
428
125990
After dropna size is:
10048
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 106510 entries, ('GB09488271', 2019) to ('GBOC369696', 2013)
Data columns (total 1 columns):
 #   Column                                  Non-Null Count   Dtype
---  ------                                  --------------   -----
 0   Accruals_&_Def._Inc._(short_t.)_th_GBP  106510 non-null  float64
dtypes: float64(1)
memory usage: 1.6+ MB
429
125990
After dropna size is:
7427
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 113937 entries, ('GB09488271', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column                                  Non-Null Count   Dtype
---  ------                                  --------------   -----
 0   Accruals_&_Def._Inc._(short_t.)_th_GBP  113937 non-null  float64
dtypes: float64(1)
memory usage: 1.7+ MB
430
125990
After dropna size is:
3969
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 117906 entries, ('GB09488271', 2019) to ('GB07266603', 2011)
Data columns (total 1 columns):
 #   Column                                  Non-Null Count   Dtype
---  ------                                  --------------   -----
 0   Accruals_&_Def._Inc._(short_t.)_th_GBP  117906 non-null  float64
dtypes: float64(1)
memory usage: 1.8+ MB
431
125990
After dropna size is:
12603
432
125990
After dropna size is:
22234

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Accruals_&_Def._Inc._(short_t.)_th_GBP'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 34837 entries, ('GB07588867', 2019) to ('GB09102173', 2018)
Data columns (total 1 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Social_Securities_&_V.A.T._th_GBP  34837 non-null  float64
dtypes: float64(1)
memory usage: 567.7+ KB
433
125990
After dropna size is:
23406
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 58243 entries, ('GB07588867', 2019) to ('GB09153143', 2017)
Data columns (total 1 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Social_Securities_&_V.A.T._th_GBP  58243 non-null  float64
dtypes: float64(1)
memory usage: 868.8+ KB
434
125990
After dropna size is:
14654
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 72897 entries, ('GB07588867', 2019) to ('GB09102173', 2016)
Data columns (total 1 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Social_Securities_&_V.A.T._th_GBP  72897 non-null  float64
dtypes: float64(1)
memory usage: 1.2+ MB
435
125990
After dropna size is:
11991
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 84888 entries, ('GB07588867', 2019) to ('GB08389817', 2015)
Data columns (total 1 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Social_Securities_&_V.A.T._th_GBP  84888 non-null  float64
dtypes: float64(1)
memory usage: 1.4+ MB
436
125990
After dropna size is:
11611
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 96499 entries, ('GB07588867', 2019) to ('GBOC369696', 2014)
Data columns (total 1 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Social_Securities_&_V.A.T._th_GBP  96499 non-null  float64
dtypes: float64(1)
memory usage: 1.5+ MB
437
125990
After dropna size is:
10433
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 106932 entries, ('GB07588867', 2019) to ('GBOC369696', 2013)
Data columns (total 1 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   Social_Securities_&_V.A.T._th_GBP  106932 non-null  float64
dtypes: float64(1)
memory usage: 1.7+ MB
438
125990
After dropna size is:
7803
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 114735 entries, ('GB07588867', 2019) to ('GB07560895', 2012)
Data columns (total 1 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   Social_Securities_&_V.A.T._th_GBP  114735 non-null  float64
dtypes: float64(1)
memory usage: 1.8+ MB
439
125990
After dropna size is:
3786
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 118521 entries, ('GB07588867', 2019) to ('GB07361608', 2011)
Data columns (total 1 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   Social_Securities_&_V.A.T._th_GBP  118521 non-null  float64
dtypes: float64(1)
memory usage: 1.8+ MB
440
125990
After dropna size is:
40213
441
125990

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Social_Securities_&_V.A.T._th_GBP'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

After dropna size is:
67005
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 107218 entries, ('GB07588867', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   Other_Current_Liabilities_th_GBP  107218 non-null  float64
dtypes: float64(1)
memory usage: 1.9+ MB
442
125990
After dropna size is:
71480
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 178698 entries, ('GB07588867', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   Other_Current_Liabilities_th_GBP  178698 non-null  float64
dtypes: float64(1)
memory usage: 2.8+ MB
443
125990
After dropna size is:
73559
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 252257 entries, ('GB07588867', 2019) to ('GBOC381395', 2016)
Data columns (total 1 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   Other_Current_Liabilities_th_GBP  252257 non-null  float64
dtypes: float64(1)
memory usage: 3.8+ MB
444
125990
After dropna size is:
65147
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 317404 entries, ('GB07588867', 2019) to ('GBOC365296', 2015)
Data columns (total 1 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   Other_Current_Liabilities_th_GBP  317404 non-null  float64
dtypes: float64(1)
memory usage: 4.7+ MB
445
125990
After dropna size is:
53156
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 370560 entries, ('GB07588867', 2019) to ('GBOC365296', 2014)
Data columns (total 1 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   Other_Current_Liabilities_th_GBP  370560 non-null  float64
dtypes: float64(1)
memory usage: 5.4+ MB
446
125990
After dropna size is:
39635
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 410195 entries, ('GB07588867', 2019) to ('GBOC365296', 2013)
Data columns (total 1 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   Other_Current_Liabilities_th_GBP  410195 non-null  float64
dtypes: float64(1)
memory usage: 5.9+ MB
447
125990
After dropna size is:
26325
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 436520 entries, ('GB07588867', 2019) to ('GBOC365296', 2012)
Data columns (total 1 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   Other_Current_Liabilities_th_GBP  436520 non-null  float64
dtypes: float64(1)
memory usage: 6.2+ MB
448
125990
After dropna size is:
12464
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 448984 entries, ('GB07588867', 2019) to ('GB07404972', 2011)
Data columns (total 1 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   Other_Current_Liabilities_th_GBP  448984 non-null  float64
dtypes: float64(1)
memory usage: 6.4+ MB
449
125990
After dropna size is:
49482
450
125990
After dropna size is:
86151
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 135633 entries, ('GB07588867', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Current_Liabilities_th_GBP  135633 non-null  float64
dtypes: float64(1)
memory usage: 2.4+ MB
451
125990
After dropna size is:
92640
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 228273 entries, ('GB07588867', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Current_Liabilities_th_GBP  228273 non-null  float64
dtypes: float64(1)
memory usage: 3.6+ MB
452
125990
After dropna size is:
90387
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 318660 entries, ('GB07588867', 2019) to ('GBOC381395', 2016)
Data columns (total 1 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Current_Liabilities_th_GBP  318660 non-null  float64
dtypes: float64(1)
memory usage: 4.8+ MB
453
125990
After dropna size is:
79992
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 398652 entries, ('GB07588867', 2019) to ('GBSC452461', 2015)
Data columns (total 1 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Current_Liabilities_th_GBP  398652 non-null  float64
dtypes: float64(1)
memory usage: 5.8+ MB
454
125990
After dropna size is:
66920
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 465572 entries, ('GB07588867', 2019) to ('GBOC369696', 2014)
Data columns (total 1 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Current_Liabilities_th_GBP  465572 non-null  float64
dtypes: float64(1)
memory usage: 6.6+ MB
455
125990
After dropna size is:
51701
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 517273 entries, ('GB07588867', 2019) to ('GBOC369696', 2013)
Data columns (total 1 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Current_Liabilities_th_GBP  517273 non-null  float64
dtypes: float64(1)
memory usage: 7.3+ MB
456
125990
After dropna size is:
34934
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 552207 entries, ('GB07588867', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Current_Liabilities_th_GBP  552207 non-null  float64
dtypes: float64(1)
memory usage: 7.7+ MB
457
125990
After dropna size is:
17288
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 569495 entries, ('GB07588867', 2019) to ('GB07266603', 2011)
Data columns (total 1 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Current_Liabilities_th_GBP  569495 non-null  float64
dtypes: float64(1)
memory usage: 8.0+ MB
458
125990
After dropna size is:
58165
459
125990
After dropna size is:
99363
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 157528 entries, ('GB09567757', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column                                       Non-Null Count   Dtype
---  ------                                       --------------   -----
 0   Net_Current_Assets_(Working_Capital)_th_GBP  157528 non-null  float64
dtypes: float64(1)
memory usage: 2.7+ MB
460
125990
After dropna size is:
106841
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 264369 entries, ('GB09567757', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column                                       Non-Null Count   Dtype
---  ------                                       --------------   -----
 0   Net_Current_Assets_(Working_Capital)_th_GBP  264369 non-null  float64
dtypes: float64(1)
memory usage: 4.1+ MB
461
125990
After dropna size is:
104312
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 368681 entries, ('GB09567757', 2019) to ('GBOC381395', 2016)
Data columns (total 1 columns):
 #   Column                                       Non-Null Count   Dtype
---  ------                                       --------------   -----
 0   Net_Current_Assets_(Working_Capital)_th_GBP  368681 non-null  float64
dtypes: float64(1)
memory usage: 5.5+ MB
462
125990
After dropna size is:
92174
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 460855 entries, ('GB09567757', 2019) to ('GBOC381395', 2015)
Data columns (total 1 columns):
 #   Column                                       Non-Null Count   Dtype
---  ------                                       --------------   -----
 0   Net_Current_Assets_(Working_Capital)_th_GBP  460855 non-null  float64
dtypes: float64(1)
memory usage: 6.6+ MB
463
125990
After dropna size is:
77964

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 538819 entries, ('GB09567757', 2019) to ('GBOC381395', 2014)
Data columns (total 1 columns):
 #   Column                                       Non-Null Count   Dtype
---  ------                                       --------------   -----
 0   Net_Current_Assets_(Working_Capital)_th_GBP  538819 non-null  float64
dtypes: float64(1)
memory usage: 7.6+ MB
464
125990
After dropna size is:
60604
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 599423 entries, ('GB09567757', 2019) to ('GBSC452461', 2013)
Data columns (total 1 columns):
 #   Column                                       Non-Null Count   Dtype
---  ------                                       --------------   -----
 0   Net_Current_Assets_(Working_Capital)_th_GBP  599423 non-null  float64
dtypes: float64(1)
memory usage: 8.4+ MB
465
125990
After dropna size is:
41620
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 641043 entries, ('GB09567757', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column                                       Non-Null Count   Dtype
---  ------                                       --------------   -----
 0   Net_Current_Assets_(Working_Capital)_th_GBP  641043 non-null  float64
dtypes: float64(1)
memory usage: 8.9+ MB
466
125990
After dropna size is:
21148
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 662191 entries, ('GB09567757', 2019) to ('GB07266603', 2011)
Data columns (total 1 columns):
 #   Column                                       Non-Null Count   Dtype
---  ------                                       --------------   -----
 0   Net_Current_Assets_(Working_Capital)_th_GBP  662191 non-null  float64
dtypes: float64(1)
memory usage: 9.2+ MB
467
125990
After dropna size is:
17348

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Net_Current_Assets_(Working_Capital)_th_GBP'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

468
125990
After dropna size is:
34208
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 51556 entries, ('GB07588867', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Working_Capital_needs_th_GBP  51556 non-null  float64
dtypes: float64(1)
memory usage: 943.1+ KB
469
125990
After dropna size is:
37266
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 88822 entries, ('GB07588867', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Working_Capital_needs_th_GBP  88822 non-null  float64
dtypes: float64(1)
memory usage: 1.4+ MB
470
125990
After dropna size is:
34278
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 123100 entries, ('GB07588867', 2019) to ('GBOC381395', 2016)
Data columns (total 1 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Working_Capital_needs_th_GBP  123100 non-null  float64
dtypes: float64(1)
memory usage: 1.9+ MB
471
125990
After dropna size is:
30907
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 154007 entries, ('GB07588867', 2019) to ('GBSC452461', 2015)
Data columns (total 1 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Working_Capital_needs_th_GBP  154007 non-null  float64
dtypes: float64(1)
memory usage: 2.4+ MB
472
125990
After dropna size is:
27648
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 181655 entries, ('GB07588867', 2019) to ('GBOC369696', 2014)
Data columns (total 1 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Working_Capital_needs_th_GBP  181655 non-null  float64
dtypes: float64(1)
memory usage: 2.7+ MB
473
125990
After dropna size is:
23034
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 204689 entries, ('GB07588867', 2019) to ('GBOC369696', 2013)
Data columns (total 1 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Working_Capital_needs_th_GBP  204689 non-null  float64
dtypes: float64(1)
memory usage: 3.1+ MB
474
125990
After dropna size is:
16399
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 221088 entries, ('GB07588867', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Working_Capital_needs_th_GBP  221088 non-null  float64
dtypes: float64(1)
memory usage: 3.3+ MB
475
125990
After dropna size is:
8156
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 229244 entries, ('GB07588867', 2019) to ('GB07266603', 2011)
Data columns (total 1 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Working_Capital_needs_th_GBP  229244 non-null  float64
dtypes: float64(1)
memory usage: 3.4+ MB
476
125990
After dropna size is:
58908
477
125990
After dropna size is:
100403
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 159311 entries, ('GB09567757', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Total_Assets_th_GBP  159311 non-null  float64
dtypes: float64(1)
memory usage: 2.7+ MB
478
125990
After dropna size is:
107991
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 267302 entries, ('GB09567757', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Total_Assets_th_GBP  267302 non-null  float64
dtypes: float64(1)
memory usage: 4.2+ MB
479
125990
After dropna size is:
105458
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 372760 entries, ('GB09567757', 2019) to ('GBOC381395', 2016)
Data columns (total 1 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Total_Assets_th_GBP  372760 non-null  float64
dtypes: float64(1)
memory usage: 5.5+ MB
480
125990
After dropna size is:
93188
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 465948 entries, ('GB09567757', 2019) to ('GBOC381395', 2015)
Data columns (total 1 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Total_Assets_th_GBP  465948 non-null  float64
dtypes: float64(1)
memory usage: 6.7+ MB
481
125990
After dropna size is:
78311
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 544259 entries, ('GB09567757', 2019) to ('GBOC381395', 2014)
Data columns (total 1 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Total_Assets_th_GBP  544259 non-null  float64
dtypes: float64(1)
memory usage: 7.7+ MB
482
125990
After dropna size is:
60304
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 604563 entries, ('GB09567757', 2019) to ('GBSC452461', 2013)
Data columns (total 1 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Total_Assets_th_GBP  604563 non-null  float64
dtypes: float64(1)
memory usage: 8.4+ MB
483
125990
After dropna size is:
41358
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 645921 entries, ('GB09567757', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Total_Assets_th_GBP  645921 non-null  float64
dtypes: float64(1)
memory usage: 9.0+ MB
484
125990
After dropna size is:
20980
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 666901 entries, ('GB09567757', 2019) to ('GB07266603', 2011)
Data columns (total 1 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Total_Assets_th_GBP  666901 non-null  float64
dtypes: float64(1)
memory usage: 9.2+ MB
485
125990
After dropna size is:
59862
486
125990
After dropna size is:
101918
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 161780 entries, ('GB09567757', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column                               Non-Null Count   Dtype
---  ------                               --------------   -----
 0   Total_Assets_less_Cur._Liab._th_GBP  161780 non-null  float64
dtypes: float64(1)
memory usage: 2.8+ MB
487
125990
After dropna size is:
109452
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 271232 entries, ('GB09567757', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column                               Non-Null Count   Dtype
---  ------                               --------------   -----
 0   Total_Assets_less_Cur._Liab._th_GBP  271232 non-null  float64
dtypes: float64(1)
memory usage: 4.2+ MB
488
125990
After dropna size is:
106772
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 378004 entries, ('GB09567757', 2019) to ('GBOC381395', 2016)
Data columns (total 1 columns):
 #   Column                               Non-Null Count   Dtype
---  ------                               --------------   -----
 0   Total_Assets_less_Cur._Liab._th_GBP  378004 non-null  float64
dtypes: float64(1)
memory usage: 5.6+ MB
489
125990
After dropna size is:
94294
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 472298 entries, ('GB09567757', 2019) to ('GBOC381395', 2015)
Data columns (total 1 columns):
 #   Column                               Non-Null Count   Dtype
---  ------                               --------------   -----
 0   Total_Assets_less_Cur._Liab._th_GBP  472298 non-null  float64
dtypes: float64(1)
memory usage: 6.8+ MB
490
125990
After dropna size is:
79172
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 551470 entries, ('GB09567757', 2019) to ('GBOC381395', 2014)
Data columns (total 1 columns):
 #   Column                               Non-Null Count   Dtype
---  ------                               --------------   -----
 0   Total_Assets_less_Cur._Liab._th_GBP  551470 non-null  float64
dtypes: float64(1)
memory usage: 7.8+ MB
491
125990
After dropna size is:
60937

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 612407 entries, ('GB09567757', 2019) to ('GBSC452461', 2013)
Data columns (total 1 columns):
 #   Column                               Non-Null Count   Dtype
---  ------                               --------------   -----
 0   Total_Assets_less_Cur._Liab._th_GBP  612407 non-null  float64
dtypes: float64(1)
memory usage: 8.5+ MB
492
125990
After dropna size is:
41754
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 654161 entries, ('GB09567757', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column                               Non-Null Count   Dtype
---  ------                               --------------   -----
 0   Total_Assets_less_Cur._Liab._th_GBP  654161 non-null  float64
dtypes: float64(1)
memory usage: 9.1+ MB
493
125990
After dropna size is:
21206
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 675367 entries, ('GB09567757', 2019) to ('GB07266603', 2011)
Data columns (total 1 columns):
 #   Column                               Non-Null Count   Dtype
---  ------                               --------------   -----
 0   Total_Assets_less_Cur._Liab._th_GBP  675367 non-null  float64
dtypes: float64(1)
memory usage: 9.3+ MB
494
125990
After dropna size is:
5503

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Total_Assets_less_Cur._Liab._th_GBP'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

495
125990
After dropna size is:
10392
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 15895 entries, ('GBOC361927', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Long_Term_Debt_th_GBP  15895 non-null  float64
dtypes: float64(1)
memory usage: 261.2+ KB
496
125990
After dropna size is:
11132
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 27027 entries, ('GBOC361927', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Long_Term_Debt_th_GBP  27027 non-null  float64
dtypes: float64(1)
memory usage: 402.2+ KB
497
125990
After dropna size is:
9961
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 36988 entries, ('GBOC361927', 2019) to ('GBOC365296', 2016)
Data columns (total 1 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Long_Term_Debt_th_GBP  36988 non-null  float64
dtypes: float64(1)
memory usage: 527.5+ KB
498
125990
After dropna size is:
8568
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 45556 entries, ('GBOC361927', 2019) to ('GBOC381395', 2015)
Data columns (total 1 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Long_Term_Debt_th_GBP  45556 non-null  float64
dtypes: float64(1)
memory usage: 635.1+ KB
499
125990
After dropna size is:
7376
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 52932 entries, ('GBOC361927', 2019) to ('GBOC381395', 2014)
Data columns (total 1 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Long_Term_Debt_th_GBP  52932 non-null  float64
dtypes: float64(1)
memory usage: 725.8+ KB
500
125990
After dropna size is:
5910
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 58842 entries, ('GBOC361927', 2019) to ('GBOC365296', 2013)
Data columns (total 1 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Long_Term_Debt_th_GBP  58842 non-null  float64
dtypes: float64(1)
memory usage: 798.6+ KB
501
125990
After dropna size is:
4184
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 63026 entries, ('GBOC361927', 2019) to ('GBOC365296', 2012)
Data columns (total 1 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Long_Term_Debt_th_GBP  63026 non-null  float64
dtypes: float64(1)
memory usage: 849.7+ KB
502
125990
After dropna size is:
2050
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 65076 entries, ('GBOC361927', 2019) to ('GB07380791', 2011)
Data columns (total 1 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Long_Term_Debt_th_GBP  65076 non-null  float64
dtypes: float64(1)
memory usage: 874.7+ KB
503
125990
After dropna size is:
1128
504
125990
After dropna size is:
2699
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 3827 entries, ('GB08443946', 2019) to ('GB09778007', 2018)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Group_Loans_(long_t.)_th_GBP  3827 non-null   float64
dtypes: float64(1)
memory usage: 64.6+ KB
505
125990
After dropna size is:
2909
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 6736 entries, ('GB08443946', 2019) to ('GB09783953', 2017)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Group_Loans_(long_t.)_th_GBP  6736 non-null   float64
dtypes: float64(1)
memory usage: 102.2+ KB
506
125990
After dropna size is:
2663
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 9399 entries, ('GB08443946', 2019) to ('GBOC365296', 2016)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Group_Loans_(long_t.)_th_GBP  9399 non-null   float64
dtypes: float64(1)
memory usage: 135.8+ KB
507
125990
After dropna size is:
2168
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 11567 entries, ('GB08443946', 2019) to ('GBOC381395', 2015)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Group_Loans_(long_t.)_th_GBP  11567 non-null  float64
dtypes: float64(1)
memory usage: 163.7+ KB
508
125990
After dropna size is:
1821
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 13388 entries, ('GB08443946', 2019) to ('GBOC381395', 2014)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Group_Loans_(long_t.)_th_GBP  13388 non-null  float64
dtypes: float64(1)
memory usage: 186.5+ KB
509
125990
After dropna size is:
1357
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 14745 entries, ('GB08443946', 2019) to ('GB07911132', 2013)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Group_Loans_(long_t.)_th_GBP  14745 non-null  float64
dtypes: float64(1)
memory usage: 203.4+ KB
510
125990
After dropna size is:
938
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 15683 entries, ('GB08443946', 2019) to ('GB07380791', 2012)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Group_Loans_(long_t.)_th_GBP  15683 non-null  float64
dtypes: float64(1)
memory usage: 215.0+ KB
511
125990
After dropna size is:
465
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 16148 entries, ('GB08443946', 2019) to ('GB07380791', 2011)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Group_Loans_(long_t.)_th_GBP  16148 non-null  float64
dtypes: float64(1)
memory usage: 220.6+ KB
512
125990
After dropna size is:
1977
513
125990
After dropna size is:
3012
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 4989 entries, ('GBOC361927', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Director_Loans_(long_t.)_th_GBP  4989 non-null   float64
dtypes: float64(1)
memory usage: 80.2+ KB
514
125990
After dropna size is:
3317
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 8306 entries, ('GBOC361927', 2019) to ('GBOC381918', 2017)
Data columns (total 1 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Director_Loans_(long_t.)_th_GBP  8306 non-null   float64
dtypes: float64(1)
memory usage: 122.4+ KB
515
125990
After dropna size is:
3425
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 11731 entries, ('GBOC361927', 2019) to ('GBOC381918', 2016)
Data columns (total 1 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Director_Loans_(long_t.)_th_GBP  11731 non-null  float64
dtypes: float64(1)
memory usage: 166.4+ KB
516
125990
After dropna size is:
3337
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 15068 entries, ('GBOC361927', 2019) to ('GBOC381918', 2015)
Data columns (total 1 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Director_Loans_(long_t.)_th_GBP  15068 non-null  float64
dtypes: float64(1)
memory usage: 208.6+ KB
517
125990
After dropna size is:
2935

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Group_Loans_(long_t.)_th_GBP'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 18003 entries, ('GBOC361927', 2019) to ('GBOC365296', 2014)
Data columns (total 1 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Director_Loans_(long_t.)_th_GBP  18003 non-null  float64
dtypes: float64(1)
memory usage: 244.6+ KB
518
125990
After dropna size is:
2494
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 20497 entries, ('GBOC361927', 2019) to ('GBOC365296', 2013)
Data columns (total 1 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Director_Loans_(long_t.)_th_GBP  20497 non-null  float64
dtypes: float64(1)
memory usage: 275.5+ KB
519
125990
After dropna size is:
1816
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 22313 entries, ('GBOC361927', 2019) to ('GBOC365296', 2012)
Data columns (total 1 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Director_Loans_(long_t.)_th_GBP  22313 non-null  float64
dtypes: float64(1)
memory usage: 297.9+ KB
520
125990
After dropna size is:
909
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 23222 entries, ('GBOC361927', 2019) to ('GBOC358257', 2011)
Data columns (total 1 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Director_Loans_(long_t.)_th_GBP  23222 non-null  float64
dtypes: float64(1)
memory usage: 309.2+ KB
521
125990
After dropna size is:
896
522
125990
After dropna size is:
1529
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 2425 entries, ('GB08460300', 2019) to ('GB09783953', 2018)
Data columns (total 1 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Hire_Purch._&_Leas._(long_t.)_th_GBP  2425 non-null   float64
dtypes: float64(1)
memory usage: 40.7+ KB
523
125990
After dropna size is:
1558
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 3983 entries, ('GB08460300', 2019) to ('GBOC399383', 2017)
Data columns (total 1 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Hire_Purch._&_Leas._(long_t.)_th_GBP  3983 non-null   float64
dtypes: float64(1)
memory usage: 61.6+ KB
524
125990
After dropna size is:
1058
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 5041 entries, ('GB08460300', 2019) to ('GB09783953', 2016)
Data columns (total 1 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Hire_Purch._&_Leas._(long_t.)_th_GBP  5041 non-null   float64
dtypes: float64(1)
memory usage: 76.0+ KB
525
125990

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Director_Loans_(long_t.)_th_GBP'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

After dropna size is:
844
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 5885 entries, ('GB08460300', 2019) to ('GB08051155', 2015)
Data columns (total 1 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Hire_Purch._&_Leas._(long_t.)_th_GBP  5885 non-null   float64
dtypes: float64(1)
memory usage: 87.5+ KB
526
125990
After dropna size is:
712
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 6597 entries, ('GB08460300', 2019) to ('GB07868880', 2014)
Data columns (total 1 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Hire_Purch._&_Leas._(long_t.)_th_GBP  6597 non-null   float64
dtypes: float64(1)
memory usage: 97.1+ KB
527
125990
After dropna size is:
557
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 7154 entries, ('GB08460300', 2019) to ('GB07868880', 2013)
Data columns (total 1 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Hire_Purch._&_Leas._(long_t.)_th_GBP  7154 non-null   float64
dtypes: float64(1)
memory usage: 104.6+ KB
528
125990
After dropna size is:
370
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 7524 entries, ('GB08460300', 2019) to ('GB07119771', 2012)
Data columns (total 1 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Hire_Purch._&_Leas._(long_t.)_th_GBP  7524 non-null   float64
dtypes: float64(1)
memory usage: 109.8+ KB
529
125990
After dropna size is:
159
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 7683 entries, ('GB08460300', 2019) to ('GB07262386', 2011)
Data columns (total 1 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Hire_Purch._&_Leas._(long_t.)_th_GBP  7683 non-null   float64
dtypes: float64(1)
memory usage: 111.8+ KB
530
125990
After dropna size is:
360
531
125990
After dropna size is:
598
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 958 entries, ('GB08460650', 2019) to ('GB09032302', 2018)
Data columns (total 1 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Hire_Purchase_(long_t.)_th_GBP  958 non-null    float64
dtypes: float64(1)
memory usage: 16.4+ KB
532
125990
After dropna size is:
581
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1539 entries, ('GB08460650', 2019) to ('GB07172183', 2017)
Data columns (total 1 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Hire_Purchase_(long_t.)_th_GBP  1539 non-null   float64
dtypes: float64(1)
memory usage: 24.5+ KB
533
125990
After dropna size is:
340
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1879 entries, ('GB08460650', 2019) to ('GB07245285', 2016)
Data columns (total 1 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Hire_Purchase_(long_t.)_th_GBP  1879 non-null   float64
dtypes: float64(1)
memory usage: 29.4+ KB
534
125990
After dropna size is:
273

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Hire_Purch._&_Leas._(long_t.)_th_GBP'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)
/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Hire_Purchase_(long_t.)_th_GBP'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 2152 entries, ('GB08460650', 2019) to ('GB07172183', 2015)
Data columns (total 1 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Hire_Purchase_(long_t.)_th_GBP  2152 non-null   float64
dtypes: float64(1)
memory usage: 33.2+ KB
535
125990
After dropna size is:
255
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 2407 entries, ('GB08460650', 2019) to ('GB07868880', 2014)
Data columns (total 1 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Hire_Purchase_(long_t.)_th_GBP  2407 non-null   float64
dtypes: float64(1)
memory usage: 37.0+ KB
536
125990
After dropna size is:
193
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 2600 entries, ('GB08460650', 2019) to ('GB07868880', 2013)
Data columns (total 1 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Hire_Purchase_(long_t.)_th_GBP  2600 non-null   float64
dtypes: float64(1)
memory usage: 39.8+ KB
537
125990
After dropna size is:
131
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 2731 entries, ('GB08460650', 2019) to ('GB07170198', 2012)
Data columns (total 1 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Hire_Purchase_(long_t.)_th_GBP  2731 non-null   float64
dtypes: float64(1)
memory usage: 41.8+ KB
538
125990
After dropna size is:
68
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 2799 entries, ('GB08460650', 2019) to ('GB07170198', 2011)
Data columns (total 1 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Hire_Purchase_(long_t.)_th_GBP  2799 non-null   float64
dtypes: float64(1)
memory usage: 42.8+ KB
539
125990
After dropna size is:
182
540
125990
After dropna size is:
366
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 548 entries, ('GB07152503', 2019) to ('GB07251871', 2018)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Leasing_(long_t.)_th_GBP  548 non-null    float64
dtypes: float64(1)
memory usage: 9.6+ KB
541
125990
After dropna size is:
405
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 953 entries, ('GB07152503', 2019) to ('GB08014200', 2017)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Leasing_(long_t.)_th_GBP  953 non-null    float64
dtypes: float64(1)
memory usage: 15.3+ KB
542
125990
After dropna size is:
329
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1282 entries, ('GB07152503', 2019) to ('GB09199616', 2016)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Leasing_(long_t.)_th_GBP  1282 non-null   float64
dtypes: float64(1)
memory usage: 20.0+ KB
543
125990
After dropna size is:
230
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1512 entries, ('GB07152503', 2019) to ('GB07253667', 2015)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Leasing_(long_t.)_th_GBP  1512 non-null   float64
dtypes: float64(1)
memory usage: 23.2+ KB
544
125990
After dropna size is:
145
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1657 entries, ('GB07152503', 2019) to ('GB07253667', 2014)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Leasing_(long_t.)_th_GBP  1657 non-null   float64
dtypes: float64(1)
memory usage: 25.1+ KB
545
125990
After dropna size is:
104
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1761 entries, ('GB07152503', 2019) to ('IE523992', 2013)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Leasing_(long_t.)_th_GBP  1761 non-null   float64
dtypes: float64(1)
memory usage: 26.6+ KB
546
125990
After dropna size is:
66
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1827 entries, ('GB07152503', 2019) to ('GB07173866', 2012)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Leasing_(long_t.)_th_GBP  1827 non-null   float64
dtypes: float64(1)
memory usage: 27.5+ KB
547
125990
After dropna size is:
35
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1862 entries, ('GB07152503', 2019) to ('GB07569777', 2011)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Leasing_(long_t.)_th_GBP  1862 non-null   float64
dtypes: float64(1)
memory usage: 27.9+ KB
548
125990
After dropna size is:
21
549
125990
After dropna size is:
49
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 70 entries, ('GB08863657', 2019) to ('GB07248898', 2018)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Preference_Shares_th_GBP  70 non-null     float64
dtypes: float64(1)
memory usage: 1.3+ KB
550
125990
After dropna size is:
65
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 135 entries, ('GB08863657', 2019) to ('GB07162508', 2017)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Preference_Shares_th_GBP  135 non-null    float64
dtypes: float64(1)
memory usage: 2.2+ KB
551
125990
After dropna size is:
56
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 191 entries, ('GB08863657', 2019) to ('GB07912813', 2016)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Preference_Shares_th_GBP  191 non-null    float64
dtypes: float64(1)
memory usage: 2.9+ KB
552
125990
After dropna size is:
58
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 249 entries, ('GB08863657', 2019) to ('GB08835632', 2015)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Preference_Shares_th_GBP  249 non-null    float64
dtypes: float64(1)
memory usage: 3.9+ KB
553
125990
After dropna size is:
56
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 305 entries, ('GB08863657', 2019) to ('GB07248898', 2014)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Preference_Shares_th_GBP  305 non-null    float64
dtypes: float64(1)
memory usage: 4.7+ KB
554
125990
After dropna size is:
34
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 339 entries, ('GB08863657', 2019) to ('GB07248898', 2013)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Preference_Shares_th_GBP  339 non-null    float64
dtypes: float64(1)
memory usage: 5.1+ KB
555
125990
After dropna size is:
30
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 369 entries, ('GB08863657', 2019) to ('GB07912813', 2012)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Preference_Shares_th_GBP  369 non-null    float64
dtypes: float64(1)
memory usage: 5.5+ KB
556
125990
After dropna size is:
16
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 385 entries, ('GB08863657', 2019) to ('GBSC389324', 2011)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Preference_Shares_th_GBP  385 non-null    float64
dtypes: float64(1)
memory usage: 5.7+ KB
557
125990
After dropna size is:
2504
558
125990
After dropna size is:
4777

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Leasing_(long_t.)_th_GBP'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 7281 entries, ('GB08287986', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Other_Long_Term_Loans_th_GBP  7281 non-null   float64
dtypes: float64(1)
memory usage: 121.5+ KB
559
125990
After dropna size is:
5002
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 12283 entries, ('GB08287986', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Other_Long_Term_Loans_th_GBP  12283 non-null  float64
dtypes: float64(1)
memory usage: 186.6+ KB
560
125990
After dropna size is:
4212
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 16495 entries, ('GB08287986', 2019) to ('GB07993043', 2016)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Other_Long_Term_Loans_th_GBP  16495 non-null  float64
dtypes: float64(1)
memory usage: 241.7+ KB
561
125990
After dropna size is:
3378
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 19873 entries, ('GB08287986', 2019) to ('GB08058491', 2015)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Other_Long_Term_Loans_th_GBP  19873 non-null  float64
dtypes: float64(1)
memory usage: 285.8+ KB
562
125990
After dropna size is:
2795
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 22668 entries, ('GB08287986', 2019) to ('GB08264364', 2014)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Other_Long_Term_Loans_th_GBP  22668 non-null  float64
dtypes: float64(1)
memory usage: 321.9+ KB
563
125990
After dropna size is:
2129
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 24797 entries, ('GB08287986', 2019) to ('GB07911132', 2013)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Other_Long_Term_Loans_th_GBP  24797 non-null  float64
dtypes: float64(1)
memory usage: 349.5+ KB
564
125990
After dropna size is:
1522
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 26319 entries, ('GB08287986', 2019) to ('IE493534', 2012)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Other_Long_Term_Loans_th_GBP  26319 non-null  float64
dtypes: float64(1)
memory usage: 368.8+ KB
565
125990
After dropna size is:
736
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 27055 entries, ('GB08287986', 2019) to ('IE493534', 2011)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Other_Long_Term_Loans_th_GBP  27055 non-null  float64
dtypes: float64(1)
memory usage: 378.1+ KB
566
125990
After dropna size is:
12123
567
125990
After dropna size is:
20276
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 32399 entries, ('GB09567757', 2019) to ('GB07560895', 2018)
Data columns (total 1 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Total_Other_Long_Term_Liab._th_GBP  32399 non-null  float64
dtypes: float64(1)
memory usage: 531.6+ KB
568
125990
After dropna size is:
21116
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 53515 entries, ('GB09567757', 2019) to ('GB08582762', 2017)
Data columns (total 1 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Total_Other_Long_Term_Liab._th_GBP  53515 non-null  float64
dtypes: float64(1)
memory usage: 806.3+ KB
569
125990
After dropna size is:
17882
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 71397 entries, ('GB09567757', 2019) to ('GB08582762', 2016)
Data columns (total 1 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Total_Other_Long_Term_Liab._th_GBP  71397 non-null  float64
dtypes: float64(1)
memory usage: 1.2+ MB
570
125990
After dropna size is:
14817
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 86214 entries, ('GB09567757', 2019) to ('GB07816198', 2015)
Data columns (total 1 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Total_Other_Long_Term_Liab._th_GBP  86214 non-null  float64
dtypes: float64(1)
memory usage: 1.4+ MB
571
125990
After dropna size is:
11731
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 97945 entries, ('GB09567757', 2019) to ('GB07816198', 2014)
Data columns (total 1 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Total_Other_Long_Term_Liab._th_GBP  97945 non-null  float64
dtypes: float64(1)
memory usage: 1.5+ MB
572
125990
After dropna size is:
8156
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 106101 entries, ('GB09567757', 2019) to ('GBNI606607', 2013)
Data columns (total 1 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   Total_Other_Long_Term_Liab._th_GBP  106101 non-null  float64
dtypes: float64(1)
memory usage: 1.6+ MB
573
125990
After dropna size is:
5058
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 111159 entries, ('GB09567757', 2019) to ('GBNI606607', 2012)
Data columns (total 1 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   Total_Other_Long_Term_Liab._th_GBP  111159 non-null  float64
dtypes: float64(1)
memory usage: 1.7+ MB
574
125990
After dropna size is:
2209
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 113368 entries, ('GB09567757', 2019) to ('GB07149148', 2011)
Data columns (total 1 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   Total_Other_Long_Term_Liab._th_GBP  113368 non-null  float64
dtypes: float64(1)
memory usage: 1.7+ MB
575
125990
After dropna size is:
4979
576
125990
After dropna size is:
8076
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 13055 entries, ('GB09567757', 2019) to ('GB07560895', 2018)
Data columns (total 1 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Accruals_&_Def._Inc._(long_t.)_th_GBP  13055 non-null  float64
dtypes: float64(1)
memory usage: 214.8+ KB
577
125990
After dropna size is:
8002

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Total_Other_Long_Term_Liab._th_GBP'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 21057 entries, ('GB09567757', 2019) to ('GB07560895', 2017)
Data columns (total 1 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Accruals_&_Def._Inc._(long_t.)_th_GBP  21057 non-null  float64
dtypes: float64(1)
memory usage: 321.8+ KB
578
125990
After dropna size is:
3625
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 24682 entries, ('GB09567757', 2019) to ('GB07560895', 2016)
Data columns (total 1 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Accruals_&_Def._Inc._(long_t.)_th_GBP  24682 non-null  float64
dtypes: float64(1)
memory usage: 371.2+ KB
579
125990
After dropna size is:
1931
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 26613 entries, ('GB09567757', 2019) to ('GB08323008', 2015)
Data columns (total 1 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Accruals_&_Def._Inc._(long_t.)_th_GBP  26613 non-null  float64
dtypes: float64(1)
memory usage: 398.1+ KB
580
125990
After dropna size is:
1128
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 27741 entries, ('GB09567757', 2019) to ('GB07560895', 2014)
Data columns (total 1 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Accruals_&_Def._Inc._(long_t.)_th_GBP  27741 non-null  float64
dtypes: float64(1)
memory usage: 413.2+ KB
581
125990
After dropna size is:
712
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 28453 entries, ('GB09567757', 2019) to ('GB07993043', 2013)
Data columns (total 1 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Accruals_&_Def._Inc._(long_t.)_th_GBP  28453 non-null  float64
dtypes: float64(1)
memory usage: 423.0+ KB
582
125990
After dropna size is:
436
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 28889 entries, ('GB09567757', 2019) to ('GB07662418', 2012)
Data columns (total 1 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Accruals_&_Def._Inc._(long_t.)_th_GBP  28889 non-null  float64
dtypes: float64(1)
memory usage: 429.0+ KB
583
125990
After dropna size is:
211
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 29100 entries, ('GB09567757', 2019) to ('GBNI602079', 2011)
Data columns (total 1 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Accruals_&_Def._Inc._(long_t.)_th_GBP  29100 non-null  float64
dtypes: float64(1)
memory usage: 431.9+ KB
584
125990
After dropna size is:
8017
585
125990
After dropna size is:
13778

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Accruals_&_Def._Inc._(long_t.)_th_GBP'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 21795 entries, ('GB09567757', 2019) to ('GBNI606607', 2018)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Other_Long_Term_Liab._th_GBP  21795 non-null  float64
dtypes: float64(1)
memory usage: 359.9+ KB
586
125990
After dropna size is:
14602
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 36397 entries, ('GB09567757', 2019) to ('GB08582762', 2017)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Other_Long_Term_Liab._th_GBP  36397 non-null  float64
dtypes: float64(1)
memory usage: 551.9+ KB
587
125990
After dropna size is:
15023
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 51420 entries, ('GB09567757', 2019) to ('GB08582762', 2016)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Other_Long_Term_Liab._th_GBP  51420 non-null  float64
dtypes: float64(1)
memory usage: 750.7+ KB
588
125990
After dropna size is:
13483
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 64903 entries, ('GB09567757', 2019) to ('GB07816198', 2015)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Other_Long_Term_Liab._th_GBP  64903 non-null  float64
dtypes: float64(1)
memory usage: 925.2+ KB
589
125990
After dropna size is:
10912
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 75815 entries, ('GB09567757', 2019) to ('GB07816198', 2014)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Other_Long_Term_Liab._th_GBP  75815 non-null  float64
dtypes: float64(1)
memory usage: 1.0+ MB
590
125990
After dropna size is:
7662
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 83477 entries, ('GB09567757', 2019) to ('GBNI606607', 2013)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Other_Long_Term_Liab._th_GBP  83477 non-null  float64
dtypes: float64(1)
memory usage: 1.3+ MB
591
125990
After dropna size is:
4730
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 88207 entries, ('GB09567757', 2019) to ('GBNI606607', 2012)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Other_Long_Term_Liab._th_GBP  88207 non-null  float64
dtypes: float64(1)
memory usage: 1.4+ MB
592
125990
After dropna size is:
2052
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 90259 entries, ('GB09567757', 2019) to ('GB07149148', 2011)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Other_Long_Term_Liab._th_GBP  90259 non-null  float64
dtypes: float64(1)
memory usage: 1.4+ MB
593
125990
After dropna size is:
4618

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Other_Long_Term_Liab._th_GBP'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

594
125990
After dropna size is:
8357
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 12975 entries, ('GB09639538', 2019) to ('GB08582762', 2018)
Data columns (total 1 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Provisions_for_Other_Liab._th_GBP  12975 non-null  float64
dtypes: float64(1)
memory usage: 212.9+ KB
595
125990
After dropna size is:
8269
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 21244 entries, ('GB09639538', 2019) to ('GB07782390', 2017)
Data columns (total 1 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Provisions_for_Other_Liab._th_GBP  21244 non-null  float64
dtypes: float64(1)
memory usage: 318.4+ KB
596
125990
After dropna size is:
8087
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 29331 entries, ('GB09639538', 2019) to ('GB07782390', 2016)
Data columns (total 1 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Provisions_for_Other_Liab._th_GBP  29331 non-null  float64
dtypes: float64(1)
memory usage: 424.1+ KB
597
125990
After dropna size is:
6839
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 36170 entries, ('GB09639538', 2019) to ('GB07782390', 2015)
Data columns (total 1 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Provisions_for_Other_Liab._th_GBP  36170 non-null  float64
dtypes: float64(1)
memory usage: 510.7+ KB
598
125990
After dropna size is:
5179
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 41349 entries, ('GB09639538', 2019) to ('GB07782390', 2014)
Data columns (total 1 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Provisions_for_Other_Liab._th_GBP  41349 non-null  float64
dtypes: float64(1)
memory usage: 573.5+ KB
599
125990
After dropna size is:
3635
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 44984 entries, ('GB09639538', 2019) to ('GB07782390', 2013)
Data columns (total 1 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Provisions_for_Other_Liab._th_GBP  44984 non-null  float64
dtypes: float64(1)
memory usage: 617.5+ KB
600
125990
After dropna size is:
2279
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 47263 entries, ('GB09639538', 2019) to ('GB07782390', 2012)
Data columns (total 1 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Provisions_for_Other_Liab._th_GBP  47263 non-null  float64
dtypes: float64(1)
memory usage: 644.8+ KB
601
125990
After dropna size is:
1020
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 48283 entries, ('GB09639538', 2019) to ('GB07470677', 2011)
Data columns (total 1 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Provisions_for_Other_Liab._th_GBP  48283 non-null  float64
dtypes: float64(1)
memory usage: 656.9+ KB
602
125990
After dropna size is:
1467
603
125990
After dropna size is:
3123
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 4590 entries, ('GB08440440', 2019) to ('GB08368531', 2018)
Data columns (total 1 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Deferred_Tax_th_GBP  4590 non-null   float64
dtypes: float64(1)
memory usage: 77.0+ KB
604
125990
After dropna size is:
3001
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 7591 entries, ('GB08440440', 2019) to ('GB08368531', 2017)
Data columns (total 1 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Deferred_Tax_th_GBP  7591 non-null   float64
dtypes: float64(1)
memory usage: 116.1+ KB
605
125990
After dropna size is:
2760

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Provisions_for_Other_Liab._th_GBP'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 10351 entries, ('GB08440440', 2019) to ('GB09114893', 2016)
Data columns (total 1 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Deferred_Tax_th_GBP  10351 non-null  float64
dtypes: float64(1)
memory usage: 153.9+ KB
606
125990
After dropna size is:
2142
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 12493 entries, ('GB08440440', 2019) to ('GB09114893', 2015)
Data columns (total 1 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Deferred_Tax_th_GBP  12493 non-null  float64
dtypes: float64(1)
memory usage: 182.2+ KB
607
125990
After dropna size is:
1630
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 14123 entries, ('GB08440440', 2019) to ('GB07258174', 2014)
Data columns (total 1 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Deferred_Tax_th_GBP  14123 non-null  float64
dtypes: float64(1)
memory usage: 203.5+ KB
608
125990
After dropna size is:
1217
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 15340 entries, ('GB08440440', 2019) to ('GB07258174', 2013)
Data columns (total 1 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Deferred_Tax_th_GBP  15340 non-null  float64
dtypes: float64(1)
memory usage: 219.9+ KB
609
125990
After dropna size is:
857
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 16197 entries, ('GB08440440', 2019) to ('GB07341487', 2012)
Data columns (total 1 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Deferred_Tax_th_GBP  16197 non-null  float64
dtypes: float64(1)
memory usage: 231.3+ KB
610
125990
After dropna size is:
437
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 16634 entries, ('GB08440440', 2019) to ('GB07341487', 2011)
Data columns (total 1 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Deferred_Tax_th_GBP  16634 non-null  float64
dtypes: float64(1)
memory usage: 237.0+ KB
611
125990
After dropna size is:
3267
612
125990
After dropna size is:
5498
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 8765 entries, ('GB09639538', 2019) to ('GB08582762', 2018)
Data columns (total 1 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Other_Provisions_th_GBP  8765 non-null   float64
dtypes: float64(1)
memory usage: 144.3+ KB
613
125990
After dropna size is:
5482
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 14247 entries, ('GB09639538', 2019) to ('GB07782390', 2017)
Data columns (total 1 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Other_Provisions_th_GBP  14247 non-null  float64
dtypes: float64(1)
memory usage: 217.5+ KB
614
125990
After dropna size is:
5494
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 19741 entries, ('GB09639538', 2019) to ('GB07782390', 2016)
Data columns (total 1 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Other_Provisions_th_GBP  19741 non-null  float64
dtypes: float64(1)
memory usage: 293.4+ KB
615
125990
After dropna size is:
4815
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 24556 entries, ('GB09639538', 2019) to ('GB07782390', 2015)
Data columns (total 1 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Other_Provisions_th_GBP  24556 non-null  float64
dtypes: float64(1)
memory usage: 357.3+ KB
616
125990
After dropna size is:
3610
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 28166 entries, ('GB09639538', 2019) to ('GB07782390', 2014)
Data columns (total 1 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Other_Provisions_th_GBP  28166 non-null  float64
dtypes: float64(1)
memory usage: 402.3+ KB
617
125990
After dropna size is:
2448
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 30614 entries, ('GB09639538', 2019) to ('GB07782390', 2013)
Data columns (total 1 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Other_Provisions_th_GBP  30614 non-null  float64
dtypes: float64(1)
memory usage: 433.1+ KB
618
125990
After dropna size is:
1447
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 32061 entries, ('GB09639538', 2019) to ('GB07782390', 2012)
Data columns (total 1 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Other_Provisions_th_GBP  32061 non-null  float64
dtypes: float64(1)
memory usage: 451.2+ KB
619
125990
After dropna size is:
593
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 32654 entries, ('GB09639538', 2019) to ('GB07470677', 2011)
Data columns (total 1 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Other_Provisions_th_GBP  32654 non-null  float64
dtypes: float64(1)
memory usage: 458.6+ KB
620
125990
After dropna size is:
261
621
125990
After dropna size is:
314
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 575 entries, ('GB08233527', 2019) to ('GB08228494', 2018)
Data columns (total 1 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Pension_Liabilities_th_GBP  575 non-null    float64
dtypes: float64(1)
memory usage: 9.0+ KB
622
125990
After dropna size is:
326
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 901 entries, ('GB08233527', 2019) to ('GB08228494', 2017)
Data columns (total 1 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Pension_Liabilities_th_GBP  901 non-null    float64
dtypes: float64(1)
memory usage: 12.8+ KB
623
125990
After dropna size is:
316
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1217 entries, ('GB08233527', 2019) to ('GB07954385', 2016)
Data columns (total 1 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Pension_Liabilities_th_GBP  1217 non-null   float64
dtypes: float64(1)
memory usage: 16.5+ KB
624
125990
After dropna size is:
267
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1484 entries, ('GB08233527', 2019) to ('GB08228494', 2015)
Data columns (total 1 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Pension_Liabilities_th_GBP  1484 non-null   float64
dtypes: float64(1)
memory usage: 19.4+ KB
625
125990
After dropna size is:
222
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1706 entries, ('GB08233527', 2019) to ('GB07954385', 2014)
Data columns (total 1 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Pension_Liabilities_th_GBP  1706 non-null   float64
dtypes: float64(1)
memory usage: 21.9+ KB
626
125990
After dropna size is:
152
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1858 entries, ('GB08233527', 2019) to ('GB07954385', 2013)
Data columns (total 1 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Pension_Liabilities_th_GBP  1858 non-null   float64
dtypes: float64(1)
memory usage: 23.6+ KB
627
125990
After dropna size is:
71
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1929 entries, ('GB08233527', 2019) to ('GB07954385', 2012)
Data columns (total 1 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Pension_Liabilities_th_GBP  1929 non-null   float64
dtypes: float64(1)
memory usage: 24.4+ KB
628
125990
After dropna size is:
15
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1944 entries, ('GB08233527', 2019) to ('GB07193289', 2011)
Data columns (total 1 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Pension_Liabilities_th_GBP  1944 non-null   float64
dtypes: float64(1)
memory usage: 24.6+ KB
629
125990
After dropna size is:
60
630
125990
After dropna size is:
127
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 187 entries, ('GB08549664', 2019) to ('GB07281277', 2018)
Data columns (total 1 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Balance_sheet_Minorities_th_GBP  187 non-null    float64
dtypes: float64(1)
memory usage: 3.3+ KB
631
125990
After dropna size is:
130
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 317 entries, ('GB08549664', 2019) to ('GB08714487', 2017)
Data columns (total 1 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Balance_sheet_Minorities_th_GBP  317 non-null    float64
dtypes: float64(1)
memory usage: 4.9+ KB
632
125990
After dropna size is:
130
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 447 entries, ('GB08549664', 2019) to ('GB07281277', 2016)
Data columns (total 1 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Balance_sheet_Minorities_th_GBP  447 non-null    float64
dtypes: float64(1)
memory usage: 6.6+ KB
633
125990

After dropna size is:
135
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 582 entries, ('GB08549664', 2019) to ('GB08714487', 2015)
Data columns (total 1 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Balance_sheet_Minorities_th_GBP  582 non-null    float64
dtypes: float64(1)
memory usage: 8.3+ KB
634
125990
After dropna size is:
107
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 689 entries, ('GB08549664', 2019) to ('GB07937886', 2014)
Data columns (total 1 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Balance_sheet_Minorities_th_GBP  689 non-null    float64
dtypes: float64(1)
memory usage: 9.7+ KB
635
125990
After dropna size is:
84
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 773 entries, ('GB08549664', 2019) to ('GB07937886', 2013)
Data columns (total 1 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Balance_sheet_Minorities_th_GBP  773 non-null    float64
dtypes: float64(1)
memory usage: 10.8+ KB
636
125990
After dropna size is:
60
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 833 entries, ('GB08549664', 2019) to ('GB07937886', 2012)
Data columns (total 1 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Balance_sheet_Minorities_th_GBP  833 non-null    float64
dtypes: float64(1)
memory usage: 11.5+ KB
637
125990
After dropna size is:
24
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 857 entries, ('GB08549664', 2019) to ('GB07281277', 2011)
Data columns (total 1 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Balance_sheet_Minorities_th_GBP  857 non-null    float64
dtypes: float64(1)
memory usage: 11.8+ KB
638
125990
After dropna size is:
19943
639
125990
After dropna size is:
34338
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 54281 entries, ('GB09567757', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Long_Term_Liabilities_th_GBP  54281 non-null  float64
dtypes: float64(1)
memory usage: 985.2+ KB
640
125990
After dropna size is:
35925
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 90206 entries, ('GB09567757', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Long_Term_Liabilities_th_GBP  90206 non-null  float64
dtypes: float64(1)
memory usage: 1.5+ MB
641
125990
After dropna size is:
31702
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 121908 entries, ('GB09567757', 2019) to ('GBOC365296', 2016)
Data columns (total 1 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Long_Term_Liabilities_th_GBP  121908 non-null  float64
dtypes: float64(1)
memory usage: 1.9+ MB
642
125990
After dropna size is:
26850
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 148758 entries, ('GB09567757', 2019) to ('GBOC381395', 2015)
Data columns (total 1 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Long_Term_Liabilities_th_GBP  148758 non-null  float64
dtypes: float64(1)
memory usage: 2.3+ MB
643
125990
After dropna size is:
21761
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 170519 entries, ('GB09567757', 2019) to ('GBOC381395', 2014)
Data columns (total 1 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Long_Term_Liabilities_th_GBP  170519 non-null  float64
dtypes: float64(1)
memory usage: 2.6+ MB
644
125990
After dropna size is:
15976
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 186495 entries, ('GB09567757', 2019) to ('GBOC365296', 2013)
Data columns (total 1 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Long_Term_Liabilities_th_GBP  186495 non-null  float64
dtypes: float64(1)
memory usage: 2.8+ MB
645
125990
After dropna size is:
10419
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 196914 entries, ('GB09567757', 2019) to ('GBOC365296', 2012)
Data columns (total 1 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Long_Term_Liabilities_th_GBP  196914 non-null  float64
dtypes: float64(1)
memory usage: 2.9+ MB
646
125990
After dropna size is:
4770
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 201684 entries, ('GB09567757', 2019) to ('GB07149148', 2011)
Data columns (total 1 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Long_Term_Liabilities_th_GBP  201684 non-null  float64
dtypes: float64(1)
memory usage: 3.0+ MB
647
125990
After dropna size is:
59723
648
125990
After dropna size is:
101625
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 161348 entries, ('GB09567757', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Net_assets_th_GBP  161348 non-null  float64
dtypes: float64(1)
memory usage: 2.8+ MB
649
125990
After dropna size is:
109101
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 270449 entries, ('GB09567757', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Net_assets_th_GBP  270449 non-null  float64
dtypes: float64(1)
memory usage: 4.2+ MB
650
125990
After dropna size is:
106304
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 376753 entries, ('GB09567757', 2019) to ('GBOC381395', 2016)
Data columns (total 1 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Net_assets_th_GBP  376753 non-null  float64
dtypes: float64(1)
memory usage: 5.6+ MB
651
125990
After dropna size is:
93846
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 470599 entries, ('GB09567757', 2019) to ('GBOC381395', 2015)
Data columns (total 1 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Net_assets_th_GBP  470599 non-null  float64
dtypes: float64(1)
memory usage: 6.8+ MB
652
125990
After dropna size is:
78751
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 549350 entries, ('GB09567757', 2019) to ('GBOC381395', 2014)
Data columns (total 1 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Net_assets_th_GBP  549350 non-null  float64
dtypes: float64(1)
memory usage: 7.8+ MB
653
125990
After dropna size is:
60585
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 609935 entries, ('GB09567757', 2019) to ('GBSC452461', 2013)
Data columns (total 1 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Net_assets_th_GBP  609935 non-null  float64
dtypes: float64(1)
memory usage: 8.5+ MB
654
125990
After dropna size is:
41481
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 651416 entries, ('GB09567757', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Net_assets_th_GBP  651416 non-null  float64
dtypes: float64(1)
memory usage: 9.0+ MB
655
125990
After dropna size is:
21051
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 672467 entries, ('GB09567757', 2019) to ('GB07266603', 2011)
Data columns (total 1 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Net_assets_th_GBP  672467 non-null  float64
dtypes: float64(1)
memory usage: 9.3+ MB
656
125990
After dropna size is:
23990

657
125990
After dropna size is:
45204
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 69194 entries, ('GB07588867', 2019) to ('IE505067', 2018)
Data columns (total 1 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Issued_Capital_th_GBP  69194 non-null  float64
dtypes: float64(1)
memory usage: 1.2+ MB
658
125990
After dropna size is:
52697
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 121891 entries, ('GB07588867', 2019) to ('IE505067', 2017)
Data columns (total 1 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Issued_Capital_th_GBP  121891 non-null  float64
dtypes: float64(1)
memory usage: 2.0+ MB
659
125990
After dropna size is:
71630
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 193521 entries, ('GB07588867', 2019) to ('IE505067', 2016)
Data columns (total 1 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Issued_Capital_th_GBP  193521 non-null  float64
dtypes: float64(1)
memory usage: 3.0+ MB
660
125990
After dropna size is:
70023
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 263544 entries, ('GB07588867', 2019) to ('IE505067', 2015)
Data columns (total 1 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Issued_Capital_th_GBP  263544 non-null  float64
dtypes: float64(1)
memory usage: 4.0+ MB
661
125990
After dropna size is:
62014
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 325558 entries, ('GB07588867', 2019) to ('GBSC452461', 2014)
Data columns (total 1 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Issued_Capital_th_GBP  325558 non-null  float64
dtypes: float64(1)
memory usage: 4.8+ MB
662
125990
After dropna size is:
49377
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 374935 entries, ('GB07588867', 2019) to ('GBSC452461', 2013)
Data columns (total 1 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Issued_Capital_th_GBP  374935 non-null  float64
dtypes: float64(1)
memory usage: 5.4+ MB
663
125990
After dropna size is:
33266
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 408201 entries, ('GB07588867', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Issued_Capital_th_GBP  408201 non-null  float64
dtypes: float64(1)
memory usage: 5.8+ MB
664
125990
After dropna size is:
16905
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 425106 entries, ('GB07588867', 2019) to ('GB07266603', 2011)
Data columns (total 1 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Issued_Capital_th_GBP  425106 non-null  float64
dtypes: float64(1)
memory usage: 6.0+ MB
665
125990
After dropna size is:
23941
666
125990
After dropna size is:
45118
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 69059 entries, ('GB07588867', 2019) to ('IE505067', 2018)
Data columns (total 1 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Ordinary_Shares_th_GBP  69059 non-null  float64
dtypes: float64(1)
memory usage: 1.2+ MB
667
125990
After dropna size is:
52606
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 121665 entries, ('GB07588867', 2019) to ('IE505067', 2017)
Data columns (total 1 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Ordinary_Shares_th_GBP  121665 non-null  float64
dtypes: float64(1)
memory usage: 2.0+ MB
668
125990
After dropna size is:
71519
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 193184 entries, ('GB07588867', 2019) to ('IE505067', 2016)
Data columns (total 1 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Ordinary_Shares_th_GBP  193184 non-null  float64
dtypes: float64(1)
memory usage: 3.0+ MB
669
125990
After dropna size is:
69936
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 263120 entries, ('GB07588867', 2019) to ('IE505067', 2015)
Data columns (total 1 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Ordinary_Shares_th_GBP  263120 non-null  float64
dtypes: float64(1)
memory usage: 4.0+ MB
670
125990
After dropna size is:
61905
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 325025 entries, ('GB07588867', 2019) to ('GBSC452461', 2014)
Data columns (total 1 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Ordinary_Shares_th_GBP  325025 non-null  float64
dtypes: float64(1)
memory usage: 4.8+ MB
671
125990
After dropna size is:
49223
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 374248 entries, ('GB07588867', 2019) to ('GBSC452461', 2013)
Data columns (total 1 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Ordinary_Shares_th_GBP  374248 non-null  float64
dtypes: float64(1)
memory usage: 5.4+ MB
672
125990
After dropna size is:
33065
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 407313 entries, ('GB07588867', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Ordinary_Shares_th_GBP  407313 non-null  float64
dtypes: float64(1)
memory usage: 5.8+ MB
673
125990
After dropna size is:
16811
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 424124 entries, ('GB07588867', 2019) to ('GB07266603', 2011)
Data columns (total 1 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Ordinary_Shares_th_GBP  424124 non-null  float64
dtypes: float64(1)
memory usage: 6.0+ MB
674
125990
After dropna size is:
26
675
125990
After dropna size is:
61
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 87 entries, ('GB08448175', 2019) to ('IE534964', 2018)
Data columns (total 1 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Other_Shares_th_GBP  87 non-null     float64
dtypes: float64(1)
memory usage: 1.6+ KB
676
125990
After dropna size is:
64
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 151 entries, ('GB08448175', 2019) to ('GB09061578', 2017)
Data columns (total 1 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Other_Shares_th_GBP  151 non-null    float64
dtypes: float64(1)
memory usage: 2.6+ KB
677
125990
After dropna size is:
92
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 243 entries, ('GB08448175', 2019) to ('GB09061578', 2016)
Data columns (total 1 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Other_Shares_th_GBP  243 non-null    float64
dtypes: float64(1)
memory usage: 4.2+ KB
678
125990
After dropna size is:
80
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 323 entries, ('GB08448175', 2019) to ('GB07343290', 2015)
Data columns (total 1 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Other_Shares_th_GBP  323 non-null    float64
dtypes: float64(1)
memory usage: 5.5+ KB
679
125990
After dropna size is:
67
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 390 entries, ('GB08448175', 2019) to ('GB08502147', 2014)
Data columns (total 1 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Other_Shares_th_GBP  390 non-null    float64
dtypes: float64(1)
memory usage: 6.5+ KB
680
125990
After dropna size is:
49
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 439 entries, ('GB08448175', 2019) to ('GB07170715', 2013)
Data columns (total 1 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Other_Shares_th_GBP  439 non-null    float64
dtypes: float64(1)
memory usage: 7.2+ KB
681
125990
After dropna size is:
58
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 497 entries, ('GB08448175', 2019) to ('GB07162508', 2012)
Data columns (total 1 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Other_Shares_th_GBP  497 non-null    float64
dtypes: float64(1)
memory usage: 8.0+ KB
682
125990
After dropna size is:
23
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 520 entries, ('GB08448175', 2019) to ('GB07244945', 2011)
Data columns (total 1 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Other_Shares_th_GBP  520 non-null    float64
dtypes: float64(1)
memory usage: 8.4+ KB
683
125990
After dropna size is:
56025

684
125990
After dropna size is:
95390
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 151415 entries, ('GB07588867', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Total_Reserves_th_GBP  151415 non-null  float64
dtypes: float64(1)
memory usage: 2.6+ MB
685
125990
After dropna size is:
101397
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 252812 entries, ('GB07588867', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Total_Reserves_th_GBP  252812 non-null  float64
dtypes: float64(1)
memory usage: 3.9+ MB
686
125990
After dropna size is:
96107
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 348919 entries, ('GB07588867', 2019) to ('GBOC381395', 2016)
Data columns (total 1 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Total_Reserves_th_GBP  348919 non-null  float64
dtypes: float64(1)
memory usage: 5.2+ MB
687
125990
After dropna size is:
83212
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 432131 entries, ('GB07588867', 2019) to ('GBSC452461', 2015)
Data columns (total 1 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Total_Reserves_th_GBP  432131 non-null  float64
dtypes: float64(1)
memory usage: 6.2+ MB
688
125990
After dropna size is:
68735
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 500866 entries, ('GB07588867', 2019) to ('GBOC369696', 2014)
Data columns (total 1 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Total_Reserves_th_GBP  500866 non-null  float64
dtypes: float64(1)
memory usage: 7.1+ MB
689
125990
After dropna size is:
52237
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 553103 entries, ('GB07588867', 2019) to ('GBOC369696', 2013)
Data columns (total 1 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Total_Reserves_th_GBP  553103 non-null  float64
dtypes: float64(1)
memory usage: 7.8+ MB
690
125990
After dropna size is:
35278
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 588381 entries, ('GB07588867', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Total_Reserves_th_GBP  588381 non-null  float64
dtypes: float64(1)
memory usage: 8.2+ MB
691
125990
After dropna size is:
17270
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 605651 entries, ('GB07588867', 2019) to ('GB07266603', 2011)
Data columns (total 1 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Total_Reserves_th_GBP  605651 non-null  float64
dtypes: float64(1)
memory usage: 8.4+ MB
692
125990
After dropna size is:
776
693
125990
After dropna size is:
1892
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 2668 entries, ('GB08287986', 2019) to ('GB09061578', 2018)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Share_Premium_Account_th_GBP  2668 non-null   float64
dtypes: float64(1)
memory usage: 44.5+ KB
694
125990
After dropna size is:
1943
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 4611 entries, ('GB08287986', 2019) to ('GB09061578', 2017)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Share_Premium_Account_th_GBP  4611 non-null   float64
dtypes: float64(1)
memory usage: 67.8+ KB
695
125990
After dropna size is:
1904
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 6515 entries, ('GB08287986', 2019) to ('GB09061578', 2016)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Share_Premium_Account_th_GBP  6515 non-null   float64
dtypes: float64(1)
memory usage: 90.6+ KB
696
125990
After dropna size is:
1651
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 8166 entries, ('GB08287986', 2019) to ('GB08662355', 2015)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Share_Premium_Account_th_GBP  8166 non-null   float64
dtypes: float64(1)
memory usage: 110.0+ KB
697
125990
After dropna size is:
1303
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 9469 entries, ('GB08287986', 2019) to ('GB07957046', 2014)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Share_Premium_Account_th_GBP  9469 non-null   float64
dtypes: float64(1)
memory usage: 125.0+ KB
698
125990
After dropna size is:
893
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 10362 entries, ('GB08287986', 2019) to ('GB07957046', 2013)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Share_Premium_Account_th_GBP  10362 non-null  float64
dtypes: float64(1)
memory usage: 135.1+ KB
699
125990
After dropna size is:
595
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 10957 entries, ('GB08287986', 2019) to ('GB07341487', 2012)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Share_Premium_Account_th_GBP  10957 non-null  float64
dtypes: float64(1)
memory usage: 142.0+ KB
700
125990
After dropna size is:
237
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 11194 entries, ('GB08287986', 2019) to ('GB07341487', 2011)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Share_Premium_Account_th_GBP  11194 non-null  float64
dtypes: float64(1)
memory usage: 144.8+ KB
701
125990
After dropna size is:
857
702
125990
After dropna size is:
657
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1514 entries, ('GB08902671', 2019) to ('GB09159925', 2018)
Data columns (total 1 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Revaluation_Reserves_th_GBP  1514 non-null   float64
dtypes: float64(1)
memory usage: 26.2+ KB
703
125990
After dropna size is:
703
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 2217 entries, ('GB08902671', 2019) to ('GB08389817', 2017)
Data columns (total 1 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Revaluation_Reserves_th_GBP  2217 non-null   float64
dtypes: float64(1)
memory usage: 36.2+ KB
704
125990
After dropna size is:
884
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 3101 entries, ('GB08902671', 2019) to ('GB07282125', 2016)
Data columns (total 1 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Revaluation_Reserves_th_GBP  3101 non-null   float64
dtypes: float64(1)
memory usage: 49.2+ KB
705
125990
After dropna size is:
908
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 4009 entries, ('GB08902671', 2019) to ('GB07282125', 2015)
Data columns (total 1 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Revaluation_Reserves_th_GBP  4009 non-null   float64
dtypes: float64(1)
memory usage: 62.6+ KB
706
125990
After dropna size is:
794
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 4803 entries, ('GB08902671', 2019) to ('GB07167315', 2014)
Data columns (total 1 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Revaluation_Reserves_th_GBP  4803 non-null   float64
dtypes: float64(1)
memory usage: 73.7+ KB
707
125990
After dropna size is:
538
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 5341 entries, ('GB08902671', 2019) to ('GB08246696', 2013)
Data columns (total 1 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Revaluation_Reserves_th_GBP  5341 non-null   float64
dtypes: float64(1)
memory usage: 81.1+ KB
708
125990
After dropna size is:
265
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 5606 entries, ('GB08902671', 2019) to ('GBSO303334', 2012)
Data columns (total 1 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Revaluation_Reserves_th_GBP  5606 non-null   float64
dtypes: float64(1)
memory usage: 84.5+ KB
709
125990
After dropna size is:
74
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 5680 entries, ('GB08902671', 2019) to ('GB07161547', 2011)
Data columns (total 1 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Revaluation_Reserves_th_GBP  5680 non-null   float64
dtypes: float64(1)
memory usage: 85.5+ KB
710
125990
After dropna size is:
25927

711
125990
After dropna size is:
51282
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 77209 entries, ('GB07588867', 2019) to ('GBSC452461', 2018)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Profit_(Loss)_Account_th_GBP  77209 non-null  float64
dtypes: float64(1)
memory usage: 1.4+ MB
712
125990
After dropna size is:
58182
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 135391 entries, ('GB07588867', 2019) to ('GBSC452461', 2017)
Data columns (total 1 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Profit_(Loss)_Account_th_GBP  135391 non-null  float64
dtypes: float64(1)
memory usage: 2.2+ MB
713
125990
After dropna size is:
74307
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 209698 entries, ('GB07588867', 2019) to ('GBSC452461', 2016)
Data columns (total 1 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Profit_(Loss)_Account_th_GBP  209698 non-null  float64
dtypes: float64(1)
memory usage: 3.3+ MB
714
125990
After dropna size is:
70951
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 280649 entries, ('GB07588867', 2019) to ('GBSC452461', 2015)
Data columns (total 1 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Profit_(Loss)_Account_th_GBP  280649 non-null  float64
dtypes: float64(1)
memory usage: 4.2+ MB
715
125990
After dropna size is:
61901
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 342550 entries, ('GB07588867', 2019) to ('IE505067', 2014)
Data columns (total 1 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Profit_(Loss)_Account_th_GBP  342550 non-null  float64
dtypes: float64(1)
memory usage: 5.0+ MB
716
125990
After dropna size is:
49350
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 391900 entries, ('GB07588867', 2019) to ('GB07266603', 2013)
Data columns (total 1 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Profit_(Loss)_Account_th_GBP  391900 non-null  float64
dtypes: float64(1)
memory usage: 5.7+ MB
717
125990
After dropna size is:
33407
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 425307 entries, ('GB07588867', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Profit_(Loss)_Account_th_GBP  425307 non-null  float64
dtypes: float64(1)
memory usage: 6.1+ MB
718
125990
After dropna size is:
16358
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 441665 entries, ('GB07588867', 2019) to ('GB07266603', 2011)
Data columns (total 1 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Profit_(Loss)_Account_th_GBP  441665 non-null  float64
dtypes: float64(1)
memory usage: 6.3+ MB
719
125990
After dropna size is:
30500

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Profit_(Loss)_Account_th_GBP'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

720
125990
After dropna size is:
46455
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 76955 entries, ('GBOC353264', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Other_Reserves_th_GBP  76955 non-null  float64
dtypes: float64(1)
memory usage: 1.3+ MB
721
125990
After dropna size is:
45710
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 122665 entries, ('GBOC353264', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Other_Reserves_th_GBP  122665 non-null  float64
dtypes: float64(1)
memory usage: 2.0+ MB
722
125990
After dropna size is:
24377
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 147042 entries, ('GBOC353264', 2019) to ('GBOC381395', 2016)
Data columns (total 1 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Other_Reserves_th_GBP  147042 non-null  float64
dtypes: float64(1)
memory usage: 2.3+ MB
723
125990
After dropna size is:
14283
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 161325 entries, ('GBOC353264', 2019) to ('GBOC369696', 2015)
Data columns (total 1 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Other_Reserves_th_GBP  161325 non-null  float64
dtypes: float64(1)
memory usage: 2.5+ MB
724
125990
After dropna size is:
8355
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 169680 entries, ('GBOC353264', 2019) to ('GBOC369696', 2014)
Data columns (total 1 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Other_Reserves_th_GBP  169680 non-null  float64
dtypes: float64(1)
memory usage: 2.6+ MB
725
125990
After dropna size is:
4008
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 173688 entries, ('GBOC353264', 2019) to ('GBOC369696', 2013)
Data columns (total 1 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Other_Reserves_th_GBP  173688 non-null  float64
dtypes: float64(1)
memory usage: 2.7+ MB
726
125990
After dropna size is:
2616
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 176304 entries, ('GBOC353264', 2019) to ('GBOC359576', 2012)
Data columns (total 1 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Other_Reserves_th_GBP  176304 non-null  float64
dtypes: float64(1)
memory usage: 2.7+ MB
727
125990
After dropna size is:
1236
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 177540 entries, ('GBOC353264', 2019) to ('GBNC000600', 2011)
Data columns (total 1 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Other_Reserves_th_GBP  177540 non-null  float64
dtypes: float64(1)
memory usage: 2.7+ MB
728
125990
After dropna size is:
2032
729
125990
After dropna size is:
5795
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 7827 entries, ('GB08463603', 2019) to ('GB08633289', 2018)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   National_Turnover_th_GBP  7827 non-null   float64
dtypes: float64(1)
memory usage: 134.4+ KB
730
125990
After dropna size is:
6564
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 14391 entries, ('GB08463603', 2019) to ('GBOC365296', 2017)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   National_Turnover_th_GBP  14391 non-null  float64
dtypes: float64(1)
memory usage: 222.2+ KB
731
125990
After dropna size is:
7525
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 21916 entries, ('GB08463603', 2019) to ('GB08633289', 2016)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   National_Turnover_th_GBP  21916 non-null  float64
dtypes: float64(1)
memory usage: 326.4+ KB
732
125990
After dropna size is:
6743
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 28659 entries, ('GB08463603', 2019) to ('GBOC369696', 2015)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   National_Turnover_th_GBP  28659 non-null  float64
dtypes: float64(1)
memory usage: 417.5+ KB
733
125990
After dropna size is:
5607
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 34266 entries, ('GB08463603', 2019) to ('GBOC369696', 2014)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   National_Turnover_th_GBP  34266 non-null  float64
dtypes: float64(1)
memory usage: 490.6+ KB
734
125990
After dropna size is:
4849
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 39115 entries, ('GB08463603', 2019) to ('GBOC369696', 2013)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   National_Turnover_th_GBP  39115 non-null  float64
dtypes: float64(1)
memory usage: 555.3+ KB
735
125990
After dropna size is:
3752
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 42867 entries, ('GB08463603', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   National_Turnover_th_GBP  42867 non-null  float64
dtypes: float64(1)
memory usage: 605.3+ KB
736
125990
After dropna size is:
1983
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 44850 entries, ('GB08463603', 2019) to ('GB07266603', 2011)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   National_Turnover_th_GBP  44850 non-null  float64
dtypes: float64(1)
memory usage: 631.7+ KB
737
125990
After dropna size is:
226
738
125990
After dropna size is:
1044
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1270 entries, ('IE539079', 2019) to ('GB09061578', 2018)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Overseas_Turnover_th_GBP  1270 non-null   float64
dtypes: float64(1)
memory usage: 22.5+ KB
739
125990
After dropna size is:
1141
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 2411 entries, ('IE539079', 2019) to ('GB09061578', 2017)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Overseas_Turnover_th_GBP  2411 non-null   float64
dtypes: float64(1)
memory usage: 37.1+ KB
740
125990
After dropna size is:
1218
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 3629 entries, ('IE539079', 2019) to ('GB09061578', 2016)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Overseas_Turnover_th_GBP  3629 non-null   float64
dtypes: float64(1)
memory usage: 53.5+ KB
741
125990
After dropna size is:
1132
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 4761 entries, ('IE539079', 2019) to ('GB09061578', 2015)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Overseas_Turnover_th_GBP  4761 non-null   float64
dtypes: float64(1)
memory usage: 68.9+ KB
742
125990
After dropna size is:
858
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 5619 entries, ('IE539079', 2019) to ('GB08094042', 2014)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Overseas_Turnover_th_GBP  5619 non-null   float64
dtypes: float64(1)
memory usage: 80.0+ KB
743
125990
After dropna size is:
650
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 6269 entries, ('IE539079', 2019) to ('GB08094042', 2013)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Overseas_Turnover_th_GBP  6269 non-null   float64
dtypes: float64(1)
memory usage: 88.3+ KB
744
125990
After dropna size is:
395
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 6664 entries, ('IE539079', 2019) to ('GB07447572', 2012)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Overseas_Turnover_th_GBP  6664 non-null   float64
dtypes: float64(1)
memory usage: 93.4+ KB
745
125990
After dropna size is:
140
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 6804 entries, ('IE539079', 2019) to ('GB07297657', 2011)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Overseas_Turnover_th_GBP  6804 non-null   float64
dtypes: float64(1)
memory usage: 95.1+ KB
746
125990
After dropna size is:
7442
747

125990
After dropna size is:
17240
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 24682 entries, ('IE566240', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Cost_of_Sales_th_GBP  24682 non-null  float64
dtypes: float64(1)
memory usage: 416.9+ KB
748
125990
After dropna size is:
20928
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 45610 entries, ('IE566240', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Cost_of_Sales_th_GBP  45610 non-null  float64
dtypes: float64(1)
memory usage: 707.2+ KB
749
125990
After dropna size is:
19464
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 65074 entries, ('IE566240', 2019) to ('GBOC381395', 2016)
Data columns (total 1 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Cost_of_Sales_th_GBP  65074 non-null  float64
dtypes: float64(1)
memory usage: 1.1+ MB
750
125990
After dropna size is:
17243
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 82317 entries, ('IE566240', 2019) to ('GBSC452461', 2015)
Data columns (total 1 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Cost_of_Sales_th_GBP  82317 non-null  float64
dtypes: float64(1)
memory usage: 1.3+ MB
751
125990
After dropna size is:
15463
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 97780 entries, ('IE566240', 2019) to ('GB08389817', 2014)
Data columns (total 1 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Cost_of_Sales_th_GBP  97780 non-null  float64
dtypes: float64(1)
memory usage: 1.6+ MB
752
125990
After dropna size is:
13315
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 111095 entries, ('IE566240', 2019) to ('GB07266603', 2013)
Data columns (total 1 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Cost_of_Sales_th_GBP  111095 non-null  float64
dtypes: float64(1)
memory usage: 1.8+ MB
753
125990
After dropna size is:
9994
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 121089 entries, ('IE566240', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Cost_of_Sales_th_GBP  121089 non-null  float64
dtypes: float64(1)
memory usage: 1.9+ MB
754
125990
After dropna size is:
5336
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 126425 entries, ('IE566240', 2019) to ('GB07266603', 2011)
Data columns (total 1 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Cost_of_Sales_th_GBP  126425 non-null  float64
dtypes: float64(1)
memory usage: 2.0+ MB
755
125990
After dropna size is:
0
756
125990
After dropna size is:
0
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 0 entries
Data columns (total 1 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Exceptional_Items_pre_GP_th_GBP  0 non-null      float64
dtypes: float64(1)
memory usage: 151.0 bytes
757
125990
After dropna size is:
4
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 4 entries, ('GBOC383443', 2017) to ('GBOC356082', 2017)
Data columns (total 1 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Exceptional_Items_pre_GP_th_GBP  4 non-null      float64
dtypes: float64(1)
memory usage: 231.0+ bytes
758
125990
After dropna size is:
0
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 4 entries, ('GBOC383443', 2017) to ('GBOC356082', 2017)
Data columns (total 1 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Exceptional_Items_pre_GP_th_GBP  4 non-null      float64
dtypes: float64(1)
memory usage: 231.0+ bytes
759
125990
After dropna size is:
0
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 4 entries, ('GBOC383443', 2017) to ('GBOC356082', 2017)
Data columns (total 1 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Exceptional_Items_pre_GP_th_GBP  4 non-null      float64
dtypes: float64(1)
memory usage: 231.0+ bytes
760
125990
After dropna size is:
1
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 5 entries, ('GBOC383443', 2017) to ('GBSC467172', 2014)
Data columns (total 1 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Exceptional_Items_pre_GP_th_GBP  5 non-null      float64
dtypes: float64(1)
memory usage: 257.0+ bytes
761
125990
After dropna size is:
0
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 5 entries, ('GBOC383443', 2017) to ('GBSC467172', 2014)
Data columns (total 1 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Exceptional_Items_pre_GP_th_GBP  5 non-null      float64
dtypes: float64(1)
memory usage: 257.0+ bytes
762
125990
After dropna size is:
1
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 6 entries, ('GBOC383443', 2017) to ('GB07623039', 2012)
Data columns (total 1 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Exceptional_Items_pre_GP_th_GBP  6 non-null      float64
dtypes: float64(1)
memory usage: 283.0+ bytes
763
125990
After dropna size is:
1
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 7 entries, ('GBOC383443', 2017) to ('GB07195881', 2011)
Data columns (total 1 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Exceptional_Items_pre_GP_th_GBP  7 non-null      float64
dtypes: float64(1)
memory usage: 309.0+ bytes
764
125990
After dropna size is:
0
765
125990
After dropna size is:
5
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 5 entries, ('GB10221323', 2018) to ('GB08439589', 2018)
Data columns (total 1 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Other_Income_pre_GP_th_GBP  5 non-null      float64
dtypes: float64(1)
memory usage: 249.0+ bytes
766
125990
After dropna size is:
27
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 32 entries, ('GB10221323', 2018) to ('GBOC375549', 2017)
Data columns (total 1 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Other_Income_pre_GP_th_GBP  32 non-null     float64
dtypes: float64(1)
memory usage: 735.0+ bytes
767
125990
After dropna size is:
18
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 50 entries, ('GB10221323', 2018) to ('GBOC381745', 2016)
Data columns (total 1 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Other_Income_pre_GP_th_GBP  50 non-null     float64
dtypes: float64(1)
memory usage: 1.0+ KB
768
125990
After dropna size is:
4
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 54 entries, ('GB10221323', 2018) to ('GBOC380912', 2015)
Data columns (total 1 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Other_Income_pre_GP_th_GBP  54 non-null     float64
dtypes: float64(1)
memory usage: 1.1+ KB
769
125990
After dropna size is:
3
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 57 entries, ('GB10221323', 2018) to ('GB08535264', 2014)
Data columns (total 1 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Other_Income_pre_GP_th_GBP  57 non-null     float64
dtypes: float64(1)
memory usage: 1.2+ KB
770
125990
After dropna size is:
2
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 59 entries, ('GB10221323', 2018) to ('GB07173727', 2013)
Data columns (total 1 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Other_Income_pre_GP_th_GBP  59 non-null     float64
dtypes: float64(1)
memory usage: 1.2+ KB
771
125990
After dropna size is:
2
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 61 entries, ('GB10221323', 2018) to ('GBOC352096', 2012)
Data columns (total 1 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Other_Income_pre_GP_th_GBP  61 non-null     float64
dtypes: float64(1)
memory usage: 1.3+ KB
772
125990
After dropna size is:
4
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 65 entries, ('GB10221323', 2018) to ('GB07262960', 2011)
Data columns (total 1 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Other_Income_pre_GP_th_GBP  65 non-null     float64
dtypes: float64(1)
memory usage: 1.3+ KB
773
125990
After dropna size is:
9496
774
125990
After dropna size is:
21323

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 30819 entries, ('GB07588867', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Gross_Profit_th_GBP  30819 non-null  float64
dtypes: float64(1)
memory usage: 521.0+ KB
775
125990
After dropna size is:
26549
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 57368 entries, ('GB07588867', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Gross_Profit_th_GBP  57368 non-null  float64
dtypes: float64(1)
memory usage: 1005.1+ KB
776
125990
After dropna size is:
23489
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 80857 entries, ('GB07588867', 2019) to ('GBOC381395', 2016)
Data columns (total 1 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Gross_Profit_th_GBP  80857 non-null  float64
dtypes: float64(1)
memory usage: 1.3+ MB
777
125990
After dropna size is:
20970
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 101827 entries, ('GB07588867', 2019) to ('GBSC452461', 2015)
Data columns (total 1 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Gross_Profit_th_GBP  101827 non-null  float64
dtypes: float64(1)
memory usage: 1.7+ MB
778
125990
After dropna size is:
18527
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 120354 entries, ('GB07588867', 2019) to ('GB08389817', 2014)
Data columns (total 1 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Gross_Profit_th_GBP  120354 non-null  float64
dtypes: float64(1)
memory usage: 1.9+ MB
779
125990
After dropna size is:
15799
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 136153 entries, ('GB07588867', 2019) to ('GB07266603', 2013)
Data columns (total 1 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Gross_Profit_th_GBP  136153 non-null  float64
dtypes: float64(1)
memory usage: 2.2+ MB
780
125990
After dropna size is:
11605
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 147758 entries, ('GB07588867', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Gross_Profit_th_GBP  147758 non-null  float64
dtypes: float64(1)
memory usage: 2.4+ MB
781
125990
After dropna size is:
6169
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 153927 entries, ('GB07588867', 2019) to ('GB07266603', 2011)
Data columns (total 1 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Gross_Profit_th_GBP  153927 non-null  float64
dtypes: float64(1)
memory usage: 2.5+ MB
782
125990
After dropna size is:
21844
783
125990
After dropna size is:
43657
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 65501 entries, ('GB09567757', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Administration_Expenses_th_GBP  65501 non-null  float64
dtypes: float64(1)
memory usage: 1.2+ MB
784
125990
After dropna size is:
52676
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 118177 entries, ('GB09567757', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   Administration_Expenses_th_GBP  118177 non-null  float64
dtypes: float64(1)
memory usage: 2.0+ MB
785
125990
After dropna size is:
42458
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 160635 entries, ('GB09567757', 2019) to ('GBOC381395', 2016)
Data columns (total 1 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   Administration_Expenses_th_GBP  160635 non-null  float64
dtypes: float64(1)
memory usage: 2.6+ MB
786
125990
After dropna size is:
35221
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 195856 entries, ('GB09567757', 2019) to ('GBSC452461', 2015)
Data columns (total 1 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   Administration_Expenses_th_GBP  195856 non-null  float64
dtypes: float64(1)
memory usage: 3.2+ MB
787
125990
After dropna size is:
30354
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 226210 entries, ('GB09567757', 2019) to ('GBOC369696', 2014)
Data columns (total 1 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   Administration_Expenses_th_GBP  226210 non-null  float64
dtypes: float64(1)
memory usage: 3.6+ MB
788
125990
After dropna size is:
26284
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 252494 entries, ('GB09567757', 2019) to ('GBOC369696', 2013)
Data columns (total 1 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   Administration_Expenses_th_GBP  252494 non-null  float64
dtypes: float64(1)
memory usage: 4.0+ MB
789
125990
After dropna size is:
19723
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 272217 entries, ('GB09567757', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   Administration_Expenses_th_GBP  272217 non-null  float64
dtypes: float64(1)
memory usage: 4.3+ MB
790
125990
After dropna size is:
10458
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 282675 entries, ('GB09567757', 2019) to ('GB07266603', 2011)
Data columns (total 1 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   Administration_Expenses_th_GBP  282675 non-null  float64
dtypes: float64(1)
memory usage: 4.4+ MB
791
125990
After dropna size is:
9396
792
125990
After dropna size is:
15825
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 25221 entries, ('GB09567757', 2019) to ('GB09748738', 2018)
Data columns (total 1 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Other_Operating_Income/Costs_pre_OP_th_GBP  25221 non-null  float64
dtypes: float64(1)
memory usage: 430.7+ KB
793
125990
After dropna size is:
18465
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 43686 entries, ('GB09567757', 2019) to ('GB09748738', 2017)
Data columns (total 1 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Other_Operating_Income/Costs_pre_OP_th_GBP  43686 non-null  float64
dtypes: float64(1)
memory usage: 707.1+ KB
794
125990
After dropna size is:
10544
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 54230 entries, ('GB09567757', 2019) to ('GB07386028', 2016)
Data columns (total 1 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Other_Operating_Income/Costs_pre_OP_th_GBP  54230 non-null  float64
dtypes: float64(1)
memory usage: 970.1+ KB
795
125990
After dropna size is:
5996
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 60226 entries, ('GB09567757', 2019) to ('GB07498412', 2015)
Data columns (total 1 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Other_Operating_Income/Costs_pre_OP_th_GBP  60226 non-null  float64
dtypes: float64(1)
memory usage: 1.0+ MB
796
125990
After dropna size is:
3319
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 63545 entries, ('GB09567757', 2019) to ('GB08358639', 2014)
Data columns (total 1 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Other_Operating_Income/Costs_pre_OP_th_GBP  63545 non-null  float64
dtypes: float64(1)
memory usage: 1.1+ MB
797
125990
After dropna size is:
2486
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 66031 entries, ('GB09567757', 2019) to ('GB07560895', 2013)
Data columns (total 1 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Other_Operating_Income/Costs_pre_OP_th_GBP  66031 non-null  float64
dtypes: float64(1)
memory usage: 1.1+ MB
798
125990
After dropna size is:
2027

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 68058 entries, ('GB09567757', 2019) to ('GB07560895', 2012)
Data columns (total 1 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Other_Operating_Income/Costs_pre_OP_th_GBP  68058 non-null  float64
dtypes: float64(1)
memory usage: 1.2+ MB
799
125990
After dropna size is:
886
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 68944 entries, ('GB09567757', 2019) to ('GB07267581', 2011)
Data columns (total 1 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Other_Operating_Income/Costs_pre_OP_th_GBP  68944 non-null  float64
dtypes: float64(1)
memory usage: 1.2+ MB
800
125990
After dropna size is:
73
801
125990
After dropna size is:
217
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 290 entries, ('GB07155337', 2019) to ('GB09361456', 2018)
Data columns (total 1 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Exceptional_Items_pre_OP_th_GBP  290 non-null    float64
dtypes: float64(1)
memory usage: 5.3+ KB
802
125990
After dropna size is:
204
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 494 entries, ('GB07155337', 2019) to ('GB07993043', 2017)
Data columns (total 1 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Exceptional_Items_pre_OP_th_GBP  494 non-null    float64
dtypes: float64(1)
memory usage: 8.6+ KB
803
125990
After dropna size is:
199
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 693 entries, ('GB07155337', 2019) to ('GB07993043', 2016)
Data columns (total 1 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Exceptional_Items_pre_OP_th_GBP  693 non-null    float64
dtypes: float64(1)
memory usage: 11.7+ KB
804
125990
After dropna size is:
158
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 851 entries, ('GB07155337', 2019) to ('GB07993043', 2015)
Data columns (total 1 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Exceptional_Items_pre_OP_th_GBP  851 non-null    float64
dtypes: float64(1)
memory usage: 14.1+ KB
805
125990
After dropna size is:
133
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 984 entries, ('GB07155337', 2019) to ('GB07251054', 2014)
Data columns (total 1 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Exceptional_Items_pre_OP_th_GBP  984 non-null    float64
dtypes: float64(1)
memory usage: 16.1+ KB
806
125990
After dropna size is:
96
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1080 entries, ('GB07155337', 2019) to ('GB07248610', 2013)
Data columns (total 1 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Exceptional_Items_pre_OP_th_GBP  1080 non-null   float64
dtypes: float64(1)
memory usage: 17.6+ KB
807
125990
After dropna size is:
56
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1136 entries, ('GB07155337', 2019) to ('GB07444534', 2012)
Data columns (total 1 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Exceptional_Items_pre_OP_th_GBP  1136 non-null   float64
dtypes: float64(1)
memory usage: 18.4+ KB
808
125990
After dropna size is:
35
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1171 entries, ('GB07155337', 2019) to ('GB07246110', 2011)
Data columns (total 1 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Exceptional_Items_pre_OP_th_GBP  1171 non-null   float64
dtypes: float64(1)
memory usage: 18.9+ KB
809
125990
After dropna size is:
23261
810
125990
After dropna size is:
46177
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 69438 entries, ('GB09567757', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Operating_Profit_th_GBP  69438 non-null  float64
dtypes: float64(1)
memory usage: 1.3+ MB
811
125990
After dropna size is:
55464
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 124902 entries, ('GB09567757', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Operating_Profit_th_GBP  124902 non-null  float64
dtypes: float64(1)
memory usage: 2.1+ MB
812
125990
After dropna size is:
44194
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 169096 entries, ('GB09567757', 2019) to ('GBOC381395', 2016)
Data columns (total 1 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Operating_Profit_th_GBP  169096 non-null  float64
dtypes: float64(1)
memory usage: 2.8+ MB
813
125990
After dropna size is:
36301
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 205397 entries, ('GB09567757', 2019) to ('GBSC452461', 2015)
Data columns (total 1 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Operating_Profit_th_GBP  205397 non-null  float64
dtypes: float64(1)
memory usage: 3.3+ MB
814
125990
After dropna size is:
30904
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 236301 entries, ('GB09567757', 2019) to ('GBOC369696', 2014)
Data columns (total 1 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Operating_Profit_th_GBP  236301 non-null  float64
dtypes: float64(1)
memory usage: 3.7+ MB
815
125990
After dropna size is:
26539
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 262840 entries, ('GB09567757', 2019) to ('GBOC369696', 2013)
Data columns (total 1 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Operating_Profit_th_GBP  262840 non-null  float64
dtypes: float64(1)
memory usage: 4.1+ MB
816
125990
After dropna size is:
19955
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 282795 entries, ('GB09567757', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Operating_Profit_th_GBP  282795 non-null  float64
dtypes: float64(1)
memory usage: 4.4+ MB
817
125990
After dropna size is:
10660
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 293455 entries, ('GB09567757', 2019) to ('GB07266603', 2011)
Data columns (total 1 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Operating_Profit_th_GBP  293455 non-null  float64
dtypes: float64(1)
memory usage: 4.6+ MB
818
125990
After dropna size is:
1078
819
125990
After dropna size is:
3157
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 4235 entries, ('GB08287986', 2019) to ('GBSC452461', 2018)
Data columns (total 1 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Other_Income_th_GBP  4235 non-null   float64
dtypes: float64(1)
memory usage: 74.9+ KB
820
125990
After dropna size is:
3497
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 7732 entries, ('GB08287986', 2019) to ('GBSC452461', 2017)
Data columns (total 1 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Other_Income_th_GBP  7732 non-null   float64
dtypes: float64(1)
memory usage: 125.1+ KB
821
125990
After dropna size is:
3252
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 10984 entries, ('GB08287986', 2019) to ('GBSC452461', 2016)
Data columns (total 1 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Other_Income_th_GBP  10984 non-null  float64
dtypes: float64(1)
memory usage: 169.3+ KB
822
125990
After dropna size is:
2645
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 13629 entries, ('GB08287986', 2019) to ('GBSC452461', 2015)
Data columns (total 1 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Other_Income_th_GBP  13629 non-null  float64
dtypes: float64(1)
memory usage: 204.2+ KB
823
125990
After dropna size is:
1944
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 15573 entries, ('GB08287986', 2019) to ('GBOC369696', 2014)
Data columns (total 1 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Other_Income_th_GBP  15573 non-null  float64
dtypes: float64(1)
memory usage: 229.7+ KB
824
125990
After dropna size is:
1525
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 17098 entries, ('GB08287986', 2019) to ('GBOC369696', 2013)
Data columns (total 1 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Other_Income_th_GBP  17098 non-null  float64
dtypes: float64(1)
memory usage: 249.9+ KB
825
125990
After dropna size is:
1030
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 18128 entries, ('GB08287986', 2019) to ('IE499628', 2012)
Data columns (total 1 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Other_Income_th_GBP  18128 non-null  float64
dtypes: float64(1)
memory usage: 263.5+ KB
826
125990
After dropna size is:
529

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 18657 entries, ('GB08287986', 2019) to ('GB07341487', 2011)
Data columns (total 1 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Other_Income_th_GBP  18657 non-null  float64
dtypes: float64(1)
memory usage: 270.4+ KB
827
125990
After dropna size is:
3220
828
125990
After dropna size is:
8190
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 11410 entries, ('GB10561617', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Total_Other_Income_&_Int._Received_th_GBP  11410 non-null  float64
dtypes: float64(1)
memory usage: 196.2+ KB
829
125990
After dropna size is:
9484
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 20894 entries, ('GB10561617', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Total_Other_Income_&_Int._Received_th_GBP  20894 non-null  float64
dtypes: float64(1)
memory usage: 330.9+ KB
830
125990
After dropna size is:
8952
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 29846 entries, ('GB10561617', 2019) to ('GBOC381395', 2016)
Data columns (total 1 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Total_Other_Income_&_Int._Received_th_GBP  29846 non-null  float64
dtypes: float64(1)
memory usage: 455.3+ KB
831
125990
After dropna size is:
7854
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 37700 entries, ('GB10561617', 2019) to ('GBSC452461', 2015)
Data columns (total 1 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Total_Other_Income_&_Int._Received_th_GBP  37700 non-null  float64
dtypes: float64(1)
memory usage: 562.0+ KB
832
125990
After dropna size is:
6424
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 44124 entries, ('GB10561617', 2019) to ('GBOC369696', 2014)
Data columns (total 1 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Total_Other_Income_&_Int._Received_th_GBP  44124 non-null  float64
dtypes: float64(1)
memory usage: 648.0+ KB
833
125990
After dropna size is:
5263
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 49387 entries, ('GB10561617', 2019) to ('GBOC369696', 2013)
Data columns (total 1 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Total_Other_Income_&_Int._Received_th_GBP  49387 non-null  float64
dtypes: float64(1)
memory usage: 719.4+ KB
834
125990
After dropna size is:
3623
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 53010 entries, ('GB10561617', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Total_Other_Income_&_Int._Received_th_GBP  53010 non-null  float64
dtypes: float64(1)
memory usage: 767.6+ KB
835
125990
After dropna size is:
1679
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 54689 entries, ('GB10561617', 2019) to ('GB07341487', 2011)
Data columns (total 1 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Total_Other_Income_&_Int._Received_th_GBP  54689 non-null  float64
dtypes: float64(1)
memory usage: 789.5+ KB
836
125990
After dropna size is:
74
837
125990
After dropna size is:
148
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 222 entries, ('GB07329166', 2019) to ('IE584857', 2018)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Exceptional_Items_th_GBP  222 non-null    float64
dtypes: float64(1)
memory usage: 4.2+ KB
838
125990

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Total_Other_Income_&_Int._Received_th_GBP'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

After dropna size is:
229
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 451 entries, ('GB07329166', 2019) to ('GB07328077', 2017)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Exceptional_Items_th_GBP  451 non-null    float64
dtypes: float64(1)
memory usage: 8.3+ KB
839
125990
After dropna size is:
247
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 698 entries, ('GB07329166', 2019) to ('IE533235', 2016)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Exceptional_Items_th_GBP  698 non-null    float64
dtypes: float64(1)
memory usage: 12.5+ KB
840
125990
After dropna size is:
230
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 928 entries, ('GB07329166', 2019) to ('GB08512254', 2015)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Exceptional_Items_th_GBP  928 non-null    float64
dtypes: float64(1)
memory usage: 16.5+ KB
841
125990
After dropna size is:
336
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1264 entries, ('GB07329166', 2019) to ('GB07767724', 2014)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Exceptional_Items_th_GBP  1264 non-null   float64
dtypes: float64(1)
memory usage: 22.1+ KB
842
125990
After dropna size is:
161
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1425 entries, ('GB07329166', 2019) to ('GB07923211', 2013)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Exceptional_Items_th_GBP  1425 non-null   float64
dtypes: float64(1)
memory usage: 24.7+ KB
843
125990
After dropna size is:
110
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1535 entries, ('GB07329166', 2019) to ('GB07550669', 2012)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Exceptional_Items_th_GBP  1535 non-null   float64
dtypes: float64(1)
memory usage: 26.4+ KB
844
125990
After dropna size is:
54
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1589 entries, ('GB07329166', 2019) to ('GB07254414', 2011)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Exceptional_Items_th_GBP  1589 non-null   float64
dtypes: float64(1)
memory usage: 27.2+ KB
845
125990
After dropna size is:
0
846
125990
After dropna size is:
0
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 0 entries
Data columns (total 1 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Profit_(Loss)_on_Sale_of_Operations_th_GBP  0 non-null      float64
dtypes: float64(1)
memory usage: 151.0 bytes
847
125990
After dropna size is:
0
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 0 entries
Data columns (total 1 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Profit_(Loss)_on_Sale_of_Operations_th_GBP  0 non-null      float64
dtypes: float64(1)
memory usage: 151.0 bytes
848
125990
After dropna size is:
0
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 0 entries
Data columns (total 1 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Profit_(Loss)_on_Sale_of_Operations_th_GBP  0 non-null      float64
dtypes: float64(1)
memory usage: 151.0 bytes
849
125990
After dropna size is:
0
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 0 entries
Data columns (total 1 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Profit_(Loss)_on_Sale_of_Operations_th_GBP  0 non-null      float64
dtypes: float64(1)
memory usage: 151.0 bytes
850
125990
After dropna size is:
0
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 0 entries
Data columns (total 1 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Profit_(Loss)_on_Sale_of_Operations_th_GBP  0 non-null      float64
dtypes: float64(1)
memory usage: 151.0 bytes
851
125990
After dropna size is:
0
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 0 entries
Data columns (total 1 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Profit_(Loss)_on_Sale_of_Operations_th_GBP  0 non-null      float64
dtypes: float64(1)
memory usage: 151.0 bytes
852
125990
After dropna size is:
0
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 0 entries
Data columns (total 1 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Profit_(Loss)_on_Sale_of_Operations_th_GBP  0 non-null      float64
dtypes: float64(1)
memory usage: 151.0 bytes
853
125990
After dropna size is:
0
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 0 entries
Data columns (total 1 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Profit_(Loss)_on_Sale_of_Operations_th_GBP  0 non-null      float64
dtypes: float64(1)
memory usage: 151.0 bytes
854
125990
After dropna size is:
0
855
125990
After dropna size is:
2
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 2 entries, ('GB08137567', 2018) to ('GB07657544', 2018)
Data columns (total 1 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Costs_of_Reorganisation_th_GBP  2 non-null      float64
dtypes: float64(1)
memory usage: 195.0+ bytes
856
125990
After dropna size is:
6
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 8 entries, ('GB08137567', 2018) to ('GB09768530', 2017)
Data columns (total 1 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Costs_of_Reorganisation_th_GBP  8 non-null      float64
dtypes: float64(1)
memory usage: 311.0+ bytes
857
125990
After dropna size is:
8
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 16 entries, ('GB08137567', 2018) to ('GB08556186', 2016)
Data columns (total 1 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Costs_of_Reorganisation_th_GBP  16 non-null     float64
dtypes: float64(1)
memory usage: 463.0+ bytes
858
125990
After dropna size is:
5
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 21 entries, ('GB08137567', 2018) to ('GB07336661', 2015)
Data columns (total 1 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Costs_of_Reorganisation_th_GBP  21 non-null     float64
dtypes: float64(1)
memory usage: 561.0+ bytes
859
125990
After dropna size is:
0
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 21 entries, ('GB08137567', 2018) to ('GB07336661', 2015)
Data columns (total 1 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Costs_of_Reorganisation_th_GBP  21 non-null     float64
dtypes: float64(1)
memory usage: 561.0+ bytes
860
125990
After dropna size is:
2
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 23 entries, ('GB08137567', 2018) to ('GB08058714', 2013)
Data columns (total 1 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Costs_of_Reorganisation_th_GBP  23 non-null     float64
dtypes: float64(1)
memory usage: 605.0+ bytes
861
125990
After dropna size is:
4
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 27 entries, ('GB08137567', 2018) to ('GB07705030', 2012)
Data columns (total 1 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Costs_of_Reorganisation_th_GBP  27 non-null     float64
dtypes: float64(1)
memory usage: 685.0+ bytes
862
125990
After dropna size is:
1
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 28 entries, ('GB08137567', 2018) to ('GB07151588', 2011)
Data columns (total 1 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Costs_of_Reorganisation_th_GBP  28 non-null     float64
dtypes: float64(1)
memory usage: 711.0+ bytes
863
125990
After dropna size is:
28

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Profit_(Loss)_on_Sale_of_Operations_th_GBP'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

864
125990
After dropna size is:
66
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 94 entries, ('GB08013316', 2019) to ('IE584857', 2018)
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Profit_(Loss)_on_Disposal_th_GBP  94 non-null     float64
dtypes: float64(1)
memory usage: 1.8+ KB
865
125990
After dropna size is:
115
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 209 entries, ('GB08013316', 2019) to ('GB07328077', 2017)
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Profit_(Loss)_on_Disposal_th_GBP  209 non-null    float64
dtypes: float64(1)
memory usage: 4.0+ KB
866
125990
After dropna size is:
125
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 334 entries, ('GB08013316', 2019) to ('GB08847212', 2016)
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Profit_(Loss)_on_Disposal_th_GBP  334 non-null    float64
dtypes: float64(1)
memory usage: 6.2+ KB
867
125990
After dropna size is:
98
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 432 entries, ('GB08013316', 2019) to ('GB08512254', 2015)
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Profit_(Loss)_on_Disposal_th_GBP  432 non-null    float64
dtypes: float64(1)
memory usage: 7.9+ KB
868
125990
After dropna size is:
208
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 640 entries, ('GB08013316', 2019) to ('GB07253498', 2014)
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Profit_(Loss)_on_Disposal_th_GBP  640 non-null    float64
dtypes: float64(1)
memory usage: 11.4+ KB
869
125990
After dropna size is:
66
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 706 entries, ('GB08013316', 2019) to ('GB07173866', 2013)
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Profit_(Loss)_on_Disposal_th_GBP  706 non-null    float64
dtypes: float64(1)
memory usage: 12.4+ KB
870
125990
After dropna size is:
48
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 754 entries, ('GB08013316', 2019) to ('GB07550669', 2012)
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Profit_(Loss)_on_Disposal_th_GBP  754 non-null    float64
dtypes: float64(1)
memory usage: 13.2+ KB
871
125990
After dropna size is:
24
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 778 entries, ('GB08013316', 2019) to ('GB07254414', 2011)
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Profit_(Loss)_on_Disposal_th_GBP  778 non-null    float64
dtypes: float64(1)
memory usage: 13.6+ KB
872
125990
After dropna size is:
46
873
125990
After dropna size is:
85
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 131 entries, ('GB07329166', 2019) to ('GB07482335', 2018)
Data columns (total 1 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Other_Exceptional_Items_th_GBP  131 non-null    float64
dtypes: float64(1)
memory usage: 2.4+ KB
874
125990
After dropna size is:
118
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 249 entries, ('GB07329166', 2019) to ('GB09768530', 2017)
Data columns (total 1 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Other_Exceptional_Items_th_GBP  249 non-null    float64
dtypes: float64(1)
memory usage: 4.6+ KB
875

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Profit_(Loss)_on_Disposal_th_GBP'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

125990
After dropna size is:
134
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 383 entries, ('GB07329166', 2019) to ('IE533235', 2016)
Data columns (total 1 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Other_Exceptional_Items_th_GBP  383 non-null    float64
dtypes: float64(1)
memory usage: 7.0+ KB
876
125990
After dropna size is:
132
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 515 entries, ('GB07329166', 2019) to ('GB07577634', 2015)
Data columns (total 1 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Other_Exceptional_Items_th_GBP  515 non-null    float64
dtypes: float64(1)
memory usage: 9.3+ KB
877
125990
After dropna size is:
128
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 643 entries, ('GB07329166', 2019) to ('GB07767724', 2014)
Data columns (total 1 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Other_Exceptional_Items_th_GBP  643 non-null    float64
dtypes: float64(1)
memory usage: 11.5+ KB
878
125990
After dropna size is:
98
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 741 entries, ('GB07329166', 2019) to ('GB07923211', 2013)
Data columns (total 1 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Other_Exceptional_Items_th_GBP  741 non-null    float64
dtypes: float64(1)
memory usage: 13.1+ KB
879
125990
After dropna size is:
65
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 806 entries, ('GB07329166', 2019) to ('GB07576869', 2012)
Data columns (total 1 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Other_Exceptional_Items_th_GBP  806 non-null    float64
dtypes: float64(1)
memory usage: 14.1+ KB
880
125990
After dropna size is:
31
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 837 entries, ('GB07329166', 2019) to ('GB07158038', 2011)
Data columns (total 1 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Other_Exceptional_Items_th_GBP  837 non-null    float64
dtypes: float64(1)
memory usage: 14.6+ KB
881
125990
After dropna size is:
23128
882
125990
After dropna size is:
45866
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 68994 entries, ('GB09567757', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Profit_(Loss)_before_Interest_paid_th_GBP  68994 non-null  float64
dtypes: float64(1)
memory usage: 1.3+ MB
883
125990
After dropna size is:
55054
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 124048 entries, ('GB09567757', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column                                     Non-Null Count   Dtype
---  ------                                     --------------   -----
 0   Profit_(Loss)_before_Interest_paid_th_GBP  124048 non-null  float64
dtypes: float64(1)
memory usage: 2.1+ MB
884
125990
After dropna size is:
43788
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 167836 entries, ('GB09567757', 2019) to ('GBOC381395', 2016)
Data columns (total 1 columns):
 #   Column                                     Non-Null Count   Dtype
---  ------                                     --------------   -----
 0   Profit_(Loss)_before_Interest_paid_th_GBP  167836 non-null  float64
dtypes: float64(1)
memory usage: 2.7+ MB
885
125990
After dropna size is:
35905
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 203741 entries, ('GB09567757', 2019) to ('GBSC452461', 2015)
Data columns (total 1 columns):
 #   Column                                     Non-Null Count   Dtype
---  ------                                     --------------   -----
 0   Profit_(Loss)_before_Interest_paid_th_GBP  203741 non-null  float64
dtypes: float64(1)
memory usage: 3.3+ MB
886
125990
After dropna size is:
30597
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 234338 entries, ('GB09567757', 2019) to ('GBOC369696', 2014)
Data columns (total 1 columns):
 #   Column                                     Non-Null Count   Dtype
---  ------                                     --------------   -----
 0   Profit_(Loss)_before_Interest_paid_th_GBP  234338 non-null  float64
dtypes: float64(1)
memory usage: 3.7+ MB
887
125990
After dropna size is:
26309
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 260647 entries, ('GB09567757', 2019) to ('GBOC369696', 2013)
Data columns (total 1 columns):
 #   Column                                     Non-Null Count   Dtype
---  ------                                     --------------   -----
 0   Profit_(Loss)_before_Interest_paid_th_GBP  260647 non-null  float64
dtypes: float64(1)
memory usage: 4.1+ MB
888
125990
After dropna size is:
19783
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 280430 entries, ('GB09567757', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column                                     Non-Null Count   Dtype
---  ------                                     --------------   -----
 0   Profit_(Loss)_before_Interest_paid_th_GBP  280430 non-null  float64
dtypes: float64(1)
memory usage: 4.4+ MB
889
125990
After dropna size is:
10563
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 290993 entries, ('GB09567757', 2019) to ('GB07266603', 2011)
Data columns (total 1 columns):
 #   Column                                     Non-Null Count   Dtype
---  ------                                     --------------   -----
 0   Profit_(Loss)_before_Interest_paid_th_GBP  290993 non-null  float64
dtypes: float64(1)
memory usage: 4.5+ MB
890
125990
After dropna size is:
2434
891
125990

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Profit_(Loss)_before_Interest_paid_th_GBP'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

After dropna size is:
6223
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 8657 entries, ('GB10561617', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Interest_Received_th_GBP  8657 non-null   float64
dtypes: float64(1)
memory usage: 148.8+ KB
892
125990
After dropna size is:
7214
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 15871 entries, ('GB10561617', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Interest_Received_th_GBP  15871 non-null  float64
dtypes: float64(1)
memory usage: 252.3+ KB
893
125990
After dropna size is:
6863
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 22734 entries, ('GB10561617', 2019) to ('GBOC381395', 2016)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Interest_Received_th_GBP  22734 non-null  float64
dtypes: float64(1)
memory usage: 349.5+ KB
894
125990
After dropna size is:
6162
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 28896 entries, ('GB10561617', 2019) to ('GB09061578', 2015)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Interest_Received_th_GBP  28896 non-null  float64
dtypes: float64(1)
memory usage: 435.1+ KB
895
125990
After dropna size is:
5148
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 34044 entries, ('GB10561617', 2019) to ('GB08058491', 2014)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Interest_Received_th_GBP  34044 non-null  float64
dtypes: float64(1)
memory usage: 504.9+ KB
896
125990
After dropna size is:
4234
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 38278 entries, ('GB10561617', 2019) to ('GB07266603', 2013)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Interest_Received_th_GBP  38278 non-null  float64
dtypes: float64(1)
memory usage: 563.5+ KB
897
125990
After dropna size is:
2899
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 41177 entries, ('GB10561617', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Interest_Received_th_GBP  41177 non-null  float64
dtypes: float64(1)
memory usage: 602.5+ KB
898
125990
After dropna size is:
1307
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 42484 entries, ('GB10561617', 2019) to ('GB07341487', 2011)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Interest_Received_th_GBP  42484 non-null  float64
dtypes: float64(1)
memory usage: 619.8+ KB
899
125990
After dropna size is:
3647
900
125990
After dropna size is:
9782
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 13429 entries, ('GBOC361927', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Interest_Paid_th_GBP  13429 non-null  float64
dtypes: float64(1)
memory usage: 229.4+ KB
901
125990
After dropna size is:
10563
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 23992 entries, ('GBOC361927', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Interest_Paid_th_GBP  23992 non-null  float64
dtypes: float64(1)
memory usage: 370.4+ KB
902
125990
After dropna size is:
9718
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 33710 entries, ('GBOC361927', 2019) to ('GBSC452461', 2016)
Data columns (total 1 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Interest_Paid_th_GBP  33710 non-null  float64
dtypes: float64(1)
memory usage: 497.9+ KB
903
125990
After dropna size is:
7805
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 41515 entries, ('GBOC361927', 2019) to ('GBSC452461', 2015)
Data columns (total 1 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Interest_Paid_th_GBP  41515 non-null  float64
dtypes: float64(1)
memory usage: 600.0+ KB
904
125990
After dropna size is:
6369
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 47884 entries, ('GBOC361927', 2019) to ('GB08058491', 2014)
Data columns (total 1 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Interest_Paid_th_GBP  47884 non-null  float64
dtypes: float64(1)
memory usage: 682.7+ KB
905
125990
After dropna size is:
5006
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 52890 entries, ('GBOC361927', 2019) to ('GB08058491', 2013)
Data columns (total 1 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Interest_Paid_th_GBP  52890 non-null  float64
dtypes: float64(1)
memory usage: 748.9+ KB
906
125990
After dropna size is:
3534
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 56424 entries, ('GBOC361927', 2019) to ('GB07937886', 2012)
Data columns (total 1 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Interest_Paid_th_GBP  56424 non-null  float64
dtypes: float64(1)
memory usage: 795.6+ KB
907
125990
After dropna size is:
1657
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 58081 entries, ('GBOC361927', 2019) to ('GB07258174', 2011)
Data columns (total 1 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Interest_Paid_th_GBP  58081 non-null  float64
dtypes: float64(1)
memory usage: 817.0+ KB
908
125990
After dropna size is:
587
909
125990
After dropna size is:
1794
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 2381 entries, ('GB10031844', 2019) to ('IE505067', 2018)
Data columns (total 1 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Paid_to_Bank_th_GBP  2381 non-null   float64
dtypes: float64(1)
memory usage: 41.6+ KB
910
125990
After dropna size is:
2042
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 4423 entries, ('GB10031844', 2019) to ('IE505067', 2017)
Data columns (total 1 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Paid_to_Bank_th_GBP  4423 non-null   float64
dtypes: float64(1)
memory usage: 70.7+ KB
911
125990
After dropna size is:
1968
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 6391 entries, ('GB10031844', 2019) to ('IE505067', 2016)
Data columns (total 1 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Paid_to_Bank_th_GBP  6391 non-null   float64
dtypes: float64(1)
memory usage: 98.2+ KB
912
125990
After dropna size is:
1714
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 8105 entries, ('GB10031844', 2019) to ('GBOC365323', 2015)
Data columns (total 1 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Paid_to_Bank_th_GBP  8105 non-null   float64
dtypes: float64(1)
memory usage: 121.7+ KB
913
125990
After dropna size is:
1361
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 9466 entries, ('GB10031844', 2019) to ('GB07937886', 2014)
Data columns (total 1 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Paid_to_Bank_th_GBP  9466 non-null   float64
dtypes: float64(1)
memory usage: 140.1+ KB
914
125990
After dropna size is:
1041
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 10507 entries, ('GB10031844', 2019) to ('GB07418349', 2013)
Data columns (total 1 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Paid_to_Bank_th_GBP  10507 non-null  float64
dtypes: float64(1)
memory usage: 153.9+ KB
915
125990
After dropna size is:
795
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 11302 entries, ('GB10031844', 2019) to ('GB07418349', 2012)
Data columns (total 1 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Paid_to_Bank_th_GBP  11302 non-null  float64
dtypes: float64(1)
memory usage: 164.5+ KB
916
125990
After dropna size is:
404
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 11706 entries, ('GB10031844', 2019) to ('GB07418349', 2011)
Data columns (total 1 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Paid_to_Bank_th_GBP  11706 non-null  float64
dtypes: float64(1)
memory usage: 169.9+ KB
917
125990
After dropna size is:
136
918
125990
After dropna size is:
445
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 581 entries, ('GB07274484', 2019) to ('GB09214380', 2018)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Paid_on_Hire_Purchase_th_GBP  581 non-null    float64
dtypes: float64(1)
memory usage: 10.4+ KB
919
125990
After dropna size is:
417
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 998 entries, ('GB07274484', 2019) to ('GB08061053', 2017)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Paid_on_Hire_Purchase_th_GBP  998 non-null    float64
dtypes: float64(1)
memory usage: 16.8+ KB
920
125990
After dropna size is:
393
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1391 entries, ('GB07274484', 2019) to ('GB08727343', 2016)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Paid_on_Hire_Purchase_th_GBP  1391 non-null   float64
dtypes: float64(1)
memory usage: 22.6+ KB
921
125990
After dropna size is:
324
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1715 entries, ('GB07274484', 2019) to ('GBOC365323', 2015)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Paid_on_Hire_Purchase_th_GBP  1715 non-null   float64
dtypes: float64(1)
memory usage: 27.3+ KB
922
125990
After dropna size is:
202

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1917 entries, ('GB07274484', 2019) to ('GB07841692', 2014)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Paid_on_Hire_Purchase_th_GBP  1917 non-null   float64
dtypes: float64(1)
memory usage: 30.2+ KB
923
125990
After dropna size is:
148
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 2065 entries, ('GB07274484', 2019) to ('GB07166793', 2013)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Paid_on_Hire_Purchase_th_GBP  2065 non-null   float64
dtypes: float64(1)
memory usage: 32.3+ KB
924
125990
After dropna size is:
98
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 2163 entries, ('GB07274484', 2019) to ('GB07173866', 2012)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Paid_on_Hire_Purchase_th_GBP  2163 non-null   float64
dtypes: float64(1)
memory usage: 33.7+ KB
925
125990
After dropna size is:
43
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 2206 entries, ('GB07274484', 2019) to ('GB07262386', 2011)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Paid_on_Hire_Purchase_th_GBP  2206 non-null   float64
dtypes: float64(1)
memory usage: 34.3+ KB
926
125990
After dropna size is:
18
927
125990
After dropna size is:
56
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 74 entries, ('IE547351', 2019) to ('IE484296', 2018)
Data columns (total 1 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Paid_on_Leasing_th_GBP  74 non-null     float64
dtypes: float64(1)
memory usage: 1.4+ KB
928
125990
After dropna size is:
70
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 144 entries, ('IE547351', 2019) to ('IE522970', 2017)
Data columns (total 1 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Paid_on_Leasing_th_GBP  144 non-null    float64
dtypes: float64(1)
memory usage: 2.4+ KB
929
125990
After dropna size is:
79
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 223 entries, ('IE547351', 2019) to ('IE523698', 2016)
Data columns (total 1 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Paid_on_Leasing_th_GBP  223 non-null    float64
dtypes: float64(1)
memory usage: 3.7+ KB
930
125990
After dropna size is:
67
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 290 entries, ('IE547351', 2019) to ('GB07253970', 2015)
Data columns (total 1 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Paid_on_Leasing_th_GBP  290 non-null    float64
dtypes: float64(1)
memory usage: 4.7+ KB
931
125990
After dropna size is:
44
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 334 entries, ('IE547351', 2019) to ('GB07938569', 2014)
Data columns (total 1 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Paid_on_Leasing_th_GBP  334 non-null    float64
dtypes: float64(1)
memory usage: 5.3+ KB
932
125990
After dropna size is:
35
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 369 entries, ('IE547351', 2019) to ('IE484296', 2013)
Data columns (total 1 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Paid_on_Leasing_th_GBP  369 non-null    float64
dtypes: float64(1)
memory usage: 5.8+ KB
933
125990
After dropna size is:
21
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 390 entries, ('IE547351', 2019) to ('GB07253970', 2012)
Data columns (total 1 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Paid_on_Leasing_th_GBP  390 non-null    float64
dtypes: float64(1)
memory usage: 6.2+ KB
934
125990
After dropna size is:
10
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 400 entries, ('IE547351', 2019) to ('IE484296', 2011)
Data columns (total 1 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Paid_on_Leasing_th_GBP  400 non-null    float64
dtypes: float64(1)
memory usage: 6.3+ KB
935
125990
After dropna size is:
3171
936
125990
After dropna size is:
8300
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 11471 entries, ('GBOC361927', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Other_Interest_Paid_th_GBP  11471 non-null  float64
dtypes: float64(1)
memory usage: 196.7+ KB
937
125990
After dropna size is:
8912
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 20383 entries, ('GBOC361927', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Other_Interest_Paid_th_GBP  20383 non-null  float64
dtypes: float64(1)
memory usage: 317.7+ KB
938
125990
After dropna size is:
8203
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 28586 entries, ('GBOC361927', 2019) to ('GBSC452461', 2016)
Data columns (total 1 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Other_Interest_Paid_th_GBP  28586 non-null  float64
dtypes: float64(1)
memory usage: 426.8+ KB
939
125990
After dropna size is:
6497
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 35083 entries, ('GBOC361927', 2019) to ('GBSC452461', 2015)
Data columns (total 1 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Other_Interest_Paid_th_GBP  35083 non-null  float64
dtypes: float64(1)
memory usage: 513.1+ KB
940
125990
After dropna size is:
5404
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 40487 entries, ('GBOC361927', 2019) to ('GB08058491', 2014)
Data columns (total 1 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Other_Interest_Paid_th_GBP  40487 non-null  float64
dtypes: float64(1)
memory usage: 584.2+ KB
941
125990
After dropna size is:
4204
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 44691 entries, ('GBOC361927', 2019) to ('GB08058491', 2013)
Data columns (total 1 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Other_Interest_Paid_th_GBP  44691 non-null  float64
dtypes: float64(1)
memory usage: 640.3+ KB
942
125990
After dropna size is:
2922
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 47613 entries, ('GBOC361927', 2019) to ('GB07937886', 2012)
Data columns (total 1 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Other_Interest_Paid_th_GBP  47613 non-null  float64
dtypes: float64(1)
memory usage: 679.4+ KB
943
125990
After dropna size is:
1321
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 48934 entries, ('GBOC361927', 2019) to ('GB07258174', 2011)
Data columns (total 1 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Other_Interest_Paid_th_GBP  48934 non-null  float64
dtypes: float64(1)
memory usage: 696.6+ KB
944
125990
After dropna size is:
4690
945
125990
After dropna size is:
11523
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 16213 entries, ('GBOC361927', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Net_Interest_th_GBP  16213 non-null  float64
dtypes: float64(1)
memory usage: 275.7+ KB
946
125990
After dropna size is:
12984
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 29197 entries, ('GBOC361927', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Net_Interest_th_GBP  29197 non-null  float64
dtypes: float64(1)
memory usage: 453.0+ KB
947
125990
After dropna size is:
12171

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 41368 entries, ('GBOC361927', 2019) to ('GBOC381395', 2016)
Data columns (total 1 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Net_Interest_th_GBP  41368 non-null  float64
dtypes: float64(1)
memory usage: 618.7+ KB
948
125990
After dropna size is:
10424
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 51792 entries, ('GBOC361927', 2019) to ('GBSC452461', 2015)
Data columns (total 1 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Net_Interest_th_GBP  51792 non-null  float64
dtypes: float64(1)
memory usage: 758.6+ KB
949
125990
After dropna size is:
8678
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 60470 entries, ('GBOC361927', 2019) to ('GB08058491', 2014)
Data columns (total 1 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Net_Interest_th_GBP  60470 non-null  float64
dtypes: float64(1)
memory usage: 873.3+ KB
950
125990
After dropna size is:
7145
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 67615 entries, ('GBOC361927', 2019) to ('GB07266603', 2013)
Data columns (total 1 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Net_Interest_th_GBP  67615 non-null  float64
dtypes: float64(1)
memory usage: 969.5+ KB
951
125990
After dropna size is:
5009
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 72624 entries, ('GBOC361927', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Net_Interest_th_GBP  72624 non-null  float64
dtypes: float64(1)
memory usage: 1.0+ MB
952
125990
After dropna size is:
2305
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 74929 entries, ('GBOC361927', 2019) to ('GB07258174', 2011)
Data columns (total 1 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Net_Interest_th_GBP  74929 non-null  float64
dtypes: float64(1)
memory usage: 1.2+ MB
953
125990
After dropna size is:
22983
954
125990
After dropna size is:
45470
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 68453 entries, ('GB09567757', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Profit_(Loss)_before_Tax_th_GBP  68453 non-null  float64
dtypes: float64(1)
memory usage: 1.2+ MB
955
125990
After dropna size is:
54623
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 123076 entries, ('GB09567757', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   Profit_(Loss)_before_Tax_th_GBP  123076 non-null  float64
dtypes: float64(1)
memory usage: 2.1+ MB
956
125990
After dropna size is:
43364
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 166440 entries, ('GB09567757', 2019) to ('GBOC381395', 2016)
Data columns (total 1 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   Profit_(Loss)_before_Tax_th_GBP  166440 non-null  float64
dtypes: float64(1)
memory usage: 2.7+ MB
957
125990
After dropna size is:
35630
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 202070 entries, ('GB09567757', 2019) to ('GBSC452461', 2015)
Data columns (total 1 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   Profit_(Loss)_before_Tax_th_GBP  202070 non-null  float64
dtypes: float64(1)
memory usage: 3.2+ MB
958
125990
After dropna size is:
30353
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 232423 entries, ('GB09567757', 2019) to ('GBOC369696', 2014)
Data columns (total 1 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   Profit_(Loss)_before_Tax_th_GBP  232423 non-null  float64
dtypes: float64(1)
memory usage: 3.7+ MB
959
125990
After dropna size is:
26149
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 258572 entries, ('GB09567757', 2019) to ('GBOC369696', 2013)
Data columns (total 1 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   Profit_(Loss)_before_Tax_th_GBP  258572 non-null  float64
dtypes: float64(1)
memory usage: 4.1+ MB
960
125990
After dropna size is:
19654
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 278226 entries, ('GB09567757', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   Profit_(Loss)_before_Tax_th_GBP  278226 non-null  float64
dtypes: float64(1)
memory usage: 4.4+ MB
961
125990
After dropna size is:
10503
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 288729 entries, ('GB09567757', 2019) to ('GB07266603', 2011)
Data columns (total 1 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   Profit_(Loss)_before_Tax_th_GBP  288729 non-null  float64
dtypes: float64(1)
memory usage: 4.5+ MB
962
125990
After dropna size is:
9937
963
125990
After dropna size is:
21164

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Profit_(Loss)_before_Tax_th_GBP'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 31101 entries, ('GB07588867', 2019) to ('GBSC452461', 2018)
Data columns (total 1 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Taxation_th_GBP  31101 non-null  float64
dtypes: float64(1)
memory usage: 530.1+ KB
964
125990
After dropna size is:
26757
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 57858 entries, ('GB07588867', 2019) to ('GBSC452461', 2017)
Data columns (total 1 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Taxation_th_GBP  57858 non-null  float64
dtypes: float64(1)
memory usage: 1.0+ MB
965
125990
After dropna size is:
20626
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 78484 entries, ('GB07588867', 2019) to ('GBSC452461', 2016)
Data columns (total 1 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Taxation_th_GBP  78484 non-null  float64
dtypes: float64(1)
memory usage: 1.3+ MB
966
125990
After dropna size is:
16155
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 94639 entries, ('GB07588867', 2019) to ('GBSC452461', 2015)
Data columns (total 1 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Taxation_th_GBP  94639 non-null  float64
dtypes: float64(1)
memory usage: 1.6+ MB
967
125990
After dropna size is:
13733
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 108372 entries, ('GB07588867', 2019) to ('GB07361608', 2014)
Data columns (total 1 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Taxation_th_GBP  108372 non-null  float64
dtypes: float64(1)
memory usage: 1.8+ MB
968
125990
After dropna size is:
12313
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 120685 entries, ('GB07588867', 2019) to ('GB07266603', 2013)
Data columns (total 1 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Taxation_th_GBP  120685 non-null  float64
dtypes: float64(1)
memory usage: 2.0+ MB
969
125990
After dropna size is:
9241
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 129926 entries, ('GB07588867', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Taxation_th_GBP  129926 non-null  float64
dtypes: float64(1)
memory usage: 2.1+ MB
970
125990
After dropna size is:
4673
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 134599 entries, ('GB07588867', 2019) to ('GB07266603', 2011)
Data columns (total 1 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Taxation_th_GBP  134599 non-null  float64
dtypes: float64(1)
memory usage: 2.2+ MB
971
125990
After dropna size is:
23057
972
125990
After dropna size is:
45572
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 68629 entries, ('GB09567757', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Profit_(Loss)_after_Tax_th_GBP  68629 non-null  float64
dtypes: float64(1)
memory usage: 1.2+ MB
973
125990
After dropna size is:
54718
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 123347 entries, ('GB09567757', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   Profit_(Loss)_after_Tax_th_GBP  123347 non-null  float64
dtypes: float64(1)
memory usage: 2.1+ MB
974
125990
After dropna size is:
43439
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 166786 entries, ('GB09567757', 2019) to ('GBOC381395', 2016)
Data columns (total 1 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   Profit_(Loss)_after_Tax_th_GBP  166786 non-null  float64
dtypes: float64(1)
memory usage: 2.7+ MB
975
125990
After dropna size is:
35680
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 202466 entries, ('GB09567757', 2019) to ('GBSC452461', 2015)
Data columns (total 1 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   Profit_(Loss)_after_Tax_th_GBP  202466 non-null  float64
dtypes: float64(1)
memory usage: 3.3+ MB
976
125990
After dropna size is:
30405
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 232871 entries, ('GB09567757', 2019) to ('GBOC369696', 2014)
Data columns (total 1 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   Profit_(Loss)_after_Tax_th_GBP  232871 non-null  float64
dtypes: float64(1)
memory usage: 3.7+ MB
977
125990
After dropna size is:
26189
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 259060 entries, ('GB09567757', 2019) to ('GBOC369696', 2013)
Data columns (total 1 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   Profit_(Loss)_after_Tax_th_GBP  259060 non-null  float64
dtypes: float64(1)
memory usage: 4.1+ MB
978
125990
After dropna size is:
19679
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 278739 entries, ('GB09567757', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   Profit_(Loss)_after_Tax_th_GBP  278739 non-null  float64
dtypes: float64(1)
memory usage: 4.4+ MB
979
125990
After dropna size is:
10518
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 289257 entries, ('GB09567757', 2019) to ('GB07266603', 2011)
Data columns (total 1 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   Profit_(Loss)_after_Tax_th_GBP  289257 non-null  float64
dtypes: float64(1)
memory usage: 4.5+ MB
980
125990
After dropna size is:
14
981
125990
After dropna size is:
46

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Profit_(Loss)_after_Tax_th_GBP'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 60 entries, ('GB08863657', 2019) to ('GB07916193', 2018)
Data columns (total 1 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Extraordinary_Items_th_GBP  60 non-null     float64
dtypes: float64(1)
memory usage: 1.2+ KB
982
125990
After dropna size is:
63
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 123 entries, ('GB08863657', 2019) to ('GB07915581', 2017)
Data columns (total 1 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Extraordinary_Items_th_GBP  123 non-null    float64
dtypes: float64(1)
memory usage: 2.3+ KB
983
125990
After dropna size is:
129
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 252 entries, ('GB08863657', 2019) to ('IE549110', 2016)
Data columns (total 1 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Extraordinary_Items_th_GBP  252 non-null    float64
dtypes: float64(1)
memory usage: 4.7+ KB
984
125990
After dropna size is:
384
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 636 entries, ('GB08863657', 2019) to ('GB08487355', 2015)
Data columns (total 1 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Extraordinary_Items_th_GBP  636 non-null    float64
dtypes: float64(1)
memory usage: 11.6+ KB
985
125990
After dropna size is:
171
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 807 entries, ('GB08863657', 2019) to ('GB08228467', 2014)
Data columns (total 1 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Extraordinary_Items_th_GBP  807 non-null    float64
dtypes: float64(1)
memory usage: 14.6+ KB
986
125990
After dropna size is:
39
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 846 entries, ('GB08863657', 2019) to ('GB07781920', 2013)
Data columns (total 1 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Extraordinary_Items_th_GBP  846 non-null    float64
dtypes: float64(1)
memory usage: 15.3+ KB
987
125990
After dropna size is:
35
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 881 entries, ('GB08863657', 2019) to ('GB07241136', 2012)
Data columns (total 1 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Extraordinary_Items_th_GBP  881 non-null    float64
dtypes: float64(1)
memory usage: 15.8+ KB
988
125990
After dropna size is:
16
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 897 entries, ('GB08863657', 2019) to ('GB07241136', 2011)
Data columns (total 1 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Extraordinary_Items_th_GBP  897 non-null    float64
dtypes: float64(1)
memory usage: 16.0+ KB
989
125990
After dropna size is:
51
990
125990
After dropna size is:
123
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 174 entries, ('GB08863657', 2019) to ('GB07281277', 2018)
Data columns (total 1 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Minority_Interests_th_GBP  174 non-null    float64
dtypes: float64(1)
memory usage: 3.1+ KB
991
125990
After dropna size is:
124
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 298 entries, ('GB08863657', 2019) to ('GB10183367', 2017)
Data columns (total 1 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Minority_Interests_th_GBP  298 non-null    float64
dtypes: float64(1)
memory usage: 4.7+ KB
992
125990
After dropna size is:
132
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 430 entries, ('GB08863657', 2019) to ('GB07281277', 2016)
Data columns (total 1 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Minority_Interests_th_GBP  430 non-null    float64
dtypes: float64(1)
memory usage: 6.4+ KB
993
125990
After dropna size is:
139
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 569 entries, ('GB08863657', 2019) to ('GB07281277', 2015)
Data columns (total 1 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Minority_Interests_th_GBP  569 non-null    float64
dtypes: float64(1)
memory usage: 8.2+ KB
994
125990
After dropna size is:
102
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 671 entries, ('GB08863657', 2019) to ('GB07937886', 2014)
Data columns (total 1 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Minority_Interests_th_GBP  671 non-null    float64
dtypes: float64(1)
memory usage: 9.6+ KB
995
125990
After dropna size is:
77
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 748 entries, ('GB08863657', 2019) to ('GB07937886', 2013)
Data columns (total 1 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Minority_Interests_th_GBP  748 non-null    float64
dtypes: float64(1)
memory usage: 10.6+ KB
996
125990
After dropna size is:
54
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 802 entries, ('GB08863657', 2019) to ('GB07937886', 2012)
Data columns (total 1 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Minority_Interests_th_GBP  802 non-null    float64
dtypes: float64(1)
memory usage: 11.2+ KB
997
125990
After dropna size is:
20
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 822 entries, ('GB08863657', 2019) to ('GB07281277', 2011)
Data columns (total 1 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Minority_Interests_th_GBP  822 non-null    float64
dtypes: float64(1)
memory usage: 11.4+ KB
998
125990
After dropna size is:
22994
999
125990
After dropna size is:
45459
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 68453 entries, ('GB09567757', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Profit_(Loss)_for_period_[=Net_income]_th_GBP  68453 non-null  float64
dtypes: float64(1)
memory usage: 1.2+ MB
1000
125990
After dropna size is:
54579
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 123032 entries, ('GB09567757', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   Profit_(Loss)_for_period_[=Net_income]_th_GBP  123032 non-null  float64
dtypes: float64(1)
memory usage: 2.1+ MB
1001
125990
After dropna size is:
43310
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 166342 entries, ('GB09567757', 2019) to ('GBOC381395', 2016)
Data columns (total 1 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   Profit_(Loss)_for_period_[=Net_income]_th_GBP  166342 non-null  float64
dtypes: float64(1)
memory usage: 2.7+ MB
1002
125990
After dropna size is:
35538
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 201880 entries, ('GB09567757', 2019) to ('GBSC452461', 2015)
Data columns (total 1 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   Profit_(Loss)_for_period_[=Net_income]_th_GBP  201880 non-null  float64
dtypes: float64(1)
memory usage: 3.2+ MB
1003
125990
After dropna size is:
30312
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 232192 entries, ('GB09567757', 2019) to ('GBOC369696', 2014)
Data columns (total 1 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   Profit_(Loss)_for_period_[=Net_income]_th_GBP  232192 non-null  float64
dtypes: float64(1)
memory usage: 3.7+ MB
1004
125990
After dropna size is:
26127

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 258319 entries, ('GB09567757', 2019) to ('GBOC369696', 2013)
Data columns (total 1 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   Profit_(Loss)_for_period_[=Net_income]_th_GBP  258319 non-null  float64
dtypes: float64(1)
memory usage: 4.1+ MB
1005
125990
After dropna size is:
19631
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 277950 entries, ('GB09567757', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   Profit_(Loss)_for_period_[=Net_income]_th_GBP  277950 non-null  float64
dtypes: float64(1)
memory usage: 4.4+ MB
1006
125990
After dropna size is:
10498
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 288448 entries, ('GB09567757', 2019) to ('GB07266603', 2011)
Data columns (total 1 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   Profit_(Loss)_for_period_[=Net_income]_th_GBP  288448 non-null  float64
dtypes: float64(1)
memory usage: 4.5+ MB
1007
125990
After dropna size is:
22924

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Profit_(Loss)_for_period_[=Net_income]_th_GBP'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

1008
125990
After dropna size is:
45297
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 68221 entries, ('GB09567757', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Retained_Profit(Loss)_th_GBP  68221 non-null  float64
dtypes: float64(1)
memory usage: 1.2+ MB
1009
125990
After dropna size is:
54288
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 122509 entries, ('GB09567757', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Retained_Profit(Loss)_th_GBP  122509 non-null  float64
dtypes: float64(1)
memory usage: 2.1+ MB
1010
125990
After dropna size is:
42992
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 165501 entries, ('GB09567757', 2019) to ('GBOC381395', 2016)
Data columns (total 1 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Retained_Profit(Loss)_th_GBP  165501 non-null  float64
dtypes: float64(1)
memory usage: 2.7+ MB
1011
125990
After dropna size is:
35197
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 200698 entries, ('GB09567757', 2019) to ('GBSC452461', 2015)
Data columns (total 1 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Retained_Profit(Loss)_th_GBP  200698 non-null  float64
dtypes: float64(1)
memory usage: 3.2+ MB
1012
125990
After dropna size is:
29907
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 230605 entries, ('GB09567757', 2019) to ('GBOC369696', 2014)
Data columns (total 1 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Retained_Profit(Loss)_th_GBP  230605 non-null  float64
dtypes: float64(1)
memory usage: 3.7+ MB
1013
125990
After dropna size is:
25723
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 256328 entries, ('GB09567757', 2019) to ('GBOC369696', 2013)
Data columns (total 1 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Retained_Profit(Loss)_th_GBP  256328 non-null  float64
dtypes: float64(1)
memory usage: 4.0+ MB
1014
125990
After dropna size is:
19379
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 275707 entries, ('GB09567757', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Retained_Profit(Loss)_th_GBP  275707 non-null  float64
dtypes: float64(1)
memory usage: 4.3+ MB
1015
125990
After dropna size is:
10340
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 286047 entries, ('GB09567757', 2019) to ('GB07266603', 2011)
Data columns (total 1 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Retained_Profit(Loss)_th_GBP  286047 non-null  float64
dtypes: float64(1)
memory usage: 4.5+ MB
1016
125990
After dropna size is:
16997

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Retained_Profit(Loss)_th_GBP'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

1017
125990
After dropna size is:
31684
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 48681 entries, ('GB09567757', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Depreciation_th_GBP  48681 non-null  float64
dtypes: float64(1)
memory usage: 888.1+ KB
1018
125990
After dropna size is:
35650
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 84331 entries, ('GB09567757', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Depreciation_th_GBP  84331 non-null  float64
dtypes: float64(1)
memory usage: 1.4+ MB
1019
125990
After dropna size is:
40908
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 125239 entries, ('GB09567757', 2019) to ('GBOC365296', 2016)
Data columns (total 1 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Depreciation_th_GBP  125239 non-null  float64
dtypes: float64(1)
memory usage: 2.0+ MB
1020
125990
After dropna size is:
38938
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 164177 entries, ('GB09567757', 2019) to ('GBOC365296', 2015)
Data columns (total 1 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Depreciation_th_GBP  164177 non-null  float64
dtypes: float64(1)
memory usage: 2.5+ MB
1021
125990
After dropna size is:
33472
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 197649 entries, ('GB09567757', 2019) to ('GBOC365296', 2014)
Data columns (total 1 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Depreciation_th_GBP  197649 non-null  float64
dtypes: float64(1)
memory usage: 2.9+ MB
1022
125990
After dropna size is:
17916
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 215565 entries, ('GB09567757', 2019) to ('GB07266603', 2013)
Data columns (total 1 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Depreciation_th_GBP  215565 non-null  float64
dtypes: float64(1)
memory usage: 3.2+ MB
1023
125990
After dropna size is:
8684
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 224249 entries, ('GB09567757', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Depreciation_th_GBP  224249 non-null  float64
dtypes: float64(1)
memory usage: 3.3+ MB
1024
125990
After dropna size is:
4650
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 228899 entries, ('GB09567757', 2019) to ('GB07266603', 2011)
Data columns (total 1 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Depreciation_th_GBP  228899 non-null  float64
dtypes: float64(1)
memory usage: 3.3+ MB
1025
125990
After dropna size is:
1368
1026
125990
After dropna size is:
3182
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 4550 entries, ('GB08084263', 2019) to ('GB09691481', 2018)
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Depreciation_Owned_Assets_th_GBP  4550 non-null   float64
dtypes: float64(1)
memory usage: 79.3+ KB
1027
125990
After dropna size is:
3833
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 8383 entries, ('GB08084263', 2019) to ('GB09277371', 2017)
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Depreciation_Owned_Assets_th_GBP  8383 non-null   float64
dtypes: float64(1)
memory usage: 134.8+ KB
1028
125990
After dropna size is:
5227
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 13610 entries, ('GB08084263', 2019) to ('GB09277371', 2016)
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Depreciation_Owned_Assets_th_GBP  13610 non-null  float64
dtypes: float64(1)
memory usage: 215.0+ KB
1029
125990
After dropna size is:
6026
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 19636 entries, ('GB08084263', 2019) to ('GB09277371', 2015)
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Depreciation_Owned_Assets_th_GBP  19636 non-null  float64
dtypes: float64(1)
memory usage: 304.7+ KB
1030
125990
After dropna size is:
5950
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 25586 entries, ('GB08084263', 2019) to ('GB08058491', 2014)
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Depreciation_Owned_Assets_th_GBP  25586 non-null  float64
dtypes: float64(1)
memory usage: 389.4+ KB
1031
125990
After dropna size is:
5389
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 30975 entries, ('GB08084263', 2019) to ('GB07560895', 2013)
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Depreciation_Owned_Assets_th_GBP  30975 non-null  float64
dtypes: float64(1)
memory usage: 465.8+ KB
1032
125990
After dropna size is:
3856
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 34831 entries, ('GB08084263', 2019) to ('GB07560895', 2012)
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Depreciation_Owned_Assets_th_GBP  34831 non-null  float64
dtypes: float64(1)
memory usage: 519.8+ KB
1033
125990
After dropna size is:
1903
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 36734 entries, ('GB08084263', 2019) to ('GB07258174', 2011)
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Depreciation_Owned_Assets_th_GBP  36734 non-null  float64
dtypes: float64(1)
memory usage: 546.0+ KB
1034
125990
After dropna size is:
11622
1035
125990
After dropna size is:
14585
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 26207 entries, ('GB09567757', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Depreciation_Other_Assets_th_GBP  26207 non-null  float64
dtypes: float64(1)
memory usage: 447.8+ KB
1036
125990
After dropna size is:
17764
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 43971 entries, ('GB09567757', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Depreciation_Other_Assets_th_GBP  43971 non-null  float64
dtypes: float64(1)
memory usage: 701.5+ KB
1037
125990
After dropna size is:
12457
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 56428 entries, ('GB09567757', 2019) to ('GB09102173', 2016)
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Depreciation_Other_Assets_th_GBP  56428 non-null  float64
dtypes: float64(1)
memory usage: 986.6+ KB
1038
125990
After dropna size is:
8943
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 65371 entries, ('GB09567757', 2019) to ('GB08389817', 2015)
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Depreciation_Other_Assets_th_GBP  65371 non-null  float64
dtypes: float64(1)
memory usage: 1.1+ MB
1039
125990
After dropna size is:
7016
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 72387 entries, ('GB09567757', 2019) to ('GB08389817', 2014)
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Depreciation_Other_Assets_th_GBP  72387 non-null  float64
dtypes: float64(1)
memory usage: 1.2+ MB
1040
125990
After dropna size is:
5999
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 78386 entries, ('GB09567757', 2019) to ('GB07266603', 2013)
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Depreciation_Other_Assets_th_GBP  78386 non-null  float64
dtypes: float64(1)
memory usage: 1.3+ MB
1041
125990
After dropna size is:
4275

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 82661 entries, ('GB09567757', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Depreciation_Other_Assets_th_GBP  82661 non-null  float64
dtypes: float64(1)
memory usage: 1.4+ MB
1042
125990
After dropna size is:
2492
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 85153 entries, ('GB09567757', 2019) to ('GB07266603', 2011)
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Depreciation_Other_Assets_th_GBP  85153 non-null  float64
dtypes: float64(1)
memory usage: 1.4+ MB
1043
125990
After dropna size is:
20
1044
125990
After dropna size is:
87
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 107 entries, ('GBOC361003', 2019) to ('GB08441190', 2018)
Data columns (total 1 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Impairment_Tangibles_th_GBP  107 non-null    float64
dtypes: float64(1)
memory usage: 2.0+ KB
1045
125990
After dropna size is:
83
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 190 entries, ('GBOC361003', 2019) to ('GB08822132', 2017)
Data columns (total 1 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Impairment_Tangibles_th_GBP  190 non-null    float64
dtypes: float64(1)
memory usage: 3.6+ KB
1046
125990
After dropna size is:
68
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 258 entries, ('GBOC361003', 2019) to ('GB07166793', 2016)
Data columns (total 1 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Impairment_Tangibles_th_GBP  258 non-null    float64
dtypes: float64(1)
memory usage: 4.8+ KB
1047
125990
After dropna size is:
49
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 307 entries, ('GBOC361003', 2019) to ('GB08820673', 2015)
Data columns (total 1 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Impairment_Tangibles_th_GBP  307 non-null    float64
dtypes: float64(1)
memory usage: 5.6+ KB
1048
125990
After dropna size is:
47
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 354 entries, ('GBOC361003', 2019) to ('GB08512887', 2014)
Data columns (total 1 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Impairment_Tangibles_th_GBP  354 non-null    float64
dtypes: float64(1)
memory usage: 6.4+ KB
1049
125990
After dropna size is:
33
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 387 entries, ('GBOC361003', 2019) to ('GB07916193', 2013)
Data columns (total 1 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Impairment_Tangibles_th_GBP  387 non-null    float64
dtypes: float64(1)
memory usage: 7.0+ KB
1050
125990
After dropna size is:
14
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 401 entries, ('GBOC361003', 2019) to ('GBSC402873', 2012)
Data columns (total 1 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Impairment_Tangibles_th_GBP  401 non-null    float64
dtypes: float64(1)
memory usage: 7.2+ KB
1051
125990
After dropna size is:
5
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 406 entries, ('GBOC361003', 2019) to ('GB07271834', 2011)
Data columns (total 1 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Impairment_Tangibles_th_GBP  406 non-null    float64
dtypes: float64(1)
memory usage: 7.3+ KB
1052
125990
After dropna size is:
2928
1053
125990
After dropna size is:
8018
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 10946 entries, ('GB07565512', 2019) to ('GBSC452461', 2018)
Data columns (total 1 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Audit_Fee_th_GBP  10946 non-null  float64
dtypes: float64(1)
memory usage: 184.3+ KB
1054
125990
After dropna size is:
8694
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 19640 entries, ('GB07565512', 2019) to ('GBSC452461', 2017)
Data columns (total 1 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Audit_Fee_th_GBP  19640 non-null  float64
dtypes: float64(1)
memory usage: 291.2+ KB
1055
125990
After dropna size is:
9136
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 28776 entries, ('GB07565512', 2019) to ('GBSC452461', 2016)
Data columns (total 1 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Audit_Fee_th_GBP  28776 non-null  float64
dtypes: float64(1)
memory usage: 405.3+ KB
1056
125990
After dropna size is:
7865
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 36641 entries, ('GB07565512', 2019) to ('GBSC452461', 2015)
Data columns (total 1 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Audit_Fee_th_GBP  36641 non-null  float64
dtypes: float64(1)
memory usage: 500.6+ KB
1057
125990
After dropna size is:
6129
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 42770 entries, ('GB07565512', 2019) to ('GB09061578', 2014)
Data columns (total 1 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Audit_Fee_th_GBP  42770 non-null  float64
dtypes: float64(1)
memory usage: 573.4+ KB
1058
125990
After dropna size is:
4567
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 47337 entries, ('GB07565512', 2019) to ('GBOC369696', 2013)
Data columns (total 1 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Audit_Fee_th_GBP  47337 non-null  float64
dtypes: float64(1)
memory usage: 627.3+ KB
1059
125990
After dropna size is:
3169
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 50506 entries, ('GB07565512', 2019) to ('GB07937886', 2012)
Data columns (total 1 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Audit_Fee_th_GBP  50506 non-null  float64
dtypes: float64(1)
memory usage: 664.7+ KB
1060
125990
After dropna size is:
1563
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 52069 entries, ('GB07565512', 2019) to ('GB07339695', 2011)
Data columns (total 1 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Audit_Fee_th_GBP  52069 non-null  float64
dtypes: float64(1)
memory usage: 683.0+ KB
1061
125990
After dropna size is:
3139
1062
125990
After dropna size is:
7310
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 10449 entries, ('GB09488271', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Non-Audit_Fee_th_GBP  10449 non-null  float64
dtypes: float64(1)
memory usage: 177.1+ KB
1063
125990
After dropna size is:
10627
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 21076 entries, ('GB09488271', 2019) to ('GBSC452461', 2017)
Data columns (total 1 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Non-Audit_Fee_th_GBP  21076 non-null  float64
dtypes: float64(1)
memory usage: 335.1+ KB
1064
125990
After dropna size is:
9486
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 30562 entries, ('GB09488271', 2019) to ('GBSC452461', 2016)
Data columns (total 1 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Non-Audit_Fee_th_GBP  30562 non-null  float64
dtypes: float64(1)
memory usage: 471.0+ KB
1065
125990
After dropna size is:
7773
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 38335 entries, ('GB09488271', 2019) to ('GBSC452461', 2015)
Data columns (total 1 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Non-Audit_Fee_th_GBP  38335 non-null  float64
dtypes: float64(1)
memory usage: 578.2+ KB
1066
125990
After dropna size is:
6585

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 44920 entries, ('GB09488271', 2019) to ('GB08389817', 2014)
Data columns (total 1 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Non-Audit_Fee_th_GBP  44920 non-null  float64
dtypes: float64(1)
memory usage: 668.2+ KB
1067
125990
After dropna size is:
6014
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 50934 entries, ('GB09488271', 2019) to ('GB07266603', 2013)
Data columns (total 1 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Non-Audit_Fee_th_GBP  50934 non-null  float64
dtypes: float64(1)
memory usage: 754.8+ KB
1068
125990
After dropna size is:
4397
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 55331 entries, ('GB09488271', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Non-Audit_Fee_th_GBP  55331 non-null  float64
dtypes: float64(1)
memory usage: 816.1+ KB
1069
125990
After dropna size is:
2352
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 57683 entries, ('GB09488271', 2019) to ('GB07266603', 2011)
Data columns (total 1 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Non-Audit_Fee_th_GBP  57683 non-null  float64
dtypes: float64(1)
memory usage: 849.1+ KB
1070
125990
After dropna size is:
371
1071
125990
After dropna size is:
1018

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Non-Audit_Fee_th_GBP'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1389 entries, ('GB08572926', 2019) to ('GBSC452461', 2018)
Data columns (total 1 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Tax_Advice_th_GBP  1389 non-null   float64
dtypes: float64(1)
memory usage: 24.1+ KB
1072
125990
After dropna size is:
1310
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 2699 entries, ('GB08572926', 2019) to ('GBSC452461', 2017)
Data columns (total 1 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Tax_Advice_th_GBP  2699 non-null   float64
dtypes: float64(1)
memory usage: 43.2+ KB
1073
125990
After dropna size is:
1410
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 4109 entries, ('GB08572926', 2019) to ('GBSC452461', 2016)
Data columns (total 1 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Tax_Advice_th_GBP  4109 non-null   float64
dtypes: float64(1)
memory usage: 63.1+ KB
1074
125990
After dropna size is:
1018
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 5127 entries, ('GB08572926', 2019) to ('GBSC452461', 2015)
Data columns (total 1 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Tax_Advice_th_GBP  5127 non-null   float64
dtypes: float64(1)
memory usage: 76.6+ KB
1075
125990
After dropna size is:
671
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 5798 entries, ('GB08572926', 2019) to ('GB07805564', 2014)
Data columns (total 1 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Tax_Advice_th_GBP  5798 non-null   float64
dtypes: float64(1)
memory usage: 85.2+ KB
1076
125990
After dropna size is:
460
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 6258 entries, ('GB08572926', 2019) to ('GB08090929', 2013)
Data columns (total 1 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Tax_Advice_th_GBP  6258 non-null   float64
dtypes: float64(1)
memory usage: 91.2+ KB
1077
125990
After dropna size is:
339
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 6597 entries, ('GB08572926', 2019) to ('GB07258174', 2012)
Data columns (total 1 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Tax_Advice_th_GBP  6597 non-null   float64
dtypes: float64(1)
memory usage: 95.7+ KB
1078
125990
After dropna size is:
141
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 6738 entries, ('GB08572926', 2019) to ('GB07258174', 2011)
Data columns (total 1 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Tax_Advice_th_GBP  6738 non-null   float64
dtypes: float64(1)
memory usage: 97.4+ KB
1079
125990
After dropna size is:
2830
1080
125990
After dropna size is:
6054
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 8884 entries, ('GB09488271', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Non-Tax_Advisory_Services_th_GBP  8884 non-null   float64
dtypes: float64(1)
memory usage: 150.6+ KB
1081
125990
After dropna size is:
8945
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 17829 entries, ('GB09488271', 2019) to ('GB09564843', 2017)
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Non-Tax_Advisory_Services_th_GBP  17829 non-null  float64
dtypes: float64(1)
memory usage: 287.1+ KB
1082
125990
After dropna size is:
7856
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 25685 entries, ('GB09488271', 2019) to ('GB08389817', 2016)
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Non-Tax_Advisory_Services_th_GBP  25685 non-null  float64
dtypes: float64(1)
memory usage: 403.1+ KB
1083
125990
After dropna size is:
6466
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 32151 entries, ('GB09488271', 2019) to ('GB08389817', 2015)
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Non-Tax_Advisory_Services_th_GBP  32151 non-null  float64
dtypes: float64(1)
memory usage: 494.9+ KB
1084
125990
After dropna size is:
5663
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 37814 entries, ('GB09488271', 2019) to ('GB08389817', 2014)
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Non-Tax_Advisory_Services_th_GBP  37814 non-null  float64
dtypes: float64(1)
memory usage: 574.3+ KB
1085
125990
After dropna size is:
5363
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 43177 entries, ('GB09488271', 2019) to ('GB07266603', 2013)
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Non-Tax_Advisory_Services_th_GBP  43177 non-null  float64
dtypes: float64(1)
memory usage: 653.4+ KB
1086
125990
After dropna size is:
3918
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 47095 entries, ('GB09488271', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Non-Tax_Advisory_Services_th_GBP  47095 non-null  float64
dtypes: float64(1)
memory usage: 709.0+ KB
1087
125990
After dropna size is:
2162
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 49257 entries, ('GB09488271', 2019) to ('GB07266603', 2011)
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Non-Tax_Advisory_Services_th_GBP  49257 non-null  float64
dtypes: float64(1)
memory usage: 739.8+ KB
1088
125990
After dropna size is:
3
1089
125990
After dropna size is:
13
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 16 entries, ('GB07934312', 2019) to ('GB09825203', 2018)
Data columns (total 1 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Other_Auditors_Services_th_GBP  16 non-null     float64
dtypes: float64(1)
memory usage: 455.0+ bytes
1090
125990
After dropna size is:
7
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 23 entries, ('GB07934312', 2019) to ('GB10081843', 2017)
Data columns (total 1 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Other_Auditors_Services_th_GBP  23 non-null     float64
dtypes: float64(1)
memory usage: 589.0+ bytes
1091
125990
After dropna size is:
8
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 31 entries, ('GB07934312', 2019) to ('GB08763412', 2016)
Data columns (total 1 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Other_Auditors_Services_th_GBP  31 non-null     float64
dtypes: float64(1)
memory usage: 741.0+ bytes
1092
125990
After dropna size is:
3
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 34 entries, ('GB07934312', 2019) to ('GB08390016', 2015)
Data columns (total 1 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Other_Auditors_Services_th_GBP  34 non-null     float64
dtypes: float64(1)
memory usage: 803.0+ bytes
1093
125990
After dropna size is:
4
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 38 entries, ('GB07934312', 2019) to ('GB07123937', 2014)
Data columns (total 1 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Other_Auditors_Services_th_GBP  38 non-null     float64
dtypes: float64(1)
memory usage: 883.0+ bytes
1094
125990
After dropna size is:
1
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 39 entries, ('GB07934312', 2019) to ('GB08036939', 2013)
Data columns (total 1 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Other_Auditors_Services_th_GBP  39 non-null     float64
dtypes: float64(1)
memory usage: 909.0+ bytes
1095
125990
After dropna size is:
7
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 46 entries, ('GB07934312', 2019) to ('GB07880012', 2012)
Data columns (total 1 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Other_Auditors_Services_th_GBP  46 non-null     float64
dtypes: float64(1)
memory usage: 1.0+ KB
1096
125990
After dropna size is:
7
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 53 entries, ('GB07934312', 2019) to ('GB07354568', 2011)
Data columns (total 1 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Other_Auditors_Services_th_GBP  53 non-null     float64
dtypes: float64(1)
memory usage: 1.1+ KB
1097

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Non-Tax_Advisory_Services_th_GBP'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

125990
After dropna size is:
1
1098
125990
After dropna size is:
5
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 6 entries, ('GB09904856', 2019) to ('GB07757472', 2018)
Data columns (total 1 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Non-Audit_Fees_paid_to_Other_Auditors_th_GBP  6 non-null      float64
dtypes: float64(1)
memory usage: 275.0+ bytes
1099
125990
After dropna size is:
1
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 7 entries, ('GB09904856', 2019) to ('GB08991088', 2017)
Data columns (total 1 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Non-Audit_Fees_paid_to_Other_Auditors_th_GBP  7 non-null      float64
dtypes: float64(1)
memory usage: 301.0+ bytes
1100
125990
After dropna size is:
7
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 14 entries, ('GB09904856', 2019) to ('GB09823986', 2016)
Data columns (total 1 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Non-Audit_Fees_paid_to_Other_Auditors_th_GBP  14 non-null     float64
dtypes: float64(1)
memory usage: 435.0+ bytes
1101
125990
After dropna size is:
1
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 15 entries, ('GB09904856', 2019) to ('GB08211361', 2015)
Data columns (total 1 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Non-Audit_Fees_paid_to_Other_Auditors_th_GBP  15 non-null     float64
dtypes: float64(1)
memory usage: 461.0+ bytes
1102
125990
After dropna size is:
0
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 15 entries, ('GB09904856', 2019) to ('GB08211361', 2015)
Data columns (total 1 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Non-Audit_Fees_paid_to_Other_Auditors_th_GBP  15 non-null     float64
dtypes: float64(1)
memory usage: 461.0+ bytes
1103
125990
After dropna size is:
0
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 15 entries, ('GB09904856', 2019) to ('GB08211361', 2015)
Data columns (total 1 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Non-Audit_Fees_paid_to_Other_Auditors_th_GBP  15 non-null     float64
dtypes: float64(1)
memory usage: 461.0+ bytes
1104
125990
After dropna size is:
2
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 17 entries, ('GB09904856', 2019) to ('GB07393102', 2012)
Data columns (total 1 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Non-Audit_Fees_paid_to_Other_Auditors_th_GBP  17 non-null     float64
dtypes: float64(1)
memory usage: 497.0+ bytes
1105
125990
After dropna size is:
0
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 17 entries, ('GB09904856', 2019) to ('GB07393102', 2012)
Data columns (total 1 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Non-Audit_Fees_paid_to_Other_Auditors_th_GBP  17 non-null     float64
dtypes: float64(1)
memory usage: 497.0+ bytes
1106
125990
After dropna size is:
1774
1107
125990
After dropna size is:
4211

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Non-Audit_Fees_paid_to_Other_Auditors_th_GBP'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 5985 entries, ('GB08437560', 2019) to ('GB08368531', 2018)
Data columns (total 1 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Total_Amortization_and_Impairment_th_GBP  5985 non-null   float64
dtypes: float64(1)
memory usage: 99.9+ KB
1108
125990
After dropna size is:
4505
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 10490 entries, ('GB08437560', 2019) to ('GB08368531', 2017)
Data columns (total 1 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Total_Amortization_and_Impairment_th_GBP  10490 non-null  float64
dtypes: float64(1)
memory usage: 156.3+ KB
1109
125990
After dropna size is:
5025
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 15515 entries, ('GB08437560', 2019) to ('GB08368531', 2016)
Data columns (total 1 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Total_Amortization_and_Impairment_th_GBP  15515 non-null  float64
dtypes: float64(1)
memory usage: 221.4+ KB
1110
125990
After dropna size is:
4790
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 20305 entries, ('GB08437560', 2019) to ('GB08368531', 2015)
Data columns (total 1 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Total_Amortization_and_Impairment_th_GBP  20305 non-null  float64
dtypes: float64(1)
memory usage: 280.4+ KB
1111
125990
After dropna size is:
4094
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 24399 entries, ('GB08437560', 2019) to ('GB08368531', 2014)
Data columns (total 1 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Total_Amortization_and_Impairment_th_GBP  24399 non-null  float64
dtypes: float64(1)
memory usage: 328.8+ KB
1112
125990
After dropna size is:
2265
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 26664 entries, ('GB08437560', 2019) to ('GB07259438', 2013)
Data columns (total 1 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Total_Amortization_and_Impairment_th_GBP  26664 non-null  float64
dtypes: float64(1)
memory usage: 355.2+ KB
1113
125990
After dropna size is:
1181
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 27845 entries, ('GB08437560', 2019) to ('IE489225', 2012)
Data columns (total 1 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Total_Amortization_and_Impairment_th_GBP  27845 non-null  float64
dtypes: float64(1)
memory usage: 368.8+ KB
1114
125990
After dropna size is:
573
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 28418 entries, ('GB08437560', 2019) to ('GB07341487', 2011)
Data columns (total 1 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Total_Amortization_and_Impairment_th_GBP  28418 non-null  float64
dtypes: float64(1)
memory usage: 375.4+ KB
1115
125990
After dropna size is:
1316
1116
125990
After dropna size is:
2565
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 3881 entries, ('GB08443668', 2019) to ('GB08425566', 2018)
Data columns (total 1 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Amortisation_th_GBP  3881 non-null   float64
dtypes: float64(1)
memory usage: 66.7+ KB
1117
125990
After dropna size is:
2775
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 6656 entries, ('GB08443668', 2019) to ('GB08425566', 2017)
Data columns (total 1 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Amortisation_th_GBP  6656 non-null   float64
dtypes: float64(1)
memory usage: 103.2+ KB
1118
125990
After dropna size is:
2580
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 9236 entries, ('GB08443668', 2019) to ('GB07856960', 2016)
Data columns (total 1 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Amortisation_th_GBP  9236 non-null   float64
dtypes: float64(1)
memory usage: 136.9+ KB
1119
125990
After dropna size is:
2133
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 11369 entries, ('GB08443668', 2019) to ('GB07221004', 2015)
Data columns (total 1 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Amortisation_th_GBP  11369 non-null  float64
dtypes: float64(1)
memory usage: 164.5+ KB
1120
125990
After dropna size is:
1890
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 13259 entries, ('GB08443668', 2019) to ('GB07221004', 2014)
Data columns (total 1 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Amortisation_th_GBP  13259 non-null  float64
dtypes: float64(1)
memory usage: 189.0+ KB
1121
125990
After dropna size is:
1577
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 14836 entries, ('GB08443668', 2019) to ('GB07341487', 2013)
Data columns (total 1 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Amortisation_th_GBP  14836 non-null  float64
dtypes: float64(1)
memory usage: 209.6+ KB
1122
125990
After dropna size is:
1110
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 15946 entries, ('GB08443668', 2019) to ('GB07341487', 2012)
Data columns (total 1 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Amortisation_th_GBP  15946 non-null  float64
dtypes: float64(1)
memory usage: 223.8+ KB
1123
125990
After dropna size is:
542
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 16488 entries, ('GB08443668', 2019) to ('GB07341487', 2011)
Data columns (total 1 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Amortisation_th_GBP  16488 non-null  float64
dtypes: float64(1)
memory usage: 230.6+ KB
1124
125990
After dropna size is:
20
1125
125990
After dropna size is:
65
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 85 entries, ('GBNC001384', 2019) to ('GB08017765', 2018)
Data columns (total 1 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Impairment_th_GBP  85 non-null     float64
dtypes: float64(1)
memory usage: 1.6+ KB
1126
125990
After dropna size is:
69
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 154 entries, ('GBNC001384', 2019) to ('GB09178183', 2017)
Data columns (total 1 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Impairment_th_GBP  154 non-null    float64
dtypes: float64(1)
memory usage: 3.0+ KB
1127
125990
After dropna size is:
64
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 218 entries, ('GBNC001384', 2019) to ('GB07546217', 2016)
Data columns (total 1 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Impairment_th_GBP  218 non-null    float64
dtypes: float64(1)
memory usage: 4.1+ KB
1128
125990
After dropna size is:
57
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 275 entries, ('GBNC001384', 2019) to ('GB08497436', 2015)
Data columns (total 1 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Impairment_th_GBP  275 non-null    float64
dtypes: float64(1)
memory usage: 5.1+ KB
1129
125990
After dropna size is:
42
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 317 entries, ('GBNC001384', 2019) to ('GB08270236', 2014)
Data columns (total 1 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Impairment_th_GBP  317 non-null    float64
dtypes: float64(1)
memory usage: 5.8+ KB
1130
125990
After dropna size is:
47
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 364 entries, ('GBNC001384', 2019) to ('GB07482335', 2013)
Data columns (total 1 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Impairment_th_GBP  364 non-null    float64
dtypes: float64(1)
memory usage: 6.6+ KB
1131
125990
After dropna size is:
26
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 390 entries, ('GBNC001384', 2019) to ('GB07584111', 2012)
Data columns (total 1 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Impairment_th_GBP  390 non-null    float64
dtypes: float64(1)
memory usage: 7.0+ KB
1132
125990
After dropna size is:
8
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 398 entries, ('GBNC001384', 2019) to ('GB07254712', 2011)
Data columns (total 1 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Impairment_th_GBP  398 non-null    float64
dtypes: float64(1)
memory usage: 7.2+ KB
1133
125990
After dropna size is:
963
1134
125990
After dropna size is:
2599
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 3562 entries, ('GB07210644', 2019) to ('GB09102173', 2018)
Data columns (total 1 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Total_Operating_Lease_Rentals_th_GBP  3562 non-null   float64
dtypes: float64(1)
memory usage: 60.3+ KB
1135
125990
After dropna size is:
2896
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 6458 entries, ('GB07210644', 2019) to ('GB09102173', 2017)
Data columns (total 1 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Total_Operating_Lease_Rentals_th_GBP  6458 non-null   float64
dtypes: float64(1)
memory usage: 98.0+ KB
1136
125990
After dropna size is:
2859
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 9317 entries, ('GB07210644', 2019) to ('GB08008359', 2016)
Data columns (total 1 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Total_Operating_Lease_Rentals_th_GBP  9317 non-null   float64
dtypes: float64(1)
memory usage: 134.8+ KB
1137
125990
After dropna size is:
2243

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 11560 entries, ('GB07210644', 2019) to ('GB08008359', 2015)
Data columns (total 1 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Total_Operating_Lease_Rentals_th_GBP  11560 non-null  float64
dtypes: float64(1)
memory usage: 163.2+ KB
1138
125990
After dropna size is:
1729
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 13289 entries, ('GB07210644', 2019) to ('GB07122226', 2014)
Data columns (total 1 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Total_Operating_Lease_Rentals_th_GBP  13289 non-null  float64
dtypes: float64(1)
memory usage: 184.6+ KB
1139
125990
After dropna size is:
1147
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 14436 entries, ('GB07210644', 2019) to ('GB07937886', 2013)
Data columns (total 1 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Total_Operating_Lease_Rentals_th_GBP  14436 non-null  float64
dtypes: float64(1)
memory usage: 198.6+ KB
1140
125990
After dropna size is:
779
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 15215 entries, ('GB07210644', 2019) to ('GB07937886', 2012)
Data columns (total 1 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Total_Operating_Lease_Rentals_th_GBP  15215 non-null  float64
dtypes: float64(1)
memory usage: 208.1+ KB
1141
125990
After dropna size is:
385
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 15600 entries, ('GB07210644', 2019) to ('GB07239390', 2011)
Data columns (total 1 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Total_Operating_Lease_Rentals_th_GBP  15600 non-null  float64
dtypes: float64(1)
memory usage: 212.7+ KB
1142
125990
After dropna size is:
296
1143
125990
After dropna size is:
757
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1053 entries, ('GB08233527', 2019) to ('GB07373235', 2018)
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Hire_of_Plant_&_Machinery_th_GBP  1053 non-null   float64
dtypes: float64(1)
memory usage: 18.7+ KB
1144
125990
After dropna size is:
637
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1690 entries, ('GB08233527', 2019) to ('GB07705131', 2017)
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Hire_of_Plant_&_Machinery_th_GBP  1690 non-null   float64
dtypes: float64(1)
memory usage: 27.8+ KB
1145
125990
After dropna size is:
613
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 2303 entries, ('GB08233527', 2019) to ('GB07705131', 2016)
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Hire_of_Plant_&_Machinery_th_GBP  2303 non-null   float64
dtypes: float64(1)
memory usage: 36.6+ KB
1146
125990
After dropna size is:
577
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 2880 entries, ('GB08233527', 2019) to ('GB07618603', 2015)
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Hire_of_Plant_&_Machinery_th_GBP  2880 non-null   float64
dtypes: float64(1)
memory usage: 44.9+ KB
1147
125990
After dropna size is:
515
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 3395 entries, ('GB08233527', 2019) to ('GB07618603', 2014)
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Hire_of_Plant_&_Machinery_th_GBP  3395 non-null   float64
dtypes: float64(1)
memory usage: 51.9+ KB
1148
125990
After dropna size is:
381
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 3776 entries, ('GB08233527', 2019) to ('GB07618603', 2013)
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Hire_of_Plant_&_Machinery_th_GBP  3776 non-null   float64
dtypes: float64(1)
memory usage: 56.9+ KB
1149
125990
After dropna size is:
269
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 4045 entries, ('GB08233527', 2019) to ('GB07241041', 2012)
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Hire_of_Plant_&_Machinery_th_GBP  4045 non-null   float64
dtypes: float64(1)
memory usage: 60.4+ KB
1150
125990
After dropna size is:
141
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 4186 entries, ('GB08233527', 2019) to ('GB07232845', 2011)
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Hire_of_Plant_&_Machinery_th_GBP  4186 non-null   float64
dtypes: float64(1)
memory usage: 62.1+ KB
1151
125990
After dropna size is:
312
1152
125990
After dropna size is:
765
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1077 entries, ('GB10001725', 2019) to ('GB09102173', 2018)
Data columns (total 1 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   Land_&_Building_or_Property_Rents_&_Other_th_GBP  1077 non-null   float64
dtypes: float64(1)
memory usage: 18.8+ KB
1153
125990
After dropna size is:
826
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1903 entries, ('GB10001725', 2019) to ('GB08510540', 2017)
Data columns (total 1 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   Land_&_Building_or_Property_Rents_&_Other_th_GBP  1903 non-null   float64
dtypes: float64(1)
memory usage: 30.0+ KB
1154
125990
After dropna size is:
823
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 2726 entries, ('GB10001725', 2019) to ('GB08510540', 2016)
Data columns (total 1 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   Land_&_Building_or_Property_Rents_&_Other_th_GBP  2726 non-null   float64
dtypes: float64(1)
memory usage: 40.8+ KB
1155
125990
After dropna size is:
777

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Hire_of_Plant_&_Machinery_th_GBP'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)
/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Land_&_Building_or_Property_Rents_&_Other_th_GBP'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 3503 entries, ('GB10001725', 2019) to ('GB07634356', 2015)
Data columns (total 1 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   Land_&_Building_or_Property_Rents_&_Other_th_GBP  3503 non-null   float64
dtypes: float64(1)
memory usage: 51.2+ KB
1156
125990
After dropna size is:
670
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 4173 entries, ('GB10001725', 2019) to ('GB08495500', 2014)
Data columns (total 1 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   Land_&_Building_or_Property_Rents_&_Other_th_GBP  4173 non-null   float64
dtypes: float64(1)
memory usage: 59.8+ KB
1157
125990
After dropna size is:
498
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 4671 entries, ('GB10001725', 2019) to ('GB08495500', 2013)
Data columns (total 1 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   Land_&_Building_or_Property_Rents_&_Other_th_GBP  4671 non-null   float64
dtypes: float64(1)
memory usage: 66.2+ KB
1158
125990
After dropna size is:
347
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 5018 entries, ('GB10001725', 2019) to ('GB07916193', 2012)
Data columns (total 1 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   Land_&_Building_or_Property_Rents_&_Other_th_GBP  5018 non-null   float64
dtypes: float64(1)
memory usage: 70.5+ KB
1159
125990
After dropna size is:
183
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 5201 entries, ('GB10001725', 2019) to ('GB07169615', 2011)
Data columns (total 1 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   Land_&_Building_or_Property_Rents_&_Other_th_GBP  5201 non-null   float64
dtypes: float64(1)
memory usage: 72.7+ KB
1160
125990
After dropna size is:
54
1161
125990
After dropna size is:
133
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 187 entries, ('GB08503147', 2019) to ('GBOC411984', 2018)
Data columns (total 1 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Research_&_Development_th_GBP  187 non-null    float64
dtypes: float64(1)
memory usage: 3.4+ KB
1162
125990
After dropna size is:
138
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 325 entries, ('GB08503147', 2019) to ('GBOC411984', 2017)
Data columns (total 1 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Research_&_Development_th_GBP  325 non-null    float64
dtypes: float64(1)
memory usage: 5.2+ KB
1163
125990
After dropna size is:
128
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 453 entries, ('GB08503147', 2019) to ('GB08771968', 2016)
Data columns (total 1 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Research_&_Development_th_GBP  453 non-null    float64
dtypes: float64(1)
memory usage: 7.0+ KB
1164
125990
After dropna size is:
67
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 520 entries, ('GB08503147', 2019) to ('GB07172423', 2015)
Data columns (total 1 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Research_&_Development_th_GBP  520 non-null    float64
dtypes: float64(1)
memory usage: 7.9+ KB
1165
125990
After dropna size is:
74
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 594 entries, ('GB08503147', 2019) to ('GB07172423', 2014)
Data columns (total 1 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Research_&_Development_th_GBP  594 non-null    float64
dtypes: float64(1)
memory usage: 8.9+ KB
1166
125990
After dropna size is:
85
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 679 entries, ('GB08503147', 2019) to ('GB07170804', 2013)
Data columns (total 1 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Research_&_Development_th_GBP  679 non-null    float64
dtypes: float64(1)
memory usage: 10.1+ KB
1167
125990
After dropna size is:
48
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 727 entries, ('GB08503147', 2019) to ('GB07576118', 2012)
Data columns (total 1 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Research_&_Development_th_GBP  727 non-null    float64
dtypes: float64(1)
memory usage: 10.7+ KB
1168
125990
After dropna size is:
21
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 748 entries, ('GB08503147', 2019) to ('GB07196638', 2011)
Data columns (total 1 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Research_&_Development_th_GBP  748 non-null    float64
dtypes: float64(1)
memory usage: 11.0+ KB
1169
125990
After dropna size is:
426
1170
125990
After dropna size is:
1893
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 2319 entries, ('GB08123133', 2019) to ('GB09061578', 2018)
Data columns (total 1 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Foreign_Exchange_Gains/Losses_th_GBP  2319 non-null   float64
dtypes: float64(1)
memory usage: 40.8+ KB
1171
125990
After dropna size is:
2114
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 4433 entries, ('GB08123133', 2019) to ('GB09061578', 2017)
Data columns (total 1 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Foreign_Exchange_Gains/Losses_th_GBP  4433 non-null   float64
dtypes: float64(1)
memory usage: 69.2+ KB
1172
125990
After dropna size is:
2320
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 6753 entries, ('GB08123133', 2019) to ('GB09061578', 2016)
Data columns (total 1 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Foreign_Exchange_Gains/Losses_th_GBP  6753 non-null   float64
dtypes: float64(1)
memory usage: 100.2+ KB
1173
125990
After dropna size is:
2205
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 8958 entries, ('GB08123133', 2019) to ('GB09061578', 2015)
Data columns (total 1 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Foreign_Exchange_Gains/Losses_th_GBP  8958 non-null   float64
dtypes: float64(1)
memory usage: 130.1+ KB
1174
125990
After dropna size is:
1610
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 10568 entries, ('GB08123133', 2019) to ('GB09061578', 2014)
Data columns (total 1 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Foreign_Exchange_Gains/Losses_th_GBP  10568 non-null  float64
dtypes: float64(1)
memory usage: 150.5+ KB
1175
125990
After dropna size is:
1145

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Research_&_Development_th_GBP'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 11713 entries, ('GB08123133', 2019) to ('GB07937886', 2013)
Data columns (total 1 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Foreign_Exchange_Gains/Losses_th_GBP  11713 non-null  float64
dtypes: float64(1)
memory usage: 165.1+ KB
1176
125990
After dropna size is:
711
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 12424 entries, ('GB08123133', 2019) to ('GB07361608', 2012)
Data columns (total 1 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Foreign_Exchange_Gains/Losses_th_GBP  12424 non-null  float64
dtypes: float64(1)
memory usage: 173.8+ KB
1177
125990
After dropna size is:
338
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 12762 entries, ('GB08123133', 2019) to ('GB07361608', 2011)
Data columns (total 1 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Foreign_Exchange_Gains/Losses_th_GBP  12762 non-null  float64
dtypes: float64(1)
memory usage: 178.0+ KB
1178
125990
After dropna size is:
7822
1179
125990
After dropna size is:
15482
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 23304 entries, ('GB10388936', 2019) to ('IE505067', 2018)
Data columns (total 1 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Remuneration_th_GBP  23304 non-null  float64
dtypes: float64(1)
memory usage: 395.6+ KB
1180
125990
After dropna size is:
19368
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 42672 entries, ('GB10388936', 2019) to ('IE505067', 2017)
Data columns (total 1 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Remuneration_th_GBP  42672 non-null  float64
dtypes: float64(1)
memory usage: 679.3+ KB
1181
125990
After dropna size is:
13892
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 56564 entries, ('GB10388936', 2019) to ('IE505067', 2016)
Data columns (total 1 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Remuneration_th_GBP  56564 non-null  float64
dtypes: float64(1)
memory usage: 988.1+ KB
1182
125990
After dropna size is:
9962
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 66526 entries, ('GB10388936', 2019) to ('GBOC369696', 2015)
Data columns (total 1 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Remuneration_th_GBP  66526 non-null  float64
dtypes: float64(1)
memory usage: 1.1+ MB
1183
125990
After dropna size is:
7120
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 73646 entries, ('GB10388936', 2019) to ('GBOC369696', 2014)
Data columns (total 1 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Remuneration_th_GBP  73646 non-null  float64
dtypes: float64(1)
memory usage: 1.2+ MB
1184
125990
After dropna size is:
5828
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 79474 entries, ('GB10388936', 2019) to ('GBOC369696', 2013)
Data columns (total 1 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Remuneration_th_GBP  79474 non-null  float64
dtypes: float64(1)
memory usage: 1.3+ MB
1185
125990
After dropna size is:
4613
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 84087 entries, ('GB10388936', 2019) to ('GB07361608', 2012)
Data columns (total 1 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Remuneration_th_GBP  84087 non-null  float64
dtypes: float64(1)
memory usage: 1.4+ MB
1186
125990
After dropna size is:
2690
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 86777 entries, ('GB10388936', 2019) to ('GB07266603', 2011)
Data columns (total 1 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Remuneration_th_GBP  86777 non-null  float64
dtypes: float64(1)
memory usage: 1.4+ MB
1187
125990
After dropna size is:
7798
1188
125990
After dropna size is:
15394
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 23192 entries, ('GB10388936', 2019) to ('IE505067', 2018)
Data columns (total 1 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Wages_&_Salaries_th_GBP  23192 non-null  float64
dtypes: float64(1)
memory usage: 393.8+ KB
1189
125990
After dropna size is:
19284
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 42476 entries, ('GB10388936', 2019) to ('IE505067', 2017)
Data columns (total 1 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Wages_&_Salaries_th_GBP  42476 non-null  float64
dtypes: float64(1)
memory usage: 676.5+ KB
1190
125990
After dropna size is:
13813
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 56289 entries, ('GB10388936', 2019) to ('IE505067', 2016)
Data columns (total 1 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Wages_&_Salaries_th_GBP  56289 non-null  float64
dtypes: float64(1)
memory usage: 983.8+ KB
1191
125990
After dropna size is:
9902
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 66191 entries, ('GB10388936', 2019) to ('GBOC369696', 2015)
Data columns (total 1 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Wages_&_Salaries_th_GBP  66191 non-null  float64
dtypes: float64(1)
memory usage: 1.1+ MB
1192
125990
After dropna size is:
7060
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 73251 entries, ('GB10388936', 2019) to ('GBOC369696', 2014)
Data columns (total 1 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Wages_&_Salaries_th_GBP  73251 non-null  float64
dtypes: float64(1)
memory usage: 1.2+ MB
1193
125990
After dropna size is:
5786
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 79037 entries, ('GB10388936', 2019) to ('GBOC369696', 2013)
Data columns (total 1 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Wages_&_Salaries_th_GBP  79037 non-null  float64
dtypes: float64(1)
memory usage: 1.3+ MB
1194
125990
After dropna size is:
4530
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 83567 entries, ('GB10388936', 2019) to ('GB07361608', 2012)
Data columns (total 1 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Wages_&_Salaries_th_GBP  83567 non-null  float64
dtypes: float64(1)
memory usage: 1.4+ MB
1195
125990
After dropna size is:
2624
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 86191 entries, ('GB10388936', 2019) to ('GB07266603', 2011)
Data columns (total 1 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Wages_&_Salaries_th_GBP  86191 non-null  float64
dtypes: float64(1)
memory usage: 1.4+ MB
1196
125990
After dropna size is:
1874
1197
125990
After dropna size is:
4574
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 6448 entries, ('GB07848729', 2019) to ('IE505067', 2018)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Social_Security_Costs_th_GBP  6448 non-null   float64
dtypes: float64(1)
memory usage: 108.1+ KB
1198
125990
After dropna size is:
5144
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 11592 entries, ('GB07848729', 2019) to ('IE505067', 2017)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Social_Security_Costs_th_GBP  11592 non-null  float64
dtypes: float64(1)
memory usage: 174.6+ KB
1199
125990
After dropna size is:
5264
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 16856 entries, ('GB07848729', 2019) to ('IE505067', 2016)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Social_Security_Costs_th_GBP  16856 non-null  float64
dtypes: float64(1)
memory usage: 243.0+ KB
1200
125990

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Wages_&_Salaries_th_GBP'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

After dropna size is:
4612
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 21468 entries, ('GB07848729', 2019) to ('GBOC369696', 2015)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Social_Security_Costs_th_GBP  21468 non-null  float64
dtypes: float64(1)
memory usage: 301.3+ KB
1201
125990
After dropna size is:
3704
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 25172 entries, ('GB07848729', 2019) to ('GBOC369696', 2014)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Social_Security_Costs_th_GBP  25172 non-null  float64
dtypes: float64(1)
memory usage: 346.9+ KB
1202
125990
After dropna size is:
2819
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 27991 entries, ('GB07848729', 2019) to ('GBOC369696', 2013)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Social_Security_Costs_th_GBP  27991 non-null  float64
dtypes: float64(1)
memory usage: 382.4+ KB
1203
125990
After dropna size is:
1980
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 29971 entries, ('GB07848729', 2019) to ('GB07361608', 2012)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Social_Security_Costs_th_GBP  29971 non-null  float64
dtypes: float64(1)
memory usage: 407.8+ KB
1204
125990
After dropna size is:
870
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 30841 entries, ('GB07848729', 2019) to ('GB07361608', 2011)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Social_Security_Costs_th_GBP  30841 non-null  float64
dtypes: float64(1)
memory usage: 418.6+ KB
1205
125990
After dropna size is:
1757
1206
125990
After dropna size is:
3827
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 5584 entries, ('GB09316950', 2019) to ('GB09102173', 2018)
Data columns (total 1 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Pension_Costs_th_GBP  5584 non-null   float64
dtypes: float64(1)
memory usage: 93.8+ KB
1207
125990
After dropna size is:
3355
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 8939 entries, ('GB09316950', 2019) to ('GB09102173', 2017)
Data columns (total 1 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Pension_Costs_th_GBP  8939 non-null   float64
dtypes: float64(1)
memory usage: 136.3+ KB
1208
125990
After dropna size is:
2717
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 11656 entries, ('GB09316950', 2019) to ('IE505067', 2016)
Data columns (total 1 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Pension_Costs_th_GBP  11656 non-null  float64
dtypes: float64(1)
memory usage: 170.3+ KB
1209
125990
After dropna size is:
2219
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 13875 entries, ('GB09316950', 2019) to ('GBOC369696', 2015)
Data columns (total 1 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Pension_Costs_th_GBP  13875 non-null  float64
dtypes: float64(1)
memory usage: 197.7+ KB
1210
125990
After dropna size is:
1744
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 15619 entries, ('GB09316950', 2019) to ('GBOC369696', 2014)
Data columns (total 1 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Pension_Costs_th_GBP  15619 non-null  float64
dtypes: float64(1)
memory usage: 218.5+ KB
1211
125990
After dropna size is:
1205
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 16824 entries, ('GB09316950', 2019) to ('GBOC369696', 2013)
Data columns (total 1 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Pension_Costs_th_GBP  16824 non-null  float64
dtypes: float64(1)
memory usage: 233.0+ KB
1212
125990
After dropna size is:
842
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 17666 entries, ('GB09316950', 2019) to ('GB07937886', 2012)
Data columns (total 1 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Pension_Costs_th_GBP  17666 non-null  float64
dtypes: float64(1)
memory usage: 243.6+ KB
1213
125990
After dropna size is:
412
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 18078 entries, ('GB09316950', 2019) to ('GB07339695', 2011)
Data columns (total 1 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Pension_Costs_th_GBP  18078 non-null  float64
dtypes: float64(1)
memory usage: 248.7+ KB
1214
125990
After dropna size is:
536
1215
125990
After dropna size is:
1224
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1760 entries, ('GB10012884', 2019) to ('GB09061578', 2018)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Other_Staff_Costs_th_GBP  1760 non-null   float64
dtypes: float64(1)
memory usage: 30.3+ KB
1216
125990
After dropna size is:
1378
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 3138 entries, ('GB10012884', 2019) to ('IE564801', 2017)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Other_Staff_Costs_th_GBP  3138 non-null   float64
dtypes: float64(1)
memory usage: 50.8+ KB
1217
125990
After dropna size is:
1311
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 4449 entries, ('GB10012884', 2019) to ('GB07232505', 2016)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Other_Staff_Costs_th_GBP  4449 non-null   float64
dtypes: float64(1)
memory usage: 70.2+ KB
1218
125990
After dropna size is:
1039
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 5488 entries, ('GB10012884', 2019) to ('GB08351545', 2015)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Other_Staff_Costs_th_GBP  5488 non-null   float64
dtypes: float64(1)
memory usage: 85.2+ KB
1219
125990
After dropna size is:
774
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 6262 entries, ('GB10012884', 2019) to ('GB08495500', 2014)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Other_Staff_Costs_th_GBP  6262 non-null   float64
dtypes: float64(1)
memory usage: 96.1+ KB
1220
125990
After dropna size is:
629
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 6891 entries, ('GB10012884', 2019) to ('GB08090929', 2013)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Other_Staff_Costs_th_GBP  6891 non-null   float64
dtypes: float64(1)
memory usage: 105.5+ KB
1221
125990
After dropna size is:
586
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 7477 entries, ('GB10012884', 2019) to ('GB07521549', 2012)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Other_Staff_Costs_th_GBP  7477 non-null   float64
dtypes: float64(1)
memory usage: 114.8+ KB
1222
125990
After dropna size is:
430
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 7907 entries, ('GB10012884', 2019) to ('GB07266603', 2011)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Other_Staff_Costs_th_GBP  7907 non-null   float64
dtypes: float64(1)
memory usage: 121.7+ KB
1223
125990
After dropna size is:
2368
1224
125990
After dropna size is:
5872
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 8240 entries, ('GB08497747', 2019) to ('IE505067', 2018)
Data columns (total 1 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Directors'_Remuneration_th_GBP  8240 non-null   float64
dtypes: float64(1)
memory usage: 140.2+ KB
1225
125990
After dropna size is:
8220
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 16460 entries, ('GB08497747', 2019) to ('IE505067', 2017)
Data columns (total 1 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Directors'_Remuneration_th_GBP  16460 non-null  float64
dtypes: float64(1)
memory usage: 260.0+ KB
1226
125990
After dropna size is:
9971

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 26431 entries, ('GB08497747', 2019) to ('IE505067', 2016)
Data columns (total 1 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Directors'_Remuneration_th_GBP  26431 non-null  float64
dtypes: float64(1)
memory usage: 409.7+ KB
1227
125990
After dropna size is:
9417
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 35848 entries, ('GB08497747', 2019) to ('GBOC369696', 2015)
Data columns (total 1 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Directors'_Remuneration_th_GBP  35848 non-null  float64
dtypes: float64(1)
memory usage: 541.7+ KB
1228
125990
After dropna size is:
9199
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 45047 entries, ('GB08497747', 2019) to ('GBOC369696', 2014)
Data columns (total 1 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Directors'_Remuneration_th_GBP  45047 non-null  float64
dtypes: float64(1)
memory usage: 669.4+ KB
1229
125990
After dropna size is:
9014
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 54061 entries, ('GB08497747', 2019) to ('GBOC369696', 2013)
Data columns (total 1 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Directors'_Remuneration_th_GBP  54061 non-null  float64
dtypes: float64(1)
memory usage: 798.8+ KB
1230
125990
After dropna size is:
7079
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 61140 entries, ('GB08497747', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Directors'_Remuneration_th_GBP  61140 non-null  float64
dtypes: float64(1)
memory usage: 898.5+ KB
1231
125990
After dropna size is:
3469
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 64609 entries, ('GB08497747', 2019) to ('GB07266603', 2011)
Data columns (total 1 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Directors'_Remuneration_th_GBP  64609 non-null  float64
dtypes: float64(1)
memory usage: 945.6+ KB
1232
125990
After dropna size is:
2332
1233
125990
After dropna size is:
5754
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 8086 entries, ('GB08497747', 2019) to ('IE505067', 2018)
Data columns (total 1 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Directors'_Fees_th_GBP  8086 non-null   float64
dtypes: float64(1)
memory usage: 137.7+ KB
1234
125990
After dropna size is:
8077
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 16163 entries, ('GB08497747', 2019) to ('IE505067', 2017)
Data columns (total 1 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Directors'_Fees_th_GBP  16163 non-null  float64
dtypes: float64(1)
memory usage: 255.7+ KB
1235
125990
After dropna size is:
9811

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: "Directors'_Remuneration_th_GBP"; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 25974 entries, ('GB08497747', 2019) to ('IE505067', 2016)
Data columns (total 1 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Directors'_Fees_th_GBP  25974 non-null  float64
dtypes: float64(1)
memory usage: 403.3+ KB
1236
125990
After dropna size is:
9235
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 35209 entries, ('GB08497747', 2019) to ('GBOC369696', 2015)
Data columns (total 1 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Directors'_Fees_th_GBP  35209 non-null  float64
dtypes: float64(1)
memory usage: 533.2+ KB
1237
125990
After dropna size is:
8947
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 44156 entries, ('GB08497747', 2019) to ('GBOC369696', 2014)
Data columns (total 1 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Directors'_Fees_th_GBP  44156 non-null  float64
dtypes: float64(1)
memory usage: 657.9+ KB
1238
125990
After dropna size is:
8839
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 52995 entries, ('GB08497747', 2019) to ('GBOC369696', 2013)
Data columns (total 1 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Directors'_Fees_th_GBP  52995 non-null  float64
dtypes: float64(1)
memory usage: 785.3+ KB
1239
125990
After dropna size is:
6995
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 59990 entries, ('GB08497747', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Directors'_Fees_th_GBP  59990 non-null  float64
dtypes: float64(1)
memory usage: 884.0+ KB
1240
125990
After dropna size is:
3425
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 63415 entries, ('GB08497747', 2019) to ('GB07266603', 2011)
Data columns (total 1 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Directors'_Fees_th_GBP  63415 non-null  float64
dtypes: float64(1)
memory usage: 930.6+ KB
1241
125990
After dropna size is:
367
1242
125990
After dropna size is:
973
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1340 entries, ('GB08444904', 2019) to ('GB07805564', 2018)
Data columns (total 1 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Pension_Contribution_th_GBP  1340 non-null   float64
dtypes: float64(1)
memory usage: 23.2+ KB
1243
125990
After dropna size is:
977
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 2317 entries, ('GB08444904', 2019) to ('GB09321895', 2017)
Data columns (total 1 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Pension_Contribution_th_GBP  2317 non-null   float64
dtypes: float64(1)
memory usage: 36.5+ KB
1244
125990
After dropna size is:
845
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 3162 entries, ('GB08444904', 2019) to ('IE505067', 2016)
Data columns (total 1 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Pension_Contribution_th_GBP  3162 non-null   float64
dtypes: float64(1)
memory usage: 48.0+ KB
1245
125990
After dropna size is:
676
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 3838 entries, ('GB08444904', 2019) to ('GB07634356', 2015)
Data columns (total 1 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Pension_Contribution_th_GBP  3838 non-null   float64
dtypes: float64(1)
memory usage: 56.8+ KB
1246
125990
After dropna size is:
522
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 4360 entries, ('GB08444904', 2019) to ('GBOC369696', 2014)
Data columns (total 1 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Pension_Contribution_th_GBP  4360 non-null   float64
dtypes: float64(1)
memory usage: 63.5+ KB
1247
125990
After dropna size is:
377
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 4737 entries, ('GB08444904', 2019) to ('GB07550125', 2013)
Data columns (total 1 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Pension_Contribution_th_GBP  4737 non-null   float64
dtypes: float64(1)
memory usage: 68.3+ KB
1248
125990
After dropna size is:
249
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 4986 entries, ('GB08444904', 2019) to ('GB08005854', 2012)
Data columns (total 1 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Pension_Contribution_th_GBP  4986 non-null   float64
dtypes: float64(1)
memory usage: 71.6+ KB
1249
125990
After dropna size is:
111

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: "Directors'_Fees_th_GBP"; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 5097 entries, ('GB08444904', 2019) to ('GB07159767', 2011)
Data columns (total 1 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Pension_Contribution_th_GBP  5097 non-null   float64
dtypes: float64(1)
memory usage: 73.0+ KB
1250
125990
After dropna size is:
97
1251
125990
After dropna size is:
335
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 432 entries, ('GB09558533', 2019) to ('GB08648913', 2018)
Data columns (total 1 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Other_Emoluments_th_GBP  432 non-null    float64
dtypes: float64(1)
memory usage: 7.8+ KB
1252
125990
After dropna size is:
502
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 934 entries, ('GB09558533', 2019) to ('GB08971136', 2017)
Data columns (total 1 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Other_Emoluments_th_GBP  934 non-null    float64
dtypes: float64(1)
memory usage: 16.1+ KB
1253
125990
After dropna size is:
379
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1313 entries, ('GB09558533', 2019) to ('GB07747048', 2016)
Data columns (total 1 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Other_Emoluments_th_GBP  1313 non-null   float64
dtypes: float64(1)
memory usage: 22.1+ KB
1254
125990
After dropna size is:
299
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1612 entries, ('GB09558533', 2019) to ('GB08866705', 2015)
Data columns (total 1 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Other_Emoluments_th_GBP  1612 non-null   float64
dtypes: float64(1)
memory usage: 26.7+ KB
1255
125990
After dropna size is:
262
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1874 entries, ('GB09558533', 2019) to ('GBOC369696', 2014)
Data columns (total 1 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Other_Emoluments_th_GBP  1874 non-null   float64
dtypes: float64(1)
memory usage: 30.8+ KB
1256
125990
After dropna size is:
227
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 2101 entries, ('GB09558533', 2019) to ('GB07747048', 2013)
Data columns (total 1 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Other_Emoluments_th_GBP  2101 non-null   float64
dtypes: float64(1)
memory usage: 34.4+ KB
1257
125990
After dropna size is:
159
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 2260 entries, ('GB09558533', 2019) to ('GB07747048', 2012)
Data columns (total 1 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Other_Emoluments_th_GBP  2260 non-null   float64
dtypes: float64(1)
memory usage: 36.9+ KB
1258
125990
After dropna size is:
104
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 2364 entries, ('GB09558533', 2019) to ('GB07232845', 2011)
Data columns (total 1 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Other_Emoluments_th_GBP  2364 non-null   float64
dtypes: float64(1)
memory usage: 38.6+ KB
1259
125990
After dropna size is:
269
1260
125990
After dropna size is:
796
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1065 entries, ('GB07151588', 2019) to ('GB08425566', 2018)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Highest_Paid_Director_th_GBP  1065 non-null   float64
dtypes: float64(1)
memory usage: 18.4+ KB
1261
125990
After dropna size is:
796
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1861 entries, ('GB07151588', 2019) to ('GB08495500', 2017)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Highest_Paid_Director_th_GBP  1861 non-null   float64
dtypes: float64(1)
memory usage: 28.5+ KB
1262
125990
After dropna size is:
787
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 2648 entries, ('GB07151588', 2019) to ('GB08495500', 2016)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Highest_Paid_Director_th_GBP  2648 non-null   float64
dtypes: float64(1)
memory usage: 38.8+ KB
1263
125990
After dropna size is:
558
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 3206 entries, ('GB07151588', 2019) to ('GB07767724', 2015)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Highest_Paid_Director_th_GBP  3206 non-null   float64
dtypes: float64(1)
memory usage: 45.8+ KB
1264
125990
After dropna size is:
440
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 3646 entries, ('GB07151588', 2019) to ('GB08495500', 2014)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Highest_Paid_Director_th_GBP  3646 non-null   float64
dtypes: float64(1)
memory usage: 51.3+ KB
1265
125990
After dropna size is:
335
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 3981 entries, ('GB07151588', 2019) to ('GB07239390', 2013)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Highest_Paid_Director_th_GBP  3981 non-null   float64
dtypes: float64(1)
memory usage: 55.4+ KB
1266
125990
After dropna size is:
211
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 4192 entries, ('GB07151588', 2019) to ('GB07239390', 2012)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Highest_Paid_Director_th_GBP  4192 non-null   float64
dtypes: float64(1)
memory usage: 58.0+ KB
1267
125990
After dropna size is:
85
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 4277 entries, ('GB07151588', 2019) to ('GB07239390', 2011)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Highest_Paid_Director_th_GBP  4277 non-null   float64
dtypes: float64(1)
memory usage: 59.0+ KB
1268
125990
After dropna size is:
23261
1269
125990
After dropna size is:
46177
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 69438 entries, ('GB09567757', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   EBITDA_th_GBP  69438 non-null  float64
dtypes: float64(1)
memory usage: 1.3+ MB
1270
125990
After dropna size is:
55464
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 124902 entries, ('GB09567757', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   EBITDA_th_GBP  124902 non-null  float64
dtypes: float64(1)
memory usage: 2.1+ MB
1271
125990
After dropna size is:
44194
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 169096 entries, ('GB09567757', 2019) to ('GBOC381395', 2016)
Data columns (total 1 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   EBITDA_th_GBP  169096 non-null  float64
dtypes: float64(1)
memory usage: 2.8+ MB
1272
125990
After dropna size is:
36301
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 205397 entries, ('GB09567757', 2019) to ('GBSC452461', 2015)
Data columns (total 1 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   EBITDA_th_GBP  205397 non-null  float64
dtypes: float64(1)
memory usage: 3.3+ MB
1273
125990
After dropna size is:
30904
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 236301 entries, ('GB09567757', 2019) to ('GBOC369696', 2014)
Data columns (total 1 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   EBITDA_th_GBP  236301 non-null  float64
dtypes: float64(1)
memory usage: 3.7+ MB
1274
125990
After dropna size is:
26539

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 262840 entries, ('GB09567757', 2019) to ('GBOC369696', 2013)
Data columns (total 1 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   EBITDA_th_GBP  262840 non-null  float64
dtypes: float64(1)
memory usage: 4.1+ MB
1275
125990
After dropna size is:
19955
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 282795 entries, ('GB09567757', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   EBITDA_th_GBP  282795 non-null  float64
dtypes: float64(1)
memory usage: 4.4+ MB
1276
125990
After dropna size is:
10660
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 293455 entries, ('GB09567757', 2019) to ('GB07266603', 2011)
Data columns (total 1 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   EBITDA_th_GBP  293455 non-null  float64
dtypes: float64(1)
memory usage: 4.6+ MB
1277
125990
After dropna size is:
1583
1278
125990
After dropna size is:
4899
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 6482 entries, ('GB08287986', 2019) to ('GBSC452461', 2018)
Data columns (total 1 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Cash_In(Out)flow_Operat._Activ._th_GBP  6482 non-null   float64
dtypes: float64(1)
memory usage: 109.2+ KB
1279
125990
After dropna size is:
5363
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 11845 entries, ('GB08287986', 2019) to ('GBSC452461', 2017)
Data columns (total 1 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Cash_In(Out)flow_Operat._Activ._th_GBP  11845 non-null  float64
dtypes: float64(1)
memory usage: 174.4+ KB
1280
125990
After dropna size is:
5864
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 17709 entries, ('GB08287986', 2019) to ('GBSC452461', 2016)
Data columns (total 1 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Cash_In(Out)flow_Operat._Activ._th_GBP  17709 non-null  float64
dtypes: float64(1)
memory usage: 247.8+ KB
1281
125990
After dropna size is:
4882
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 22591 entries, ('GB08287986', 2019) to ('IE510402', 2015)
Data columns (total 1 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Cash_In(Out)flow_Operat._Activ._th_GBP  22591 non-null  float64
dtypes: float64(1)
memory usage: 307.2+ KB
1282
125990
After dropna size is:
3603
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 26194 entries, ('GB08287986', 2019) to ('GBOC369696', 2014)
Data columns (total 1 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Cash_In(Out)flow_Operat._Activ._th_GBP  26194 non-null  float64
dtypes: float64(1)
memory usage: 349.6+ KB
1283
125990
After dropna size is:
2517
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 28711 entries, ('GB08287986', 2019) to ('GBOC369696', 2013)
Data columns (total 1 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Cash_In(Out)flow_Operat._Activ._th_GBP  28711 non-null  float64
dtypes: float64(1)
memory usage: 379.0+ KB
1284
125990
After dropna size is:
1686
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 30397 entries, ('GB08287986', 2019) to ('GB07361608', 2012)
Data columns (total 1 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Cash_In(Out)flow_Operat._Activ._th_GBP  30397 non-null  float64
dtypes: float64(1)
memory usage: 398.4+ KB
1285
125990
After dropna size is:
894
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 31291 entries, ('GB08287986', 2019) to ('GB07361608', 2011)
Data columns (total 1 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Cash_In(Out)flow_Operat._Activ._th_GBP  31291 non-null  float64
dtypes: float64(1)
memory usage: 408.6+ KB
1286
125990
After dropna size is:
709
1287
125990
After dropna size is:
1865
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 2574 entries, ('GB08287986', 2019) to ('IE505067', 2018)
Data columns (total 1 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Cash_In(Out)flow_Ret._on_Invest._th_GBP  2574 non-null   float64
dtypes: float64(1)
memory usage: 44.0+ KB
1288
125990
After dropna size is:
1899
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 4473 entries, ('GB08287986', 2019) to ('IE505067', 2017)
Data columns (total 1 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Cash_In(Out)flow_Ret._on_Invest._th_GBP  4473 non-null   float64
dtypes: float64(1)
memory usage: 68.9+ KB
1289
125990
After dropna size is:
1823
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 6296 entries, ('GB08287986', 2019) to ('IE505067', 2016)
Data columns (total 1 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Cash_In(Out)flow_Ret._on_Invest._th_GBP  6296 non-null   float64
dtypes: float64(1)
memory usage: 93.0+ KB
1290
125990
After dropna size is:
1492
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 7788 entries, ('GB08287986', 2019) to ('GB07193901', 2015)
Data columns (total 1 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Cash_In(Out)flow_Ret._on_Invest._th_GBP  7788 non-null   float64
dtypes: float64(1)
memory usage: 112.7+ KB
1291
125990
After dropna size is:
1308
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 9096 entries, ('GB08287986', 2019) to ('GB07937886', 2014)
Data columns (total 1 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Cash_In(Out)flow_Ret._on_Invest._th_GBP  9096 non-null   float64
dtypes: float64(1)
memory usage: 129.7+ KB
1292
125990
After dropna size is:
965

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Cash_In(Out)flow_Operat._Activ._th_GBP'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 10061 entries, ('GB08287986', 2019) to ('GBOC369696', 2013)
Data columns (total 1 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Cash_In(Out)flow_Ret._on_Invest._th_GBP  10061 non-null  float64
dtypes: float64(1)
memory usage: 141.8+ KB
1293
125990
After dropna size is:
639
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 10700 entries, ('GB08287986', 2019) to ('GB07937886', 2012)
Data columns (total 1 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Cash_In(Out)flow_Ret._on_Invest._th_GBP  10700 non-null  float64
dtypes: float64(1)
memory usage: 149.6+ KB
1294
125990
After dropna size is:
299
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 10999 entries, ('GB08287986', 2019) to ('GB07341487', 2011)
Data columns (total 1 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Cash_In(Out)flow_Ret._on_Invest._th_GBP  10999 non-null  float64
dtypes: float64(1)
memory usage: 153.3+ KB
1295
125990
After dropna size is:
142
1296
125990
After dropna size is:
784
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 926 entries, ('GB09662120', 2019) to ('GB07258174', 2018)
Data columns (total 1 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Cash_Out(In)flow_Investing_Activ._th_GBP  926 non-null    float64
dtypes: float64(1)
memory usage: 16.5+ KB
1297
125990
After dropna size is:
955
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1881 entries, ('GB09662120', 2019) to ('GB09927146', 2017)
Data columns (total 1 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Cash_Out(In)flow_Investing_Activ._th_GBP  1881 non-null   float64
dtypes: float64(1)
memory usage: 29.3+ KB
1298
125990
After dropna size is:
983
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 2864 entries, ('GB09662120', 2019) to ('GB09927146', 2016)
Data columns (total 1 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Cash_Out(In)flow_Investing_Activ._th_GBP  2864 non-null   float64
dtypes: float64(1)
memory usage: 42.2+ KB
1299
125990
After dropna size is:
812
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 3676 entries, ('GB09662120', 2019) to ('IE549110', 2015)
Data columns (total 1 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Cash_Out(In)flow_Investing_Activ._th_GBP  3676 non-null   float64
dtypes: float64(1)
memory usage: 52.3+ KB
1300
125990
After dropna size is:
581
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 4257 entries, ('GB09662120', 2019) to ('GB08094042', 2014)
Data columns (total 1 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Cash_Out(In)flow_Investing_Activ._th_GBP  4257 non-null   float64
dtypes: float64(1)
memory usage: 59.7+ KB
1301
125990
After dropna size is:
376
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 4633 entries, ('GB09662120', 2019) to ('GB08094042', 2013)
Data columns (total 1 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Cash_Out(In)flow_Investing_Activ._th_GBP  4633 non-null   float64
dtypes: float64(1)
memory usage: 64.4+ KB
1302
125990
After dropna size is:
300

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Cash_In(Out)flow_Ret._on_Invest._th_GBP'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)
/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Cash_Out(In)flow_Investing_Activ._th_GBP'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 4933 entries, ('GB09662120', 2019) to ('GB07258174', 2012)
Data columns (total 1 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Cash_Out(In)flow_Investing_Activ._th_GBP  4933 non-null   float64
dtypes: float64(1)
memory usage: 68.2+ KB
1303
125990
After dropna size is:
147
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 5080 entries, ('GB09662120', 2019) to ('GB07258174', 2011)
Data columns (total 1 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Cash_Out(In)flow_Investing_Activ._th_GBP  5080 non-null   float64
dtypes: float64(1)
memory usage: 70.0+ KB
1304
125990
After dropna size is:
782
1305
125990
After dropna size is:
2159
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 2941 entries, ('IE561097', 2019) to ('GB07122226', 2018)
Data columns (total 1 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Capital_Expenditure_&_Financ._Invest._th_GBP  2941 non-null   float64
dtypes: float64(1)
memory usage: 50.0+ KB
1306
125990
After dropna size is:
2299
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 5240 entries, ('IE561097', 2019) to ('GB07122226', 2017)
Data columns (total 1 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Capital_Expenditure_&_Financ._Invest._th_GBP  5240 non-null   float64
dtypes: float64(1)
memory usage: 79.4+ KB
1307
125990
After dropna size is:
2505
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 7745 entries, ('IE561097', 2019) to ('GB07973984', 2016)
Data columns (total 1 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Capital_Expenditure_&_Financ._Invest._th_GBP  7745 non-null   float64
dtypes: float64(1)
memory usage: 112.0+ KB
1308
125990
After dropna size is:
2039
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 9784 entries, ('IE561097', 2019) to ('IE510402', 2015)
Data columns (total 1 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Capital_Expenditure_&_Financ._Invest._th_GBP  9784 non-null   float64
dtypes: float64(1)
memory usage: 138.4+ KB
1309
125990
After dropna size is:
1490
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 11274 entries, ('IE561097', 2019) to ('GB07937886', 2014)
Data columns (total 1 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Capital_Expenditure_&_Financ._Invest._th_GBP  11274 non-null  float64
dtypes: float64(1)
memory usage: 156.9+ KB
1310
125990
After dropna size is:
1005
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 12279 entries, ('IE561097', 2019) to ('GBOC369696', 2013)
Data columns (total 1 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Capital_Expenditure_&_Financ._Invest._th_GBP  12279 non-null  float64
dtypes: float64(1)
memory usage: 169.3+ KB
1311
125990
After dropna size is:
681
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 12960 entries, ('IE561097', 2019) to ('GB07937886', 2012)
Data columns (total 1 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Capital_Expenditure_&_Financ._Invest._th_GBP  12960 non-null  float64
dtypes: float64(1)
memory usage: 177.6+ KB
1312
125990
After dropna size is:
378
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 13338 entries, ('IE561097', 2019) to ('GB07361608', 2011)
Data columns (total 1 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Capital_Expenditure_&_Financ._Invest._th_GBP  13338 non-null  float64
dtypes: float64(1)
memory usage: 182.2+ KB
1313
125990
After dropna size is:
0
1314
125990
After dropna size is:
4
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 4 entries, ('IE549286', 2018) to ('IE572312', 2018)
Data columns (total 1 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Acquisition_&_Disposal_th_GBP  4 non-null      float64
dtypes: float64(1)
memory usage: 231.0+ bytes
1315
125990
After dropna size is:
11
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 15 entries, ('IE549286', 2018) to ('IE589299', 2017)
Data columns (total 1 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Acquisition_&_Disposal_th_GBP  15 non-null     float64
dtypes: float64(1)
memory usage: 413.0+ bytes
1316
125990
After dropna size is:
23
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 38 entries, ('IE549286', 2018) to ('IE528520', 2016)
Data columns (total 1 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Acquisition_&_Disposal_th_GBP  38 non-null     float64
dtypes: float64(1)
memory usage: 827.0+ bytes
1317
125990
After dropna size is:
79
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 117 entries, ('IE549286', 2018) to ('IE515988', 2015)
Data columns (total 1 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Acquisition_&_Disposal_th_GBP  117 non-null    float64
dtypes: float64(1)
memory usage: 2.2+ KB
1318
125990
After dropna size is:
108
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 225 entries, ('IE549286', 2018) to ('GB07255861', 2014)
Data columns (total 1 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Acquisition_&_Disposal_th_GBP  225 non-null    float64
dtypes: float64(1)
memory usage: 4.1+ KB
1319
125990
After dropna size is:
79
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 304 entries, ('IE549286', 2018) to ('GB07169615', 2013)
Data columns (total 1 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Acquisition_&_Disposal_th_GBP  304 non-null    float64
dtypes: float64(1)
memory usage: 5.3+ KB
1320
125990
After dropna size is:
71
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 375 entries, ('IE549286', 2018) to ('GB07169615', 2012)
Data columns (total 1 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Acquisition_&_Disposal_th_GBP  375 non-null    float64
dtypes: float64(1)
memory usage: 6.4+ KB
1321
125990

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Capital_Expenditure_&_Financ._Invest._th_GBP'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)
/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Acquisition_&_Disposal_th_GBP'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

After dropna size is:
47
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 422 entries, ('IE549286', 2018) to ('GB07341487', 2011)
Data columns (total 1 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Acquisition_&_Disposal_th_GBP  422 non-null    float64
dtypes: float64(1)
memory usage: 7.2+ KB
1322
125990
After dropna size is:
75
1323
125990
After dropna size is:
226
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 301 entries, ('GB08287986', 2019) to ('GB07580983', 2018)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Equity_Dividends_Paid_th_GBP  301 non-null    float64
dtypes: float64(1)
memory usage: 5.5+ KB
1324
125990
After dropna size is:
206
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 507 entries, ('GB08287986', 2019) to ('IE505067', 2017)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Equity_Dividends_Paid_th_GBP  507 non-null    float64
dtypes: float64(1)
memory usage: 8.4+ KB
1325
125990
After dropna size is:
214
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 721 entries, ('GB08287986', 2019) to ('GB08750331', 2016)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Equity_Dividends_Paid_th_GBP  721 non-null    float64
dtypes: float64(1)
memory usage: 11.6+ KB
1326
125990
After dropna size is:
136
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 857 entries, ('GB08287986', 2019) to ('GB07160642', 2015)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Equity_Dividends_Paid_th_GBP  857 non-null    float64
dtypes: float64(1)
memory usage: 13.6+ KB
1327
125990
After dropna size is:
111
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 968 entries, ('GB08287986', 2019) to ('IE520617', 2014)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Equity_Dividends_Paid_th_GBP  968 non-null    float64
dtypes: float64(1)
memory usage: 15.2+ KB
1328
125990
After dropna size is:
94
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1062 entries, ('GB08287986', 2019) to ('GB07951785', 2013)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Equity_Dividends_Paid_th_GBP  1062 non-null   float64
dtypes: float64(1)
memory usage: 16.5+ KB
1329
125990
After dropna size is:
48
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1110 entries, ('GB08287986', 2019) to ('GB07232845', 2012)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Equity_Dividends_Paid_th_GBP  1110 non-null   float64
dtypes: float64(1)
memory usage: 17.2+ KB
1330
125990
After dropna size is:
25
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1135 entries, ('GB08287986', 2019) to ('GB07449467', 2011)
Data columns (total 1 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Equity_Dividends_Paid_th_GBP  1135 non-null   float64
dtypes: float64(1)
memory usage: 17.6+ KB
1331
125990
After dropna size is:
1
1332
125990
After dropna size is:
0
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1 entries, ('GBOC390305', 2019) to ('GBOC390305', 2019)
Data columns (total 1 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Management_of_Liquid_Resources_th_GBP  1 non-null      float64
dtypes: float64(1)
memory usage: 177.0+ bytes
1333
125990
After dropna size is:
5
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 6 entries, ('GBOC390305', 2019) to ('GB09069316', 2017)
Data columns (total 1 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Management_of_Liquid_Resources_th_GBP  6 non-null      float64
dtypes: float64(1)
memory usage: 275.0+ bytes
1334
125990
After dropna size is:
2
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 8 entries, ('GBOC390305', 2019) to ('GBSC505093', 2016)
Data columns (total 1 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Management_of_Liquid_Resources_th_GBP  8 non-null      float64
dtypes: float64(1)
memory usage: 319.0+ bytes
1335
125990
After dropna size is:
13
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 21 entries, ('GBOC390305', 2019) to ('GB07563436', 2015)
Data columns (total 1 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Management_of_Liquid_Resources_th_GBP  21 non-null     float64
dtypes: float64(1)
memory usage: 561.0+ bytes
1336
125990
After dropna size is:
20
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 41 entries, ('GBOC390305', 2019) to ('GB07563436', 2014)
Data columns (total 1 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Management_of_Liquid_Resources_th_GBP  41 non-null     float64
dtypes: float64(1)
memory usage: 889.0+ bytes
1337
125990
After dropna size is:
26
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 67 entries, ('GBOC390305', 2019) to ('GB07563436', 2013)
Data columns (total 1 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Management_of_Liquid_Resources_th_GBP  67 non-null     float64
dtypes: float64(1)
memory usage: 1.3+ KB
1338
125990
After dropna size is:
15
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 82 entries, ('GBOC390305', 2019) to ('GB07255861', 2012)
Data columns (total 1 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Management_of_Liquid_Resources_th_GBP  82 non-null     float64
dtypes: float64(1)
memory usage: 1.5+ KB
1339
125990
After dropna size is:
7
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 89 entries, ('GBOC390305', 2019) to ('GB07255861', 2011)
Data columns (total 1 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Management_of_Liquid_Resources_th_GBP  89 non-null     float64
dtypes: float64(1)
memory usage: 1.6+ KB
1340
125990
After dropna size is:
788
1341
125990
After dropna size is:
2674
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 3462 entries, ('GB10575212', 2019) to ('GB07122226', 2018)
Data columns (total 1 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Cash_Out(In)flow_from_Financing_th_GBP  3462 non-null   float64
dtypes: float64(1)
memory usage: 59.7+ KB
1342
125990
After dropna size is:
3035
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 6497 entries, ('GB10575212', 2019) to ('IE600555', 2017)
Data columns (total 1 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Cash_Out(In)flow_from_Financing_th_GBP  6497 non-null   float64
dtypes: float64(1)
memory usage: 98.9+ KB
1343
125990
After dropna size is:
3455
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 9952 entries, ('GB10575212', 2019) to ('IE489225', 2016)
Data columns (total 1 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Cash_Out(In)flow_from_Financing_th_GBP  9952 non-null   float64
dtypes: float64(1)
memory usage: 143.8+ KB
1344
125990
After dropna size is:
2879
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 12831 entries, ('GB10575212', 2019) to ('IE510402', 2015)
Data columns (total 1 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Cash_Out(In)flow_from_Financing_th_GBP  12831 non-null  float64
dtypes: float64(1)
memory usage: 180.7+ KB
1345
125990
After dropna size is:
2144
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 14975 entries, ('GB10575212', 2019) to ('GBOC369696', 2014)
Data columns (total 1 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Cash_Out(In)flow_from_Financing_th_GBP  14975 non-null  float64
dtypes: float64(1)
memory usage: 208.1+ KB
1346
125990
After dropna size is:
1410
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 16385 entries, ('GB10575212', 2019) to ('GBOC369696', 2013)
Data columns (total 1 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Cash_Out(In)flow_from_Financing_th_GBP  16385 non-null  float64
dtypes: float64(1)
memory usage: 225.7+ KB
1347
125990
After dropna size is:
1047
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 17432 entries, ('GB10575212', 2019) to ('GB07937886', 2012)
Data columns (total 1 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Cash_Out(In)flow_from_Financing_th_GBP  17432 non-null  float64
dtypes: float64(1)
memory usage: 238.8+ KB
1348
125990
After dropna size is:
600
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 18032 entries, ('GB10575212', 2019) to ('GB07258174', 2011)
Data columns (total 1 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Cash_Out(In)flow_from_Financing_th_GBP  18032 non-null  float64
dtypes: float64(1)
memory usage: 246.5+ KB
1349
125990
After dropna size is:
1559
1350
125990
After dropna size is:
4688

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Cash_Out(In)flow_from_Financing_th_GBP'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 6247 entries, ('GB08287986', 2019) to ('GBSC452461', 2018)
Data columns (total 1 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Increase(Decrease)_Cash_&_Equiv._th_GBP  6247 non-null   float64
dtypes: float64(1)
memory usage: 105.0+ KB
1351
125990
After dropna size is:
5133
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 11380 entries, ('GB08287986', 2019) to ('GBSC452461', 2017)
Data columns (total 1 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Increase(Decrease)_Cash_&_Equiv._th_GBP  11380 non-null  float64
dtypes: float64(1)
memory usage: 167.9+ KB
1352
125990
After dropna size is:
5547
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 16927 entries, ('GB08287986', 2019) to ('GBSC452461', 2016)
Data columns (total 1 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Increase(Decrease)_Cash_&_Equiv._th_GBP  16927 non-null  float64
dtypes: float64(1)
memory usage: 237.6+ KB
1353
125990
After dropna size is:
4597
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 21524 entries, ('GB08287986', 2019) to ('IE510402', 2015)
Data columns (total 1 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Increase(Decrease)_Cash_&_Equiv._th_GBP  21524 non-null  float64
dtypes: float64(1)
memory usage: 293.5+ KB
1354
125990
After dropna size is:
3262
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 24786 entries, ('GB08287986', 2019) to ('GBOC369696', 2014)
Data columns (total 1 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Increase(Decrease)_Cash_&_Equiv._th_GBP  24786 non-null  float64
dtypes: float64(1)
memory usage: 332.2+ KB
1355
125990
After dropna size is:
2364
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 27150 entries, ('GB08287986', 2019) to ('GBOC369696', 2013)
Data columns (total 1 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Increase(Decrease)_Cash_&_Equiv._th_GBP  27150 non-null  float64
dtypes: float64(1)
memory usage: 359.8+ KB
1356
125990
After dropna size is:
1583
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 28733 entries, ('GB08287986', 2019) to ('GB07361608', 2012)
Data columns (total 1 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Increase(Decrease)_Cash_&_Equiv._th_GBP  28733 non-null  float64
dtypes: float64(1)
memory usage: 378.1+ KB
1357
125990
After dropna size is:
807
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 29540 entries, ('GB08287986', 2019) to ('GB07361608', 2011)
Data columns (total 1 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Increase(Decrease)_Cash_&_Equiv._th_GBP  29540 non-null  float64
dtypes: float64(1)
memory usage: 387.3+ KB
1358
125990
After dropna size is:
12305
1359
125990
After dropna size is:
23191

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Increase(Decrease)_Cash_&_Equiv._th_GBP'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 35496 entries, ('GB07588867', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Return_on_Shareholders_Funds_(%)  35496 non-null  float64
dtypes: float64(1)
memory usage: 600.1+ KB
1360
125990
After dropna size is:
27073
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 62569 entries, ('GB07588867', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Return_on_Shareholders_Funds_(%)  62569 non-null  float64
dtypes: float64(1)
memory usage: 1.1+ MB
1361
125990
After dropna size is:
20752
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 83321 entries, ('GB07588867', 2019) to ('GBOC381395', 2016)
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Return_on_Shareholders_Funds_(%)  83321 non-null  float64
dtypes: float64(1)
memory usage: 1.4+ MB
1362
125990
After dropna size is:
17104
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 100425 entries, ('GB07588867', 2019) to ('GBSC452461', 2015)
Data columns (total 1 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   Return_on_Shareholders_Funds_(%)  100425 non-null  float64
dtypes: float64(1)
memory usage: 1.7+ MB
1363
125990
After dropna size is:
14295
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 114720 entries, ('GB07588867', 2019) to ('GB08058491', 2014)
Data columns (total 1 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   Return_on_Shareholders_Funds_(%)  114720 non-null  float64
dtypes: float64(1)
memory usage: 1.9+ MB
1364
125990
After dropna size is:
11908
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 126628 entries, ('GB07588867', 2019) to ('GB07266603', 2013)
Data columns (total 1 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   Return_on_Shareholders_Funds_(%)  126628 non-null  float64
dtypes: float64(1)
memory usage: 2.1+ MB
1365
125990
After dropna size is:
8859
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 135487 entries, ('GB07588867', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   Return_on_Shareholders_Funds_(%)  135487 non-null  float64
dtypes: float64(1)
memory usage: 2.2+ MB
1366
125990
After dropna size is:
4620
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 140107 entries, ('GB07588867', 2019) to ('GB07361608', 2011)
Data columns (total 1 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   Return_on_Shareholders_Funds_(%)  140107 non-null  float64
dtypes: float64(1)
memory usage: 2.3+ MB
1367
125990
After dropna size is:
19579
1368
125990
After dropna size is:
39291

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Return_on_Shareholders_Funds_(%)'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 58870 entries, ('GB09567757', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Return_on_Capital_Employed_(%)  58870 non-null  float64
dtypes: float64(1)
memory usage: 1.1+ MB
1369
125990
After dropna size is:
46329
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 105199 entries, ('GB09567757', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   Return_on_Capital_Employed_(%)  105199 non-null  float64
dtypes: float64(1)
memory usage: 1.8+ MB
1370
125990
After dropna size is:
37356
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 142555 entries, ('GB09567757', 2019) to ('GBOC381395', 2016)
Data columns (total 1 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   Return_on_Capital_Employed_(%)  142555 non-null  float64
dtypes: float64(1)
memory usage: 2.3+ MB
1371
125990
After dropna size is:
30495
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 173050 entries, ('GB09567757', 2019) to ('GBSC452461', 2015)
Data columns (total 1 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   Return_on_Capital_Employed_(%)  173050 non-null  float64
dtypes: float64(1)
memory usage: 2.8+ MB
1372
125990
After dropna size is:
25855
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 198905 entries, ('GB09567757', 2019) to ('GBOC369696', 2014)
Data columns (total 1 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   Return_on_Capital_Employed_(%)  198905 non-null  float64
dtypes: float64(1)
memory usage: 3.2+ MB
1373
125990
After dropna size is:
21813
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 220718 entries, ('GB09567757', 2019) to ('GBOC369696', 2013)
Data columns (total 1 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   Return_on_Capital_Employed_(%)  220718 non-null  float64
dtypes: float64(1)
memory usage: 3.5+ MB
1374
125990
After dropna size is:
16254
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 236972 entries, ('GB09567757', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   Return_on_Capital_Employed_(%)  236972 non-null  float64
dtypes: float64(1)
memory usage: 3.7+ MB
1375
125990
After dropna size is:
8773
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 245745 entries, ('GB09567757', 2019) to ('GB07361608', 2011)
Data columns (total 1 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   Return_on_Capital_Employed_(%)  245745 non-null  float64
dtypes: float64(1)
memory usage: 3.9+ MB
1376
125990
After dropna size is:
20586

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Return_on_Capital_Employed_(%)'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

1377
125990
After dropna size is:
41767
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 62353 entries, ('GB09567757', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Return_on_Total_Assets_(%)  62353 non-null  float64
dtypes: float64(1)
memory usage: 1.1+ MB
1378
125990
After dropna size is:
50572
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 112925 entries, ('GB09567757', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Return_on_Total_Assets_(%)  112925 non-null  float64
dtypes: float64(1)
memory usage: 1.9+ MB
1379
125990
After dropna size is:
40761
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 153686 entries, ('GB09567757', 2019) to ('GBOC381395', 2016)
Data columns (total 1 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Return_on_Total_Assets_(%)  153686 non-null  float64
dtypes: float64(1)
memory usage: 2.5+ MB
1380
125990
After dropna size is:
33684
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 187370 entries, ('GB09567757', 2019) to ('GBSC452461', 2015)
Data columns (total 1 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Return_on_Total_Assets_(%)  187370 non-null  float64
dtypes: float64(1)
memory usage: 3.0+ MB
1381
125990
After dropna size is:
28828
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 216198 entries, ('GB09567757', 2019) to ('GBOC369696', 2014)
Data columns (total 1 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Return_on_Total_Assets_(%)  216198 non-null  float64
dtypes: float64(1)
memory usage: 3.4+ MB
1382
125990
After dropna size is:
24868
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 241066 entries, ('GB09567757', 2019) to ('GBOC369696', 2013)
Data columns (total 1 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Return_on_Total_Assets_(%)  241066 non-null  float64
dtypes: float64(1)
memory usage: 3.8+ MB
1383
125990
After dropna size is:
18718
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 259784 entries, ('GB09567757', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Return_on_Total_Assets_(%)  259784 non-null  float64
dtypes: float64(1)
memory usage: 4.1+ MB
1384
125990
After dropna size is:
9921
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 269705 entries, ('GB09567757', 2019) to ('GB07266603', 2011)
Data columns (total 1 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Return_on_Total_Assets_(%)  269705 non-null  float64
dtypes: float64(1)
memory usage: 4.2+ MB
1385
125990
After dropna size is:
19513

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Return_on_Total_Assets_(%)'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

1386
125990
After dropna size is:
38286
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 57799 entries, ('GB09567757', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Profit_margin_(%)  57799 non-null  float64
dtypes: float64(1)
memory usage: 1.1+ MB
1387
125990
After dropna size is:
46265
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 104064 entries, ('GB09567757', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Profit_margin_(%)  104064 non-null  float64
dtypes: float64(1)
memory usage: 1.8+ MB
1388
125990
After dropna size is:
36088
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 140152 entries, ('GB09567757', 2019) to ('GBSC452461', 2016)
Data columns (total 1 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Profit_margin_(%)  140152 non-null  float64
dtypes: float64(1)
memory usage: 2.3+ MB
1389
125990
After dropna size is:
29814
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 169966 entries, ('GB09567757', 2019) to ('GBSC452461', 2015)
Data columns (total 1 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Profit_margin_(%)  169966 non-null  float64
dtypes: float64(1)
memory usage: 2.8+ MB
1390
125990
After dropna size is:
25563
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 195529 entries, ('GB09567757', 2019) to ('GB08389817', 2014)
Data columns (total 1 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Profit_margin_(%)  195529 non-null  float64
dtypes: float64(1)
memory usage: 3.2+ MB
1391
125990
After dropna size is:
22326
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 217855 entries, ('GB09567757', 2019) to ('GB07266603', 2013)
Data columns (total 1 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Profit_margin_(%)  217855 non-null  float64
dtypes: float64(1)
memory usage: 3.5+ MB
1392
125990
After dropna size is:
16815
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 234670 entries, ('GB09567757', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Profit_margin_(%)  234670 non-null  float64
dtypes: float64(1)
memory usage: 3.8+ MB
1393
125990
After dropna size is:
8879
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 243549 entries, ('GB09567757', 2019) to ('GB07266603', 2011)
Data columns (total 1 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Profit_margin_(%)  243549 non-null  float64
dtypes: float64(1)
memory usage: 3.9+ MB
1394
125990
After dropna size is:
8882
1395
125990

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Profit_margin_(%)'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

After dropna size is:
20146
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 29028 entries, ('GB07588867', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Gross_margin_(%)  29028 non-null  float64
dtypes: float64(1)
memory usage: 492.1+ KB
1396
125990
After dropna size is:
25027
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 54055 entries, ('GB07588867', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Gross_margin_(%)  54055 non-null  float64
dtypes: float64(1)
memory usage: 951.5+ KB
1397
125990
After dropna size is:
22413
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 76468 entries, ('GB07588867', 2019) to ('GBSC452461', 2016)
Data columns (total 1 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Gross_margin_(%)  76468 non-null  float64
dtypes: float64(1)
memory usage: 1.3+ MB
1398
125990
After dropna size is:
20131
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 96599 entries, ('GB07588867', 2019) to ('GBSC452461', 2015)
Data columns (total 1 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Gross_margin_(%)  96599 non-null  float64
dtypes: float64(1)
memory usage: 1.6+ MB
1399
125990
After dropna size is:
17831
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 114430 entries, ('GB07588867', 2019) to ('GB08389817', 2014)
Data columns (total 1 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Gross_margin_(%)  114430 non-null  float64
dtypes: float64(1)
memory usage: 1.9+ MB
1400
125990
After dropna size is:
15222
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 129652 entries, ('GB07588867', 2019) to ('GB07266603', 2013)
Data columns (total 1 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Gross_margin_(%)  129652 non-null  float64
dtypes: float64(1)
memory usage: 2.1+ MB
1401
125990
After dropna size is:
11199
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 140851 entries, ('GB07588867', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Gross_margin_(%)  140851 non-null  float64
dtypes: float64(1)
memory usage: 2.3+ MB
1402
125990
After dropna size is:
5940
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 146791 entries, ('GB07588867', 2019) to ('GB07266603', 2011)
Data columns (total 1 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Gross_margin_(%)  146791 non-null  float64
dtypes: float64(1)
memory usage: 2.3+ MB
1403
125990
After dropna size is:
8846
1404
125990
After dropna size is:
20000

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Gross_margin_(%)'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 28846 entries, ('GB07588867', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Berry_ratio_(x)  28846 non-null  float64
dtypes: float64(1)
memory usage: 487.9+ KB
1405
125990
After dropna size is:
24982
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 53828 entries, ('GB07588867', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Berry_ratio_(x)  53828 non-null  float64
dtypes: float64(1)
memory usage: 945.1+ KB
1406
125990
After dropna size is:
22265
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 76093 entries, ('GB07588867', 2019) to ('GBOC381395', 2016)
Data columns (total 1 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Berry_ratio_(x)  76093 non-null  float64
dtypes: float64(1)
memory usage: 1.3+ MB
1407
125990
After dropna size is:
19993
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 96086 entries, ('GB07588867', 2019) to ('GBSC452461', 2015)
Data columns (total 1 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Berry_ratio_(x)  96086 non-null  float64
dtypes: float64(1)
memory usage: 1.6+ MB
1408
125990
After dropna size is:
17817
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 113903 entries, ('GB07588867', 2019) to ('GB08389817', 2014)
Data columns (total 1 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Berry_ratio_(x)  113903 non-null  float64
dtypes: float64(1)
memory usage: 1.8+ MB
1409
125990
After dropna size is:
15248
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 129151 entries, ('GB07588867', 2019) to ('GB07266603', 2013)
Data columns (total 1 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Berry_ratio_(x)  129151 non-null  float64
dtypes: float64(1)
memory usage: 2.1+ MB
1410
125990
After dropna size is:
11178
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 140329 entries, ('GB07588867', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Berry_ratio_(x)  140329 non-null  float64
dtypes: float64(1)
memory usage: 2.2+ MB
1411
125990
After dropna size is:
5881
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 146210 entries, ('GB07588867', 2019) to ('GB07266603', 2011)
Data columns (total 1 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Berry_ratio_(x)  146210 non-null  float64
dtypes: float64(1)
memory usage: 2.3+ MB
1412
125990
After dropna size is:
19961
1413
125990
After dropna size is:
39371

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Berry_ratio_(x)'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 59332 entries, ('GB09567757', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   EBIT_margin_(%)  59332 non-null  float64
dtypes: float64(1)
memory usage: 1.1+ MB
1414
125990
After dropna size is:
47529
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 106861 entries, ('GB09567757', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   EBIT_margin_(%)  106861 non-null  float64
dtypes: float64(1)
memory usage: 1.8+ MB
1415
125990
After dropna size is:
37347
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 144208 entries, ('GB09567757', 2019) to ('GBSC452461', 2016)
Data columns (total 1 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   EBIT_margin_(%)  144208 non-null  float64
dtypes: float64(1)
memory usage: 2.4+ MB
1416
125990
After dropna size is:
30857
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 175065 entries, ('GB09567757', 2019) to ('GBSC452461', 2015)
Data columns (total 1 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   EBIT_margin_(%)  175065 non-null  float64
dtypes: float64(1)
memory usage: 2.9+ MB
1417
125990
After dropna size is:
26381
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 201446 entries, ('GB09567757', 2019) to ('GBOC369696', 2014)
Data columns (total 1 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   EBIT_margin_(%)  201446 non-null  float64
dtypes: float64(1)
memory usage: 3.3+ MB
1418
125990
After dropna size is:
22899
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 224345 entries, ('GB09567757', 2019) to ('GB07266603', 2013)
Data columns (total 1 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   EBIT_margin_(%)  224345 non-null  float64
dtypes: float64(1)
memory usage: 3.6+ MB
1419
125990
After dropna size is:
17229
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 241574 entries, ('GB09567757', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   EBIT_margin_(%)  241574 non-null  float64
dtypes: float64(1)
memory usage: 3.9+ MB
1420
125990
After dropna size is:
9099
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 250673 entries, ('GB09567757', 2019) to ('GB07266603', 2011)
Data columns (total 1 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   EBIT_margin_(%)  250673 non-null  float64
dtypes: float64(1)
memory usage: 4.0+ MB
1421
125990
After dropna size is:
7830

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'EBIT_margin_(%)'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

1422
125990
After dropna size is:
17522
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 25352 entries, ('GB09567757', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   EBITDA_margin_(%)  25352 non-null  float64
dtypes: float64(1)
memory usage: 431.0+ KB
1423
125990
After dropna size is:
21248
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 46600 entries, ('GB09567757', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   EBITDA_margin_(%)  46600 non-null  float64
dtypes: float64(1)
memory usage: 734.1+ KB
1424
125990
After dropna size is:
17429
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 64029 entries, ('GB09567757', 2019) to ('GB09783953', 2016)
Data columns (total 1 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   EBITDA_margin_(%)  64029 non-null  float64
dtypes: float64(1)
memory usage: 1.1+ MB
1425
125990
After dropna size is:
14754
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 78783 entries, ('GB09567757', 2019) to ('GB08389817', 2015)
Data columns (total 1 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   EBITDA_margin_(%)  78783 non-null  float64
dtypes: float64(1)
memory usage: 1.3+ MB
1426
125990
After dropna size is:
12716
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 91499 entries, ('GB09567757', 2019) to ('GB08389817', 2014)
Data columns (total 1 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   EBITDA_margin_(%)  91499 non-null  float64
dtypes: float64(1)
memory usage: 1.5+ MB
1427
125990
After dropna size is:
11083
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 102582 entries, ('GB09567757', 2019) to ('GB07266603', 2013)
Data columns (total 1 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   EBITDA_margin_(%)  102582 non-null  float64
dtypes: float64(1)
memory usage: 1.7+ MB
1428
125990
After dropna size is:
7895
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 110477 entries, ('GB09567757', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   EBITDA_margin_(%)  110477 non-null  float64
dtypes: float64(1)
memory usage: 1.8+ MB
1429
125990
After dropna size is:
4214
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 114691 entries, ('GB09567757', 2019) to ('GB07266603', 2011)
Data columns (total 1 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   EBITDA_margin_(%)  114691 non-null  float64
dtypes: float64(1)
memory usage: 1.8+ MB
1430
125990
After dropna size is:
16340
1431
125990
After dropna size is:
31709

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'EBITDA_margin_(%)'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 48049 entries, ('GB09567757', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Net_Assets_Turnover_(x)  48049 non-null  float64
dtypes: float64(1)
memory usage: 903.4+ KB
1432
125990
After dropna size is:
38235
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 86284 entries, ('GB09567757', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Net_Assets_Turnover_(x)  86284 non-null  float64
dtypes: float64(1)
memory usage: 1.5+ MB
1433
125990
After dropna size is:
29989
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 116273 entries, ('GB09567757', 2019) to ('GBSC452461', 2016)
Data columns (total 1 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Net_Assets_Turnover_(x)  116273 non-null  float64
dtypes: float64(1)
memory usage: 2.0+ MB
1434
125990
After dropna size is:
24556
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 140829 entries, ('GB09567757', 2019) to ('GBSC452461', 2015)
Data columns (total 1 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Net_Assets_Turnover_(x)  140829 non-null  float64
dtypes: float64(1)
memory usage: 2.3+ MB
1435
125990
After dropna size is:
20553
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 161382 entries, ('GB09567757', 2019) to ('GB08058491', 2014)
Data columns (total 1 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Net_Assets_Turnover_(x)  161382 non-null  float64
dtypes: float64(1)
memory usage: 2.6+ MB
1436
125990
After dropna size is:
17651
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 179033 entries, ('GB09567757', 2019) to ('GB07266603', 2013)
Data columns (total 1 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Net_Assets_Turnover_(x)  179033 non-null  float64
dtypes: float64(1)
memory usage: 2.9+ MB
1437
125990
After dropna size is:
13372
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 192405 entries, ('GB09567757', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Net_Assets_Turnover_(x)  192405 non-null  float64
dtypes: float64(1)
memory usage: 3.1+ MB
1438
125990
After dropna size is:
6902
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 199307 entries, ('GB09567757', 2019) to ('GB07266603', 2011)
Data columns (total 1 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Net_Assets_Turnover_(x)  199307 non-null  float64
dtypes: float64(1)
memory usage: 3.2+ MB
1439
125990
After dropna size is:
11501
1440
125990
After dropna size is:
23990

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Net_Assets_Turnover_(x)'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 35491 entries, ('IE566240', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Fixed_Assets_Turnover_(x)  35491 non-null  float64
dtypes: float64(1)
memory usage: 599.0+ KB
1441
125990
After dropna size is:
28457
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 63948 entries, ('IE566240', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Fixed_Assets_Turnover_(x)  63948 non-null  float64
dtypes: float64(1)
memory usage: 1.1+ MB
1442
125990
After dropna size is:
22879
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 86827 entries, ('IE566240', 2019) to ('IE505067', 2016)
Data columns (total 1 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Fixed_Assets_Turnover_(x)  86827 non-null  float64
dtypes: float64(1)
memory usage: 1.4+ MB
1443
125990
After dropna size is:
18810
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 105637 entries, ('IE566240', 2019) to ('GB08389817', 2015)
Data columns (total 1 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Fixed_Assets_Turnover_(x)  105637 non-null  float64
dtypes: float64(1)
memory usage: 1.7+ MB
1444
125990
After dropna size is:
15913
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 121550 entries, ('IE566240', 2019) to ('GB08389817', 2014)
Data columns (total 1 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Fixed_Assets_Turnover_(x)  121550 non-null  float64
dtypes: float64(1)
memory usage: 2.0+ MB
1445
125990
After dropna size is:
13816
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 135366 entries, ('IE566240', 2019) to ('GB07266603', 2013)
Data columns (total 1 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Fixed_Assets_Turnover_(x)  135366 non-null  float64
dtypes: float64(1)
memory usage: 2.2+ MB
1446
125990
After dropna size is:
10170
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 145536 entries, ('IE566240', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Fixed_Assets_Turnover_(x)  145536 non-null  float64
dtypes: float64(1)
memory usage: 2.3+ MB
1447
125990
After dropna size is:
5418
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 150954 entries, ('IE566240', 2019) to ('GB07266603', 2011)
Data columns (total 1 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Fixed_Assets_Turnover_(x)  150954 non-null  float64
dtypes: float64(1)
memory usage: 2.4+ MB
1448
125990
After dropna size is:
3311
1449
125990
After dropna size is:
8932
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 12243 entries, ('GBOC361927', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Interest_Cover_(x)  12243 non-null  float64
dtypes: float64(1)
memory usage: 209.0+ KB
1450
125990
After dropna size is:
9489

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Fixed_Assets_Turnover_(x)'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 21732 entries, ('GBOC361927', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Interest_Cover_(x)  21732 non-null  float64
dtypes: float64(1)
memory usage: 335.0+ KB
1451
125990
After dropna size is:
8655
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 30387 entries, ('GBOC361927', 2019) to ('GBSC452461', 2016)
Data columns (total 1 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Interest_Cover_(x)  30387 non-null  float64
dtypes: float64(1)
memory usage: 448.0+ KB
1452
125990
After dropna size is:
6881
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 37268 entries, ('GBOC361927', 2019) to ('GBSC452461', 2015)
Data columns (total 1 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Interest_Cover_(x)  37268 non-null  float64
dtypes: float64(1)
memory usage: 537.5+ KB
1453
125990
After dropna size is:
5507
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 42775 entries, ('GBOC361927', 2019) to ('GB08058491', 2014)
Data columns (total 1 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Interest_Cover_(x)  42775 non-null  float64
dtypes: float64(1)
memory usage: 608.5+ KB
1454
125990
After dropna size is:
4240
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 47015 entries, ('GBOC361927', 2019) to ('GB08058491', 2013)
Data columns (total 1 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Interest_Cover_(x)  47015 non-null  float64
dtypes: float64(1)
memory usage: 664.2+ KB
1455
125990
After dropna size is:
2961
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 49976 entries, ('GBOC361927', 2019) to ('GB07937886', 2012)
Data columns (total 1 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Interest_Cover_(x)  49976 non-null  float64
dtypes: float64(1)
memory usage: 702.9+ KB
1456
125990
After dropna size is:
1357
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 51333 entries, ('GBOC361927', 2019) to ('GB07258174', 2011)
Data columns (total 1 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Interest_Cover_(x)  51333 non-null  float64
dtypes: float64(1)
memory usage: 720.2+ KB
1457
125990
After dropna size is:
2312
1458
125990
After dropna size is:
5297
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 7609 entries, ('IE566240', 2019) to ('GB08582762', 2018)
Data columns (total 1 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Stock_Turnover_(x)  7609 non-null   float64
dtypes: float64(1)
memory usage: 128.8+ KB
1459
125990
After dropna size is:
6270
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 13879 entries, ('IE566240', 2019) to ('GB08582762', 2017)
Data columns (total 1 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Stock_Turnover_(x)  13879 non-null  float64
dtypes: float64(1)
memory usage: 216.7+ KB
1460
125990
After dropna size is:
6267
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 20146 entries, ('IE566240', 2019) to ('GB08058491', 2016)
Data columns (total 1 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Stock_Turnover_(x)  20146 non-null  float64
dtypes: float64(1)
memory usage: 305.9+ KB
1461
125990
After dropna size is:
5543

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Interest_Cover_(x)'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 25689 entries, ('IE566240', 2019) to ('GB08058491', 2015)
Data columns (total 1 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Stock_Turnover_(x)  25689 non-null  float64
dtypes: float64(1)
memory usage: 382.9+ KB
1462
125990
After dropna size is:
5131
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 30820 entries, ('IE566240', 2019) to ('GB08058491', 2014)
Data columns (total 1 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Stock_Turnover_(x)  30820 non-null  float64
dtypes: float64(1)
memory usage: 453.4+ KB
1463
125990
After dropna size is:
4402
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 35222 entries, ('IE566240', 2019) to ('GB08058491', 2013)
Data columns (total 1 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Stock_Turnover_(x)  35222 non-null  float64
dtypes: float64(1)
memory usage: 513.8+ KB
1464
125990
After dropna size is:
3409
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 38631 entries, ('IE566240', 2019) to ('GB07192669', 2012)
Data columns (total 1 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Stock_Turnover_(x)  38631 non-null  float64
dtypes: float64(1)
memory usage: 560.9+ KB
1465
125990
After dropna size is:
1801
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 40432 entries, ('IE566240', 2019) to ('GBNC000600', 2011)
Data columns (total 1 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Stock_Turnover_(x)  40432 non-null  float64
dtypes: float64(1)
memory usage: 585.7+ KB
1466
125990
After dropna size is:
5119
1467
125990
After dropna size is:
12687

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Stock_Turnover_(x)'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 17806 entries, ('GB09507385', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Debtors_Turnover_(x)  17806 non-null  float64
dtypes: float64(1)
memory usage: 303.8+ KB
1468
125990
After dropna size is:
14456
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 32262 entries, ('GB09507385', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Debtors_Turnover_(x)  32262 non-null  float64
dtypes: float64(1)
memory usage: 502.1+ KB
1469
125990
After dropna size is:
13711
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 45973 entries, ('GB09507385', 2019) to ('GBSC452461', 2016)
Data columns (total 1 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Debtors_Turnover_(x)  45973 non-null  float64
dtypes: float64(1)
memory usage: 690.3+ KB
1470
125990
After dropna size is:
11856
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 57829 entries, ('GB09507385', 2019) to ('GBOC369696', 2015)
Data columns (total 1 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Debtors_Turnover_(x)  57829 non-null  float64
dtypes: float64(1)
memory usage: 850.5+ KB
1471
125990
After dropna size is:
10374
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 68203 entries, ('GB09507385', 2019) to ('GBOC369696', 2014)
Data columns (total 1 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Debtors_Turnover_(x)  68203 non-null  float64
dtypes: float64(1)
memory usage: 1.1+ MB
1472
125990
After dropna size is:
9235
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 77438 entries, ('GB09507385', 2019) to ('GBOC369696', 2013)
Data columns (total 1 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Debtors_Turnover_(x)  77438 non-null  float64
dtypes: float64(1)
memory usage: 1.2+ MB
1473
125990
After dropna size is:
7099
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 84537 entries, ('GB09507385', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Debtors_Turnover_(x)  84537 non-null  float64
dtypes: float64(1)
memory usage: 1.3+ MB
1474
125990
After dropna size is:
3546
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 88083 entries, ('GB09507385', 2019) to ('GB07266603', 2011)
Data columns (total 1 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Debtors_Turnover_(x)  88083 non-null  float64
dtypes: float64(1)
memory usage: 1.4+ MB
1475
125990
After dropna size is:
5220

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Debtors_Turnover_(x)'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

1476
125990
After dropna size is:
12853
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 18073 entries, ('GB09507385', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Debtor_Collection_(days)  18073 non-null  float64
dtypes: float64(1)
memory usage: 307.8+ KB
1477
125990
After dropna size is:
14644
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 32717 entries, ('GB09507385', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Debtor_Collection_(days)  32717 non-null  float64
dtypes: float64(1)
memory usage: 508.2+ KB
1478
125990
After dropna size is:
13850
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 46567 entries, ('GB09507385', 2019) to ('GBSC452461', 2016)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Debtor_Collection_(days)  46567 non-null  float64
dtypes: float64(1)
memory usage: 698.2+ KB
1479
125990
After dropna size is:
11963
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 58530 entries, ('GB09507385', 2019) to ('GBOC369696', 2015)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Debtor_Collection_(days)  58530 non-null  float64
dtypes: float64(1)
memory usage: 860.0+ KB
1480
125990
After dropna size is:
10466
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 68996 entries, ('GB09507385', 2019) to ('GBOC369696', 2014)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Debtor_Collection_(days)  68996 non-null  float64
dtypes: float64(1)
memory usage: 1.1+ MB
1481
125990
After dropna size is:
9321
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 78317 entries, ('GB09507385', 2019) to ('GBOC369696', 2013)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Debtor_Collection_(days)  78317 non-null  float64
dtypes: float64(1)
memory usage: 1.3+ MB
1482
125990
After dropna size is:
7122
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 85439 entries, ('GB09507385', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Debtor_Collection_(days)  85439 non-null  float64
dtypes: float64(1)
memory usage: 1.4+ MB
1483
125990
After dropna size is:
3562
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 89001 entries, ('GB09507385', 2019) to ('GB07266603', 2011)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Debtor_Collection_(days)  89001 non-null  float64
dtypes: float64(1)
memory usage: 1.4+ MB
1484
125990
After dropna size is:
5658
1485
125990
After dropna size is:
13928
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 19586 entries, ('GB07588867', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Creditors_Payment_(days)  19586 non-null  float64
dtypes: float64(1)
memory usage: 332.7+ KB
1486
125990
After dropna size is:
15529

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Debtor_Collection_(days)'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 35115 entries, ('GB07588867', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Creditors_Payment_(days)  35115 non-null  float64
dtypes: float64(1)
memory usage: 542.5+ KB
1487
125990
After dropna size is:
14601
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 49716 entries, ('GB07588867', 2019) to ('GBSC452461', 2016)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Creditors_Payment_(days)  49716 non-null  float64
dtypes: float64(1)
memory usage: 741.1+ KB
1488
125990
After dropna size is:
12866
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 62582 entries, ('GB07588867', 2019) to ('GBSC452461', 2015)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Creditors_Payment_(days)  62582 non-null  float64
dtypes: float64(1)
memory usage: 913.8+ KB
1489
125990
After dropna size is:
11054
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 73636 entries, ('GB07588867', 2019) to ('GB08058491', 2014)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Creditors_Payment_(days)  73636 non-null  float64
dtypes: float64(1)
memory usage: 1.2+ MB
1490
125990
After dropna size is:
9202
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 82838 entries, ('GB07588867', 2019) to ('GBOC369696', 2013)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Creditors_Payment_(days)  82838 non-null  float64
dtypes: float64(1)
memory usage: 1.3+ MB
1491
125990
After dropna size is:
6903
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 89741 entries, ('GB07588867', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Creditors_Payment_(days)  89741 non-null  float64
dtypes: float64(1)
memory usage: 1.4+ MB
1492
125990
After dropna size is:
3649
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 93390 entries, ('GB07588867', 2019) to ('GB07266603', 2011)
Data columns (total 1 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Creditors_Payment_(days)  93390 non-null  float64
dtypes: float64(1)
memory usage: 1.5+ MB
1493
125990
After dropna size is:
47305

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Creditors_Payment_(days)'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

1494
125990
After dropna size is:
82537
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 129842 entries, ('GB07588867', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Current_ratio_(x)  129842 non-null  float64
dtypes: float64(1)
memory usage: 2.3+ MB
1495
125990
After dropna size is:
89081
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 218923 entries, ('GB07588867', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Current_ratio_(x)  218923 non-null  float64
dtypes: float64(1)
memory usage: 3.4+ MB
1496
125990
After dropna size is:
87145
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 306068 entries, ('GB07588867', 2019) to ('GBOC381395', 2016)
Data columns (total 1 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Current_ratio_(x)  306068 non-null  float64
dtypes: float64(1)
memory usage: 4.6+ MB
1497
125990
After dropna size is:
77258
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 383326 entries, ('GB07588867', 2019) to ('GBSC452461', 2015)
Data columns (total 1 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Current_ratio_(x)  383326 non-null  float64
dtypes: float64(1)
memory usage: 5.6+ MB
1498
125990
After dropna size is:
64683
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 448009 entries, ('GB07588867', 2019) to ('GBOC369696', 2014)
Data columns (total 1 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Current_ratio_(x)  448009 non-null  float64
dtypes: float64(1)
memory usage: 6.4+ MB
1499
125990
After dropna size is:
50056
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 498065 entries, ('GB07588867', 2019) to ('GBOC369696', 2013)
Data columns (total 1 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Current_ratio_(x)  498065 non-null  float64
dtypes: float64(1)
memory usage: 7.0+ MB
1500
125990
After dropna size is:
33904
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 531969 entries, ('GB07588867', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Current_ratio_(x)  531969 non-null  float64
dtypes: float64(1)
memory usage: 7.5+ MB
1501
125990
After dropna size is:
16711
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 548680 entries, ('GB07588867', 2019) to ('GB07266603', 2011)
Data columns (total 1 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Current_ratio_(x)  548680 non-null  float64
dtypes: float64(1)
memory usage: 7.7+ MB
1502
125990
After dropna size is:
47234

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Current_ratio_(x)'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

1503
125990
After dropna size is:
82438
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 129672 entries, ('GB07588867', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Liquidity_ratio_(x)  129672 non-null  float64
dtypes: float64(1)
memory usage: 2.3+ MB
1504
125990
After dropna size is:
88963
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 218635 entries, ('GB07588867', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Liquidity_ratio_(x)  218635 non-null  float64
dtypes: float64(1)
memory usage: 3.4+ MB
1505
125990
After dropna size is:
86958
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 305593 entries, ('GB07588867', 2019) to ('GBOC381395', 2016)
Data columns (total 1 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Liquidity_ratio_(x)  305593 non-null  float64
dtypes: float64(1)
memory usage: 4.6+ MB
1506
125990
After dropna size is:
77063
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 382656 entries, ('GB07588867', 2019) to ('GBSC452461', 2015)
Data columns (total 1 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Liquidity_ratio_(x)  382656 non-null  float64
dtypes: float64(1)
memory usage: 5.6+ MB
1507
125990
After dropna size is:
64476
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 447132 entries, ('GB07588867', 2019) to ('GBOC369696', 2014)
Data columns (total 1 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Liquidity_ratio_(x)  447132 non-null  float64
dtypes: float64(1)
memory usage: 6.4+ MB
1508
125990
After dropna size is:
49885
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 497017 entries, ('GB07588867', 2019) to ('GBOC369696', 2013)
Data columns (total 1 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Liquidity_ratio_(x)  497017 non-null  float64
dtypes: float64(1)
memory usage: 7.0+ MB
1509
125990
After dropna size is:
33772
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 530789 entries, ('GB07588867', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Liquidity_ratio_(x)  530789 non-null  float64
dtypes: float64(1)
memory usage: 7.5+ MB
1510
125990
After dropna size is:
16656
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 547445 entries, ('GB07588867', 2019) to ('GB07266603', 2011)
Data columns (total 1 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Liquidity_ratio_(x)  547445 non-null  float64
dtypes: float64(1)
memory usage: 7.7+ MB
1511
125990
After dropna size is:
17706

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Liquidity_ratio_(x)'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

1512
125990
After dropna size is:
30530
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 48236 entries, ('GB09683141', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Shareholders_liquidity_ratio_(x)  48236 non-null  float64
dtypes: float64(1)
memory usage: 878.0+ KB
1513
125990
After dropna size is:
31999
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 80235 entries, ('GB09683141', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Shareholders_liquidity_ratio_(x)  80235 non-null  float64
dtypes: float64(1)
memory usage: 1.3+ MB
1514
125990
After dropna size is:
28244
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 108479 entries, ('GB09683141', 2019) to ('GB08582762', 2016)
Data columns (total 1 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   Shareholders_liquidity_ratio_(x)  108479 non-null  float64
dtypes: float64(1)
memory usage: 1.7+ MB
1515
125990
After dropna size is:
23809
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 132288 entries, ('GB09683141', 2019) to ('GB07816198', 2015)
Data columns (total 1 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   Shareholders_liquidity_ratio_(x)  132288 non-null  float64
dtypes: float64(1)
memory usage: 2.0+ MB
1516
125990
After dropna size is:
19228
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 151516 entries, ('GB09683141', 2019) to ('GB07816198', 2014)
Data columns (total 1 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   Shareholders_liquidity_ratio_(x)  151516 non-null  float64
dtypes: float64(1)
memory usage: 2.3+ MB
1517
125990
After dropna size is:
13951
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 165467 entries, ('GB09683141', 2019) to ('GBNI606607', 2013)
Data columns (total 1 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   Shareholders_liquidity_ratio_(x)  165467 non-null  float64
dtypes: float64(1)
memory usage: 2.5+ MB
1518
125990
After dropna size is:
9072
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 174539 entries, ('GB09683141', 2019) to ('GBNI606607', 2012)
Data columns (total 1 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   Shareholders_liquidity_ratio_(x)  174539 non-null  float64
dtypes: float64(1)
memory usage: 2.6+ MB
1519
125990
After dropna size is:
4178
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 178717 entries, ('GB09683141', 2019) to ('GB07149148', 2011)
Data columns (total 1 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   Shareholders_liquidity_ratio_(x)  178717 non-null  float64
dtypes: float64(1)
memory usage: 2.7+ MB
1520
125990
After dropna size is:
49367

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Shareholders_liquidity_ratio_(x)'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

1521
125990
After dropna size is:
83704
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 133071 entries, ('GB07588867', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   Solvency_ratio_(Asset_based)_(%)  133071 non-null  float64
dtypes: float64(1)
memory usage: 2.3+ MB
1522
125990
After dropna size is:
90700
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 223771 entries, ('GB07588867', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   Solvency_ratio_(Asset_based)_(%)  223771 non-null  float64
dtypes: float64(1)
memory usage: 3.5+ MB
1523
125990
After dropna size is:
88819
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 312590 entries, ('GB07588867', 2019) to ('GBOC381395', 2016)
Data columns (total 1 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   Solvency_ratio_(Asset_based)_(%)  312590 non-null  float64
dtypes: float64(1)
memory usage: 4.7+ MB
1524
125990
After dropna size is:
78747
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 391337 entries, ('GB07588867', 2019) to ('GBSC452461', 2015)
Data columns (total 1 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   Solvency_ratio_(Asset_based)_(%)  391337 non-null  float64
dtypes: float64(1)
memory usage: 5.7+ MB
1525
125990
After dropna size is:
65976
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 457313 entries, ('GB07588867', 2019) to ('GBSC452461', 2014)
Data columns (total 1 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   Solvency_ratio_(Asset_based)_(%)  457313 non-null  float64
dtypes: float64(1)
memory usage: 6.5+ MB
1526
125990
After dropna size is:
50838
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 508151 entries, ('GB07588867', 2019) to ('GBSC452461', 2013)
Data columns (total 1 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   Solvency_ratio_(Asset_based)_(%)  508151 non-null  float64
dtypes: float64(1)
memory usage: 7.2+ MB
1527
125990
After dropna size is:
35122
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 543273 entries, ('GB07588867', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   Solvency_ratio_(Asset_based)_(%)  543273 non-null  float64
dtypes: float64(1)
memory usage: 7.6+ MB
1528
125990
After dropna size is:
18006
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 561279 entries, ('GB07588867', 2019) to ('GB07266603', 2011)
Data columns (total 1 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   Solvency_ratio_(Asset_based)_(%)  561279 non-null  float64
dtypes: float64(1)
memory usage: 7.9+ MB
1529
125990
After dropna size is:
21413

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Solvency_ratio_(Asset_based)_(%)'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

1530
125990
After dropna size is:
36821
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 58234 entries, ('GB10106271', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Solvency_ratio_(Liability_based)_(%)  58234 non-null  float64
dtypes: float64(1)
memory usage: 1.0+ MB
1531
125990
After dropna size is:
41283
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 99517 entries, ('GB10106271', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Solvency_ratio_(Liability_based)_(%)  99517 non-null  float64
dtypes: float64(1)
memory usage: 1.6+ MB
1532
125990
After dropna size is:
41417
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 140934 entries, ('GB10106271', 2019) to ('GBSC452461', 2016)
Data columns (total 1 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   Solvency_ratio_(Liability_based)_(%)  140934 non-null  float64
dtypes: float64(1)
memory usage: 2.2+ MB
1533
125990
After dropna size is:
37115
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 178049 entries, ('GB10106271', 2019) to ('GBSC452461', 2015)
Data columns (total 1 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   Solvency_ratio_(Liability_based)_(%)  178049 non-null  float64
dtypes: float64(1)
memory usage: 2.7+ MB
1534
125990
After dropna size is:
30771
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 208820 entries, ('GB10106271', 2019) to ('IE505067', 2014)
Data columns (total 1 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   Solvency_ratio_(Liability_based)_(%)  208820 non-null  float64
dtypes: float64(1)
memory usage: 3.2+ MB
1535
125990
After dropna size is:
23684
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 232504 entries, ('GB10106271', 2019) to ('GBNI606607', 2013)
Data columns (total 1 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   Solvency_ratio_(Liability_based)_(%)  232504 non-null  float64
dtypes: float64(1)
memory usage: 3.5+ MB
1536
125990
After dropna size is:
16052
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 248556 entries, ('GB10106271', 2019) to ('GB07266603', 2012)
Data columns (total 1 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   Solvency_ratio_(Liability_based)_(%)  248556 non-null  float64
dtypes: float64(1)
memory usage: 3.7+ MB
1537
125990
After dropna size is:
7967
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 256523 entries, ('GB10106271', 2019) to ('GB07266603', 2011)
Data columns (total 1 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   Solvency_ratio_(Liability_based)_(%)  256523 non-null  float64
dtypes: float64(1)
memory usage: 3.8+ MB
1538
125990
After dropna size is:
5451
1539
125990
After dropna size is:
10270
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 15721 entries, ('GBOC361927', 2019) to ('GBOC381395', 2018)
Data columns (total 1 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Asset_Cover_(x)  15721 non-null  float64
dtypes: float64(1)
memory usage: 258.3+ KB
1540
125990
After dropna size is:
11012

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Solvency_ratio_(Liability_based)_(%)'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 26733 entries, ('GBOC361927', 2019) to ('GBOC381395', 2017)
Data columns (total 1 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Asset_Cover_(x)  26733 non-null  float64
dtypes: float64(1)
memory usage: 398.1+ KB
1541
125990
After dropna size is:
9840
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 36573 entries, ('GBOC361927', 2019) to ('GBOC365296', 2016)
Data columns (total 1 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Asset_Cover_(x)  36573 non-null  float64
dtypes: float64(1)
memory usage: 522.0+ KB
1542
125990
After dropna size is:
8469
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 45042 entries, ('GBOC361927', 2019) to ('GBOC381395', 2015)
Data columns (total 1 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Asset_Cover_(x)  45042 non-null  float64
dtypes: float64(1)
memory usage: 628.4+ KB
1543
125990
After dropna size is:
7296
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 52338 entries, ('GBOC361927', 2019) to ('GBOC381395', 2014)
Data columns (total 1 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Asset_Cover_(x)  52338 non-null  float64
dtypes: float64(1)
memory usage: 718.3+ KB
1544
125990
After dropna size is:
5838
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 58176 entries, ('GBOC361927', 2019) to ('GBOC365296', 2013)
Data columns (total 1 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Asset_Cover_(x)  58176 non-null  float64
dtypes: float64(1)
memory usage: 790.3+ KB
1545
125990
After dropna size is:
4153
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 62329 entries, ('GBOC361927', 2019) to ('GBOC365296', 2012)
Data columns (total 1 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Asset_Cover_(x)  62329 non-null  float64
dtypes: float64(1)
memory usage: 841.1+ KB
1546
125990
After dropna size is:
2026
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 64355 entries, ('GBOC361927', 2019) to ('GB07380791', 2011)
Data columns (total 1 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Asset_Cover_(x)  64355 non-null  float64
dtypes: float64(1)
memory usage: 865.8+ KB
1547
125990
After dropna size is:
9239
1548
125990
After dropna size is:
14646
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 23885 entries, ('GB08410946', 2019) to ('IE505067', 2018)
Data columns (total 1 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Profit_per_employee_(unit)_GBP  23885 non-null  float64
dtypes: float64(1)
memory usage: 408.1+ KB
1549
125990
After dropna size is:
17631

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Asset_Cover_(x)'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 41516 entries, ('GB08410946', 2019) to ('IE505067', 2017)
Data columns (total 1 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Profit_per_employee_(unit)_GBP  41516 non-null  float64
dtypes: float64(1)
memory usage: 657.6+ KB
1550
125990
After dropna size is:
12526
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 54042 entries, ('GB08410946', 2019) to ('IE505067', 2016)
Data columns (total 1 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Profit_per_employee_(unit)_GBP  54042 non-null  float64
dtypes: float64(1)
memory usage: 824.2+ KB
1551
125990
After dropna size is:
7729
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 61771 entries, ('GB08410946', 2019) to ('GBOC369696', 2015)
Data columns (total 1 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Profit_per_employee_(unit)_GBP  61771 non-null  float64
dtypes: float64(1)
memory usage: 1.0+ MB
1552
125990
After dropna size is:
5475
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 67246 entries, ('GB08410946', 2019) to ('GBOC369696', 2014)
Data columns (total 1 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Profit_per_employee_(unit)_GBP  67246 non-null  float64
dtypes: float64(1)
memory usage: 1.1+ MB
1553
125990
After dropna size is:
4363
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 71609 entries, ('GB08410946', 2019) to ('GBOC369696', 2013)
Data columns (total 1 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Profit_per_employee_(unit)_GBP  71609 non-null  float64
dtypes: float64(1)
memory usage: 1.2+ MB
1554
125990
After dropna size is:
3110
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 74719 entries, ('GB08410946', 2019) to ('GB07361608', 2012)
Data columns (total 1 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Profit_per_employee_(unit)_GBP  74719 non-null  float64
dtypes: float64(1)
memory usage: 1.2+ MB
1555
125990
After dropna size is:
1630
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 76349 entries, ('GB08410946', 2019) to ('GB07361608', 2011)
Data columns (total 1 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Profit_per_employee_(unit)_GBP  76349 non-null  float64
dtypes: float64(1)
memory usage: 1.2+ MB
1556
125990
After dropna size is:
9281
1557
125990
After dropna size is:
14781
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 24062 entries, ('GB08410946', 2019) to ('IE505067', 2018)
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Turnover_per_employee_(unit)_GBP  24062 non-null  float64
dtypes: float64(1)
memory usage: 411.4+ KB
1558
125990
After dropna size is:
17747

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Profit_per_employee_(unit)_GBP'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 41809 entries, ('GB08410946', 2019) to ('IE505067', 2017)
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Turnover_per_employee_(unit)_GBP  41809 non-null  float64
dtypes: float64(1)
memory usage: 664.1+ KB
1559
125990
After dropna size is:
12640
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 54449 entries, ('GB08410946', 2019) to ('IE505067', 2016)
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Turnover_per_employee_(unit)_GBP  54449 non-null  float64
dtypes: float64(1)
memory usage: 833.7+ KB
1560
125990
After dropna size is:
7780
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 62229 entries, ('GB08410946', 2019) to ('GBOC369696', 2015)
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Turnover_per_employee_(unit)_GBP  62229 non-null  float64
dtypes: float64(1)
memory usage: 1.0+ MB
1561
125990
After dropna size is:
5461
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 67690 entries, ('GB08410946', 2019) to ('GBOC369696', 2014)
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Turnover_per_employee_(unit)_GBP  67690 non-null  float64
dtypes: float64(1)
memory usage: 1.1+ MB
1562
125990
After dropna size is:
4318
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 72008 entries, ('GB08410946', 2019) to ('GBOC369696', 2013)
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Turnover_per_employee_(unit)_GBP  72008 non-null  float64
dtypes: float64(1)
memory usage: 1.2+ MB
1563
125990
After dropna size is:
3120
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 75128 entries, ('GB08410946', 2019) to ('GB07361608', 2012)
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Turnover_per_employee_(unit)_GBP  75128 non-null  float64
dtypes: float64(1)
memory usage: 1.2+ MB
1564
125990
After dropna size is:
1588
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 76716 entries, ('GB08410946', 2019) to ('GB07361608', 2011)
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Turnover_per_employee_(unit)_GBP  76716 non-null  float64
dtypes: float64(1)
memory usage: 1.2+ MB
1565
125990
After dropna size is:
7140
1566
125990
After dropna size is:
14055
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 21195 entries, ('GB10388936', 2019) to ('IE505067', 2018)
Data columns (total 1 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Salaries/Turnover  21195 non-null  float64
dtypes: float64(1)
memory usage: 360.6+ KB
1567
125990

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Turnover_per_employee_(unit)_GBP'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

After dropna size is:
17620
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 38815 entries, ('GB10388936', 2019) to ('IE505067', 2017)
Data columns (total 1 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Salaries/Turnover  38815 non-null  float64
dtypes: float64(1)
memory usage: 622.6+ KB
1568
125990
After dropna size is:
12044
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 50859 entries, ('GB10388936', 2019) to ('IE505067', 2016)
Data columns (total 1 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Salaries/Turnover  50859 non-null  float64
dtypes: float64(1)
memory usage: 798.3+ KB
1569
125990
After dropna size is:
8453
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 59312 entries, ('GB10388936', 2019) to ('GB08389817', 2015)
Data columns (total 1 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Salaries/Turnover  59312 non-null  float64
dtypes: float64(1)
memory usage: 1.0+ MB
1570
125990
After dropna size is:
6021
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 65333 entries, ('GB10388936', 2019) to ('GB08389817', 2014)
Data columns (total 1 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Salaries/Turnover  65333 non-null  float64
dtypes: float64(1)
memory usage: 1.1+ MB
1571
125990
After dropna size is:
5136
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 70469 entries, ('GB10388936', 2019) to ('GB07266603', 2013)
Data columns (total 1 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Salaries/Turnover  70469 non-null  float64
dtypes: float64(1)
memory usage: 1.2+ MB
1572
125990
After dropna size is:
4178
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 74647 entries, ('GB10388936', 2019) to ('GB07361608', 2012)
Data columns (total 1 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Salaries/Turnover  74647 non-null  float64
dtypes: float64(1)
memory usage: 1.2+ MB
1573
125990
After dropna size is:
2439
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 77086 entries, ('GB10388936', 2019) to ('GB07266603', 2011)
Data columns (total 1 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Salaries/Turnover  77086 non-null  float64
dtypes: float64(1)
memory usage: 1.3+ MB
1574
125990
After dropna size is:
4734
1575
125990
After dropna size is:
6907
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 11641 entries, ('GB08358308', 2019) to ('IE505067', 2018)
Data columns (total 1 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Average_Remuneration_per_employee_(unit)_GBP  11641 non-null  float64
dtypes: float64(1)
memory usage: 200.5+ KB
1576
125990
After dropna size is:
8926
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 20567 entries, ('GB08358308', 2019) to ('IE505067', 2017)
Data columns (total 1 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Average_Remuneration_per_employee_(unit)_GBP  20567 non-null  float64
dtypes: float64(1)
memory usage: 329.8+ KB
1577
125990
After dropna size is:
7452
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 28019 entries, ('GB08358308', 2019) to ('IE505067', 2016)
Data columns (total 1 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Average_Remuneration_per_employee_(unit)_GBP  28019 non-null  float64
dtypes: float64(1)
memory usage: 431.6+ KB
1578
125990
After dropna size is:
5874
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 33893 entries, ('GB08358308', 2019) to ('GBOC369696', 2015)
Data columns (total 1 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Average_Remuneration_per_employee_(unit)_GBP  33893 non-null  float64
dtypes: float64(1)
memory usage: 506.8+ KB
1579
125990
After dropna size is:
4487
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 38380 entries, ('GB08358308', 2019) to ('GBOC369696', 2014)
Data columns (total 1 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Average_Remuneration_per_employee_(unit)_GBP  38380 non-null  float64
dtypes: float64(1)
memory usage: 562.4+ KB
1580
125990
After dropna size is:
3595
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 41975 entries, ('GB08358308', 2019) to ('GBOC369696', 2013)
Data columns (total 1 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Average_Remuneration_per_employee_(unit)_GBP  41975 non-null  float64
dtypes: float64(1)
memory usage: 609.2+ KB
1581
125990
After dropna size is:
2525
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 44500 entries, ('GB08358308', 2019) to ('GB07361608', 2012)
Data columns (total 1 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Average_Remuneration_per_employee_(unit)_GBP  44500 non-null  float64
dtypes: float64(1)
memory usage: 641.5+ KB
1582
125990
After dropna size is:
1314
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 45814 entries, ('GB08358308', 2019) to ('GB07361608', 2011)
Data columns (total 1 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Average_Remuneration_per_employee_(unit)_GBP  45814 non-null  float64
dtypes: float64(1)
memory usage: 658.5+ KB
1583
125990
After dropna size is:
14792

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Average_Remuneration_per_employee_(unit)_GBP'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

1584
125990
After dropna size is:
20148
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 34940 entries, ('GB08410946', 2019) to ('IE505067', 2018)
Data columns (total 1 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Shareholders_Funds_per_employee_(unit)_GBP  34940 non-null  float64
dtypes: float64(1)
memory usage: 573.2+ KB
1585
125990
After dropna size is:
19706
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 54646 entries, ('GB08410946', 2019) to ('IE505067', 2017)
Data columns (total 1 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Shareholders_Funds_per_employee_(unit)_GBP  54646 non-null  float64
dtypes: float64(1)
memory usage: 823.2+ KB
1586
125990
After dropna size is:
11354
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 66000 entries, ('GB08410946', 2019) to ('IE505067', 2016)
Data columns (total 1 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Shareholders_Funds_per_employee_(unit)_GBP  66000 non-null  float64
dtypes: float64(1)
memory usage: 963.6+ KB
1587
125990
After dropna size is:
5135
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 71135 entries, ('GB08410946', 2019) to ('IE505067', 2015)
Data columns (total 1 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Shareholders_Funds_per_employee_(unit)_GBP  71135 non-null  float64
dtypes: float64(1)
memory usage: 1.1+ MB
1588
125990
After dropna size is:
3244
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 74379 entries, ('GB08410946', 2019) to ('IE505067', 2014)
Data columns (total 1 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Shareholders_Funds_per_employee_(unit)_GBP  74379 non-null  float64
dtypes: float64(1)
memory usage: 1.2+ MB
1589
125990
After dropna size is:
2524
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 76903 entries, ('GB08410946', 2019) to ('GB07361608', 2013)
Data columns (total 1 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Shareholders_Funds_per_employee_(unit)_GBP  76903 non-null  float64
dtypes: float64(1)
memory usage: 1.2+ MB
1590
125990
After dropna size is:
1782
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 78685 entries, ('GB08410946', 2019) to ('GB07361608', 2012)
Data columns (total 1 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Shareholders_Funds_per_employee_(unit)_GBP  78685 non-null  float64
dtypes: float64(1)
memory usage: 1.3+ MB
1591
125990
After dropna size is:
926
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 79611 entries, ('GB08410946', 2019) to ('GB07361608', 2011)
Data columns (total 1 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Shareholders_Funds_per_employee_(unit)_GBP  79611 non-null  float64
dtypes: float64(1)
memory usage: 1.3+ MB
1592
125990
After dropna size is:
9222
1593
125990
After dropna size is:
18208

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Shareholders_Funds_per_employee_(unit)_GBP'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 27430 entries, ('GB07407685', 2019) to ('IE505067', 2018)
Data columns (total 1 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Working_Capital_per_employee_(unit)_GBP  27430 non-null  float64
dtypes: float64(1)
memory usage: 449.3+ KB
1594
125990
After dropna size is:
19067
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 46497 entries, ('GB07407685', 2019) to ('IE505067', 2017)
Data columns (total 1 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Working_Capital_per_employee_(unit)_GBP  46497 non-null  float64
dtypes: float64(1)
memory usage: 690.5+ KB
1595
125990
After dropna size is:
12597
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 59094 entries, ('GB07407685', 2019) to ('IE505067', 2016)
Data columns (total 1 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Working_Capital_per_employee_(unit)_GBP  59094 non-null  float64
dtypes: float64(1)
memory usage: 843.4+ KB
1596
125990
After dropna size is:
6894
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 65988 entries, ('GB07407685', 2019) to ('GBOC369696', 2015)
Data columns (total 1 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Working_Capital_per_employee_(unit)_GBP  65988 non-null  float64
dtypes: float64(1)
memory usage: 926.7+ KB
1597
125990
After dropna size is:
4472
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 70460 entries, ('GB07407685', 2019) to ('GBOC369696', 2014)
Data columns (total 1 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Working_Capital_per_employee_(unit)_GBP  70460 non-null  float64
dtypes: float64(1)
memory usage: 980.5+ KB
1598
125990
After dropna size is:
3040
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 73500 entries, ('GB07407685', 2019) to ('GBOC369696', 2013)
Data columns (total 1 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Working_Capital_per_employee_(unit)_GBP  73500 non-null  float64
dtypes: float64(1)
memory usage: 1017.9+ KB
1599
125990
After dropna size is:
2031
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 75531 entries, ('GB07407685', 2019) to ('GB07361608', 2012)
Data columns (total 1 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Working_Capital_per_employee_(unit)_GBP  75531 non-null  float64
dtypes: float64(1)
memory usage: 1.0+ MB
1600
125990
After dropna size is:
1053
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 76584 entries, ('GB07407685', 2019) to ('GB07361608', 2011)
Data columns (total 1 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Working_Capital_per_employee_(unit)_GBP  76584 non-null  float64
dtypes: float64(1)
memory usage: 1.0+ MB
1601
125990
After dropna size is:
21686

/usr/local/lib/python3.6/dist-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'Working_Capital_per_employee_(unit)_GBP'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

1602
125990
After dropna size is:
31758
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 53444 entries, ('GB08410946', 2019) to ('IE505067', 2018)
Data columns (total 1 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Total_Assets_per_employee_(unit)_GBP  53444 non-null  float64
dtypes: float64(1)
memory usage: 971.4+ KB
1603
125990
After dropna size is:
31681
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 85125 entries, ('GB08410946', 2019) to ('IE505067', 2017)
Data columns (total 1 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Total_Assets_per_employee_(unit)_GBP  85125 non-null  float64
dtypes: float64(1)
memory usage: 1.4+ MB
1604
125990
After dropna size is:
19812
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 104937 entries, ('GB08410946', 2019) to ('IE505067', 2016)
Data columns (total 1 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   Total_Assets_per_employee_(unit)_GBP  104937 non-null  float64
dtypes: float64(1)
memory usage: 1.6+ MB
1605
125990
After dropna size is:
9726
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 114663 entries, ('GB08410946', 2019) to ('GBOC369696', 2015)
Data columns (total 1 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   Total_Assets_per_employee_(unit)_GBP  114663 non-null  float64
dtypes: float64(1)
memory usage: 1.8+ MB
1606
125990
After dropna size is:
6146
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 120809 entries, ('GB08410946', 2019) to ('GBOC369696', 2014)
Data columns (total 1 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   Total_Assets_per_employee_(unit)_GBP  120809 non-null  float64
dtypes: float64(1)
memory usage: 1.9+ MB
1607
125990
After dropna size is:
4540
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 125349 entries, ('GB08410946', 2019) to ('GBOC369696', 2013)
Data columns (total 1 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   Total_Assets_per_employee_(unit)_GBP  125349 non-null  float64
dtypes: float64(1)
memory usage: 1.9+ MB
1608
125990
After dropna size is:
3112
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 128461 entries, ('GB08410946', 2019) to ('GB07361608', 2012)
Data columns (total 1 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   Total_Assets_per_employee_(unit)_GBP  128461 non-null  float64
dtypes: float64(1)
memory usage: 2.0+ MB
1609
125990
After dropna size is:
1632
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 130093 entries, ('GB08410946', 2019) to ('GB07361608', 2011)
Data columns (total 1 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   Total_Assets_per_employee_(unit)_GBP  130093 non-null  float64
dtypes: float64(1)
memory usage: 2.0+ MB
1610

In [14]:
gifi = pd.HDFStore('bdv-data-gifi.h5')
for gifi_column_key in gifi.keys();
    df = gifi.get(gifi_column_key)
    printdf.info

In [16]:
ta.info

<bound method DataFrame.info of                  Total_Assets_th_GBP
bv_id      year
GB09567757 2019             1.391000
GB07588867 2019             4.519000
GBOC353264 2019            26.831000
GB10106271 2019             0.980000
IE566240   2019             3.368926
...                              ...
GB07386028 2011             4.825000
GB07361608 2011            68.216000
GB07213850 2011             0.002000
GB07404972 2011            18.309000
GB07266603 2011            18.115000

[666901 rows x 1 columns]>